import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type EventName = "booking_created" | "booking_pending" | "booking_approved" | "booking_rejected" | "booking_completed" | "booking_cancelled" | "payment_received";
type Channel = "EMAIL" | "SMS" | "ADMIN_EMAIL";
type ChannelState = "sent" | "skipped" | "not_configured" | "failed";
type Lang = "tr" | "en" | "de" | "fr" | "es" | "ru" | "zh" | "ar" | "ku";
type Audience = "CUSTOMER" | "ADMIN";
type NoticeMedium = "email" | "sms";

interface BookingRow {
  id:string; reference:string; booking_type:string; item_name:string; customer_name:string;
  customer_email:string|null; customer_phone:string; customer_locale:string|null;
  start_at:string|null; end_at:string|null; total_price:number|null; currency:string;
  payment_method:string; payment_status:string; amount_paid:number; status:string;
}
interface NotificationContext { paymentMethod?:string; paymentAmount?:number; paymentTransactionId?:string; }
interface TemplateRow { subject_template:string; intro_template:string; next_step_template:string; }
interface ChannelReport { state:ChannelState; providerMessageId?:string; reason?:string; }
interface DeliveryLease { acquired:boolean; id?:string; priorMessageId?:string; }
interface ResendCredentials { configured:boolean; apiKey:string; mailFrom:string; adminTo:string; source:'vault'|'environment'|'none'; }
interface TwilioCredentials { configured:boolean; accountSid:string; authToken:string; from:string; messagingServiceSid:string; source:'vault'|'environment'|'none'; }

const URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const EVENTS:EventName[]=["booking_created","booking_pending","booking_approved","booking_rejected","booking_completed","booking_cancelled","payment_received"];

function json(body:unknown,status=200):Response{return Response.json(body,{status,headers:{"cache-control":"no-store","content-type":"application/json; charset=utf-8"}});}
function clean(value:unknown,max=500):string{return typeof value==="string"?value.trim().slice(0,max):"";}
function escapeHtml(value:unknown):string{return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function headers(extra:Record<string,string>={}):Record<string,string>{return{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,"content-type":"application/json",...extra};}
async function db(path:string,init:RequestInit={}):Promise<Response>{return fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})},signal:init.signal||AbortSignal.timeout(12_000)});}
function language(locale:string|null):Lang{
  const raw=clean(locale,16).toLowerCase().replace(/_/g,"-");
  const primary=raw.split("-")[0]||"";
  const aliases:Record<string,Lang>={
    tr:"tr",en:"en",de:"de",fr:"fr",es:"es",ru:"ru",zh:"zh",ar:"ar",ku:"ku",
    ckb:"ku",kmr:"ku",kur:"ku",
    "zh-cn":"zh","zh-hans":"zh","zh-tw":"zh","zh-hant":"zh",
  };
  if(raw&&aliases[raw])return aliases[raw];
  if(primary&&aliases[primary])return aliases[primary];
  return "tr";
}
function moneyValue(value:unknown):number{const parsed=Number(value);return Number.isFinite(parsed)?Math.max(0,Math.round(parsed*100)/100):0;}

async function providerCredentials(provider:'RESEND'|'TWILIO'):Promise<Record<string,unknown>|null>{
  try{
    const response=await db('rpc/service_notification_provider_credentials_v2213',{method:'POST',body:JSON.stringify({p_provider:provider})});
    if(!response.ok)return null;
    const payload=await response.json().catch(()=>null);
    return payload&&typeof payload==='object'&&!Array.isArray(payload)?payload as Record<string,unknown>:null;
  }catch{return null;}
}
async function resolveResendCredentials():Promise<ResendCredentials>{
  const vault=await providerCredentials('RESEND');
  const apiKey=clean(vault?.['apiKey'],500),mailFrom=clean(vault?.['mailFrom'],240),adminTo=clean(vault?.['adminTo'],240);
  if(vault?.['configured']===true&&apiKey&&mailFrom)return{configured:true,apiKey,mailFrom,adminTo,source:'vault'};
  const provider=clean(Deno.env.get('EMAIL_PROVIDER'),30).toLowerCase(),envKey=clean(Deno.env.get('RESEND_API_KEY'),500),envFrom=clean(Deno.env.get('MAIL_FROM'),240),envAdmin=clean(Deno.env.get('MAIL_ADMIN_TO'),240);
  if(provider==='resend'&&envKey&&envFrom)return{configured:true,apiKey:envKey,mailFrom:envFrom,adminTo:envAdmin,source:'environment'};
  return{configured:false,apiKey:'',mailFrom:'',adminTo:'',source:'none'};
}
async function resolveTwilioCredentials():Promise<TwilioCredentials>{
  const vault=await providerCredentials('TWILIO');
  const accountSid=clean(vault?.['accountSid'],200),authToken=clean(vault?.['authToken'],300),from=clean(vault?.['from'],60),messagingServiceSid=clean(vault?.['messagingServiceSid'],200);
  if(vault?.['configured']===true&&accountSid&&authToken&&(from||messagingServiceSid))return{configured:true,accountSid,authToken,from,messagingServiceSid,source:'vault'};
  const provider=clean(Deno.env.get('SMS_PROVIDER'),30).toLowerCase(),sid=clean(Deno.env.get('TWILIO_ACCOUNT_SID'),200),token=clean(Deno.env.get('TWILIO_AUTH_TOKEN'),300),envFrom=clean(Deno.env.get('TWILIO_FROM'),60),messagingSid=clean(Deno.env.get('TWILIO_MESSAGING_SERVICE_SID'),200);
  if(provider==='twilio'&&sid&&token&&(envFrom||messagingSid))return{configured:true,accountSid:sid,authToken:token,from:envFrom,messagingServiceSid:messagingSid,source:'environment'};
  return{configured:false,accountSid:'',authToken:'',from:'',messagingServiceSid:'',source:'none'};
}

const subjectCopy:Record<Lang,Record<EventName,string>>={
  tr:{booking_created:"Talebiniz kayıt altına alındı",booking_pending:"Talebiniz kontrol ediliyor",booking_approved:"Rezervasyonunuz onaylandı",booking_rejected:"Talebinizle ilgili bir güncelleme var",booking_completed:"İşleminiz tamamlandı",booking_cancelled:"Rezervasyonunuz iptal edildi",payment_received:"Ödemeniz alındı"},
  en:{booking_created:"We received your request",booking_pending:"Your request is being reviewed",booking_approved:"Your reservation is approved",booking_rejected:"There is an update about your request",booking_completed:"Your request is completed",booking_cancelled:"Your reservation is cancelled",payment_received:"We received your payment"},
  de:{booking_created:"Ihre Anfrage wurde empfangen",booking_pending:"Ihre Anfrage wird geprüft",booking_approved:"Ihre Reservierung wurde bestätigt",booking_rejected:"Aktualisierung zu Ihrer Anfrage",booking_completed:"Ihr Vorgang wurde abgeschlossen",booking_cancelled:"Ihre Reservierung wurde storniert",payment_received:"Ihre Zahlung ist eingegangen"},
  fr:{booking_created:"Votre demande a bien été reçue",booking_pending:"Votre demande est en cours d'examen",booking_approved:"Votre réservation est confirmée",booking_rejected:"Mise à jour concernant votre demande",booking_completed:"Votre demande est terminée",booking_cancelled:"Votre réservation est annulée",payment_received:"Votre paiement a bien été reçu"},
  es:{booking_created:"Hemos recibido su solicitud",booking_pending:"Su solicitud está en revisión",booking_approved:"Su reserva está confirmada",booking_rejected:"Hay una actualización sobre su solicitud",booking_completed:"Su solicitud se ha completado",booking_cancelled:"Su reserva ha sido cancelada",payment_received:"Hemos recibido su pago"},
  ru:{booking_created:"Мы получили ваш запрос",booking_pending:"Ваш запрос находится на проверке",booking_approved:"Ваше бронирование подтверждено",booking_rejected:"Есть обновление по вашему запросу",booking_completed:"Ваш запрос выполнен",booking_cancelled:"Ваше бронирование отменено",payment_received:"Мы получили ваш платёж"},
  zh:{booking_created:"我们已收到您的申请",booking_pending:"您的申请正在审核中",booking_approved:"您的预订已确认",booking_rejected:"您的申请有更新",booking_completed:"您的申请已完成",booking_cancelled:"您的预订已取消",payment_received:"我们已收到您的付款"},
  ar:{booking_created:"استلمنا طلبكم",booking_pending:"طلبكم قيد المراجعة",booking_approved:"تم تأكيد حجزكم",booking_rejected:"هناك تحديث بخصوص طلبكم",booking_completed:"اكتمل طلبكم",booking_cancelled:"تم إلغاء حجزكم",payment_received:"استلمنا دفعتكم"},
  ku:{booking_created:"Daxwaza we hat tomarkirin",booking_pending:"Daxwaza we tê kontrolkirin",booking_approved:"Rezervasyona we hate pejirandin",booking_rejected:"Nûvekirinek li ser daxwaza we heye",booking_completed:"Karê we qediya",booking_cancelled:"Rezervasyona we hate betalkirin",payment_received:"Dravdana we hat wergirtin"},
};
function nextStep(event:EventName,lang:Lang):string{
  const copy:Record<Lang,Record<EventName,string>>={
    tr:{booking_created:"Talebiniz sistemimize güvenli biçimde kaydedildi. Ekibimiz araç, tarih ve teslim ayrıntılarını kontrol edecek. Kesin uygunluk netleştiğinde sizinle iletişime geçeceğiz. Referans numaranızı saklayın.",booking_pending:"Talebiniz aktif olarak inceleniyor. Araç veya tur uygunluğu, tarih ve operasyon ayrıntıları netleşmeden sizden kesinleşmiş işlem beklemiyoruz.",booking_approved:"Güzel haber: rezervasyonunuz onaylandı. Teslim veya buluşma ayrıntıları ile varsa ödeme adımını bu referans üzerinden takip edebilirsiniz. Bir ayrıntı değişirse ekibimiz sizinle iletişime geçer.",booking_rejected:"Bu talep mevcut koşullarda onaylanamadı. Uygun olduğunda farklı araç, tarih veya hizmet seçeneği için bizimle iletişime geçebilirsiniz.",booking_completed:"İşleminiz tamamlandı. Alperler Auto'yu tercih ettiğiniz için teşekkür ederiz. Yeni bir araç, transfer veya tur ihtiyacınız olduğunda aynı kanallardan bize ulaşabilirsiniz.",booking_cancelled:"Rezervasyonunuz iptal edildi. Yeni tarih veya farklı bir seçenek isterseniz talebinizi yeniden oluşturabilir ya da doğrudan ekibimizle iletişime geçebilirsiniz.",payment_received:"Ödemeniz güvenli biçimde muhasebe kaydına işlendi. Güncel bakiye bilgilerinizi bu rezervasyon referansı üzerinden takip edebilirsiniz."},
    en:{booking_created:"Your request was securely saved. Our team will check the vehicle, dates and handover details. We will contact you once availability is confirmed. Please keep your reference number.",booking_pending:"Your request is under active review. We are not asking you for a final commitment until vehicle or tour availability, dates and operational details are clear.",booking_approved:"Good news: your reservation is approved. You can follow handover or meeting details and any payment step with this reference. If something changes, our team will contact you.",booking_rejected:"This request could not be approved under the current conditions. You are welcome to contact us for another vehicle, date or service option.",booking_completed:"Your request is completed. Thank you for choosing Alperler Auto. Reach us through the same channels whenever you need a vehicle, transfer or tour again.",booking_cancelled:"Your reservation has been cancelled. If you want a new date or another option, create a new request or contact our team directly.",payment_received:"Your payment was securely recorded in our accounts. You can follow your current balance with this reservation reference."},
    de:{booking_created:"Ihre Anfrage wurde sicher gespeichert. Unser Team prüft Fahrzeug, Termine und Übergabedetails. Sobald die Verfügbarkeit feststeht, melden wir uns. Bitte bewahren Sie Ihre Referenznummer auf.",booking_pending:"Ihre Anfrage wird aktiv geprüft. Wir erwarten von Ihnen keinen endgültigen Schritt, bevor Fahrzeug- oder Tourverfügbarkeit, Termine und operative Details klar sind.",booking_approved:"Gute Nachricht: Ihre Reservierung ist bestätigt. Übergabe- oder Treffpunktdetails sowie offene Zahlungsschritte können Sie über diese Referenz verfolgen. Bei Änderungen meldet sich unser Team.",booking_rejected:"Diese Anfrage konnte unter den aktuellen Bedingungen nicht bestätigt werden. Kontaktieren Sie uns gerne für ein anderes Fahrzeug, Datum oder eine andere Leistung.",booking_completed:"Ihr Vorgang ist abgeschlossen. Vielen Dank, dass Sie Alperler Auto gewählt haben. Bei neuem Bedarf an Fahrzeug, Transfer oder Tour erreichen Sie uns über dieselben Kanäle.",booking_cancelled:"Ihre Reservierung wurde storniert. Für einen neuen Termin oder eine Alternative können Sie eine neue Anfrage stellen oder unser Team direkt kontaktieren.",payment_received:"Ihre Zahlung wurde sicher in unserer Buchhaltung erfasst. Den aktuellen Saldo können Sie über diese Reservierungsreferenz verfolgen."},
    fr:{booking_created:"Votre demande a été enregistrée en toute sécurité. Notre équipe vérifiera le véhicule, les dates et les détails de remise. Nous vous contacterons dès que la disponibilité sera confirmée. Conservez votre numéro de référence.",booking_pending:"Votre demande est en cours d'examen. Nous ne vous demandons aucun engagement définitif tant que la disponibilité du véhicule ou du circuit, les dates et les détails opérationnels ne sont pas clarifiés.",booking_approved:"Bonne nouvelle: votre réservation est confirmée. Vous pouvez suivre les détails de remise ou de rendez-vous et toute étape de paiement avec cette référence. En cas de changement, notre équipe vous contactera.",booking_rejected:"Cette demande n'a pas pu être confirmée dans les conditions actuelles. Contactez-nous pour un autre véhicule, une autre date ou un autre service.",booking_completed:"Votre demande est terminée. Merci d'avoir choisi Alperler Auto. Contactez-nous par les mêmes canaux pour un prochain véhicule, transfert ou circuit.",booking_cancelled:"Votre réservation a été annulée. Pour une nouvelle date ou une autre option, créez une nouvelle demande ou contactez directement notre équipe.",payment_received:"Votre paiement a été enregistré en toute sécurité. Vous pouvez suivre le solde actuel avec cette référence de réservation."},
    es:{booking_created:"Su solicitud se guardó de forma segura. Nuestro equipo revisará el vehículo, las fechas y los detalles de entrega. Le contactaremos cuando se confirme la disponibilidad. Conserve su número de referencia.",booking_pending:"Su solicitud está en revisión activa. No le pedimos un compromiso definitivo hasta aclarar la disponibilidad del vehículo o tour, las fechas y los detalles operativos.",booking_approved:"Buenas noticias: su reserva está confirmada. Puede seguir los detalles de entrega o encuentro y cualquier paso de pago con esta referencia. Si algo cambia, nuestro equipo le contactará.",booking_rejected:"Esta solicitud no pudo aprobarse con las condiciones actuales. Puede contactarnos para otro vehículo, fecha o servicio.",booking_completed:"Su solicitud está completada. Gracias por elegir Alperler Auto. Contáctenos por los mismos canales cuando necesite de nuevo un vehículo, traslado o tour.",booking_cancelled:"Su reserva ha sido cancelada. Si desea una nueva fecha u otra opción, cree una nueva solicitud o contacte directamente a nuestro equipo.",payment_received:"Su pago se registró de forma segura en nuestra contabilidad. Puede seguir el saldo actual con esta referencia de reserva."},
    ru:{booking_created:"Ваш запрос надёжно сохранён. Наша команда проверит автомобиль, даты и детали передачи. Мы свяжемся с вами, когда подтвердим доступность. Сохраните номер заявки.",booking_pending:"Ваш запрос активно проверяется. Мы не просим вас о окончательном решении, пока не будут ясны доступность автомобиля или тура, даты и операционные детали.",booking_approved:"Хорошие новости: бронирование подтверждено. Детали передачи или встречи и шаги оплаты можно отслеживать по этому номеру. Если что-то изменится, команда свяжется с вами.",booking_rejected:"Этот запрос не удалось подтвердить при текущих условиях. Свяжитесь с нами, чтобы выбрать другой автомобиль, дату или услугу.",booking_completed:"Ваш запрос выполнен. Спасибо, что выбрали Alperler Auto. Обращайтесь к нам по тем же каналам, когда снова понадобится автомобиль, трансфер или тур.",booking_cancelled:"Ваше бронирование отменено. Если нужна новая дата или другой вариант, создайте новый запрос или напрямую свяжитесь с нашей командой.",payment_received:"Ваш платёж надёжно зафиксирован в учёте. Текущий баланс можно отслеживать по этому номеру бронирования."},
    zh:{booking_created:"您的申请已安全保存。我们的团队将核对车辆、日期和交车细节。确认可订后我们会与您联系。请妥善保存参考编号。",booking_pending:"您的申请正在审核中。在车辆或行程可订情况、日期和运营细节明确之前，我们不会要求您完成最终确认。",booking_approved:"好消息：您的预订已确认。您可通过此参考编号查看交车或会面细节以及付款步骤。如有变更，我们的团队会与您联系。",booking_rejected:"根据当前条件，此申请未能获批。欢迎联系我们选择其他车辆、日期或服务。",booking_completed:"您的申请已完成。感谢选择 Alperler Auto。如再次需要车辆、接送或行程，可通过相同渠道联系我们。",booking_cancelled:"您的预订已取消。如需新的日期或其他方案，可重新提交申请或直接联系我们的团队。",payment_received:"您的付款已安全记入账目。您可通过此预订参考编号查看当前余额。"},
    ar:{booking_created:"تم حفظ طلبكم بأمان. سيراجع فريقنا المركبة والتواريخ وتفاصيل التسليم. سنتواصل معكم عند تأكيد التوفر. يرجى الاحتفاظ برقم المرجع.",booking_pending:"طلبكم قيد المراجعة النشطة. لا نطلب منكم التزاماً نهائياً قبل توضيح توفر المركبة أو الجولة والتواريخ والتفاصيل التشغيلية.",booking_approved:"خبر سار: تم تأكيد حجزكم. يمكنكم متابعة تفاصيل التسليم أو الموعد وأي خطوة دفع عبر هذا المرجع. إذا تغيّر أي تفصيل سيتواصل فريقنا معكم.",booking_rejected:"تعذّر اعتماد هذا الطلب وفق الظروف الحالية. يمكنكم التواصل معنا لاختيار مركبة أو تاريخ أو خدمة أخرى.",booking_completed:"اكتمل طلبكم. شكراً لاختياركم Alperler Auto. تواصلوا معنا عبر القنوات نفسها متى احتجتم مركبة أو نقلاً أو جولة مجدداً.",booking_cancelled:"تم إلغاء حجزكم. إذا رغبتم بتاريخ جديد أو خيار آخر يمكنكم إنشاء طلب جديد أو التواصل مباشرة مع فريقنا.",payment_received:"تم تسجيل دفعتكم بأمان في الحسابات. يمكنكم متابعة الرصيد الحالي عبر مرجع هذا الحجز."},
    ku:{booking_created:"Daxwaza we bi ewlehî hate tomarkirin. Tîma me dê erebe, dîrok û hûrguliyên teslîmê kontrol bike. Gava guncawî diyar bibe em ê bi we re têkilî daynin. Hejmara referansa xwe biparêzin.",booking_pending:"Daxwaza we bi awayekî çalak tê vekolîn. Em ji we gavê dawî naxwazin heta ku guncawiya erebe an gerê, dîrok û hûrguliyên operasyonê zelal bibin.",booking_approved:"Nûçeya baş: rezervasyona we hate pejirandin. Hûn dikarin hûrguliyên teslîm an hevdîtinê û gava dravdanê bi vê referansê bişopînin. Heke tiştek biguhere tîma me dê bi we re têkilî dayne.",booking_rejected:"Ev daxwaz di şertên niha de nehat pejirandin. Ji bo erebe, dîrok an xizmeteke din dikarin bi me re têkilî daynin.",booking_completed:"Karê we qediya. Spas ji bo hilbijartina Alperler Auto. Dema dîsa erebe, veguhestin an ger hewce be bi heman kanalan bigihin me.",booking_cancelled:"Rezervasyona we hate betalkirin. Heke dîrokeke nû an vebijarkeke din dixwazin, daxwazeke nû çêbikin an rasterast bi tîma me re têkilî daynin.",payment_received:"Dravdana we bi ewlehî di tomara hesabê de hate tomarkirin. Hûn dikarin balansa niha bi vê referansa rezervasyonê bişopînin."},
  };
  return copy[lang][event];
}
function typeLabel(type:string,lang:Lang):string{
  const values:Record<Lang,Record<string,string>>={
    tr:{RENTAL:"Araç Kiralama",TOUR:"Tur Rezervasyonu",SALE_INQUIRY:"Araç Satın Alma Talebi",APPOINTMENT:"Randevu Talebi"},
    en:{RENTAL:"Car Rental",TOUR:"Tour Reservation",SALE_INQUIRY:"Vehicle Purchase Inquiry",APPOINTMENT:"Appointment Request"},
    de:{RENTAL:"Autovermietung",TOUR:"Tourreservierung",SALE_INQUIRY:"Fahrzeugkauf-Anfrage",APPOINTMENT:"Terminanfrage"},
    fr:{RENTAL:"Location de voiture",TOUR:"Réservation de circuit",SALE_INQUIRY:"Demande d'achat de véhicule",APPOINTMENT:"Demande de rendez-vous"},
    es:{RENTAL:"Alquiler de coche",TOUR:"Reserva de tour",SALE_INQUIRY:"Consulta de compra de vehículo",APPOINTMENT:"Solicitud de cita"},
    ru:{RENTAL:"Аренда автомобиля",TOUR:"Бронирование тура",SALE_INQUIRY:"Запрос на покупку автомобиля",APPOINTMENT:"Запрос на встречу"},
    zh:{RENTAL:"汽车租赁",TOUR:"行程预订",SALE_INQUIRY:"购车咨询",APPOINTMENT:"预约申请"},
    ar:{RENTAL:"تأجير سيارة",TOUR:"حجز جولة",SALE_INQUIRY:"استفسار شراء مركبة",APPOINTMENT:"طلب موعد"},
    ku:{RENTAL:"Kirêkirina erebeyê",TOUR:"Rezervasyona gerê",SALE_INQUIRY:"Daxwaza kirîna erebeyê",APPOINTMENT:"Daxwaza hevdîtinê"},
  };
  return values[lang][type]||type;
}
function labels(lang:Lang){
  const map:Record<Lang,{hello:string;reference:string;service:string;start:string;end:string;total:string;paymentMethod:string;payment:string;paid:string;balance:string;status:string;next:string}>={
    tr:{hello:"Merhaba",reference:"Referans",service:"Hizmet",start:"Başlangıç",end:"Bitiş",total:"Toplam",paymentMethod:"Ödeme yöntemi",payment:"Ödeme durumu",paid:"Ödenen",balance:"Kalan",status:"Rezervasyon durumu",next:"Sıradaki adım"},
    en:{hello:"Hello",reference:"Reference",service:"Service",start:"Start",end:"End",total:"Total",paymentMethod:"Payment method",payment:"Payment status",paid:"Paid",balance:"Balance",status:"Reservation status",next:"Next step"},
    de:{hello:"Hallo",reference:"Referenz",service:"Leistung",start:"Beginn",end:"Ende",total:"Gesamt",paymentMethod:"Zahlungsart",payment:"Zahlungsstatus",paid:"Bezahlt",balance:"Restbetrag",status:"Reservierungsstatus",next:"Nächster Schritt"},
    fr:{hello:"Bonjour",reference:"Référence",service:"Service",start:"Début",end:"Fin",total:"Total",paymentMethod:"Mode de paiement",payment:"Statut du paiement",paid:"Payé",balance:"Solde",status:"Statut de réservation",next:"Prochaine étape"},
    es:{hello:"Hola",reference:"Referencia",service:"Servicio",start:"Inicio",end:"Fin",total:"Total",paymentMethod:"Método de pago",payment:"Estado del pago",paid:"Pagado",balance:"Saldo",status:"Estado de la reserva",next:"Siguiente paso"},
    ru:{hello:"Здравствуйте",reference:"Номер",service:"Услуга",start:"Начало",end:"Окончание",total:"Итого",paymentMethod:"Способ оплаты",payment:"Статус оплаты",paid:"Оплачено",balance:"Остаток",status:"Статус бронирования",next:"Следующий шаг"},
    zh:{hello:"您好",reference:"参考编号",service:"服务",start:"开始",end:"结束",total:"合计",paymentMethod:"支付方式",payment:"支付状态",paid:"已付",balance:"余额",status:"预订状态",next:"下一步"},
    ar:{hello:"مرحباً",reference:"المرجع",service:"الخدمة",start:"البداية",end:"النهاية",total:"الإجمالي",paymentMethod:"طريقة الدفع",payment:"حالة الدفع",paid:"المدفوع",balance:"المتبقي",status:"حالة الحجز",next:"الخطوة التالية"},
    ku:{hello:"Silav",reference:"Referans",service:"Xizmet",start:"Destpêk",end:"Dawî",total:"Giştî",paymentMethod:"Rêbaza dravdanê",payment:"Rewşa dravdanê",paid:"Dayîn",balance:"Mayî",status:"Rewşa rezervasyonê",next:"Gava din"},
  };
  return map[lang];
}
function formatDate(value:string|null,lang:Lang):string{if(!value)return"-";const date=new Date(value);if(Number.isNaN(date.getTime()))return value;const tag=lang==="tr"?"tr-TR":lang==="zh"?"zh-CN":lang==="ku"?"tr-TR":lang;try{return new Intl.DateTimeFormat(tag,{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(date);}catch{return new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(date);}}
function formatMoney(value:number|null,currency:string,lang:Lang):string{if(value===null||!Number.isFinite(Number(value)))return"-";const tag=lang==="tr"?"tr-TR":lang==="zh"?"zh-CN":lang==="ku"?"tr-TR":lang;try{return new Intl.NumberFormat(tag,{style:"currency",currency,maximumFractionDigits:2}).format(Number(value));}catch{return`${value} ${currency}`;}}
function paymentMethodLabel(value:string,lang:Lang):string{
  const key=value.toUpperCase();
  const map:Record<Lang,Record<string,string>>={
    tr:{NONE:"Ödeme gerekmiyor",CARD:"Kart",EFT:"Havale / EFT",OFFICE:"Ofiste ödeme"},
    en:{NONE:"No payment required",CARD:"Card",EFT:"Bank transfer",OFFICE:"Pay at office"},
    de:{NONE:"Keine Zahlung erforderlich",CARD:"Karte",EFT:"Überweisung",OFFICE:"Zahlung im Büro"},
    fr:{NONE:"Aucun paiement requis",CARD:"Carte",EFT:"Virement bancaire",OFFICE:"Paiement au bureau"},
    es:{NONE:"No se requiere pago",CARD:"Tarjeta",EFT:"Transferencia bancaria",OFFICE:"Pago en oficina"},
    ru:{NONE:"Оплата не требуется",CARD:"Карта",EFT:"Банковский перевод",OFFICE:"Оплата в офисе"},
    zh:{NONE:"无需付款",CARD:"银行卡",EFT:"银行转账",OFFICE:"到店支付"},
    ar:{NONE:"لا يلزم الدفع",CARD:"بطاقة",EFT:"تحويل بنكي",OFFICE:"الدفع في المكتب"},
    ku:{NONE:"Dravdan ne hewce ye",CARD:"Kart",EFT:"Havale / EFT",OFFICE:"Dravdana li ofîsê"},
  };
  return map[lang][key]||key;
}
function paymentStatusLabel(value:string,lang:Lang):string{
  const key=value.toUpperCase();
  const map:Record<Lang,Record<string,string>>={
    tr:{NOT_REQUIRED:"Gerekmiyor",PENDING:"Ödeme bekleniyor",PAID:"Ödendi",FAILED:"Başarısız",REFUNDED:"İade edildi",CANCELLED:"İptal edildi"},
    en:{NOT_REQUIRED:"Not required",PENDING:"Payment pending",PAID:"Paid",FAILED:"Failed",REFUNDED:"Refunded",CANCELLED:"Cancelled"},
    de:{NOT_REQUIRED:"Nicht erforderlich",PENDING:"Zahlung ausstehend",PAID:"Bezahlt",FAILED:"Fehlgeschlagen",REFUNDED:"Erstattet",CANCELLED:"Storniert"},
    fr:{NOT_REQUIRED:"Non requis",PENDING:"Paiement en attente",PAID:"Payé",FAILED:"Échec",REFUNDED:"Remboursé",CANCELLED:"Annulé"},
    es:{NOT_REQUIRED:"No requerido",PENDING:"Pago pendiente",PAID:"Pagado",FAILED:"Fallido",REFUNDED:"Reembolsado",CANCELLED:"Cancelado"},
    ru:{NOT_REQUIRED:"Не требуется",PENDING:"Ожидает оплаты",PAID:"Оплачено",FAILED:"Ошибка",REFUNDED:"Возвращено",CANCELLED:"Отменено"},
    zh:{NOT_REQUIRED:"不需要",PENDING:"待付款",PAID:"已付款",FAILED:"失败",REFUNDED:"已退款",CANCELLED:"已取消"},
    ar:{NOT_REQUIRED:"غير مطلوب",PENDING:"بانتظار الدفع",PAID:"مدفوع",FAILED:"فشل",REFUNDED:"مُسترد",CANCELLED:"ملغى"},
    ku:{NOT_REQUIRED:"Ne hewce ye",PENDING:"Dravdan tê payîn",PAID:"Hate dayîn",FAILED:"Têk çû",REFUNDED:"Hate vegerandin",CANCELLED:"Hate betalkirin"},
  };
  return map[lang][key]||key;
}
function bookingStatusLabel(value:string,lang:Lang):string{
  const key=value.toUpperCase();
  const map:Record<Lang,Record<string,string>>={
    tr:{PENDING:"Onay bekliyor",APPROVED:"Onaylandı",REJECTED:"Onaylanmadı",COMPLETED:"Tamamlandı",CANCELLED:"İptal edildi"},
    en:{PENDING:"Pending approval",APPROVED:"Approved",REJECTED:"Not approved",COMPLETED:"Completed",CANCELLED:"Cancelled"},
    de:{PENDING:"Bestätigung ausstehend",APPROVED:"Bestätigt",REJECTED:"Nicht bestätigt",COMPLETED:"Abgeschlossen",CANCELLED:"Storniert"},
    fr:{PENDING:"En attente de confirmation",APPROVED:"Confirmé",REJECTED:"Non confirmé",COMPLETED:"Terminé",CANCELLED:"Annulé"},
    es:{PENDING:"Pendiente de aprobación",APPROVED:"Aprobada",REJECTED:"No aprobada",COMPLETED:"Completada",CANCELLED:"Cancelada"},
    ru:{PENDING:"Ожидает подтверждения",APPROVED:"Подтверждено",REJECTED:"Не подтверждено",COMPLETED:"Завершено",CANCELLED:"Отменено"},
    zh:{PENDING:"待确认",APPROVED:"已确认",REJECTED:"未通过",COMPLETED:"已完成",CANCELLED:"已取消"},
    ar:{PENDING:"بانتظار التأكيد",APPROVED:"مؤكد",REJECTED:"غير مؤكد",COMPLETED:"مكتمل",CANCELLED:"ملغى"},
    ku:{PENDING:"Li benda pejirandinê",APPROVED:"Hate pejirandin",REJECTED:"Nehat pejirandin",COMPLETED:"Qediya",CANCELLED:"Hate betalkirin"},
  };
  return map[lang][key]||key;
}
function paymentNotice(booking:BookingRow,event:EventName,lang:Lang,context:NotificationContext,medium:NoticeMedium):string{
  if(event==="payment_received"||booking.payment_status==="PAID")return"";
  const method=(context.paymentMethod||booking.payment_method||"").toUpperCase();
  const sms:Record<string,Record<Lang,string>>={
    OFFICE:{tr:"Ödeme ofiste yapılacaktır. Bu mesaj ödeme makbuzu değildir; tahsilat sonrası ayrıca onay gönderilir.",en:"Payment will be collected at the office. This message is not a receipt; a separate confirmation follows collection.",de:"Die Zahlung erfolgt im Büro. Diese Nachricht ist kein Zahlungsbeleg; nach der Zahlung folgt eine Bestätigung.",fr:"Le paiement sera effectué au bureau. Ce message n’est pas un reçu; une confirmation suivra après encaissement.",es:"El pago se realizará en la oficina. Este mensaje no es un recibo; después del cobro enviaremos una confirmación aparte.",ru:"Оплата будет принята в офисе. Это сообщение не является квитанцией; после оплаты придёт отдельное подтверждение.",zh:"将在门店收款。本短信不是收据；收款后会另行发送确认。",ar:"سيتم تحصيل الدفع في المكتب. هذه الرسالة ليست إيصالاً؛ ستُرسل تأكيد منفصل بعد التحصيل.",ku:"Dravdan li ofîsê dê were kirin. Ev peyam makbûza dravdanê nîne; piştî standinê pejirandinek cuda tê şandin."},
    EFT:{tr:"Havale / EFT henüz bekleniyor. Bu mesaj ödeme makbuzu değildir; doğrulama sonrası ayrıca onay gönderilir.",en:"Bank transfer is still pending. This message is not a receipt; a confirmation follows verification.",de:"Die Überweisung ist noch ausstehend. Diese Nachricht ist kein Zahlungsbeleg; nach Bestätigung folgt eine Zahlungsbestätigung.",fr:"Le virement est encore en attente. Ce message n’est pas un reçu; une confirmation suivra après validation.",es:"La transferencia aún está pendiente. Este mensaje no es un recibo; tras la verificación enviaremos una confirmación.",ru:"Банковский перевод ещё ожидается. Это сообщение не является квитанцией; после проверки придёт подтверждение.",zh:"银行转账仍待确认。本短信不是收据；核实后会另行发送确认。",ar:"التحويل البنكي ما زال معلقاً. هذه الرسالة ليست إيصالاً؛ ستُرسل تأكيد بعد التحقق.",ku:"Havale / EFT hîn tê payîn. Ev peyam makbûza dravdanê nîne; piştî pejirandinê pejirandinek cuda tê şandin."},
    CARD:{tr:"Kart ödemesi henüz tamamlanmadı. Onay yalnız başarılı tahsilat sonrasında gönderilir.",en:"Card payment is not completed yet. Confirmation follows only after a successful charge.",de:"Die Kartenzahlung ist noch nicht abgeschlossen. Die Bestätigung folgt erst nach erfolgreicher Zahlung.",fr:"Le paiement par carte n’est pas encore finalisé. La confirmation suit uniquement après paiement réussi.",es:"El pago con tarjeta aún no está completado. La confirmación se envía solo tras un cobro correcto.",ru:"Оплата картой ещё не завершена. Подтверждение отправляется только после успешного списания.",zh:"银行卡付款尚未完成。仅在成功扣款后发送确认。",ar:"دفع البطاقة لم يكتمل بعد. يُرسل التأكيد فقط بعد التحصيل الناجح.",ku:"Dravdana kartê hîn neqediyaye. Pejirandin tenê piştî standina serkeftî tê şandin."},
  };
  const email:Record<string,Record<Lang,string>>={
    OFFICE:{tr:"Ödeme ofiste yapılacaktır. Bu e-posta rezervasyon kaydınızı doğrular; ödeme makbuzu değildir. Tahsilat yapıldığında ayrıca ödeme onayı gönderilecektir.",en:"Payment will be collected at the office. This email confirms your reservation and is not a payment receipt. A separate payment confirmation will be sent after collection.",de:"Die Zahlung erfolgt im Büro. Diese E-Mail bestätigt Ihre Reservierung, ist jedoch kein Zahlungsbeleg. Nach der Zahlung erhalten Sie eine separate Bestätigung.",fr:"Le paiement sera effectué au bureau. Cet e-mail confirme votre réservation mais ne constitue pas un reçu de paiement. Une confirmation distincte sera envoyée après encaissement.",es:"El pago se realizará en la oficina. Este correo confirma su reserva y no es un recibo de pago. Tras el cobro enviaremos una confirmación aparte.",ru:"Оплата будет принята в офисе. Это письмо подтверждает бронирование и не является квитанцией. После оплаты придёт отдельное подтверждение.",zh:"将在门店收款。本邮件确认您的预订，并非付款收据。收款后将另行发送付款确认。",ar:"سيتم تحصيل الدفع في المكتب. يؤكد هذا البريد حجزكم وليس إيصالاً بالدفع. سيُرسل تأكيد دفع منفصل بعد التحصيل.",ku:"Dravdan li ofîsê dê were kirin. Ev e-name rezervasyona we pejirandî dike; makbûza dravdanê nîne. Dema standin çêbibe pejirandina dravdanê ya cuda tê şandin."},
    EFT:{tr:"Havale / EFT ödemesi henüz bekleniyor. Bu e-posta ödeme makbuzu değildir; tahsilat doğrulandığında ayrıca ödeme onayı gönderilecektir.",en:"Your bank transfer is still pending. This email is not a payment receipt; a separate confirmation will be sent after payment is verified.",de:"Die Überweisung ist noch ausstehend. Diese E-Mail ist kein Zahlungsbeleg; nach Bestätigung der Zahlung erhalten Sie eine separate Bestätigung.",fr:"Le virement est encore en attente. Cet e-mail n’est pas un reçu; une confirmation distincte sera envoyée après validation du paiement.",es:"Su transferencia aún está pendiente. Este correo no es un recibo; tras verificar el pago enviaremos una confirmación aparte.",ru:"Банковский перевод ещё ожидается. Это письмо не является квитанцией; после проверки оплаты придёт отдельное подтверждение.",zh:"银行转账仍待确认。本邮件不是付款收据；核实付款后将另行发送确认。",ar:"التحويل البنكي ما زال معلقاً. هذا البريد ليس إيصالاً؛ سيُرسل تأكيد منفصل بعد التحقق من الدفع.",ku:"Dravdana Havale / EFT hîn tê payîn. Ev e-name makbûza dravdanê nîne; dema standin were pejirandin pejirandina dravdanê ya cuda tê şandin."},
    CARD:{tr:"Kart ödemesi henüz tamamlanmadı. Ödeme onayı yalnız başarılı tahsilat sonrasında gönderilir.",en:"Card payment is not completed yet. A payment confirmation is sent only after a successful charge.",de:"Die Kartenzahlung ist noch nicht abgeschlossen. Eine Zahlungsbestätigung wird erst nach erfolgreicher Belastung gesendet.",fr:"Le paiement par carte n’est pas encore finalisé. Une confirmation sera envoyée uniquement après encaissement réussi.",es:"El pago con tarjeta aún no está completado. La confirmación de pago se envía solo tras un cobro correcto.",ru:"Оплата картой ещё не завершена. Подтверждение оплаты отправляется только после успешного списания.",zh:"银行卡付款尚未完成。仅在成功扣款后发送付款确认。",ar:"دفع البطاقة لم يكتمل بعد. يُرسل تأكيد الدفع فقط بعد التحصيل الناجح.",ku:"Dravdana kartê hîn neqediyaye. Pejirandina dravdanê tenê piştî standina serkeftî tê şandin."},
  };
  const table=medium==="sms"?sms:email;
  return table[method]?.[lang]||"";
}
async function bookingById(id:string):Promise<BookingRow|null>{const response=await db(`bookings?id=eq.${encodeURIComponent(id)}&deleted_at=is.null&select=id,reference,booking_type,item_name,customer_name,customer_email,customer_phone,customer_locale,start_at,end_at,total_price,currency,payment_method,payment_status,amount_paid,status&limit=1`);if(!response.ok)throw new Error(`BOOKING_READ_${response.status}`);const rows=await response.json();return Array.isArray(rows)&&rows[0]?rows[0] as BookingRow:null;}
async function siteConfig():Promise<Record<string,any>>{const response=await db("site_config?key=in.(business_profile,site_settings)&select=key,value");if(!response.ok)return{};const rows=await response.json();const result:Record<string,any>={};for(const row of Array.isArray(rows)?rows:[])result[row.key]=row.value||{};return result;}
async function templateFor(event:EventName,audience:Audience,lang:Lang):Promise<TemplateRow|null>{const response=await db(`notification_templates?event_key=eq.${encodeURIComponent(event)}&audience=eq.${audience}&locale=eq.${lang}&is_active=eq.true&select=subject_template,intro_template,next_step_template&limit=1`);if(!response.ok)return null;const rows=await response.json().catch(()=>[]);return Array.isArray(rows)&&rows[0]?rows[0] as TemplateRow:null;}
function renderTemplate(value:string,vars:Record<string,string>,max:number):string{return clean(value,max).replace(/\{\{([a-z_]+)\}\}/g,(_match,key:string)=>vars[key]??"");}
function notificationVars(booking:BookingRow,lang:Lang,context:NotificationContext):Record<string,string>{const paid=moneyValue(booking.amount_paid);const total=moneyValue(booking.total_price);const balance=Math.max(0,Math.round((total-paid)*100)/100);const currentPayment=moneyValue(context.paymentAmount);return{customer_name:booking.customer_name,reference:booking.reference,item_name:booking.item_name,total:formatMoney(total,booking.currency,lang),payment_method:paymentMethodLabel(context.paymentMethod||booking.payment_method,lang),payment_status:paymentStatusLabel(booking.payment_status,lang),amount_paid:formatMoney(paid,booking.currency,lang),balance_due:formatMoney(balance,booking.currency,lang),payment_amount:formatMoney(currentPayment||paid,booking.currency,lang)};}
function paymentNotice(booking:BookingRow,event:EventName,lang:Lang,context:NotificationContext,medium:NoticeMedium):string{
  if(event==="payment_received"||booking.payment_status==="PAID")return"";
  const method=(context.paymentMethod||booking.payment_method||"").toUpperCase();
  if(medium==="sms"){
    if(method==="OFFICE")return lang==="tr"?"Ödeme ofiste yapılacaktır. Bu mesaj ödeme makbuzu değildir; tahsilat sonrası ayrıca onay gönderilir.":lang==="de"?"Die Zahlung erfolgt im Büro. Diese Nachricht ist kein Zahlungsbeleg; nach der Zahlung folgt eine Bestätigung.":lang==="fr"?"Le paiement sera effectué au bureau. Ce message n’est pas un reçu; une confirmation suivra après encaissement.":"Payment will be collected at the office. This message is not a receipt; a separate confirmation follows collection.";
    if(method==="EFT")return lang==="tr"?"Havale / EFT henüz bekleniyor. Bu mesaj ödeme makbuzu değildir; doğrulama sonrası ayrıca onay gönderilir.":lang==="de"?"Die Überweisung ist noch ausstehend. Diese Nachricht ist kein Zahlungsbeleg; nach Bestätigung folgt eine Zahlungsbestätigung.":lang==="fr"?"Le virement est encore en attente. Ce message n’est pas un reçu; une confirmation suivra après validation.":"Bank transfer is still pending. This message is not a receipt; a confirmation follows verification.";
    if(method==="CARD")return lang==="tr"?"Kart ödemesi henüz tamamlanmadı. Onay yalnız başarılı tahsilat sonrasında gönderilir.":lang==="de"?"Die Kartenzahlung ist noch nicht abgeschlossen. Die Bestätigung folgt erst nach erfolgreicher Zahlung.":lang==="fr"?"Le paiement par carte n’est pas encore finalisé. La confirmation suit uniquement après paiement réussi.":"Card payment is not completed yet. Confirmation follows only after a successful charge.";
    return"";
  }
  if(method==="OFFICE")return lang==="tr"?"Ödeme ofiste yapılacaktır. Bu e-posta rezervasyon kaydınızı doğrular; ödeme makbuzu değildir. Tahsilat yapıldığında ayrıca ödeme onayı gönderilecektir.":lang==="de"?"Die Zahlung erfolgt im Büro. Diese E-Mail bestätigt Ihre Reservierung, ist jedoch kein Zahlungsbeleg. Nach der Zahlung erhalten Sie eine separate Bestätigung.":lang==="fr"?"Le paiement sera effectué au bureau. Cet e-mail confirme votre réservation mais ne constitue pas un reçu de paiement. Une confirmation distincte sera envoyée après encaissement.":"Payment will be collected at the office. This email confirms your reservation and is not a payment receipt. A separate payment confirmation will be sent after collection.";
  if(method==="EFT")return lang==="tr"?"Havale / EFT ödemesi henüz bekleniyor. Bu e-posta ödeme makbuzu değildir; tahsilat doğrulandığında ayrıca ödeme onayı gönderilecektir.":lang==="de"?"Die Überweisung ist noch ausstehend. Diese E-Mail ist kein Zahlungsbeleg; nach Bestätigung der Zahlung erhalten Sie eine separate Bestätigung.":lang==="fr"?"Le virement est encore en attente. Cet e-mail n’est pas un reçu; une confirmation distincte sera envoyée après validation du paiement.":"Your bank transfer is still pending. This email is not a payment receipt; a separate confirmation will be sent after payment is verified.";
  if(method==="CARD")return lang==="tr"?"Kart ödemesi henüz tamamlanmadı. Ödeme onayı yalnız başarılı tahsilat sonrasında gönderilir.":lang==="de"?"Die Kartenzahlung ist noch nicht abgeschlossen. Eine Zahlungsbestätigung wird erst nach erfolgreicher Belastung gesendet.":lang==="fr"?"Le paiement par carte n’est pas encore finalisé. Une confirmation sera envoyée uniquement après encaissement réussi.":"Card payment is not completed yet. A payment confirmation is sent only after a successful charge.";
  return"";
}

async function buildMail(booking:BookingRow,event:EventName,config:Record<string,any>,admin:boolean,context:NotificationContext){
  const lang=admin?"tr":language(booking.customer_locale);const l=labels(lang);const settings=config.site_settings||{};const profile=config.business_profile||{};
  const vars=notificationVars(booking,lang,context);const total=moneyValue(booking.total_price);const paid=moneyValue(booking.amount_paid);const balance=Math.max(0,Math.round((total-paid)*100)/100);
  const template=admin?null:await templateFor(event,"CUSTOMER",lang);
  const subject=admin?`${event==="payment_received"?"Ödeme alındı":"Yeni işlem"} | ${typeLabel(booking.booking_type,"tr")} | ${booking.reference}`:template?renderTemplate(template.subject_template,vars,240):`${subjectCopy[lang][event]} | ${booking.reference}`;
  const introText=admin?`${booking.customer_name} adlı müşteri için ${typeLabel(booking.booking_type,"tr").toLowerCase()} kaydında ${event==="payment_received"?"ödeme alındı":"yeni bir güncelleme var"}.`:template?renderTemplate(template.intro_template,vars,3000):`${l.hello} ${booking.customer_name}, talebiniz ${booking.reference} referansıyla sistemimize kaydedildi.`;
  const nextText=template?renderTemplate(template.next_step_template,vars,3000):nextStep(event,lang);
  const logoUrl=clean(settings.logoUrl,1000);const logo=/^https:\/\//i.test(logoUrl)?`<img src="${escapeHtml(logoUrl)}" alt="Alperler Auto" style="max-height:58px;max-width:220px;margin-bottom:20px" />`:`<div style="font-family:Georgia,serif;font-size:26px;font-weight:800;margin-bottom:20px">Alperler Auto</div>`;
  const phone=clean(settings.phone||profile.phone,80);const email=clean(settings.email||profile.email,180);const address=clean(settings.address||profile.address,300);const website=clean(profile.website,400);
  const social=[['Instagram',settings.instagramUrl],['Facebook',settings.facebookUrl],['TikTok',settings.tiktokUrl],['YouTube',settings.youtubeUrl],['X',settings.twitterUrl]].filter(([,url])=>typeof url==="string"&&/^https:\/\//i.test(String(url))).map(([name,url])=>`<a href="${escapeHtml(url)}" style="display:inline-block;margin:0 12px 8px 0;color:#bfdbfe;text-decoration:none;font-weight:700">${escapeHtml(name)}</a>`).join("");
  const rows=[[l.reference,booking.reference],[l.service,booking.item_name],[l.start,formatDate(booking.start_at,lang)],[l.end,formatDate(booking.end_at,lang)],[l.total,formatMoney(total,booking.currency,lang)],[l.paymentMethod,paymentMethodLabel(context.paymentMethod||booking.payment_method,lang)],[l.payment,paymentStatusLabel(booking.payment_status,lang)],[l.paid,formatMoney(paid,booking.currency,lang)],[l.balance,formatMoney(balance,booking.currency,lang)],[l.status,bookingStatusLabel(booking.status,lang)]];
  const notice=paymentNotice(booking,event,lang,context,"email");const noticeHtml=notice?`<div style="margin-top:18px;padding:16px;border-radius:14px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;font-size:14px;line-height:1.65"><strong>${escapeHtml(paymentMethodLabel(context.paymentMethod||booking.payment_method,lang))}</strong><br>${escapeHtml(notice)}</div>`:"";
  const adminDetails=admin?`<div style="margin-top:18px;padding:14px 16px;border-radius:12px;background:#fff7ed;color:#9a3412;font-size:13px;line-height:1.6"><strong>Müşteri iletişimi</strong><br>${escapeHtml(booking.customer_phone)}${booking.customer_email?` · ${escapeHtml(booking.customer_email)}`:""}</div>`:"";
  const contact=[phone,email,address,website].filter(Boolean).map(escapeHtml).join(" · ");
  const html=`<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,Helvetica,sans-serif;color:#0f172a"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fff;border:1px solid #dbe3ee;border-radius:20px;overflow:hidden;box-shadow:0 10px 30px rgba(15,23,42,.06)"><tr><td style="padding:32px">${logo}<div style="font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#2563eb">${escapeHtml(typeLabel(booking.booking_type,lang))}</div><h1 style="font-size:28px;line-height:1.2;margin:10px 0 14px">${escapeHtml(subject)}</h1><p style="font-size:16px;line-height:1.7;color:#475569;margin:0 0 22px">${escapeHtml(introText)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f8fafc;border-radius:14px">${rows.map(([label,value])=>`<tr><td style="padding:10px 16px;color:#64748b;font-size:13px;border-bottom:1px solid #edf2f7">${escapeHtml(label)}</td><td style="padding:10px 16px;text-align:right;font-weight:700;font-size:14px;border-bottom:1px solid #edf2f7">${escapeHtml(value)}</td></tr>`).join("")}</table>${noticeHtml}<div style="margin-top:20px;padding:18px;border-radius:14px;background:#eff6ff;border:1px solid #bfdbfe"><div style="font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#1d4ed8">${escapeHtml(l.next)}</div><p style="margin:8px 0 0;color:#1e3a8a;font-size:14px;line-height:1.65">${escapeHtml(nextText)}</p></div>${adminDetails}</td></tr><tr><td style="background:#071124;color:#cbd5e1;padding:24px 32px;font-size:12px;line-height:1.75"><strong style="color:#fff;font-size:14px">Alperler Auto</strong>${contact?`<br>${contact}`:""}${social?`<div style="margin-top:12px">${social}</div>`:""}</td></tr></table></td></tr></table></body></html>`;
  const plain=`${subject}\n\n${introText}\n\n${rows.map(([label,value])=>`${label}: ${value}`).join("\n")}${notice?`\n\n${notice}`:""}\n\n${l.next}: ${nextText}\n\nAlperler Auto${phone?` | ${phone}`:""}${email?` | ${email}`:""}`;
  return{subject,html,text:plain};
}

function normalizePhone(value:string):string|null{let phone=value.trim().replace(/[^0-9+]/g,"");if(phone.startsWith("00"))phone=`+${phone.slice(2)}`;if(/^05\d{9}$/.test(phone))phone=`+9${phone}`;else if(/^5\d{9}$/.test(phone))phone=`+90${phone}`;else if(/^90\d{10}$/.test(phone))phone=`+${phone}`;return/^\+[1-9]\d{7,14}$/.test(phone)?phone:null;}
async function acquire(bookingId:string,eventKey:string,channel:Channel,recipient:string):Promise<DeliveryLease>{const query=`notification_deliveries?booking_id=eq.${encodeURIComponent(bookingId)}&event_key=eq.${encodeURIComponent(eventKey)}&channel=eq.${channel}&select=id,status,provider_message_id,attempt_count&limit=1`;let response=await db(query);if(!response.ok)throw new Error("DELIVERY_STATE_READ_FAILED");let rows=await response.json();const existing=Array.isArray(rows)?rows[0]:null;if(existing&&["SENT","DELIVERED","PROCESSING"].includes(String(existing.status)))return{acquired:false,priorMessageId:existing.provider_message_id||undefined};if(existing?.id){response=await db(`notification_deliveries?id=eq.${encodeURIComponent(existing.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"PROCESSING",attempt_count:Number(existing.attempt_count||0)+1,last_error:null})});if(!response.ok)throw new Error("DELIVERY_LEASE_UPDATE_FAILED");return{acquired:true,id:existing.id};}response=await db("notification_deliveries?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({booking_id:bookingId,event_key:eventKey,channel,recipient,status:"PROCESSING",attempt_count:1})});if(response.status===409)return{acquired:false};if(!response.ok)throw new Error("DELIVERY_LEASE_CREATE_FAILED");rows=await response.json();return{acquired:true,id:rows?.[0]?.id};}
async function finish(id:string|undefined,state:ChannelState,provider:string,messageId?:string,reason?:string):Promise<void>{if(!id)return;const status=state==="sent"?"SENT":state==="failed"?"FAILED":"SKIPPED";await db(`notification_deliveries?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status,provider,provider_message_id:messageId||null,last_error:reason||null,sent_at:state==="sent"?new Date().toISOString():null})});}

async function emailChannel(to:string|null,booking:BookingRow,event:EventName,deliveryKey:string,config:Record<string,any>,admin:boolean,context:NotificationContext,credentials:ResendCredentials):Promise<ChannelReport>{
  if(!to)return{state:"skipped",reason:"EMAIL_MISSING"};const channel:Channel=admin?"ADMIN_EMAIL":"EMAIL";const lease=await acquire(booking.id,deliveryKey,channel,to);if(!lease.acquired)return{state:"sent",providerMessageId:lease.priorMessageId};
  if(!credentials.configured){await finish(lease.id,"not_configured","resend",undefined,"EMAIL_NOT_CONFIGURED");return{state:"not_configured",reason:"EMAIL_NOT_CONFIGURED"};}
  try{const mail=await buildMail(booking,event,config,admin,context);const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${credentials.apiKey}`,"content-type":"application/json"},body:JSON.stringify({from:credentials.mailFrom,to:[to],subject:mail.subject,html:mail.html,text:mail.text}),signal:AbortSignal.timeout(10_000)});const result=await response.json().catch(()=>({}));if(!response.ok||!result.id)throw new Error(`EMAIL_SEND_FAILED_${response.status}`);await finish(lease.id,"sent","resend",String(result.id));return{state:"sent",providerMessageId:String(result.id)};}catch(error){const reason=error instanceof Error?error.message:"EMAIL_SEND_FAILED";await finish(lease.id,"failed","resend",undefined,reason);return{state:"failed",reason};}
}
async function smsChannel(booking:BookingRow,event:EventName,deliveryKey:string,context:NotificationContext,credentials:TwilioCredentials):Promise<ChannelReport>{
  const to=normalizePhone(booking.customer_phone);if(!to)return{state:"skipped",reason:"PHONE_MISSING_OR_INVALID"};const lease=await acquire(booking.id,deliveryKey,"SMS",to);if(!lease.acquired)return{state:"sent",providerMessageId:lease.priorMessageId};
  if(!credentials.configured){await finish(lease.id,"not_configured","twilio",undefined,"SMS_NOT_CONFIGURED");return{state:"not_configured",reason:"SMS_NOT_CONFIGURED"};}
  const lang=language(booking.customer_locale);const vars=notificationVars(booking,lang,context);const template=await templateFor(event,"CUSTOMER",lang);const subject=template?renderTemplate(template.subject_template,vars,240):subjectCopy[lang][event];const intro=template?renderTemplate(template.intro_template,vars,1200):`${booking.item_name} | ${booking.reference}`;const next=template?renderTemplate(template.next_step_template,vars,1200):nextStep(event,lang);const notice=paymentNotice(booking,event,lang,context,"sms");const body=`${subject} | ${intro}${notice?` ${notice}`:""} ${next}`.replace(/\s+/g," ").trim().slice(0,420);
  try{const payload=new URLSearchParams({To:to,Body:body});if(credentials.messagingServiceSid)payload.set("MessagingServiceSid",credentials.messagingServiceSid);else payload.set("From",credentials.from);const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(credentials.accountSid)}/Messages.json`,{method:"POST",headers:{authorization:`Basic ${btoa(`${credentials.accountSid}:${credentials.authToken}`)}`,"content-type":"application/x-www-form-urlencoded"},body:payload,signal:AbortSignal.timeout(10_000)});const result=await response.json().catch(()=>({}));if(!response.ok||!result.sid)throw new Error(`SMS_SEND_FAILED_${response.status}`);await finish(lease.id,"sent","twilio",String(result.sid));return{state:"sent",providerMessageId:String(result.sid)};}catch(error){const reason=error instanceof Error?error.message:"SMS_SEND_FAILED";await finish(lease.id,"failed","twilio",undefined,reason);return{state:"failed",reason};}
}

Deno.serve(async(request)=>{
  if(request.method!=="POST")return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);if(!URL||!SERVICE_KEY)return json({ok:false,code:"SERVER_CONFIG_MISSING"},503);if(request.headers.get("authorization")!==`Bearer ${SERVICE_KEY}`)return json({ok:false,code:"FORBIDDEN"},403);
  let input:any;try{input=await request.json();}catch{return json({ok:false,code:"INVALID_JSON"},400);}const bookingId=clean(input?.bookingId,80);const event=clean(input?.event,40) as EventName;if(!bookingId||!EVENTS.includes(event))return json({ok:false,code:"INVALID_NOTIFICATION_REQUEST"},400);
  const suppliedKey=clean(input?.deliveryKey,120);const deliveryKey=/^[a-z0-9:_-]{3,120}$/i.test(suppliedKey)?suppliedKey:event;const context:NotificationContext={};const method=clean(input?.paymentMethod,20).toUpperCase();if(["CARD","EFT","OFFICE","NONE"].includes(method))context.paymentMethod=method;const paymentAmount=moneyValue(input?.paymentAmount);if(paymentAmount>0)context.paymentAmount=paymentAmount;const paymentTransactionId=clean(input?.paymentTransactionId,80);if(paymentTransactionId)context.paymentTransactionId=paymentTransactionId;
  try{const booking=await bookingById(bookingId);if(!booking)return json({ok:false,code:"BOOKING_NOT_FOUND"},404);const[config,resend,twilio]=await Promise.all([siteConfig(),resolveResendCredentials(),resolveTwilioCredentials()]);const adminTo=resend.adminTo||clean(config.site_settings?.email,240)||clean(config.business_profile?.email,240)||null;const[email,sms,adminEmail]=await Promise.all([emailChannel(booking.customer_email,booking,event,deliveryKey,config,false,context,resend),smsChannel(booking,event,deliveryKey,context,twilio),emailChannel(adminTo,booking,event,deliveryKey,config,true,context,resend)]);return json({ok:email.state==="sent"||sms.state==="sent"||adminEmail.state==="sent",bookingId,event,deliveryKey,email,sms,adminEmail});}catch(error){console.error("booking-notify failed",error);return json({ok:false,code:"NOTIFICATION_WORKER_FAILED"},500);}
});
