import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const supabase=createClient(URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const BUCKET="partner-uploads";
const MAX_FILES=10;
const MAX_FILE_BYTES=50*1024*1024;
const MAX_TOTAL_BYTES=200*1024*1024;
const mimeExtensions:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","video/mp4":"mp4","application/pdf":"pdf"};

function json(body:unknown,status=200){return Response.json(body,{status,headers:{"cache-control":"no-store","content-type":"application/json; charset=utf-8"}});}
function clean(value:unknown,max:number){return typeof value==="string"?value.trim().slice(0,max):"";}
function enumValue(value:unknown,allowed:string[],fallback:string|null=null){const v=clean(value,60).toUpperCase();return allowed.includes(v)?v:fallback;}
function serviceHeaders(extra:Record<string,string>={}){return{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,"content-type":"application/json",...extra};}
async function db(path:string,init:RequestInit={}){return fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...serviceHeaders(),...(init.headers||{})},signal:init.signal||AbortSignal.timeout(12_000)});}
async function digest(value:string){const raw=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(raw)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function rate(key:string,scope:string,seconds:number,limit:number){const response=await db("rpc/consume_rate_limit",{method:"POST",body:JSON.stringify({p_key_hash:key,p_scope:scope,p_window_seconds:seconds,p_limit:limit})});if(!response.ok)throw new Error("RATE_LIMIT_BACKEND_FAILED");return Boolean(await response.json());}
async function rpc(name:string,body:Record<string,unknown>){const response=await db(`rpc/${name}`,{method:"POST",body:JSON.stringify(body)});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(String(payload?.message||payload?.code||`${name.toUpperCase()}_${response.status}`));return payload;}
async function requireAdmin(request:Request){
  const authorization=request.headers.get("authorization")||"";
  if(!/^Bearer\s+\S+/i.test(authorization))throw new Error("UNAUTHORIZED");
  const userResponse=await fetch(`${URL}/auth/v1/user`,{headers:{apikey:SERVICE_KEY,authorization},signal:AbortSignal.timeout(8_000)});
  if(!userResponse.ok)throw new Error("UNAUTHORIZED");
  const user=await userResponse.json();const id=clean(user?.id,80);if(!id)throw new Error("UNAUTHORIZED");
  const adminResponse=await db(`admin_users?user_id=eq.${encodeURIComponent(id)}&is_active=eq.true&select=user_id,role&limit=1`);
  if(!adminResponse.ok)throw new Error("ADMIN_LOOKUP_FAILED");const rows=await adminResponse.json();if(!Array.isArray(rows)||!rows[0])throw new Error("FORBIDDEN");
  return{id,email:clean(user?.email,160),role:String(rows[0].role||"support")};
}

interface UploadInput{name?:string;type?:string;size?:number}
interface PartnerInit{
  operation?:string;idempotencyKey?:string;intent?:string;name?:string;phone?:string;email?:string;carBrand?:string;carModel?:string;modelYear?:number;km?:number;askingPrice?:number;withDriver?:boolean;notes?:string;files?:UploadInput[];website?:string;
  fuelType?:string;transmission?:string;bodyType?:string;exteriorColor?:string;provinceCode?:string;districtCode?:string;preferredBranchId?:string;ownershipStatus?:string;damageDeclaration?:string;expertReportAvailable?:boolean;termsAccepted?:boolean;privacyAccepted?:boolean;
  licensePlate?:string;vin?:string;registrationReference?:string;ownershipConfirmed?:boolean;
}
function validateFiles(files:UploadInput[]){if(files.length>MAX_FILES)throw new Error("TOO_MANY_FILES");let total=0;return files.map(file=>{const type=clean(file.type,100).toLowerCase();const size=Number(file.size||0);const ext=mimeExtensions[type];if(!ext)throw new Error("UNSUPPORTED_FILE_TYPE");if(!Number.isInteger(size)||size<1||size>MAX_FILE_BYTES)throw new Error("INVALID_FILE_SIZE");total+=size;if(total>MAX_TOTAL_BYTES)throw new Error("TOTAL_UPLOAD_TOO_LARGE");return{originalName:clean(file.name,180)||`file.${ext}`,type,size,ext};});}
async function validateGeo(provinceCode:string,districtCode:string){if(!provinceCode&&!districtCode)return;if(!/^TUR\d{3}$/.test(provinceCode)||!/^TUR\d{6}$/.test(districtCode))throw new Error("INVALID_GEO_CODES");const response=await db(`geo_districts?code=eq.${encodeURIComponent(districtCode)}&province_code=eq.${encodeURIComponent(provinceCode)}&select=code&limit=1`);if(!response.ok)throw new Error("GEO_LOOKUP_FAILED");const rows=await response.json();if(!Array.isArray(rows)||!rows[0])throw new Error("INVALID_GEO_PAIR");}
async function validateBranch(branchId:string){if(!branchId)return;if(!/^[0-9a-f-]{36}$/i.test(branchId))throw new Error("INVALID_BRANCH_ID");const response=await db(`branches?id=eq.${encodeURIComponent(branchId)}&select=id&limit=1`);if(!response.ok)throw new Error("BRANCH_LOOKUP_FAILED");const rows=await response.json();if(!Array.isArray(rows)||!rows[0])throw new Error("BRANCH_NOT_FOUND");}

async function sendMail(to:string,subject:string,html:string,text:string){const provider=clean(Deno.env.get("EMAIL_PROVIDER"),30).toLowerCase();const key=clean(Deno.env.get("RESEND_API_KEY"),500);const from=clean(Deno.env.get("MAIL_FROM"),240);if(provider!=="resend"||!key||!from)return{state:"not_configured",reason:"EMAIL_NOT_CONFIGURED"};try{const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({from,to:[to],subject,html,text}),signal:AbortSignal.timeout(10_000)});const result=await response.json().catch(()=>({}));if(!response.ok||!result.id)throw new Error(`EMAIL_SEND_FAILED_${response.status}`);return{state:"sent",id:String(result.id)};}catch(error){return{state:"failed",reason:error instanceof Error?error.message:"EMAIL_SEND_FAILED"};}}
async function notificationConfig(){const response=await db("site_config?key=eq.business_profile&select=value&limit=1");const rows=response.ok?await response.json():[];return Array.isArray(rows)&&rows[0]?.value?rows[0].value:{};}
async function logDelivery(row:any,eventKey:string,channel:string,recipient:string,result:any){await db("notification_deliveries",{method:"POST",headers:{Prefer:"return=minimal,resolution=ignore-duplicates"},body:JSON.stringify({partner_request_id:row.id,event_key:eventKey,channel,recipient,provider:"resend",provider_message_id:result?.id||null,status:result?.state==="sent"?"SENT":result?.state==="failed"?"FAILED":"SKIPPED",attempt_count:1,last_error:result?.reason||null,sent_at:result?.state==="sent"?new Date().toISOString():null})}).catch(()=>undefined);}
async function notifyReceived(row:any){const profile=await notificationConfig();const adminTo=clean(Deno.env.get("MAIL_ADMIN_TO"),240)||clean(profile.email,240);const footer=[profile.phone,profile.email,profile.address,profile.website].filter(Boolean).join(" · ");const customer=row.customer_email?await sendMail(row.customer_email,`Araç Değerlendirme Başvurunuz Alındı | ${row.reference}`,`<div style="font-family:Arial,sans-serif;color:#0f172a;line-height:1.65"><h2>Başvurunuz alındı</h2><p>Sayın ${row.customer_name},</p><p><strong>${row.vehicle_brand||""} ${row.vehicle_model||""}</strong> aracınız için başvurunuz güvenli şekilde kaydedildi.</p><p><strong>Referans:</strong> ${row.reference}</p><p>Beklediğiniz fiyat başvuru bilginizdir; Alperler Auto piyasa değerlemesi veya resmi teklif değildir. Resmi teklif ancak uzman incelemesi sonrasında oluşturulur.</p>${footer?`<hr><small>${footer}</small>`:""}</div>`,`Araç değerlendirme başvurunuz kaydedildi. Referans: ${row.reference}. Beklenen fiyatınız resmi değerleme değildir; resmi teklif uzman incelemesinden sonra oluşturulur.`):{state:"skipped",reason:"EMAIL_MISSING"};const admin=adminTo?await sendMail(adminTo,`Yeni Araç Değerlendirme Başvurusu | ${row.reference}`,`<div style="font-family:Arial,sans-serif;color:#0f172a"><h2>Yeni araç başvurusu</h2><p><b>${row.reference}</b></p><p>${row.customer_name} · ${row.customer_phone}</p><p>${row.vehicle_brand||""} ${row.vehicle_model||""} ${row.model_year||""}</p></div>`,`Yeni araç başvurusu ${row.reference} ${row.customer_name} ${row.customer_phone}`):{state:"skipped",reason:"ADMIN_EMAIL_MISSING"};await Promise.all([logDelivery(row,"partner_request_received","EMAIL",row.customer_email||"",customer),logDelivery(row,"partner_request_received","ADMIN_EMAIL",adminTo||"",admin)]);return{customerEmail:customer,adminEmail:admin};}
async function readRequest(reference:string){const response=await db(`partner_requests?reference=eq.${encodeURIComponent(reference)}&select=*&limit=1`);if(!response.ok)throw new Error("PARTNER_READ_FAILED");const rows=await response.json();return Array.isArray(rows)?rows[0]:null;}
async function notifyValuation(row:any,result:any){if(!row?.customer_email)return;const model=String(result?.offerModel||"");const amount=Number(result?.offerAmount||0);const share=Number(result?.revenueSharePercent||0);const valid=result?.validUntil?new Date(result.validUntil).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"}):"belirtilmedi";const offer=model==="PURCHASE"?`${amount.toLocaleString("tr-TR")} ${result.currency||"TRY"} satın alma teklifi`:model==="MONTHLY_GUARANTEE"?`${amount.toLocaleString("tr-TR")} ${result.currency||"TRY"} aylık garanti modeli`:model==="REVENUE_SHARE"?`%${share.toLocaleString("tr-TR")} gelir paylaşımı modeli`:"uygun bulunmadı";const delivery=await sendMail(row.customer_email,`Araç Değerlendirme Sonucu | ${row.reference}`,`<div style="font-family:Arial,sans-serif;color:#0f172a;line-height:1.65"><h2>Değerlendirme sonucu</h2><p>Sayın ${row.customer_name},</p><p><strong>${row.vehicle_brand||""} ${row.vehicle_model||""}</strong> için değerlendirme tamamlandı.</p><p><strong>Sonuç:</strong> ${offer}</p><p><strong>Teklif geçerliliği:</strong> ${valid}</p><p>Teklif, araç bilgilerinin doğrulanması ve gerekiyorsa fiziki ekspertiz sonucuna bağlıdır. Nihai devir/kiralama şartları sözleşme ile kesinleşir.</p></div>`,`Değerlendirme sonucu ${row.reference}: ${offer}. Geçerlilik: ${valid}. Nihai şartlar doğrulama/ekspertiz ve sözleşmeye bağlıdır.`);await logDelivery(row,"partner_valuation_finalized","EMAIL",row.customer_email,delivery);}
async function notifyAppointment(row:any,result:any){if(!row?.customer_email)return;const when=result?.startsAt?new Date(result.startsAt).toLocaleString("tr-TR",{timeZone:result.timezone||"Europe/Istanbul"}):"";const delivery=await sendMail(row.customer_email,`Araç Değerlendirme Randevusu | ${row.reference}`,`<div style="font-family:Arial,sans-serif;color:#0f172a;line-height:1.65"><h2>Randevunuz oluşturuldu</h2><p>Sayın ${row.customer_name},</p><p><strong>Tarih ve saat:</strong> ${when}</p><p><strong>Tür:</strong> ${result.appointmentType||"INSPECTION"}</p><p>Ruhsat ve araçla ilgili mevcut belgeleri yanınızda bulundurmanız değerlendirmeyi hızlandırır.</p></div>`,`Randevu ${row.reference}: ${when}. Tür: ${result.appointmentType||"INSPECTION"}.`);await logDelivery(row,"partner_appointment_scheduled","EMAIL",row.customer_email,delivery);}

async function initRequest(request:Request,input:PartnerInit){
  if(clean(input.website,200))return json({ok:true,accepted:true},202);
  const intent=clean(input.intent,20).toLowerCase();if(!["sell","rent"].includes(intent))return json({ok:false,code:"INVALID_INTENT"},400);
  if(input.termsAccepted!==true||input.privacyAccepted!==true)return json({ok:false,code:"CONSENT_REQUIRED"},400);
  const name=clean(input.name,160),phone=clean(input.phone,40),email=clean(input.email,160).toLowerCase()||null,brand=clean(input.carBrand,100),model=clean(input.carModel,100),notes=clean(input.notes,4000)||null;
  const modelYear=Number(input.modelYear||0),mileage=Number(input.km||0);
  if(!name||!brand||!model||!/^[+0-9()\s-]{7,24}$/.test(phone))return json({ok:false,code:"INVALID_REQUIRED_FIELDS"},400);
  if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({ok:false,code:"INVALID_EMAIL"},400);
  if(!Number.isInteger(modelYear)||modelYear<1950||modelYear>new Date().getUTCFullYear()+1)return json({ok:false,code:"INVALID_MODEL_YEAR"},400);
  if(!Number.isFinite(mileage)||mileage<0||mileage>5_000_000)return json({ok:false,code:"INVALID_MILEAGE"},400);
  const provinceCode=clean(input.provinceCode,20),districtCode=clean(input.districtCode,20),preferredBranchId=clean(input.preferredBranchId,80);
  try{await validateGeo(provinceCode,districtCode);await validateBranch(preferredBranchId);}catch(error){return json({ok:false,code:error instanceof Error?error.message:"INVALID_LOCATION"},400);}
  const fuelType=enumValue(input.fuelType,["GASOLINE","DIESEL","HYBRID","ELECTRIC","LPG","OTHER"]);
  const transmission=enumValue(input.transmission,["AUTOMATIC","MANUAL","SEMI_AUTOMATIC","OTHER"]);
  const ownershipStatus=enumValue(input.ownershipStatus,["OWNER","AUTHORIZED_SELLER","COMPANY_VEHICLE","OTHER"]);
  const files=validateFiles(Array.isArray(input.files)?input.files:[]);const idempotencyKey=clean(input.idempotencyKey,120)||crypto.randomUUID();
  const ip=clean(request.headers.get("x-client-ip")||request.headers.get("x-forwarded-for")?.split(",")[0]||"unknown",100);const network=await digest(`${ip}|${clean(request.headers.get("user-agent"),300)}`);const contact=await digest(`${phone}|${email||""}`);
  if(!(await rate(network,"partner_network_minute",60,3))||!(await rate(network,"partner_network_hour",3600,12))||!(await rate(contact,"partner_contact_day",86400,5)))return json({ok:false,code:"RATE_LIMITED",message:"Çok fazla başvuru gönderildi. Lütfen daha sonra tekrar deneyin."},429);
  const existingResponse=await db(`partner_requests?idempotency_key=eq.${encodeURIComponent(idempotencyKey)}&select=*&limit=1`);if(existingResponse.ok){const rows=await existingResponse.json();if(Array.isArray(rows)&&rows[0])return json({ok:true,duplicate:true,reference:rows[0].reference,status:rows[0].status},200);}
  const uploadToken=crypto.randomUUID()+crypto.randomUUID(),uploadTokenHash=await digest(uploadToken);const expectedPaths:Array<{path:string;originalName:string;type:string;size:number}>=[];
  const row={idempotency_key:idempotencyKey,intent:intent==="sell"?"SELL":"RENT",customer_name:name,customer_email:email,customer_phone:phone,vehicle_brand:brand,vehicle_model:model,model_year:modelYear,mileage_km:Math.round(mileage),asking_price:Number.isFinite(Number(input.askingPrice))&&Number(input.askingPrice)>=0?Number(input.askingPrice):null,with_driver:Boolean(input.withDriver),description:notes,status:files.length?"UPLOADING":"NEW",upload_token_hash:files.length?uploadTokenHash:null,submitted_at:files.length?null:new Date().toISOString(),media_paths:[],fuel_type:fuelType,transmission,body_type:clean(input.bodyType,80)||null,exterior_color:clean(input.exteriorColor,80)||null,province_code:provinceCode||null,district_code:districtCode||null,preferred_branch_id:preferredBranchId||null,ownership_status:ownershipStatus,damage_declaration:clean(input.damageDeclaration,2000)||null,expert_report_available:Boolean(input.expertReportAvailable),terms_accepted_at:new Date().toISOString(),privacy_accepted_at:new Date().toISOString()};
  const insert=await db("partner_requests?select=*",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});if(!insert.ok)return json({ok:false,code:"PARTNER_REQUEST_CREATE_FAILED"},500);const saved=(await insert.json())[0];
  const hasIdentity=Boolean(clean(input.licensePlate,20)||clean(input.vin,30)||clean(input.registrationReference,80)||input.ownershipConfirmed);
  if(hasIdentity){try{await rpc("service_attach_partner_request_identity_v172",{p_partner_request_id:saved.id,p_license_plate:clean(input.licensePlate,20)||null,p_vin:clean(input.vin,30)||null,p_registration_reference:clean(input.registrationReference,80)||null,p_ownership_confirmed:Boolean(input.ownershipConfirmed)});}catch{await db(`partner_requests?id=eq.${encodeURIComponent(saved.id)}`,{method:"PATCH",body:JSON.stringify({status:"CLOSED",internal_notes:"Private identity save failed during V172 submission."})});return json({ok:false,code:"PRIVATE_IDENTITY_SAVE_FAILED"},500);}}
  if(!files.length){const delivery=await notifyReceived(saved);return json({ok:true,reference:saved.reference,requestId:saved.id,status:"NEW",uploads:[],delivery},201);}
  const uploads=[];for(const file of files){const path=`${saved.id}/${crypto.randomUUID()}.${file.ext}`;const{data,error}=await supabase.storage.from(BUCKET).createSignedUploadUrl(path,{upsert:false});if(error||!data?.token||!data?.signedUrl){await db(`partner_requests?id=eq.${encodeURIComponent(saved.id)}`,{method:"PATCH",body:JSON.stringify({status:"CLOSED",internal_notes:"Upload URL generation failed."})});return json({ok:false,code:"UPLOAD_URL_CREATE_FAILED"},500);}expectedPaths.push({path,originalName:file.originalName,type:file.type,size:file.size});uploads.push({path,token:data.token,signedUrl:data.signedUrl,originalName:file.originalName,type:file.type,size:file.size});}
  const patch=await db(`partner_requests?id=eq.${encodeURIComponent(saved.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({media_paths:expectedPaths})});if(!patch.ok)return json({ok:false,code:"UPLOAD_MANIFEST_SAVE_FAILED"},500);return json({ok:true,reference:saved.reference,requestId:saved.id,status:"UPLOADING",uploadToken,uploads},201);
}

async function finalizeRequest(input:any){const reference=clean(input?.reference,80),uploadToken=clean(input?.uploadToken,200);if(!reference||!uploadToken)return json({ok:false,code:"FINALIZE_TOKEN_REQUIRED"},400);const row=await readRequest(reference);if(!row)return json({ok:false,code:"PARTNER_REQUEST_NOT_FOUND"},404);if(row.status==="NEW"&&row.submitted_at)return json({ok:true,reference,status:"NEW",duplicate:true});if(row.status!=="UPLOADING"||!row.upload_token_hash)return json({ok:false,code:"PARTNER_REQUEST_NOT_FINALIZABLE"},409);if((await digest(uploadToken))!==row.upload_token_hash)return json({ok:false,code:"INVALID_FINALIZE_TOKEN"},403);const expected=Array.isArray(row.media_paths)?row.media_paths:[];const{data:objects,error}=await supabase.storage.from(BUCKET).list(row.id,{limit:100,sortBy:{column:"name",order:"asc"}});if(error)return json({ok:false,code:"UPLOAD_VERIFY_FAILED"},500);const names=new Set((objects||[]).map(object=>object.name));const missing=expected.filter((item:any)=>!names.has(String(item.path||"").split("/").pop()||""));if(missing.length)return json({ok:false,code:"UPLOADS_INCOMPLETE",missing:missing.map((item:any)=>item.originalName||item.path)},409);const update=await db(`partner_requests?id=eq.${encodeURIComponent(row.id)}&select=*`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:"NEW",submitted_at:new Date().toISOString(),upload_token_hash:null})});if(!update.ok)return json({ok:false,code:"PARTNER_REQUEST_FINALIZE_FAILED"},500);const saved=(await update.json())[0];const delivery=await notifyReceived(saved);return json({ok:true,reference:saved.reference,status:saved.status,mediaCount:expected.length,delivery});}

async function listAdmin(request:Request){try{const admin=await requireAdmin(request);const snapshot=await rpc("service_partner_request_admin_snapshot_v172",{p_actor:admin.id,p_limit:500});const rows=Array.isArray(snapshot)?snapshot:[];const requests=rows.map((entry:any)=>{const payload=entry?.payload||entry||{};return{...(payload.request||{}),v172_identity:payload.identity||null,v172_valuation:payload.latestValuation||null,v172_appointment:payload.latestAppointment||null};});return json({ok:true,requests});}catch(error){const code=error instanceof Error?error.message:"UNAUTHORIZED";return json({ok:false,code},code==="UNAUTHORIZED"?401:code==="FORBIDDEN"||code==="ADMIN_REQUIRED"?403:500);}}

async function updateAdmin(request:Request,input:any){try{const admin=await requireAdmin(request);const reference=clean(input?.reference,80);if(!reference)return json({ok:false,code:"REFERENCE_REQUIRED"},400);const action=clean(input?.action,40).toLowerCase()||"status";
  if(action==="valuation"){const result=await rpc("service_record_partner_valuation_v172",{p_reference:reference,p_actor:admin.id,p_valuation_status:enumValue(input?.valuationStatus,["DRAFT","FINAL"],"DRAFT"),p_condition_grade:enumValue(input?.conditionGrade,["A","B","C","D","E"]),p_market_low:input?.marketLow==null?null:Number(input.marketLow),p_market_high:input?.marketHigh==null?null:Number(input.marketHigh),p_offer_model:enumValue(input?.offerModel,["PURCHASE","MONTHLY_GUARANTEE","REVENUE_SHARE","DECLINE"]),p_offer_amount:input?.offerAmount==null?null:Number(input.offerAmount),p_revenue_share_percent:input?.revenueSharePercent==null?null:Number(input.revenueSharePercent),p_currency:enumValue(input?.currency,["TRY","EUR","USD","CHF"],"TRY"),p_inspection_required:input?.inspectionRequired!==false,p_rationale:clean(input?.rationale,4000)||null,p_valid_until:clean(input?.validUntil,80)||null});if(String(result?.valuationStatus||"")==="FINAL"){const row=await readRequest(reference);await notifyValuation(row,result);}return json({ok:true,action,result});}
  if(action==="appointment"){const result=await rpc("service_schedule_partner_appointment_v172",{p_reference:reference,p_actor:admin.id,p_branch_id:clean(input?.branchId,80)||null,p_starts_at:clean(input?.startsAt,80),p_timezone:clean(input?.timezone,80)||"Europe/Istanbul",p_appointment_type:enumValue(input?.appointmentType,["INSPECTION","HANDOVER","CALL","OTHER"],"INSPECTION"),p_notes:clean(input?.notes,2000)||null});const row=await readRequest(reference);await notifyAppointment(row,result);return json({ok:true,action,result});}
  if(action==="identity"){const result=await rpc("service_upsert_partner_request_identity_v172",{p_reference:reference,p_actor:admin.id,p_license_plate:clean(input?.licensePlate,20)||null,p_vin:clean(input?.vin,30)||null,p_registration_reference:clean(input?.registrationReference,80)||null,p_ownership_confirmed:Boolean(input?.ownershipConfirmed)});return json({ok:true,action,result});}
  if(action==="assign"){const assignedTo=clean(input?.assignedTo,80)||null,nextActionAt=clean(input?.nextActionAt,80)||null;const existing=await readRequest(reference);if(!existing)return json({ok:false,code:"PARTNER_REQUEST_NOT_FOUND"},404);const response=await db(`partner_requests?id=eq.${encodeURIComponent(existing.id)}&select=*`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({assigned_to:assignedTo,next_action_at:nextActionAt,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("PARTNER_ASSIGN_FAILED");const saved=(await response.json())[0];await db("audit_logs",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({actor_user_id:admin.id,actor_email:admin.email,action:"partner_request_assigned",entity_type:"partner_request",entity_id:reference,before_data:{assigned_to:existing.assigned_to,next_action_at:existing.next_action_at},after_data:{assigned_to:saved.assigned_to,next_action_at:saved.next_action_at}})}).catch(()=>undefined);return json({ok:true,request:saved});}
  const status=clean(input?.status,30).toUpperCase(),internalNotes=clean(input?.internalNotes,4000)||null;if(!["NEW","REVIEWING","CONTACTED","OFFERED","ACCEPTED","REJECTED","CLOSED"].includes(status))return json({ok:false,code:"INVALID_UPDATE"},400);const existing=await readRequest(reference);if(!existing)return json({ok:false,code:"PARTNER_REQUEST_NOT_FOUND"},404);const response=await db(`partner_requests?id=eq.${encodeURIComponent(existing.id)}&select=*`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status,internal_notes:internalNotes,last_contact_at:status==="CONTACTED"?new Date().toISOString():existing.last_contact_at})});if(!response.ok){const p=await response.json().catch(()=>({}));throw new Error(String(p?.message||"PARTNER_UPDATE_FAILED"));}const saved=(await response.json())[0];await db("audit_logs",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({actor_user_id:admin.id,actor_email:admin.email,action:"partner_request_updated",entity_type:"partner_request",entity_id:reference,before_data:existing,after_data:saved})}).catch(()=>undefined);return json({ok:true,request:saved});
}catch(error){const code=error instanceof Error?error.message:"PARTNER_UPDATE_FAILED";return json({ok:false,code},code==="UNAUTHORIZED"?401:code==="FORBIDDEN"||code==="ADMIN_REQUIRED"?403:code.includes("INVALID")||code.includes("REQUIRED")?400:code.includes("NOT_FOUND")?404:code==="PARTNER_FINAL_VALUATION_REQUIRED"?409:500);}}

Deno.serve(async request=>{if(!URL||!SERVICE_KEY)return json({ok:false,code:"SERVER_CONFIG_MISSING"},503);if(request.method==="GET")return listAdmin(request);if(!["POST","PATCH"].includes(request.method))return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);let input:any;try{input=await request.json();}catch{return json({ok:false,code:"INVALID_JSON"},400);}if(request.method==="PATCH")return updateAdmin(request,input);const operation=clean(input?.operation,20).toLowerCase();if(operation==="finalize")return finalizeRequest(input);return initRequest(request,input as PartnerInit);});
