import { Injectable, inject } from "@angular/core";
import { BranchPortalAuthService } from "./branch-portal-auth.service";
import { SUPABASE_PROJECT_URL, SUPABASE_PUBLISHABLE_KEY } from "../supabase.config";

export interface BranchTourV171{id:string;slug:string;title:string;price:number;duration:string;capacity?:number;meetingPoint:string;description:string;itinerary:string[];included:string[];excluded:string[];highlights:string[];publicationStatus:string;reviewNote?:string;updatedAt:string;}
export interface BranchTourDraftV171{id?:string;slug?:string;title:string;price:number;duration:string;capacity?:number;meetingPoint:string;description:string;itinerary:string[];included:string[];excluded:string[];highlights:string[];}
const BRANCH_TOUR_SELECT="id,seo_slug,title,price_per_person,duration,capacity,meeting_point,description,itinerary,included_items,excluded_items,metadata,publication_status,review_note,updated_at";

@Injectable({providedIn:"root"})
export class BranchPortalToursV171Service{
  private readonly auth=inject(BranchPortalAuthService);
  async list(branchId:string):Promise<BranchTourV171[]>{const token=await this.token();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/tours?branch_id=eq.${encodeURIComponent(branchId)}&listing_origin=eq.BRANCH&select=${BRANCH_TOUR_SELECT}&order=updated_at.desc`,{headers:this.headers(token),cache:"no-store"});if(!response.ok)throw new Error(`BRANCH_TOURS_LOAD_${response.status}`);return(await response.json() as any[]).map(row=>this.map(row));}
  async save(branchId:string,input:BranchTourDraftV171,submitForReview:boolean):Promise<BranchTourV171>{const token=await this.token();const title=input.title.trim().slice(0,240),duration=input.duration.trim().slice(0,120),meeting=input.meetingPoint.trim().slice(0,240),description=input.description.trim().slice(0,10000);const price=Number(input.price);if(!title||!duration||!meeting||description.length<40||!Number.isFinite(price)||price<=0||!input.itinerary.length||!input.included.length)throw new Error("TOUR_REQUIRED_FIELDS");const payload:Record<string,unknown>={title,category:"BRANCH_TOUR",short_description:description.slice(0,700),description,price_per_person:price,currency:"TRY",duration,capacity:this.numberOrNull(input.capacity),meeting_point:meeting,itinerary:this.cleanArray(input.itinerary,100,500),included_items:this.cleanArray(input.included,100,300),excluded_items:this.cleanArray(input.excluded,100,300),is_featured:false,is_active:true,publication_status:submitForReview?"PENDING_REVIEW":"DRAFT",branch_id:branchId,listing_origin:"BRANCH",metadata:{portalVersion:171,highlights:this.cleanArray(input.highlights,50,300)}};let rows:any[];if(input.id){rows=await this.rest<any[]>(`tours?id=eq.${encodeURIComponent(input.id)}&branch_id=eq.${encodeURIComponent(branchId)}&select=${BRANCH_TOUR_SELECT}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)},token);}else{payload["seo_slug"]=this.slug(input.slug||title,branchId);rows=await this.rest<any[]>(`tours?select=${BRANCH_TOUR_SELECT}`,{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)},token);}const row=rows[0];if(!row)throw new Error("BRANCH_TOUR_SAVE_FAILED");return this.map(row);}
  async submit(branchId:string,id:string):Promise<void>{const token=await this.token();await this.rest(`tours?id=eq.${encodeURIComponent(id)}&branch_id=eq.${encodeURIComponent(branchId)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({publication_status:"PENDING_REVIEW"})},token);}
  async archive(branchId:string,id:string):Promise<void>{const token=await this.token();await this.rest(`tours?id=eq.${encodeURIComponent(id)}&branch_id=eq.${encodeURIComponent(branchId)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({is_active:false,publication_status:"DRAFT"})},token);}
  private map(row:any):BranchTourV171{const metadata=row?.metadata&&typeof row.metadata==="object"?row.metadata:{};return{id:String(row.id),slug:String(row.seo_slug||""),title:String(row.title||""),price:Number(row.price_per_person||0),duration:String(row.duration||""),capacity:row.capacity==null?undefined:Number(row.capacity),meetingPoint:String(row.meeting_point||""),description:String(row.description||""),itinerary:Array.isArray(row.itinerary)?row.itinerary.map(String):[],included:Array.isArray(row.included_items)?row.included_items.map(String):[],excluded:Array.isArray(row.excluded_items)?row.excluded_items.map(String):[],highlights:Array.isArray(metadata.highlights)?metadata.highlights.map(String):[],publicationStatus:String(row.publication_status||"DRAFT"),reviewNote:row.review_note?String(row.review_note):undefined,updatedAt:String(row.updated_at||"")};}
  private cleanArray(values:string[],maxItems:number,maxLen:number):string[]{return [...new Set(values.map(v=>String(v||"").trim().slice(0,maxLen)).filter(Boolean))].slice(0,maxItems);}
  private numberOrNull(value:unknown):number|null{const n=Number(value);return Number.isFinite(n)&&n>0?Math.round(n):null;}
  private slug(value:string,branchId:string):string{const base=value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/ğ/g,"g").replace(/ü/g,"u").replace(/ş/g,"s").replace(/ö/g,"o").replace(/ç/g,"c").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"tur";return `br-${branchId.slice(0,8)}-${crypto.randomUUID().slice(0,8)}-${base}`.slice(0,140);}
  private async token():Promise<string>{const token=await this.auth.getAccessToken();if(!token)throw new Error("BRANCH_SESSION_REQUIRED");return token;}
  private headers(token:string,extra:Record<string,string>={}):Record<string,string>{return{apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${token}`,"content-type":"application/json",accept:"application/json",...extra};}
  private async rest<T=unknown>(path:string,init:RequestInit,token:string):Promise<T>{const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/${path}`,{...init,headers:this.headers(token,init.headers as Record<string,string>||{}),signal:AbortSignal.timeout(10000)});if(!response.ok){const detail=await response.text().catch(()=>"");throw new Error(`BRANCH_TOUR_DB_${response.status}:${detail.slice(0,180)}`);}if(response.status===204)return undefined as T;return await response.json() as T;}
}
