import { Injectable, inject } from "@angular/core";
import { AuthService } from "./auth.service";
import { BranchPortalAuthService } from "./branch-portal-auth.service";
import { SUPABASE_PROJECT_URL, SUPABASE_PUBLISHABLE_KEY } from "../supabase.config";

export interface BranchPlanV171 {id:string;code:string;name:string;short_description:string;monthly_fee:number;currency:string;billing_interval:"MONTHLY"|"YEARLY";entitlements:Record<string,unknown>;sales_copy:{headline?:string;benefits?:string[]};is_active:boolean;sort_order:number;}
export interface BranchSubscriptionV171 {id:string;branch_id:string;plan_id:string;status:string;price_override?:number|null;is_complimentary:boolean;current_period_start:string;current_period_end?:string|null;grace_ends_at?:string|null;auto_renew:boolean;provider?:string|null;plan?:BranchPlanV171;branch?:{id:string;name:string;city?:string;district?:string;operator_display_name?:string};}
export interface BranchInvoiceV171 {id:string;branch_id:string;invoice_number:string;status:string;amount:number;currency:string;period_start:string;period_end:string;issued_at:string;due_at:string;paid_at?:string|null;payment_reference?:string|null;}
export interface BranchEntitlementV171 {branch_id:string;branch_name:string;status:string;plan_code:string;plan_name:string;effective_price:number;currency:string;current_period_end?:string|null;grace_ends_at?:string|null;can_operate:boolean;}
interface CheckoutResponse{ok?:boolean;code?:string;checkoutUrl?:string;externalReference?:string;provider?:string;status?:string;message?:string;}

@Injectable({providedIn:"root"})
export class BranchSubscriptionV171Service {
  private readonly adminAuth=inject(AuthService);
  private readonly portalAuth=inject(BranchPortalAuthService);
  private readonly planSelect="id,code,name,short_description,monthly_fee,currency,billing_interval,entitlements,sales_copy,is_active,sort_order";
  private readonly subscriptionSelect="id,branch_id,plan_id,status,price_override,is_complimentary,current_period_start,current_period_end,grace_ends_at,auto_renew,provider";
  private readonly invoiceSelect="id,branch_id,invoice_number,status,amount,currency,period_start,period_end,issued_at,due_at,paid_at,payment_reference";
  private readonly branchSelect="id,name,city,district,operator_display_name";
  private publicHeaders(){return{apikey:SUPABASE_PUBLISHABLE_KEY,accept:"application/json"};}
  private async adminHeaders(){const token=await this.adminAuth.getAccessToken();if(!token)throw new Error("ADMIN_AUTH_REQUIRED");return{...this.publicHeaders(),authorization:`Bearer ${token}`,"content-type":"application/json"};}
  private async portalHeaders(){const token=await this.portalAuth.getAccessToken();if(!token)throw new Error("BRANCH_SESSION_REQUIRED");return{...this.publicHeaders(),authorization:`Bearer ${token}`,"content-type":"application/json"};}
  private subscriptionProjection():string{return`${this.subscriptionSelect},plan:branch_subscription_plans(${this.planSelect}),branch:branches(${this.branchSelect})`;}
  async plans(includeInactive=false):Promise<BranchPlanV171[]>{const token=includeInactive?await this.adminAuth.getAccessToken().catch(()=>null):null;const headers=token?{...this.publicHeaders(),authorization:`Bearer ${token}`} : this.publicHeaders();const filter=includeInactive?"":"&is_active=eq.true";const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscription_plans?select=${this.planSelect}&order=sort_order.asc${filter}`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_PLANS_UNAVAILABLE");return await response.json() as BranchPlanV171[];}
  async mySubscriptions():Promise<BranchSubscriptionV171[]>{const headers=await this.portalHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscriptions?select=${this.subscriptionProjection()}&order=created_at.desc`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_SUBSCRIPTION_UNAVAILABLE");return await response.json() as BranchSubscriptionV171[];}
  async myInvoices(branchId?:string):Promise<BranchInvoiceV171[]>{const headers=await this.portalHeaders();const filter=branchId?`&branch_id=eq.${encodeURIComponent(branchId)}`:"";const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscription_invoices?select=${this.invoiceSelect}&order=issued_at.desc${filter}`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_INVOICES_UNAVAILABLE");return await response.json() as BranchInvoiceV171[];}
  async myEntitlements():Promise<BranchEntitlementV171[]>{const headers=await this.portalHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/rpc/my_branch_subscription_entitlements_v1714`,{method:"POST",headers,body:"{}",cache:"no-store"});if(!response.ok)throw new Error("BRANCH_ENTITLEMENT_UNAVAILABLE");return await response.json() as BranchEntitlementV171[];}
  async canOpenPortal():Promise<boolean>{const rows=await this.myEntitlements();return rows.some(row=>row.can_operate===true);}
  async checkoutInvoice(invoiceId:string):Promise<string>{const token=await this.portalAuth.getAccessToken();if(!token)throw new Error("BRANCH_SESSION_REQUIRED");const origin=window.location.origin;const response=await fetch("/api/payments?op=branch-subscription-session",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({invoiceId,returnUrl:`${origin}/branch-portal/subscription?payment=success`,cancelUrl:`${origin}/branch-portal/subscription?payment=cancelled`})});const payload=await response.json().catch(()=>({})) as CheckoutResponse;if(!response.ok||payload.ok!==true||!payload.checkoutUrl)throw new Error(String(payload.code||payload.message||"BRANCH_PAYMENT_SESSION_FAILED"));return payload.checkoutUrl;}
  async adminSubscriptions():Promise<BranchSubscriptionV171[]>{const headers=await this.adminHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscriptions?select=${this.subscriptionProjection()}&order=updated_at.desc`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_SUBSCRIPTIONS_ADMIN_UNAVAILABLE");return await response.json() as BranchSubscriptionV171[];}
  async updatePlan(id:string,patch:Partial<Pick<BranchPlanV171,"name"|"short_description"|"monthly_fee"|"currency"|"billing_interval"|"entitlements"|"sales_copy"|"is_active"|"sort_order">>):Promise<void>{const headers=await this.adminHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscription_plans?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("BRANCH_PLAN_UPDATE_FAILED");}
  async updateSubscription(id:string,patch:{plan_id?:string;status?:string;price_override?:number|null;is_complimentary?:boolean;current_period_end?:string|null;grace_ends_at?:string|null;auto_renew?:boolean}):Promise<void>{const headers=await this.adminHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscriptions?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("BRANCH_SUBSCRIPTION_UPDATE_FAILED");}
}
