import { Injectable, inject, signal } from "@angular/core";
import { BranchPortalAuthService } from "./branch-portal-auth.service";
import { SUPABASE_PROJECT_URL, SUPABASE_PUBLISHABLE_KEY } from "../supabase.config";

export type BranchListingMediaOwner="VEHICLE"|"TOUR";
export interface BranchListingMediaV171{id:string;owner:BranchListingMediaOwner;ownerId:string;kind:"IMAGE"|"VIDEO";url:string;posterUrl?:string;altText:string;sortOrder:number;isCover:boolean;isActive:boolean;objectPath?:string;}
interface DbRow{id:string;vehicle_id?:string|null;tour_id?:string|null;kind:"IMAGE"|"VIDEO";storage_bucket?:string|null;object_path?:string|null;external_url?:string|null;poster_url?:string|null;alt_text?:string|null;sort_order?:number|null;is_cover?:boolean|null;is_active?:boolean|null;}

@Injectable({providedIn:"root"})
export class BranchListingMediaV171Service{
  private readonly auth=inject(BranchPortalAuthService);private readonly bucket="catalog-media";private readonly _progress=signal(0);readonly progress=this._progress.asReadonly();
  async load(owner:BranchListingMediaOwner,ownerId:string):Promise<BranchListingMediaV171[]>{const token=await this.requiredToken();const column=owner==="VEHICLE"?"vehicle_id":"tour_id";const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/catalog_media?${column}=eq.${encodeURIComponent(ownerId)}&select=*&order=sort_order.asc,created_at.asc`,{headers:this.headers(token),cache:"no-store"});if(!response.ok)throw new Error(`LISTING_MEDIA_LOAD_${response.status}`);return(await response.json() as DbRow[]).map(row=>this.map(row));}
  async upload(branchId:string,owner:BranchListingMediaOwner,ownerId:string,file:File,options:{altText?:string;posterUrl?:string;isCover?:boolean;sortOrder?:number}={}):Promise<BranchListingMediaV171>{this.validate(file);const token=await this.requiredToken();const kind=file.type.startsWith("video/")?"VIDEO":"IMAGE";if(options.isCover&&kind!=="IMAGE")throw new Error("Kapak yalnız fotoğraf olabilir.");const folder=owner.toLowerCase();const path=`branch/${branchId}/${folder}/${ownerId}/${crypto.randomUUID()}.${this.ext(file)}`;this._progress.set(0);try{const upload=await fetch(`${SUPABASE_PROJECT_URL}/storage/v1/object/${this.bucket}/${path.split("/").map(encodeURIComponent).join("/")}`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${token}`,"content-type":file.type,"cache-control":"3600","x-upsert":"false"},body:file});if(!upload.ok)throw new Error(`LISTING_MEDIA_UPLOAD_${upload.status}`);this._progress.set(65);const body:Record<string,unknown>={kind,storage_bucket:this.bucket,object_path:path,external_url:null,poster_url:options.posterUrl||null,source_url:null,source_name:"Şube Portalı",license:"BUSINESS_OWNED",attribution:"Yerel şube işletmesi",alt_text:(options.altText||file.name).trim().slice(0,300),sort_order:options.sortOrder??0,is_cover:false,is_active:true,metadata:{originalName:file.name,mimeType:file.type,fileSize:file.size,reviewStatus:"BRANCH_SUBMITTED",branchId}};body[owner==="VEHICLE"?"vehicle_id":"tour_id"]=ownerId;const create=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/catalog_media?select=*`,{method:"POST",headers:{...this.headers(token),Prefer:"return=representation"},body:JSON.stringify(body)});if(!create.ok){await this.removeObject(path,token).catch(()=>undefined);throw new Error(`LISTING_MEDIA_CREATE_${create.status}`);}const item=this.map((await create.json() as DbRow[])[0]);if(options.isCover)await this.setCover(item.id);this._progress.set(100);return options.isCover?{...item,isCover:true}:item;}finally{if(this._progress()<100)this._progress.set(0);}}
  async setCover(id:string):Promise<void>{const token=await this.requiredToken();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/rpc/set_catalog_media_cover`,{method:"POST",headers:this.headers(token),body:JSON.stringify({p_media_id:id})});if(!response.ok)throw new Error("LISTING_MEDIA_COVER_FAILED");}
  async update(item:BranchListingMediaV171,patch:{altText?:string;sortOrder?:number;posterUrl?:string;isActive?:boolean}):Promise<void>{const token=await this.requiredToken();const body:Record<string,unknown>={};if(patch.altText!==undefined)body["alt_text"]=patch.altText.trim().slice(0,300);if(patch.sortOrder!==undefined)body["sort_order"]=Math.max(0,Math.round(patch.sortOrder));if(patch.posterUrl!==undefined)body["poster_url"]=patch.posterUrl?.trim()||null;if(patch.isActive!==undefined)body["is_active"]=patch.isActive;if(!Object.keys(body).length)return;const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/catalog_media?id=eq.${encodeURIComponent(item.id)}`,{method:"PATCH",headers:this.headers(token),body:JSON.stringify(body)});if(!response.ok)throw new Error(`LISTING_MEDIA_UPDATE_${response.status}`);}
  async remove(item:BranchListingMediaV171):Promise<void>{const token=await this.requiredToken();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/rpc/remove_catalog_media_safe`,{method:"POST",headers:this.headers(token),body:JSON.stringify({p_media_id:item.id})});if(!response.ok)throw new Error("LISTING_MEDIA_REMOVE_FAILED");if(item.objectPath)await this.removeObject(item.objectPath,token).catch(()=>undefined);}
  private map(row:DbRow):BranchListingMediaV171{const owner:BranchListingMediaOwner=row.vehicle_id?"VEHICLE":"TOUR";const ownerId=String(row.vehicle_id||row.tour_id||"");const url=row.storage_bucket===this.bucket&&row.object_path?`/catalog-media/${row.object_path}`:String(row.external_url||"");return{id:String(row.id),owner,ownerId,kind:row.kind,url,posterUrl:row.poster_url||undefined,altText:String(row.alt_text||"İlan medyası"),sortOrder:Number(row.sort_order||0),isCover:row.is_cover===true,isActive:row.is_active!==false,objectPath:row.object_path||undefined};}
  private validate(file:File){const allowed=new Set(["image/jpeg","image/png","image/webp","image/avif","video/mp4","video/webm"]);if(!allowed.has(file.type))throw new Error("MEDIA_TYPE_NOT_ALLOWED");if(file.size<1||file.size>50*1024*1024)throw new Error("MEDIA_TOO_LARGE");}
  private ext(file:File):string{return({"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/avif":"avif","video/mp4":"mp4","video/webm":"webm"} as Record<string,string>)[file.type]||"bin";}
  private async requiredToken():Promise<string>{const token=await this.auth.getAccessToken();if(!token)throw new Error("BRANCH_SESSION_REQUIRED");return token;}
  private headers(token:string):Record<string,string>{return{apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${token}`,"content-type":"application/json",accept:"application/json"};}
  private async removeObject(path:string,token:string):Promise<void>{await fetch(`${SUPABASE_PROJECT_URL}/storage/v1/object/${this.bucket}/${path.split("/").map(encodeURIComponent).join("/")}`,{method:"DELETE",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${token}`}});}
}
