import { Injectable, inject } from "@angular/core";
import { AuthService } from "./auth.service";
import { SUPABASE_PROJECT_URL, SUPABASE_PUBLISHABLE_KEY } from "../supabase.config";

export interface BranchPlanV171 {id:string;code:string;name:string;short_description:string;monthly_fee:number;currency:string;billing_interval:"MONTHLY"|"YEARLY";entitlements:Record<string,unknown>;sales_copy:{headline?:string;benefits?:string[]};is_active:boolean;sort_order:number;}
export interface BranchSubscriptionV171 {id:string;branch_id:string;plan_id:string;status:string;price_override?:number|null;is_complimentary:boolean;current_period_start:string;current_period_end?:string|null;grace_ends_at?:string|null;auto_renew:boolean;provider?:string|null;plan?:BranchPlanV171;branch?:{id:string;name:string;city?:string;district?:string;operator_display_name?:string};}
export interface BranchInvoiceV171 {id:string;branch_id:string;invoice_number:string;status:string;amount:number;currency:string;period_start:string;period_end:string;issued_at:string;due_at:string;paid_at?:string|null;payment_reference?:string|null;}

@Injectable({providedIn:"root"})
export class BranchSubscriptionV171Service {
  private readonly auth=inject(AuthService);
  private publicHeaders(){return{apikey:SUPABASE_PUBLISHABLE_KEY,accept:"application/json"};}
  private async authHeaders(){const token=await this.auth.getAccessToken();if(!token)throw new Error("AUTH_REQUIRED");return{...this.publicHeaders(),authorization:`Bearer ${token}`,"content-type":"application/json"};}
  async plans(includeInactive=false):Promise<BranchPlanV171[]>{const token=includeInactive?await this.auth.getAccessToken().catch(()=>null):null;const headers=token?{...this.publicHeaders(),authorization:`Bearer ${token}`} : this.publicHeaders();const filter=includeInactive?"":"&is_active=eq.true";const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscription_plans?select=*&order=sort_order.asc${filter}`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_PLANS_UNAVAILABLE");return await response.json() as BranchPlanV171[];}
  async mySubscriptions():Promise<BranchSubscriptionV171[]>{const headers=await this.authHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscriptions?select=*,plan:branch_subscription_plans(*),branch:branches(id,name,city,district,operator_display_name)&order=created_at.desc`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_SUBSCRIPTION_UNAVAILABLE");return await response.json() as BranchSubscriptionV171[];}
  async myInvoices(branchId?:string):Promise<BranchInvoiceV171[]>{const headers=await this.authHeaders();const filter=branchId?`&branch_id=eq.${encodeURIComponent(branchId)}`:"";const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscription_invoices?select=*&order=issued_at.desc${filter}`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_INVOICES_UNAVAILABLE");return await response.json() as BranchInvoiceV171[];}
  async adminSubscriptions():Promise<BranchSubscriptionV171[]>{const headers=await this.authHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscriptions?select=*,plan:branch_subscription_plans(*),branch:branches(id,name,city,district,operator_display_name)&order=updated_at.desc`,{headers,cache:"no-store"});if(!response.ok)throw new Error("BRANCH_SUBSCRIPTIONS_ADMIN_UNAVAILABLE");return await response.json() as BranchSubscriptionV171[];}
  async updatePlan(id:string,patch:Partial<Pick<BranchPlanV171,"name"|"short_description"|"monthly_fee"|"currency"|"billing_interval"|"entitlements"|"sales_copy"|"is_active"|"sort_order">>):Promise<void>{const headers=await this.authHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscription_plans?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("BRANCH_PLAN_UPDATE_FAILED");}
  async updateSubscription(id:string,patch:{plan_id?:string;status?:string;price_override?:number|null;is_complimentary?:boolean;current_period_end?:string|null;grace_ends_at?:string|null;auto_renew?:boolean}):Promise<void>{const headers=await this.authHeaders();const response=await fetch(`${SUPABASE_PROJECT_URL}/rest/v1/branch_subscriptions?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("BRANCH_SUBSCRIPTION_UPDATE_FAILED");}
}
