import { SiteConfig } from "../models/site-config.model";

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  logoUrl: "",
  adminDisplayName: "İshak Alper",
  adminEmails: ["ishak595@gmail.com", "ramcofero.yt@gmail.com"],
  companyName: "Alperler Rent A Car",
  tagline: "Kiralama • Satış • Tur",
  phone: "0537 959 48 51",
  email: "alperlerauto@gmail.com",
  address: "Hakkari Yüksekova Merkez",
  whatsapp: "905379594851",
  whatsappMessage: "Merhaba, Alperler Rent A Car hizmetleri hakkında hızlı bilgi almak istiyorum.",
  instagramUrl: "https://www.instagram.com/umut.alperr/",
  twitterUrl: "",
  facebookUrl: "",
  youtubeUrl: "",
  tiktokUrl: "",

  rentalExtras: [
    { id: "driver", label: "Şoförlü kiralama", description: "Profesyonel sürücü hizmeti", icon: "person_pin", enabled: true, sortOrder: 10, pricePerDay: 1500, pricePerHour: 100 },
    { id: "child-seat", label: "Bebek / çocuk koltuğu", description: "Yaşa uygun güvenlik koltuğu", icon: "child_friendly", enabled: true, sortOrder: 20, pricePerDay: 250 },
    { id: "extra-protection", label: "Ek güvence paketi", description: "Standart kapsama ek koruma talebi", icon: "verified_user", enabled: true, sortOrder: 30, pricePerDay: 450 },
    { id: "additional-driver", label: "Ek sürücü", description: "Sözleşmeye ikinci sürücü eklenmesi", icon: "group_add", enabled: true, sortOrder: 40, pricePerDay: 350 },
    { id: "airport-delivery", label: "Havalimanı teslim / iade", description: "Havalimanı teslimat hizmeti", icon: "flight", enabled: true, sortOrder: 50, flatPrice: 750 },
    { id: "after-hours", label: "Mesai dışı teslim / iade", description: "Normal operasyon saatleri dışındaki teslimat", icon: "schedule", enabled: true, sortOrder: 60, flatPrice: 500 },
    { id: "snow-chain", label: "Kar zinciri seti", description: "Kış koşulları için zincir seti", icon: "ac_unit", enabled: true, sortOrder: 70, flatPrice: 300 },
  ],
  rentalFuelPricePerLiter: 85,
  rentalAverageConsumptionPer100Km: 8.5,
  rentalRoutePricing: [],

  seoTitle: "Alperler Rent A Car | Yüksekova Araç Kiralama, Satış, Transfer ve Turlar",
  seoKeywords: "yüksekova araç kiralama, hakkari rent a car, satılık araç, vip transfer, yüksekova tur, alperler rent a car",
  seoDescription: "Yüksekova ve Hakkâri çevresinde araç kiralama, satılık araç, şoförlü transfer, özel gün aracı ve bölgesel tur seçeneklerini Alperler Rent A Car ile tek yerden planlayın.",
  seoAuthor: "Alperler Rent A Car",
  seoOgTitle: "Alperler Rent A Car | Yüksekova",
  seoOgDescription: "Araç kiralama, satış, transfer ve bölgesel tur seçeneklerini tek yerden planlayın.",
  seoOgImage: "",
  seoTwitterHandle: "",

  aboutTitle: "Alperler Güvencesiyle Yüksekova’da Otomotiv ve Yolculuk Çözümleri",
  aboutText: `Alperler, farklı iş alanlarında büyümek üzere oluşturulan şirket çatımızdır. Alperler Rent A Car, bu yapının müşteriye dönük araç kiralama, araç satışı, şoförlü transfer, özel gün aracı ve bölgesel tur hizmetidir. Alperler Auto ise otomotiv ve filo operasyonlarımızın altyapı adıdır.

Alperler Rent A Car’ın kurucusu İshak Alper’dir. Amacımız gerçek araç ve güncel bilgiyi göstermek, müşterinin ihtiyacını hızlı anlamak, talebi kayıt altına almak ve rezervasyon, teslim, ödeme ve operasyon süreçlerini izlenebilir hale getirmektir.`,
  team: [
    { id: 1, name: "İshak Alper", role: "Kurucu · Strateji ve Dijital Operasyon", description: "Alperler Rent A Car’ın kurucusu. Marka stratejisi, dijital sistem, müşteri deneyimi ve büyüme modelini yönetir.", image: "" },
  ],

  kvkkText: `KVKK AYDINLATMA METNİ\n\nAlperler Rent A Car hizmetleri kapsamında paylaştığınız kişisel veriler, talep ve rezervasyonların yürütülmesi, müşteri iletişimi, güvenlik, yasal yükümlülükler ve açık onay verilmişse pazarlama/analitik işlemleri için ilgili mevzuata uygun şekilde işlenir.\n\nİşlenen veri ve hukuki sebep kullanılan hizmete göre değişebilir. KVKK kapsamındaki başvuru ve bilgi talepleri için güncel iletişim kanallarımızı kullanabilirsiniz.`,
  privacyText: `GİZLİLİK POLİTİKASI\n\nAlperler Rent A Car, hizmetin gerektirmediği kişisel verileri toplamamayı ve ödeme kartı sırları gibi hassas bilgileri kendi uygulama veritabanında saklamamayı hedefler. Rezervasyon ve iletişim bilgileri yalnız ilgili işlemin yürütülmesi, güvenlik ve yasal yükümlülükler için kullanılır.\n\nZorunlu olmayan analitik ve pazarlama teknolojileri geçerli kullanıcı tercihine tabidir.`,
  cookiesText: `ÇEREZ VE ANALİTİK POLİTİKASI\n\nSitenin çalışması için gerekli teknik depolama mekanizmaları kullanılabilir. Zorunlu olmayan analitik ve pazarlama teknolojileri yalnız geçerli tercih/onay mekanizması kapsamında etkinleştirilir. Kullanıcı tercihi daha sonra değiştirilebilir.`,
  termsText: `KULLANIM ŞARTLARI\n\nSitedeki talep, ilan, fiyat ve uygunluk bilgileri güncel kayıtlar üzerinden sunulur. Kesin kiralama, satış veya tur işlemi gerekli teyit ve sözleşme adımları tamamlandığında oluşur. Kullanıcı formlarda doğru ve güncel bilgi vermekle yükümlüdür. Emredici tüketici hakları saklıdır.`,
  distanceSellingText: `MESAFELİ İŞLEM VE ÖN BİLGİLENDİRME ESASLARI\n\nBağlayıcı bir uzaktan işlem kurulmadan önce hizmetin temel nitelikleri, toplam bedel, ödeme/ifa koşulları, sağlayıcı bilgileri ve uygulanabilir iptal/cayma hükümleri müşteriye açıkça gösterilir. Belirli tarihli araç kiralama ve bazı belirli tarihli hizmetlerde mevzuattaki istisnalar uygulanabilir.`,
  cancellationText: `İADE VE İPTAL POLİTİKASI\n\nİptal ve iade şartları hizmet türü, tarih ve rezervasyon koşullarına göre işlem öncesinde gösterilir. Her işlem için koşulsuz aynı cayma/iade kuralı varmış gibi beyanda bulunulmaz. Kanundan doğan tüketici hakları saklıdır.`,
  insuranceText: `ARAÇ SİGORTA VE SORUMLULUK BİLGİLENDİRMESİ\n\nSigorta, kasko, muafiyet, depozito ve hasar sorumluluğu araç ve poliçe bazında değişebilir. Nihai kapsam ilgili poliçe ve kiralama sözleşmesiyle belirlenir; işlem öncesinde araç özelindeki koşullar müşteriye teyit edilir.`,
  rentalTermsText: `ARAÇ KİRALAMA KOŞULLARI\n\nKesin kiralama; araç, tarih, sürücü tercihi, ücret, teslim/iade ve uygulanabilir sözleşme şartları doğrulandığında oluşur. Şoför, ek sürücü, teslimat ve diğer ücretli hizmetler yalnız müşteri seçtiğinde toplam fiyata eklenir.`,
  salesTermsText: `İKİNCİ EL SATIŞ VE İLAN KOŞULLARI\n\nWeb ilanı tek başına resmi satış veya mülkiyet devri oluşturmaz. Araç bilgileri mevcut kayıt ve belgelere dayanmalı; resmi satış ve devir yürürlükteki mevzuata uygun kanallardan tamamlanmalıdır.`,
  tourTermsText: `TUR VE TRANSFER HİZMET KOŞULLARI\n\nRota, kapasite, araç, buluşma noktası, dahil/hariç hizmetler ve ücret ilgili kayıt üzerinden gösterilir. Kesin işlem tarih, kapasite ve operasyon uygunluğu doğrulandığında oluşur.`,
  partnerTermsText: `ARACINI DEĞERLENDİR BAŞVURU KOŞULLARI\n\nBaşvuru bir ön değerlendirme talebidir; aracın satın alındığı, filoya kabul edildiği veya ilanının otomatik yayımlandığı anlamına gelmez. Mülkiyet, yetki ve araç bilgileri gerektiğinde doğrulanır.`,
  branchTermsText: `ŞUBE VE BAYİLİK BAŞVURU KOŞULLARI\n\nBaşvuru tek başına franchise, acentelik veya marka kullanım hakkı oluşturmaz. Gerekli şirket, faaliyet, güvenlik ve operasyon belgeleri tamamlandıktan sonra merkezi onay süreci uygulanır.`,
  commercialCommunicationText: `BÜLTEN VE TİCARİ ELEKTRONİK İLETİ BİLGİLENDİRMESİ\n\nPazarlama iletileri yürürlükteki onay ve ret kurallarına tabidir. Kullanıcı abonelikten çıkma hakkını her zaman kullanabilir. Hizmetin ifası için zorunlu işlem mesajları pazarlama mesajlarından ayrı değerlendirilir.`,

  theme: "luxury",
  homeContent: {
    heroTrustLine: "YÜKSEKOVA • 5 DAKİKADA TALEP • GERÇEK ARAÇ • YEREL EKİP",
    heroTitle: "Aracı aramakla vakit kaybetmeyin. 5 dakikada planınızı başlatın.",
    heroSubtitle: "Kiralık araç, şoförlü transfer, düğün aracı veya tur... İhtiyacınızı seçin; gerçek seçenekleri karşılaştırın, fiyatı görün ve yerel ekibe doğrudan ulaşın.",
    searchPlaceholder: "Araç, model, tur veya ihtiyacınızı yazın",
    searchButtonLabel: "Bul",
    trustPrice: "Fiyatı baştan görün",
    trustSupport: "5 dakikada talep bırakın",
    trustVerified: "Gerçek araç, yerel ekip",
    bookingTitle: "5 dakikada planınızı oluşturun",
    bookingSubtitle: "Ne istediğinizi, tarihi ve teslim noktasını seçin. Size uyan seçenekleri hemen görün; kesin uygunluğu yerel ekibimiz doğrulasın.",
    plannerKicker: "HIZLI PLANLAMA",
    plannerNote: "Talep göndermek ücretsizdir. Kesin rezervasyon, araç ve tarih uygunluğu doğrulandıktan sonra oluşur.",
    plannerServiceLabel: "Ne için araç veya hizmet arıyorsunuz?",
    plannerServiceIndividual: "Şoförsüz araç kiralama",
    plannerServiceDriver: "Şoförlü araç / transfer",
    plannerServiceWedding: "Düğün / özel gün aracı",
    plannerServiceTour: "Tur / gezi planı",
    plannerPickupLabel: "Nereden teslim almak istiyorsunuz?",
    plannerPickupPlaceholder: "Teslim noktasını seçin",
    plannerTourDateLabel: "Tur tarihi",
    plannerStartDateLabel: "Alış tarihi",
    plannerEndDateLabel: "İade tarihi",
    plannerButtonRental: "Bu Tarihe Uyan Araçları Göster",
    plannerButtonDriver: "Şoförlü Seçenekleri Göster",
    plannerButtonWedding: "Özel Gün Araçlarını Göster",
    plannerButtonTour: "Bu Tarihe Uyan Turları Göster",
    plannerLoadingText: "Size uygun seçenekler hazırlanıyor...",
    plannerErrorTourDate: "Tur tarihini seçin.",
    plannerErrorStartDate: "Alış tarihini seçin.",
    plannerErrorEndDate: "İade tarihini seçin.",
    plannerErrorDateOrder: "İade tarihi alış tarihinden sonra olmalıdır.",
    plannerErrorPickup: "Teslim alma noktasını seçin."
  }
};
