import { DestroyRef, Injectable, inject, signal } from '@angular/core';
import { AuthService } from './auth.service';
import { PublicContentRealtimeService } from './public-content-realtime.service';
import { SUPABASE_PROJECT_URL, SUPABASE_PUBLISHABLE_KEY } from '../supabase.config';

export interface FooterSettings {
  isEnabled:boolean;brandSummary:string;servicesTitle:string;corporateTitle:string;legalTitle:string;
  newsletterEnabled:boolean;newsletterTitle:string;newsletterDescription:string;newsletterButtonText:string;
  showPhone:boolean;showWhatsapp:boolean;showSocial:boolean;showFeedback:boolean;showLegalLinks:boolean;
  homeLabel:string;contactLabel:string;phoneLabel:string;whatsappLabel:string;defaultTagline:string;whatsappDefaultMessage:string;
  legalMoreLabel:string;newsletterEmailLabel:string;newsletterEmailPlaceholder:string;newsletterFreeNote:string;newsletterLegalLabel:string;
  newsletterSuccessMessage:string;newsletterInvalidEmailMessage:string;newsletterErrorMessage:string;copyrightSuffix:string;
}
export interface PrefooterSettings { isEnabled:boolean;badge:string;title:string;description:string;primaryLabel:string;primaryRoute:string;secondaryLabel:string;secondaryRoute:string;trustItems:string[];showOnHome:boolean;showOnInner:boolean; }
export type FooterLinkGroup='SERVICES'|'CORPORATE'|'LEGAL'|'BOTTOM';
export type FooterLinkAction='ROUTE'|'LEGAL'|'FEEDBACK'|'EXTERNAL'|'ADMIN';
export interface FooterLink { linkKey:string;groupKey:FooterLinkGroup;label:string;actionType:FooterLinkAction;route?:string;queryParams:Record<string,string>;externalUrl?:string;sortOrder:number;isEnabled:boolean;opensNewTab:boolean;isSecondary:boolean; }
interface SiteSnapshot {ok?:boolean;code?:string;footerSettings?:Record<string,unknown>;footerLinks?:Record<string,unknown>[];prefooterSettings?:Record<string,unknown>;capabilities?:{settings?:boolean};}
interface FooterMutation {ok?:boolean;code?:string;footerSettings?:Record<string,unknown>;footerLinks?:Record<string,unknown>[];prefooterSettings?:Record<string,unknown>;}

const DEFAULT_FOOTER_SETTINGS:FooterSettings={
  isEnabled:true,brandSummary:'Araç kiralama, ikinci el satış, transfer ve bölgesel tur hizmetlerini tek yerde planlayın.',servicesTitle:'Hizmetler',corporateTitle:'Alperler Auto',legalTitle:'Yasal',
  newsletterEnabled:true,newsletterTitle:'Yeni araç ve fırsatları kaçırmayın',newsletterDescription:'Sadece yeni ilan, tur ve kampanya olduğunda haber alın. Abonelik ücretsizdir.',newsletterButtonText:'Ücretsiz Abone Ol',
  showPhone:true,showWhatsapp:true,showSocial:true,showFeedback:true,showLegalLinks:true,
  homeLabel:'Ana Sayfa',contactLabel:'İletişim',phoneLabel:'Telefon',whatsappLabel:'WhatsApp',defaultTagline:'Kiralama • Satış • Tur',whatsappDefaultMessage:'Merhaba, Alperler Rent A Car hizmetleri hakkında bilgi almak istiyorum.',
  legalMoreLabel:'Diğer yasal bilgiler',newsletterEmailLabel:'E-posta adresi',newsletterEmailPlaceholder:'ornek@eposta.com',newsletterFreeNote:'Abonelik ücretsizdir.',newsletterLegalLabel:'Ticari ileti ve abonelik koşulları',
  newsletterSuccessMessage:'Aboneliğiniz kaydedildi.',newsletterInvalidEmailMessage:'Geçerli bir e-posta adresi girin.',newsletterErrorMessage:'Abonelik şu anda tamamlanamadı. Lütfen tekrar deneyin.',copyrightSuffix:'Tüm hakları saklıdır.'
};
const DEFAULT_PREFOOTER:PrefooterSettings={isEnabled:true,badge:'Size Uygun Sonraki Adım',title:'Planınızı Birlikte Netleştirelim',description:'Araç kiralama, ikinci el araç, tur, transfer, randevu veya aracınızı değerlendirme konusunda hangi adımın size uygun olduğunu birlikte netleştirin.',primaryLabel:'Bize Ulaşın',primaryRoute:'/contact',secondaryLabel:'Randevu Oluştur',secondaryRoute:'/appointment',trustItems:['Kiralama, satış, tur ve transfer tek ekipte','WhatsApp ve telefon desteği','İçerikler canlı katalog ve şube verisinden gelir'],showOnHome:true,showOnInner:true};

@Injectable({providedIn:'root'})
export class FooterSettingsService{
  private readonly auth=inject(AuthService);private readonly realtime=inject(PublicContentRealtimeService);private readonly destroyRef=inject(DestroyRef);private readonly endpoint='/api/partner?op=site-content-admin';
  private readonly footerSettingsSelect='config_key,is_enabled,brand_summary,services_title,corporate_title,legal_title,newsletter_enabled,newsletter_title,newsletter_description,newsletter_button_text,show_phone,show_whatsapp,show_social,show_feedback,show_legal_links,home_label,contact_label,phone_label,whatsapp_label,default_tagline,whatsapp_default_message,legal_more_label,newsletter_email_label,newsletter_email_placeholder,newsletter_free_note,newsletter_legal_label,newsletter_success_message,newsletter_invalid_email_message,newsletter_error_message,copyright_suffix';
  private readonly footerLinkSelect='link_key,config_key,group_key,label,action_type,route,query_params,external_url,sort_order,is_enabled,opens_new_tab,is_secondary';
  private readonly prefooterSelect='config_key,is_enabled,badge,title,description,primary_label,primary_route,secondary_label,secondary_route,trust_items,show_on_home,show_on_inner';
  private readonly _settings=signal<FooterSettings>({...DEFAULT_FOOTER_SETTINGS});private readonly _prefooter=signal<PrefooterSettings>({...DEFAULT_PREFOOTER});private readonly _links=signal<FooterLink[]>([]);private readonly _loading=signal(false);private refreshTimer?:number;
  readonly settings=this._settings.asReadonly();readonly prefooter=this._prefooter.asReadonly();readonly links=this._links.asReadonly();readonly loading=this._loading.asReadonly();

  constructor(){void this.refreshPublic();const unwatch=this.realtime.watch(['footer_settings','footer_links','prefooter_settings'],()=>this.queueRefresh());this.destroyRef.onDestroy(()=>{unwatch();if(this.refreshTimer!==undefined&&typeof window!=='undefined')window.clearTimeout(this.refreshTimer);});}
  linksFor(group:FooterLinkGroup,secondary?:boolean):FooterLink[]{return this._links().filter(link=>link.groupKey===group&&link.isEnabled&&(secondary===undefined||link.isSecondary===secondary)).sort((a,b)=>a.sortOrder-b.sortOrder||a.label.localeCompare(b.label,'tr'));}

  async refreshPublic():Promise<void>{this._loading.set(true);try{const [settingsResponse,linksResponse,prefooterResponse]=await Promise.all([fetch(`${SUPABASE_PROJECT_URL}/rest/v1/footer_settings?config_key=eq.main&select=${this.footerSettingsSelect}`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,accept:'application/json'},cache:'no-store'}),fetch(`${SUPABASE_PROJECT_URL}/rest/v1/footer_links?config_key=eq.main&is_enabled=eq.true&select=${this.footerLinkSelect}&order=group_key.asc,sort_order.asc`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,accept:'application/json'},cache:'no-store'}),fetch(`${SUPABASE_PROJECT_URL}/rest/v1/prefooter_settings?config_key=eq.main&select=${this.prefooterSelect}`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,accept:'application/json'},cache:'no-store'})]);if(settingsResponse.ok){const rows=await settingsResponse.json() as Record<string,unknown>[];if(rows[0])this._settings.set(this.fromRow(rows[0]));}if(linksResponse.ok){const rows=await linksResponse.json() as Record<string,unknown>[];this._links.set(rows.map(row=>this.linkFromRow(row)));}if(prefooterResponse.ok){const rows=await prefooterResponse.json() as Record<string,unknown>[];if(rows[0])this._prefooter.set(this.prefooterFromRow(rows[0]));}}finally{this._loading.set(false);}}

  async refreshAdmin():Promise<void>{const token=await this.requiredToken();const payload=await this.gateway<SiteSnapshot>('GET',token);if(payload.ok!==true)throw new Error(payload.code||'FOOTER_ADMIN_LOAD_FAILED');this._settings.set(payload.footerSettings?this.fromRow(payload.footerSettings):{...DEFAULT_FOOTER_SETTINGS});this._links.set((payload.footerLinks||[]).map(row=>this.linkFromRow(row)));this._prefooter.set(payload.prefooterSettings?this.prefooterFromRow(payload.prefooterSettings):{...DEFAULT_PREFOOTER});}
  async save(settings:FooterSettings,links:FooterLink[]=this._links()):Promise<void>{const token=await this.requiredToken();const normalizedLinks=links.map((link,index)=>this.normalizeLink(link,index));const payload=await this.gateway<FooterMutation>('PATCH',token,{action:'saveFooter',settings:this.settingsPayload(settings),links:normalizedLinks});if(payload.ok!==true)throw new Error(payload.code||'FOOTER_SAVE_FAILED');this._settings.set(payload.footerSettings?this.fromRow(payload.footerSettings):settings);this._links.set((payload.footerLinks||[]).map(row=>this.linkFromRow(row)));}
  async savePrefooter(settings:PrefooterSettings):Promise<void>{this.validatePrefooter(settings);const token=await this.requiredToken();const payload=await this.gateway<FooterMutation>('PATCH',token,{action:'savePrefooter',settings:{isEnabled:Boolean(settings.isEnabled),badge:this.clean(settings.badge,100),title:this.clean(settings.title,180),description:this.clean(settings.description,700),primaryLabel:this.clean(settings.primaryLabel,100),primaryRoute:settings.primaryRoute.trim(),secondaryLabel:this.clean(settings.secondaryLabel,100),secondaryRoute:settings.secondaryRoute.trim(),trustItems:settings.trustItems.map(item=>this.clean(item,160)).filter(Boolean).slice(0,6),showOnHome:Boolean(settings.showOnHome),showOnInner:Boolean(settings.showOnInner)}});if(payload.ok!==true)throw new Error(payload.code||'PREFOOTER_SAVE_FAILED');this._prefooter.set(payload.prefooterSettings?this.prefooterFromRow(payload.prefooterSettings):settings);}

  private validatePrefooter(settings:PrefooterSettings){if(!settings.title.trim()||!settings.primaryLabel.trim()||!settings.primaryRoute.startsWith('/')||!settings.secondaryRoute.startsWith('/'))throw new Error('PREFOOTER_SETTINGS_INVALID');}
  private settingsPayload(settings:FooterSettings){return{
    isEnabled:Boolean(settings.isEnabled),brandSummary:this.clean(settings.brandSummary,700),servicesTitle:this.clean(settings.servicesTitle,80)||DEFAULT_FOOTER_SETTINGS.servicesTitle,corporateTitle:this.clean(settings.corporateTitle,80)||DEFAULT_FOOTER_SETTINGS.corporateTitle,legalTitle:this.clean(settings.legalTitle,80)||DEFAULT_FOOTER_SETTINGS.legalTitle,
    newsletterEnabled:Boolean(settings.newsletterEnabled),newsletterTitle:this.clean(settings.newsletterTitle,180)||DEFAULT_FOOTER_SETTINGS.newsletterTitle,newsletterDescription:this.clean(settings.newsletterDescription,500),newsletterButtonText:this.clean(settings.newsletterButtonText,80)||DEFAULT_FOOTER_SETTINGS.newsletterButtonText,
    showPhone:Boolean(settings.showPhone),showWhatsapp:Boolean(settings.showWhatsapp),showSocial:Boolean(settings.showSocial),showFeedback:Boolean(settings.showFeedback),showLegalLinks:Boolean(settings.showLegalLinks),
    homeLabel:this.clean(settings.homeLabel,80)||DEFAULT_FOOTER_SETTINGS.homeLabel,contactLabel:this.clean(settings.contactLabel,80)||DEFAULT_FOOTER_SETTINGS.contactLabel,phoneLabel:this.clean(settings.phoneLabel,80)||DEFAULT_FOOTER_SETTINGS.phoneLabel,whatsappLabel:this.clean(settings.whatsappLabel,80)||DEFAULT_FOOTER_SETTINGS.whatsappLabel,
    defaultTagline:this.clean(settings.defaultTagline,180)||DEFAULT_FOOTER_SETTINGS.defaultTagline,whatsappDefaultMessage:this.clean(settings.whatsappDefaultMessage,500)||DEFAULT_FOOTER_SETTINGS.whatsappDefaultMessage,legalMoreLabel:this.clean(settings.legalMoreLabel,120)||DEFAULT_FOOTER_SETTINGS.legalMoreLabel,
    newsletterEmailLabel:this.clean(settings.newsletterEmailLabel,100)||DEFAULT_FOOTER_SETTINGS.newsletterEmailLabel,newsletterEmailPlaceholder:this.clean(settings.newsletterEmailPlaceholder,160)||DEFAULT_FOOTER_SETTINGS.newsletterEmailPlaceholder,newsletterFreeNote:this.clean(settings.newsletterFreeNote,180)||DEFAULT_FOOTER_SETTINGS.newsletterFreeNote,newsletterLegalLabel:this.clean(settings.newsletterLegalLabel,180)||DEFAULT_FOOTER_SETTINGS.newsletterLegalLabel,
    newsletterSuccessMessage:this.clean(settings.newsletterSuccessMessage,220)||DEFAULT_FOOTER_SETTINGS.newsletterSuccessMessage,newsletterInvalidEmailMessage:this.clean(settings.newsletterInvalidEmailMessage,220)||DEFAULT_FOOTER_SETTINGS.newsletterInvalidEmailMessage,newsletterErrorMessage:this.clean(settings.newsletterErrorMessage,220)||DEFAULT_FOOTER_SETTINGS.newsletterErrorMessage,copyrightSuffix:this.clean(settings.copyrightSuffix,120)||DEFAULT_FOOTER_SETTINGS.copyrightSuffix
  };}
  private normalizeLink(link:FooterLink,index:number):FooterLink{const action=(['ROUTE','LEGAL','FEEDBACK','EXTERNAL','ADMIN'].includes(link.actionType)?link.actionType:'ROUTE') as FooterLinkAction;return{linkKey:String(link.linkKey||`custom.${crypto.randomUUID()}`).toLowerCase().replace(/[^a-z0-9._-]/g,'').slice(0,80),groupKey:(['SERVICES','CORPORATE','LEGAL','BOTTOM'].includes(link.groupKey)?link.groupKey:'SERVICES') as FooterLinkGroup,label:this.clean(link.label,100),actionType:action,route:action==='EXTERNAL'||action==='FEEDBACK'?undefined:this.clean(link.route||'',300),queryParams:link.queryParams&&typeof link.queryParams==='object'?link.queryParams:{},externalUrl:action==='EXTERNAL'?this.clean(link.externalUrl||'',1000):undefined,sortOrder:Number.isFinite(Number(link.sortOrder))?Math.max(0,Math.min(Number(link.sortOrder),10000)):index*10,isEnabled:link.isEnabled!==false,opensNewTab:Boolean(link.opensNewTab),isSecondary:Boolean(link.isSecondary)};}
  private fromRow(row:Record<string,unknown>):FooterSettings{return{
    isEnabled:(row['is_enabled']??row['isEnabled'])!==false,brandSummary:this.str(row,'brand_summary','brandSummary',DEFAULT_FOOTER_SETTINGS.brandSummary),servicesTitle:this.str(row,'services_title','servicesTitle',DEFAULT_FOOTER_SETTINGS.servicesTitle),corporateTitle:this.str(row,'corporate_title','corporateTitle',DEFAULT_FOOTER_SETTINGS.corporateTitle),legalTitle:this.str(row,'legal_title','legalTitle',DEFAULT_FOOTER_SETTINGS.legalTitle),
    newsletterEnabled:(row['newsletter_enabled']??row['newsletterEnabled'])!==false,newsletterTitle:this.str(row,'newsletter_title','newsletterTitle',DEFAULT_FOOTER_SETTINGS.newsletterTitle),newsletterDescription:this.str(row,'newsletter_description','newsletterDescription',DEFAULT_FOOTER_SETTINGS.newsletterDescription),newsletterButtonText:this.str(row,'newsletter_button_text','newsletterButtonText',DEFAULT_FOOTER_SETTINGS.newsletterButtonText),
    showPhone:(row['show_phone']??row['showPhone'])!==false,showWhatsapp:(row['show_whatsapp']??row['showWhatsapp'])!==false,showSocial:(row['show_social']??row['showSocial'])!==false,showFeedback:(row['show_feedback']??row['showFeedback'])!==false,showLegalLinks:(row['show_legal_links']??row['showLegalLinks'])!==false,
    homeLabel:this.str(row,'home_label','homeLabel',DEFAULT_FOOTER_SETTINGS.homeLabel),contactLabel:this.str(row,'contact_label','contactLabel',DEFAULT_FOOTER_SETTINGS.contactLabel),phoneLabel:this.str(row,'phone_label','phoneLabel',DEFAULT_FOOTER_SETTINGS.phoneLabel),whatsappLabel:this.str(row,'whatsapp_label','whatsappLabel',DEFAULT_FOOTER_SETTINGS.whatsappLabel),defaultTagline:this.str(row,'default_tagline','defaultTagline',DEFAULT_FOOTER_SETTINGS.defaultTagline),whatsappDefaultMessage:this.str(row,'whatsapp_default_message','whatsappDefaultMessage',DEFAULT_FOOTER_SETTINGS.whatsappDefaultMessage),legalMoreLabel:this.str(row,'legal_more_label','legalMoreLabel',DEFAULT_FOOTER_SETTINGS.legalMoreLabel),
    newsletterEmailLabel:this.str(row,'newsletter_email_label','newsletterEmailLabel',DEFAULT_FOOTER_SETTINGS.newsletterEmailLabel),newsletterEmailPlaceholder:this.str(row,'newsletter_email_placeholder','newsletterEmailPlaceholder',DEFAULT_FOOTER_SETTINGS.newsletterEmailPlaceholder),newsletterFreeNote:this.str(row,'newsletter_free_note','newsletterFreeNote',DEFAULT_FOOTER_SETTINGS.newsletterFreeNote),newsletterLegalLabel:this.str(row,'newsletter_legal_label','newsletterLegalLabel',DEFAULT_FOOTER_SETTINGS.newsletterLegalLabel),newsletterSuccessMessage:this.str(row,'newsletter_success_message','newsletterSuccessMessage',DEFAULT_FOOTER_SETTINGS.newsletterSuccessMessage),newsletterInvalidEmailMessage:this.str(row,'newsletter_invalid_email_message','newsletterInvalidEmailMessage',DEFAULT_FOOTER_SETTINGS.newsletterInvalidEmailMessage),newsletterErrorMessage:this.str(row,'newsletter_error_message','newsletterErrorMessage',DEFAULT_FOOTER_SETTINGS.newsletterErrorMessage),copyrightSuffix:this.str(row,'copyright_suffix','copyrightSuffix',DEFAULT_FOOTER_SETTINGS.copyrightSuffix)
  };}
  private prefooterFromRow(row:Record<string,unknown>):PrefooterSettings{const raw=row['trust_items']??row['trustItems'];return{isEnabled:(row['is_enabled']??row['isEnabled'])!==false,badge:String(row['badge']||DEFAULT_PREFOOTER.badge),title:String(row['title']||DEFAULT_PREFOOTER.title),description:String(row['description']||DEFAULT_PREFOOTER.description),primaryLabel:String(row['primary_label']||row['primaryLabel']||DEFAULT_PREFOOTER.primaryLabel),primaryRoute:String(row['primary_route']||row['primaryRoute']||DEFAULT_PREFOOTER.primaryRoute),secondaryLabel:String(row['secondary_label']||row['secondaryLabel']||DEFAULT_PREFOOTER.secondaryLabel),secondaryRoute:String(row['secondary_route']||row['secondaryRoute']||DEFAULT_PREFOOTER.secondaryRoute),trustItems:Array.isArray(raw)?raw.map(String).filter(Boolean).slice(0,6):[...DEFAULT_PREFOOTER.trustItems],showOnHome:(row['show_on_home']??row['showOnHome'])!==false,showOnInner:(row['show_on_inner']??row['showOnInner'])!==false};}
  private linkFromRow(row:Record<string,unknown>):FooterLink{return{linkKey:String(row['link_key']||row['linkKey']||''),groupKey:String(row['group_key']||row['groupKey']||'SERVICES') as FooterLinkGroup,label:String(row['label']||''),actionType:String(row['action_type']||row['actionType']||'ROUTE') as FooterLinkAction,route:row['route']?String(row['route']):undefined,queryParams:row['query_params']&&typeof row['query_params']==='object'?row['query_params'] as Record<string,string>:row['queryParams']&&typeof row['queryParams']==='object'?row['queryParams'] as Record<string,string>:{},externalUrl:row['external_url']?String(row['external_url']):undefined,sortOrder:Number(row['sort_order']??row['sortOrder']??0),isEnabled:(row['is_enabled']??row['isEnabled'])!==false,opensNewTab:Boolean(row['opens_new_tab']??row['opensNewTab']),isSecondary:Boolean(row['is_secondary']??row['isSecondary'])};}
  private str(row:Record<string,unknown>,snake:string,camel:string,fallback:string){return String(row[snake]??row[camel]??fallback).trim()||fallback;}
  private queueRefresh(){if(typeof window==='undefined'){void this.refreshPublic();return;}if(this.refreshTimer!==undefined)window.clearTimeout(this.refreshTimer);this.refreshTimer=window.setTimeout(()=>{this.refreshTimer=undefined;void this.refreshPublic();},120);}
  private clean(value:string,max:number){return String(value||'').replace(/\s+/g,' ').trim().slice(0,max);}
  private async requiredToken(){const token=await this.auth.getAccessToken();if(!token)throw new Error('ADMIN_SESSION_REQUIRED');return token;}
  private async gateway<T>(method:'GET'|'PATCH',token:string,body?:unknown):Promise<T>{const response=await fetch(this.endpoint,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',accept:'application/json','x-request-id':crypto.randomUUID()},body:method==='GET'?undefined:JSON.stringify(body),cache:'no-store'});const payload=await response.json().catch(()=>({})) as T&{code?:string;message?:string};if(!response.ok)throw new Error(String(payload.code||payload.message||`FOOTER_GATEWAY_${response.status}`));return payload;}
}
