import { Injectable } from '@angular/core';
import { Car, Vehicle } from '../models/car.model';
import { SUPABASE_PROJECT_URL, SUPABASE_PUBLISHABLE_KEY } from '../supabase.config';
import { CampaignRecord } from './campaign.service';

export interface CatalogPage<T> { items:T[]; page:number; pageSize:number; hasMore:boolean; }
export interface VehicleFacetsV217 { brands:string[]; years:number[]; fuels:string[]; transmissions:string[]; bodyTypes:string[]; colors:string[]; priceMin:number; priceMax:number; hourlyPriceMin:number; hourlyPriceMax:number; kmMin:number; kmMax:number; }
export interface TourFacetsV217 { durations:string[]; categories:string[]; locations:string[]; priceMin:number; priceMax:number; }
export interface VehicleQueryV217 {
  category:'RENTAL'|'SALE'; page?:number; pageSize?:number; search?:string; brand?:string; year?:number|string; fuel?:string; transmission?:string; bodyType?:string; color?:string; branchId?:string;
  minPrice?:number|null; maxPrice?:number|null; minKm?:number|null; maxKm?:number|null; minSeats?:number|null; driverMode?:'any'|'with'|'without'; hourlyOnly?:boolean; availableOnly?:boolean;
  damageFilter?:'all'|'clean'|'declared'|'tramer-unverified'; warrantyOnly?:boolean; saleStatus?:'available'|'all'|'sold'; sortBy?:'recommended'|'priceAsc'|'priceDesc'|'yearDesc'|'kmAsc'; signal?:AbortSignal;
}
export interface TourQueryV217 { page?:number; pageSize?:number; search?:string; duration?:string; category?:string; location?:string; minPrice?:number|null; maxPrice?:number|null; sortBy?:'featured'|'priceAsc'|'priceDesc'|'title'; signal?:AbortSignal; }
export interface BlogQueryV217 { page?:number; pageSize?:number; search?:string; signal?:AbortSignal; }
export interface TourCardV217 extends Vehicle { shortDescription?:string; categoryName?:string; locationName?:string; latitude?:number; longitude?:number; mapUrl?:string; }
export interface BlogCardV217 { id:string; cloudId:string; cloudSlug?:string; title:string; summary:string; content:string; image?:string; authorName?:string; readTime:string; date:string; publishedAt?:string; }
export interface BranchCardV217 { id:string; name:string; code?:string; slug?:string; district?:string; city?:string; publicDescription?:string; heroImage?:string; networkType?:string; isPickupPoint:boolean; isReturnPoint:boolean; }

const EMPTY_VEHICLE_FACETS:VehicleFacetsV217={brands:[],years:[],fuels:[],transmissions:[],bodyTypes:[],colors:[],priceMin:0,priceMax:0,hourlyPriceMin:0,hourlyPriceMax:0,kmMin:0,kmMax:0};
const EMPTY_TOUR_FACETS:TourFacetsV217={durations:[],categories:[],locations:[],priceMin:0,priceMax:0};

@Injectable({providedIn:'root'})
export class ScalablePublicCatalogV217Service {
  private readonly headers={apikey:SUPABASE_PUBLISHABLE_KEY,accept:'application/json','cache-control':'no-cache'};
  private readonly uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

  async listVehicles(input:VehicleQueryV217):Promise<CatalogPage<Car>>{
    const page=this.page(input.page),pageSize=this.pageSize(input.pageSize);const params=new URLSearchParams();
    params.set('select','*');params.set('category',`eq.${input.category}`);this.applySearch(params,input.search);
    if(input.brand)params.set('brand',`eq.${this.filterValue(input.brand)}`);if(input.year)params.set('model_year',`eq.${Number(input.year)}`);if(input.fuel)params.set('fuel_type',`eq.${this.filterValue(input.fuel)}`);if(input.transmission)params.set('transmission',`eq.${this.filterValue(input.transmission)}`);if(input.bodyType)params.set('body_type',`eq.${this.filterValue(input.bodyType)}`);if(input.color)params.set('color',`eq.${this.filterValue(input.color)}`);if(input.branchId&&this.uuid.test(input.branchId))params.set('branch_id',`eq.${input.branchId}`);
    const priceColumn=input.category==='RENTAL'&&input.hourlyOnly?'rental_price_hourly':input.category==='RENTAL'?'rental_price_daily':'price';
    if(this.number(input.minPrice)!=null)params.set(priceColumn,`gte.${this.number(input.minPrice)}`);if(this.number(input.maxPrice)!=null)params.append(priceColumn,`lte.${this.number(input.maxPrice)}`);if(this.number(input.minKm)!=null)params.set('mileage_km',`gte.${this.number(input.minKm)}`);if(this.number(input.maxKm)!=null)params.append('mileage_km',`lte.${this.number(input.maxKm)}`);if(this.number(input.minSeats)!=null&&Number(input.minSeats)>0)params.set('seats',`gte.${Math.floor(Number(input.minSeats))}`);
    if(input.hourlyOnly)params.set('hourly_rental_enabled','eq.true');if(input.availableOnly)params.set('availability_status','eq.AVAILABLE');
    if(input.category==='SALE'){if(input.saleStatus==='available'||!input.saleStatus)params.set('availability_status','neq.SOLD');else if(input.saleStatus==='sold')params.set('availability_status','eq.SOLD');if(input.damageFilter==='clean')params.set('is_damage_free','eq.true');else if(input.damageFilter==='declared')params.set('is_damage_free','eq.false');else if(input.damageFilter==='tramer-unverified')params.set('tramer_status','eq.UNKNOWN');if(input.warrantyOnly)params.set('has_warranty','eq.true');}
    if(input.driverMode==='with')params.set('driver_option','in.(WITH_DRIVER,BOTH)');else if(input.driverMode==='without')params.set('driver_option','in.(WITHOUT_DRIVER,BOTH)');
    params.set('order',this.vehicleOrder(input.sortBy||'recommended',priceColumn));this.pageParams(params,page,pageSize);
    const rows=await this.get<any[]>(`public_vehicle_catalog_v217?${params}`,input.signal);return this.pageResult(rows,page,pageSize,row=>this.mapVehicle(row,input.category));
  }

  async vehicleFacets(category:'RENTAL'|'SALE',signal?:AbortSignal):Promise<VehicleFacetsV217>{
    try{const payload=await this.rpc<Record<string,unknown>>('public_vehicle_facets_v217',{p_category:category},signal);return{brands:this.strings(payload['brands']),years:this.numbers(payload['years']),fuels:this.strings(payload['fuels']),transmissions:this.strings(payload['transmissions']),bodyTypes:this.strings(payload['bodyTypes']),colors:this.strings(payload['colors']),priceMin:this.num(payload['priceMin']),priceMax:this.num(payload['priceMax']),hourlyPriceMin:this.num(payload['hourlyPriceMin']),hourlyPriceMax:this.num(payload['hourlyPriceMax']),kmMin:this.num(payload['kmMin']),kmMax:this.num(payload['kmMax'])};}catch{return{...EMPTY_VEHICLE_FACETS};}
  }

  async listTours(input:TourQueryV217={}):Promise<CatalogPage<TourCardV217>>{
    const page=this.page(input.page),pageSize=this.pageSize(input.pageSize);const params=new URLSearchParams();params.set('select','*');this.applySearch(params,input.search);
    if(input.duration&&input.duration!=='ALL')params.set('duration',`eq.${this.filterValue(input.duration)}`);if(input.category&&input.category!=='ALL')params.set('category',`eq.${this.filterValue(input.category)}`);if(input.location&&input.location!=='ALL')params.set('location_name',`eq.${this.filterValue(input.location)}`);if(this.number(input.minPrice)!=null)params.set('price_per_person',`gte.${this.number(input.minPrice)}`);if(this.number(input.maxPrice)!=null)params.append('price_per_person',`lte.${this.number(input.maxPrice)}`);
    params.set('order',this.tourOrder(input.sortBy||'featured'));this.pageParams(params,page,pageSize);const rows=await this.get<any[]>(`public_tour_catalog_v217?${params}`,input.signal);return this.pageResult(rows,page,pageSize,row=>this.mapTour(row));
  }

  async tourFacets(signal?:AbortSignal):Promise<TourFacetsV217>{try{const payload=await this.rpc<Record<string,unknown>>('public_tour_facets_v217',{},signal);return{durations:this.strings(payload['durations']),categories:this.strings(payload['categories']),locations:this.strings(payload['locations']),priceMin:this.num(payload['priceMin']),priceMax:this.num(payload['priceMax'])};}catch{return{...EMPTY_TOUR_FACETS};}}

  async listBlogs(input:BlogQueryV217={}):Promise<CatalogPage<BlogCardV217>>{const page=this.page(input.page),pageSize=this.pageSize(input.pageSize);const params=new URLSearchParams();params.set('select','*');this.applySearch(params,input.search);params.set('order','published_at.desc.nullslast,id.asc');this.pageParams(params,page,pageSize);const rows=await this.get<any[]>(`public_blog_catalog_v217?${params}`,input.signal);return this.pageResult(rows,page,pageSize,row=>this.mapBlog(row));}

  async vehiclesByIdentifiers(ids:string[],category?:'RENTAL'|'SALE'):Promise<Car[]>{const clean=this.identifiers(ids);if(!clean.length)return[];const uuids=clean.filter(id=>this.uuid.test(id));const other=clean.filter(id=>!this.uuid.test(id));const rows:any[]=[];for(const chunk of this.chunks(uuids,40)){const p=new URLSearchParams({select:'*',id:`in.(${chunk.join(',')})`});if(category)p.set('category',`eq.${category}`);rows.push(...await this.get<any[]>(`public_vehicle_catalog_v217?${p}`));}for(const id of other.slice(0,80)){const safe=this.filterValue(id);const p=new URLSearchParams({select:'*',or:`(stock_code.eq.${safe},seo_slug.eq.${safe})`,limit:'1'});if(category)p.set('category',`eq.${category}`);rows.push(...await this.get<any[]>(`public_vehicle_catalog_v217?${p}`));}const mapped=rows.map(row=>this.mapVehicle(row,String(row.category)==='SALE'?'SALE':'RENTAL'));return this.restoreOrder(mapped,clean,item=>[String(item.cloudId||item.id),String(item.cloudStockCode||''),String(item.cloudSlug||'')]);}
  async toursByIdentifiers(ids:string[]):Promise<TourCardV217[]>{const clean=this.identifiers(ids);if(!clean.length)return[];const rows:any[]=[];for(const chunk of this.chunks(clean.filter(id=>this.uuid.test(id)),40)){rows.push(...await this.get<any[]>(`public_tour_catalog_v217?select=*&id=in.(${chunk.join(',')})`));}for(const id of clean.filter(id=>!this.uuid.test(id)).slice(0,80)){rows.push(...await this.get<any[]>(`public_tour_catalog_v217?select=*&seo_slug=eq.${encodeURIComponent(this.filterValue(id))}&limit=1`));}return this.restoreOrder(rows.map(row=>this.mapTour(row)),clean,item=>[String(item.cloudId||item.id),String(item.cloudSlug||'')]);}
  async blogsByIdentifiers(ids:string[]):Promise<BlogCardV217[]>{const clean=this.identifiers(ids);if(!clean.length)return[];const rows:any[]=[];for(const chunk of this.chunks(clean.filter(id=>this.uuid.test(id)),40)){rows.push(...await this.get<any[]>(`public_blog_catalog_v217?select=*&id=in.(${chunk.join(',')})`));}for(const id of clean.filter(id=>!this.uuid.test(id)).slice(0,80)){rows.push(...await this.get<any[]>(`public_blog_catalog_v217?select=*&slug=eq.${encodeURIComponent(this.filterValue(id))}&limit=1`));}return this.restoreOrder(rows.map(row=>this.mapBlog(row)),clean,item=>[item.cloudId,String(item.cloudSlug||'')]);}
  async campaignsByIdentifiers(ids:string[]):Promise<CampaignRecord[]>{const clean=this.identifiers(ids).filter(id=>this.uuid.test(id));if(!clean.length)return[];const rows:any[]=[];for(const chunk of this.chunks(clean,40))rows.push(...await this.get<any[]>(`public_campaign_catalog_v217?select=*&id=in.(${chunk.join(',')})`));return this.restoreOrder(rows.map(row=>this.mapCampaign(row)),clean,item=>[item.id,item.slug]);}
  async latestCampaigns(limit=6):Promise<CampaignRecord[]>{const p=new URLSearchParams({select:'*',order:'sort_order.asc,priority.asc,id.asc',limit:String(this.limit(limit,1,50))});return(await this.get<any[]>(`public_campaign_catalog_v217?${p}`)).map(row=>this.mapCampaign(row));}
  async listBranches(limit=8):Promise<BranchCardV217[]>{const p=new URLSearchParams({select:'*',order:'sort_order.asc,name.asc',limit:String(this.limit(limit,1,50))});return(await this.get<any[]>(`public_branch_catalog_v217?${p}`)).map(row=>({id:String(row.id),name:String(row.name||''),code:String(row.code||'')||undefined,slug:String(row.slug||'')||undefined,district:String(row.district||'')||undefined,city:String(row.city||'')||undefined,publicDescription:String(row.public_description||'')||undefined,heroImage:String(row.hero_image||'')||undefined,networkType:String(row.network_type||'')||undefined,isPickupPoint:row.is_pickup_point===true,isReturnPoint:row.is_return_point===true}));}

  private mapVehicle(row:any,category:'RENTAL'|'SALE'):Car{const m=this.object(row.metadata);const images=Array.isArray(row.images)?row.images.filter((v:unknown)=>typeof v==='string'&&v.trim()):[];const daily=Number(row.rental_price_daily??row.price??0),sale=Number(row.price??0);return{...m,id:String(row.id),cloudId:String(row.id),cloudStockCode:String(row.stock_code||'')||undefined,cloudSlug:String(row.seo_slug||'')||undefined,category,brand:String(row.brand||''),model:String(row.model||''),series:String(row.series||m['series']||'')||undefined,year:this.optionalNumber(row.model_year),price:category==='RENTAL'?(Number.isFinite(daily)?daily:0):(Number.isFinite(sale)?sale:0),hourlyPrice:this.optionalNumber(row.rental_price_hourly),hourlyRentalEnabled:row.hourly_rental_enabled===true,minimumRentalHours:this.optionalNumber(row.minimum_rental_hours),hourlyMileageLimit:this.optionalNumber(row.hourly_mileage_limit),km:this.optionalNumber(row.mileage_km),fuel:String(row.fuel_type||'')||undefined,transmission:String(row.transmission||'')||undefined,type:String(row.body_type||'')||undefined,color:String(row.color||'')||undefined,engineVolume:String(row.engine||'')||undefined,seats:this.optionalNumber(row.seats),doors:this.optionalNumber(row.doors),location:String(row.location||'')||undefined,description:String(row.description||''),features:Array.isArray(row.features)?row.features:[],images,gallery:images,image:String(row.cover_image||images[0]||'')||undefined,isFeatured:row.is_featured===true,isAvailable:String(row.availability_status||'AVAILABLE')==='AVAILABLE',availability:String(row.availability_status||''),driverOption:(String(row.driver_option||m['driverOption']||'')||undefined) as Car['driverOption'],warranty:String(row.warranty||m['warranty']||'')||undefined,damageStatus:String(row.damage_status||m['damageStatus']||'')||undefined,tramerStatus:(String(row.tramer_status||m['tramerStatus']||'')||undefined) as Car['tramerStatus'],hasWarranty:row.has_warranty===true,isDamageFree:row.is_damage_free===true,isPaintless:row.is_paintless===true,isReplaceFree:row.is_replace_free===true,displayPriority:this.optionalNumber(row.display_priority),publicationStatus:row.publication_status,publishedAt:row.published_at||undefined,scheduledAt:row.scheduled_at||undefined,branchId:row.branch_id||undefined,listingOrigin:row.listing_origin||undefined,createdAt:row.created_at||undefined,updatedAt:row.updated_at||undefined,bookedDates:Array.isArray(m['bookedDates'])?m['bookedDates'] as any:[]};}
  private mapTour(row:any):TourCardV217{const m=this.object(row.metadata);const images=Array.isArray(row.images)?row.images.filter((v:unknown)=>typeof v==='string'&&v.trim()):[];return{...m,id:String(row.id),cloudId:String(row.id),cloudSlug:String(row.seo_slug||'')||undefined,category:'TOUR',title:String(row.title||''),description:String(row.description||row.short_description||''),shortDescription:String(row.short_description||'')||undefined,price:this.num(row.price_per_person),image:String(row.cover_image||images[0]||'')||undefined,images,gallery:images,duration:String(row.duration||'')||undefined,capacity:this.optionalNumber(row.capacity),meetingPoint:String(row.meeting_point||'')||undefined,itinerary:Array.isArray(row.itinerary)?row.itinerary:[],includedItems:Array.isArray(row.included_items)?row.included_items:[],excludedItems:Array.isArray(row.excluded_items)?row.excluded_items:[],isFeatured:row.is_featured===true,badge:String(row.badge||m['badge']||'')||undefined,location:String(row.location_name||row.meeting_point||'')||undefined,locationName:String(row.location_name||'')||undefined,categoryName:String(row.category||'')||undefined,latitude:this.optionalNumber(row.latitude),longitude:this.optionalNumber(row.longitude),mapUrl:String(row.map_url||'')||undefined,publicationStatus:row.publication_status,publishedAt:row.published_at||undefined,branchId:row.branch_id||undefined,listingOrigin:row.listing_origin||undefined,createdAt:row.created_at||undefined,updatedAt:row.updated_at||undefined};}
  private mapBlog(row:any):BlogCardV217{const m=this.object(row.metadata);const published=String(row.published_at||'');return{id:String(row.id),cloudId:String(row.id),cloudSlug:String(row.slug||'')||undefined,title:String(row.title||''),summary:String(row.excerpt||''),content:String(row.content||''),image:String(row.cover_image||'')||undefined,authorName:String(row.author_name||'')||undefined,readTime:String(m['readTime']||'4 Dk Okuma'),date:String(m['originalDate']||(published?new Date(published).toLocaleDateString('tr-TR'):'')),publishedAt:published||undefined};}
  private mapCampaign(row:any):CampaignRecord{return{id:String(row.id),title:String(row.title||''),slug:String(row.slug||''),shortDescription:String(row.short_description||'')||undefined,description:String(row.description||'')||undefined,badge:String(row.badge||'')||undefined,campaignType:(row.campaign_type||'CUSTOM') as CampaignRecord['campaignType'],coverImage:String(row.cover_image||'')||undefined,oldPrice:this.optionalNumber(row.old_price),newPrice:this.optionalNumber(row.new_price),discountPercent:this.optionalNumber(row.discount_percent),discountMethod:(row.discount_method||'FIXED_AMOUNT') as CampaignRecord['discountMethod'],discountValue:this.num(row.discount_value),discountScope:(row.discount_scope||'UNIT') as CampaignRecord['discountScope'],visibilityMode:(row.visibility_mode||'CAMPAIGN_ONLY') as CampaignRecord['visibilityMode'],minimumOrderAmount:this.num(row.minimum_order_amount),minimumRentalDays:this.optionalNumber(row.minimum_rental_days),minimumRentalHours:this.optionalNumber(row.minimum_rental_hours),maxRedemptions:this.optionalNumber(row.max_redemptions),perCustomerLimit:this.num(row.per_customer_limit)||1,allowReferralDiscount:row.allow_referral_discount!==false,allowLoyaltyRedemption:row.allow_loyalty_redemption!==false,priority:this.num(row.priority),targetType:row.target_type||undefined,targetId:row.target_id||undefined,ctaLabel:String(row.cta_label||'Fırsatı İncele'),ctaUrl:String(row.cta_url||'')||undefined,whatsappMessage:String(row.whatsapp_message||'')||undefined,startsAt:row.starts_at||undefined,endsAt:row.ends_at||undefined,publicationStatus:(row.publication_status||'PUBLISHED') as CampaignRecord['publicationStatus'],isActive:row.is_active!==false,sortOrder:this.num(row.sort_order),metadata:this.object(row.metadata)};}

  private applySearch(params:URLSearchParams,raw?:string){const tokens=this.normalizeSearch(raw).split(' ').filter(Boolean).slice(0,6);if(tokens.length===1)params.set('search_text',`ilike.*${tokens[0]}*`);else if(tokens.length>1)params.set('and',`(${tokens.map(token=>`search_text.ilike.*${token}*`).join(',')})`);}
  private vehicleOrder(sort:string,priceColumn:string){if(sort==='priceAsc')return`${priceColumn}.asc.nullslast,id.asc`;if(sort==='priceDesc')return`${priceColumn}.desc.nullslast,id.asc`;if(sort==='yearDesc')return'model_year.desc.nullslast,id.asc';if(sort==='kmAsc')return'mileage_km.asc.nullslast,id.asc';return'is_featured.desc,display_priority.desc,published_at.desc.nullslast,id.asc';}
  private tourOrder(sort:string){if(sort==='priceAsc')return'price_per_person.asc.nullslast,id.asc';if(sort==='priceDesc')return'price_per_person.desc.nullslast,id.asc';if(sort==='title')return'title.asc,id.asc';return'is_featured.desc,published_at.desc.nullslast,id.asc';}
  private pageParams(params:URLSearchParams,page:number,pageSize:number){params.set('limit',String(pageSize+1));params.set('offset',String(page*pageSize));}
  private pageResult<T>(rows:any[],page:number,pageSize:number,map:(row:any)=>T):CatalogPage<T>{return{items:rows.slice(0,pageSize).map(map),page,pageSize,hasMore:rows.length>pageSize};}
  private async get<T>(path:string,signal?:AbortSignal):Promise<T>{const response=await this.fetch(`${SUPABASE_PROJECT_URL}/rest/v1/${path}`,{method:'GET',headers:this.headers,cache:'no-store'},signal);if(!response.ok)throw new Error(`PUBLIC_CATALOG_${response.status}`);return await response.json() as T;}
  private async rpc<T>(name:string,body:Record<string,unknown>,signal?:AbortSignal):Promise<T>{const response=await this.fetch(`${SUPABASE_PROJECT_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{...this.headers,'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'},signal);if(!response.ok)throw new Error(`PUBLIC_CATALOG_RPC_${response.status}`);return await response.json() as T;}
  private async fetch(url:string,init:RequestInit,signal?:AbortSignal){const controller=new AbortController();const timeout=typeof window!=='undefined'?window.setTimeout(()=>controller.abort(),12000):undefined;const onAbort=()=>controller.abort();signal?.addEventListener('abort',onAbort,{once:true});try{return await fetch(url,{...init,signal:controller.signal});}finally{if(timeout!==undefined)window.clearTimeout(timeout);signal?.removeEventListener('abort',onAbort);}}
  private normalizeSearch(value?:string){return String(value||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim().slice(0,120);}
  private filterValue(value:unknown){return String(value||'').replace(/[(),]/g,' ').replace(/\s+/g,' ').trim().slice(0,120);}
  private number(value:unknown):number|null{if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
  private optionalNumber(value:unknown):number|undefined{const n=this.number(value);return n===null?undefined:n;}
  private num(value:unknown){const n=Number(value);return Number.isFinite(n)?n:0;}
  private page(value:unknown){return Math.max(0,Math.floor(Number(value)||0));}
  private pageSize(value:unknown){return this.limit(Number(value)||24,8,48);}
  private limit(value:number,min:number,max:number){return Math.max(min,Math.min(max,Math.floor(value)||min));}
  private strings(value:unknown){return Array.isArray(value)?value.map(String).map(v=>v.trim()).filter(Boolean):[];}
  private numbers(value:unknown){return Array.isArray(value)?value.map(Number).filter(Number.isFinite):[];}
  private object(value:unknown):Record<string,any>{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};}
  private identifiers(ids:string[]){return [...new Set(ids.map(id=>String(id||'').trim()).filter(Boolean))].slice(0,200);}
  private chunks<T>(items:T[],size:number){const result:T[][]=[];for(let i=0;i<items.length;i+=size)result.push(items.slice(i,i+size));return result;}
  private restoreOrder<T>(items:T[],ids:string[],keys:(item:T)=>string[]):T[]{const index=new Map(ids.map((id,i)=>[id,i]));return [...items].sort((a,b)=>Math.min(...keys(a).map(k=>index.get(k)??1e9))-Math.min(...keys(b).map(k=>index.get(k)??1e9)));}
}
