import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const URL=Deno.env.get("SUPABASE_URL")||"";
const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"cache-control":"no-store","content-type":"application/json; charset=utf-8"}});
const clean=(v:unknown,m:number)=>typeof v==="string"?v.trim().slice(0,m):"";
const headers=(extra:Record<string,string>={})=>({apikey:KEY,authorization:`Bearer ${KEY}`,"content-type":"application/json",...extra});
const db=(path:string,init:RequestInit={})=>fetch(`${URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})}});
async function admin(req:Request){const authorization=req.headers.get("authorization")||"";if(!/^Bearer\s+\S+/i.test(authorization))throw new Error("UNAUTHORIZED");const ur=await fetch(`${URL}/auth/v1/user`,{headers:{apikey:KEY,authorization},signal:AbortSignal.timeout(8000)});if(!ur.ok)throw new Error("UNAUTHORIZED");const u=await ur.json(),id=clean(u?.id,80),email=clean(u?.email,160);if(!id)throw new Error("UNAUTHORIZED");const ar=await db(`admin_users?user_id=eq.${encodeURIComponent(id)}&is_active=eq.true&select=user_id,role&limit=1`);if(!ar.ok)throw new Error("ADMIN_LOOKUP_FAILED");const rows=await ar.json();if(!Array.isArray(rows)||!rows[0])throw new Error("FORBIDDEN");return{id,email,role:String(rows[0].role||"support")}}
Deno.serve(async req=>{try{const a=await admin(req);if(req.method==="GET"){const r=await db("contact_messages?select=*&order=created_at.desc&limit=500");if(!r.ok)throw new Error("CONTACT_LIST_FAILED");return json({ok:true,messages:await r.json()})}if(req.method==="PATCH"){const input=await req.json().catch(()=>({})),reference=clean(input?.reference,80),status=clean(input?.status,20).toUpperCase(),notes=clean(input?.internalNotes,4000)||null;if(!reference||!["NEW","READ","REPLIED","ARCHIVED"].includes(status))return json({ok:false,code:"INVALID_UPDATE"},400);const oldR=await db(`contact_messages?reference=eq.${encodeURIComponent(reference)}&select=*&limit=1`);if(!oldR.ok)throw new Error("CONTACT_READ_FAILED");const old=await oldR.json();if(!Array.isArray(old)||!old[0])return json({ok:false,code:"CONTACT_NOT_FOUND"},404);const update={status,internal_notes:notes,assigned_to:a.id,...(status==="READ"&&!old[0].read_at?{read_at:new Date().toISOString()}:{}),...(status==="REPLIED"&&!old[0].replied_at?{replied_at:new Date().toISOString()}:{}),...(status==="ARCHIVED"?{archived_at:new Date().toISOString()}: {})};const r=await db(`contact_messages?id=eq.${encodeURIComponent(old[0].id)}&select=*`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(update)});if(!r.ok)throw new Error("CONTACT_UPDATE_FAILED");const saved=(await r.json())[0];await db("audit_logs",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({actor_user_id:a.id,actor_email:a.email,action:"contact_message_updated",entity_type:"contact_message",entity_id:reference,before_data:old[0],after_data:saved})}).catch(()=>undefined);return json({ok:true,message:saved})}return json({ok:false,code:"METHOD_NOT_ALLOWED"},405)}catch(e){const c=e instanceof Error?e.message:"CONTACT_ADMIN_FAILED";return json({ok:false,code:c},c==="UNAUTHORIZED"?401:c==="FORBIDDEN"?403:500)}});