import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BranchFinanceV225Service } from '../services/branch-finance-v225.service';

@Component({selector:'app-branch-portal-finance-v225',standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="finance" aria-labelledby="branch-finance-title"><header><div><p class="kicker">ŞUBE FİNANSI</p><h2 id="branch-finance-title">Gelir, gider ve ödeme kontrolü</h2><span>Yalnız seçili şubenin finans hareketleri gösterilir. Platform geliri abonelik modelidir, işlem başına komisyon uygulanmaz.</span></div><button type="button" (click)="reload()" [disabled]="finance.loading()">Yenile</button></header>
@if(message()){<p class="notice success" role="status">{{message()}}</p>}@if(error()||finance.lastError()){<p class="notice error" role="alert">{{error()||finance.lastError()}}</p>}
@if(finance.snapshot();as data){<div class="metrics"><article><small>Gelir</small><strong>{{data.summary.income|number:'1.0-2'}} TRY</strong></article><article><small>Gider</small><strong>{{data.summary.expense|number:'1.0-2'}} TRY</strong></article><article><small>Açık Bakiye</small><strong>{{data.summary.outstanding|number:'1.0-2'}} TRY</strong></article><article><small>Rezervasyon</small><strong>{{data.summary.bookingCount}}</strong></article></div>
<div class="grid-two"><section class="card"><h3>Banka ve Vergi Profili</h3><p>Bu bilgiler private şemada tutulur ve halka açık şube profilinden ayrıdır.</p><div class="form-grid"><label><span>Banka</span><input [(ngModel)]="profile.bankName" name="financeBank"/></label><label><span>IBAN</span><input [(ngModel)]="profile.iban" name="financeIban" autocomplete="off"/></label><label><span>Hesap Sahibi</span><input [(ngModel)]="profile.accountHolder" name="financeHolder"/></label><label><span>Yasal Ünvan</span><input [(ngModel)]="profile.legalName" name="financeLegal"/></label><label><span>Vergi No</span><input [(ngModel)]="profile.taxNumber" name="financeTax" autocomplete="off"/></label><label><span>Vergi Dairesi</span><input [(ngModel)]="profile.taxOffice" name="financeTaxOffice"/></label><label><span>Ödeme Sağlayıcısı</span><select [(ngModel)]="profile.preferredProvider" name="financeProvider"><option value="NONE">Bağlı değil</option><option value="PAYTR">PayTR</option><option value="IYZICO">iyzico</option></select></label></div><button type="button" class="primary" (click)="saveProfile()" [disabled]="working()">Finans Profilini Kaydet</button><p class="status">Payout durumu: {{data.financeProfile.payoutStatus}} · {{data.financeProfile.payoutEnabled?'Aktif':'Kapalı'}}</p></section>
<section class="card"><h3>Gider Kaydı</h3><p>Bakım, yakıt, sigorta, vergi ve diğer gerçek şube giderlerini kaydedin.</p><div class="form-grid"><label><span>Tutar</span><input [(ngModel)]="expense.amount" name="expenseAmount" type="number" min="0.01" step="0.01"/></label><label><span>Kategori</span><select [(ngModel)]="expense.category" name="expenseCategory"><option>MAINTENANCE</option><option>FUEL</option><option>CLEANING</option><option>INSURANCE</option><option>TAX</option><option>ADVERTISING</option><option>SALARY</option><option>OFFICE</option><option>SERVICE</option><option>OTHER</option></select></label><label><span>Para Birimi</span><select [(ngModel)]="expense.currency" name="expenseCurrency"><option>TRY</option><option>EUR</option><option>USD</option><option>CHF</option></select></label><label><span>Firma / Kişi</span><input [(ngModel)]="expense.counterpartyName" name="expenseCounterparty"/></label><label><span>Fiş No</span><input [(ngModel)]="expense.receiptNumber" name="expenseReceipt"/></label><label><span>Fatura No</span><input [(ngModel)]="expense.invoiceNumber" name="expenseInvoice"/></label><label class="wide"><span>Açıklama</span><textarea [(ngModel)]="expense.description" name="expenseDescription" rows="3"></textarea></label></div><button type="button" class="primary" (click)="addExpense()" [disabled]="working()">Gideri Kaydet</button></section></div>
<section class="card"><h3>Şubede Alınan Ödeme</h3><p>Nakit/ofis veya EFT ödemesini kaydetmeden önce müşteri adı ve telefonu rezervasyonla eşleştirilir.</p><div class="payment-grid"><label><span>Rezervasyon No</span><input [(ngModel)]="payment.bookingReference" name="paymentBooking"/></label><label><span>Tutar</span><input [(ngModel)]="payment.amount" name="paymentAmount" type="number" min="0.01" step="0.01"/></label><label><span>Yöntem</span><select [(ngModel)]="payment.method" name="paymentMethod"><option value="OFFICE">Ofiste</option><option value="EFT">EFT</option></select></label><label><span>Ödeyen Ad Soyad</span><input [(ngModel)]="payment.payerName" name="payerName"/></label><label><span>Ödeyen Telefon</span><input [(ngModel)]="payment.payerPhone" name="payerPhone" autocomplete="tel"/></label><label><span>Referans</span><input [(ngModel)]="payment.externalReference" name="paymentRef"/></label></div><button type="button" class="primary" (click)="recordPayment()" [disabled]="working()">Ödemeyi Doğrula ve Kaydet</button></section>
<section class="card"><h3>Rezervasyon Kimlik Kontrolü</h3><div class="table-wrap"><table><thead><tr><th>Rezervasyon</th><th>Müşteri</th><th>Ödeme</th><th>İmza / Teslim</th><th>İşlem</th></tr></thead><tbody>@for(row of data.bookings;track row.reference){<tr><td><strong>{{row.reference}}</strong><small>{{row.itemName}}</small></td><td>{{row.customerName}}<small>{{row.customerPhone}}</small></td><td>{{row.payerMatchStatus}}</td><td>{{row.signerMatchStatus}}</td><td><div class="row-actions"><button type="button" (click)="confirmSigner(row.reference,true)" [disabled]="working()">Eşleşti</button><button type="button" class="danger" (click)="confirmSigner(row.reference,false)" [disabled]="working()">Eşleşmedi</button></div></td></tr>}@empty{<tr><td colspan="5">Rezervasyon bulunamadı.</td></tr>}</tbody></table></div></section>
<section class="card"><h3>Finans Hareketleri</h3><div class="table-wrap"><table><thead><tr><th>Tarih</th><th>Tür</th><th>Açıklama</th><th>Tutar</th><th>Kaynak</th></tr></thead><tbody>@for(row of data.transactions;track row.id){<tr><td>{{row.occurred_at|date:'dd.MM.yyyy HH:mm'}}</td><td>{{row.direction}} / {{row.category}}</td><td>{{row.counterparty_name||row.description||row.reference||'-'}}</td><td>{{row.net_amount|number:'1.0-2'}} {{row.currency}}</td><td>{{row.source}}</td></tr>}@empty{<tr><td colspan="5">Bu dönemde finans hareketi yok.</td></tr>}</tbody></table></div></section>}
</section>`,styles:[`:host{display:block}.finance{color:#0f172a}.finance>header{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.kicker{margin:0;color:#2563eb;font-size:10px;font-weight:950;letter-spacing:.13em}.finance h2{margin:4px 0 0;font-size:22px}.finance>header span,.card>p,.status{display:block;margin-top:5px;color:#64748b;font-size:12px;line-height:1.5}.finance>header button,.primary,.row-actions button{min-height:42px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;padding:0 12px;font-weight:900}.primary{margin-top:12px;border-color:#2563eb;background:#2563eb;color:#fff}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}.metrics article,.card{border:1px solid #e2e8f0;border-radius:18px;background:#fff;padding:14px}.metrics small,.metrics strong{display:block}.metrics small{color:#64748b;font-size:10px;font-weight:900}.metrics strong{margin-top:4px;font-size:18px}.grid-two{display:grid;gap:12px;margin-top:12px}.card{margin-top:12px}.grid-two .card{margin-top:0}.card h3{margin:0;font-size:16px}.form-grid,.payment-grid{display:grid;gap:9px;margin-top:12px}.form-grid label,.payment-grid label{display:grid;gap:4px}.form-grid span,.payment-grid span{font-size:10px;font-weight:900;color:#475569}input,select,textarea{width:100%;min-height:42px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;padding:8px;color:#0f172a}.wide{grid-column:1/-1}.table-wrap{margin-top:12px;overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:10px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top}td small{display:block;margin-top:3px;color:#64748b}.row-actions{display:flex;gap:6px}.row-actions button{min-height:36px}.row-actions .danger{border-color:#fecdd3;color:#9f1239}.notice{margin:10px 0;border-radius:10px;padding:10px;font-size:12px}.success{background:#ecfdf5;color:#065f46}.error{background:#fff1f2;color:#9f1239}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #60a5fa;outline-offset:2px}@media(min-width:820px){.grid-two{grid-template-columns:1fr 1fr}.form-grid{grid-template-columns:1fr 1fr}.payment-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.metrics{grid-template-columns:repeat(2,1fr)}.finance>header{flex-direction:column}.finance>header button{width:100%}}`]})
export class BranchPortalFinanceV225Component implements OnInit{
 readonly finance=inject(BranchFinanceV225Service);readonly working=signal(false);readonly message=signal('');readonly error=signal('');
 profile={bankName:'',iban:'',accountHolder:'',legalName:'',taxNumber:'',taxOffice:'',preferredProvider:'NONE' as 'PAYTR'|'IYZICO'|'NONE'};
 expense={amount:0,category:'OTHER',currency:'TRY',counterpartyName:'',receiptNumber:'',invoiceNumber:'',description:''};
 payment={bookingReference:'',amount:0,method:'OFFICE' as 'OFFICE'|'EFT',payerName:'',payerPhone:'',externalReference:''};
 async ngOnInit(){await this.reload();}
 async reload(){this.error.set('');try{const s=await this.finance.refresh();this.profile={bankName:s.financeProfile.bankName||'',iban:s.financeProfile.iban||'',accountHolder:s.financeProfile.accountHolder||'',legalName:s.financeProfile.legalName||'',taxNumber:s.financeProfile.taxNumber||'',taxOffice:s.financeProfile.taxOffice||'',preferredProvider:s.financeProfile.preferredProvider||'NONE'};}catch(e){this.error.set(this.msg(e));}}
 async saveProfile(){await this.run(async()=>{await this.finance.saveProfile(this.profile);this.message.set('Finans profili kaydedildi. Merkez doğrulaması tamamlanana kadar payout kapalı kalır.');});}
 async addExpense(){await this.run(async()=>{await this.finance.addExpense(this.expense);this.expense={amount:0,category:'OTHER',currency:'TRY',counterpartyName:'',receiptNumber:'',invoiceNumber:'',description:''};this.message.set('Gider kaydı oluşturuldu.');});}
 async recordPayment(){await this.run(async()=>{await this.finance.recordOfflinePayment(this.payment);this.payment={bookingReference:'',amount:0,method:'OFFICE',payerName:'',payerPhone:'',externalReference:''};this.message.set('Ödeme kimlik eşleşmesiyle birlikte kaydedildi.');});}
 async confirmSigner(reference:string,matches:boolean){await this.run(async()=>{await this.finance.confirmSigner(reference,matches);this.message.set(matches?'İmza/teslim kimliği doğrulandı.':'İmza/teslim kimliği eşleşmedi olarak işaretlendi.');});}
 private async run(task:()=>Promise<void>){if(this.working())return;this.working.set(true);this.error.set('');this.message.set('');try{await task();}catch(e){this.error.set(this.msg(e));}finally{this.working.set(false);}}
 private msg(e:unknown){const raw=e instanceof Error?e.message:'';if(raw.includes('PAYER_IDENTITY_MISMATCH'))return'Ödeyen kişinin adı veya telefonu rezervasyondaki müşteriyle eşleşmiyor.';if(raw.includes('PAYMENT_EXCEEDS'))return'Girilen tutar kalan rezervasyon bakiyesini aşıyor.';if(raw.includes('INVALID_IBAN'))return'IBAN biçimini kontrol edin.';if(raw.includes('SUBSCRIPTION'))return'Bu işlem için şube aboneliği aktif olmalıdır.';if(raw.includes('FINANCE'))return'Bu finans işlemi için yetkiniz bulunmuyor.';return raw||'İşlem tamamlanamadı.';}
}
