import { CommonModule } from "@angular/common";
import { Component, OnInit, inject, signal } from "@angular/core";
import { MatIconModule } from "@angular/material/icon";
import { RouterLink } from "@angular/router";
import { BranchInvoiceV171, BranchSubscriptionV171, BranchSubscriptionV171Service } from "../services/branch-subscription-v171.service";

@Component({selector:"app-branch-subscription-v171",standalone:true,imports:[CommonModule,MatIconModule,RouterLink],template:`
<main class="min-h-screen bg-slate-100 pb-20 text-slate-900"><header class="border-b border-slate-200 bg-white"><div class="mx-auto flex min-h-16 max-w-6xl items-center justify-between px-4 md:px-8"><div><p class="text-[10px] font-black uppercase tracking-[.16em] text-blue-600">Şube Portalı</p><h1 class="text-lg font-black">Abonelik ve Faturalar</h1></div><a routerLink="/branch-portal" class="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white no-underline">Portala Dön</a></div></header><section class="mx-auto max-w-6xl px-4 py-8 md:px-8">
@if(error()){<p role="alert" class="rounded-2xl bg-rose-50 p-4 font-bold text-rose-800">{{error()}}</p>}
<div class="grid gap-5 lg:grid-cols-2">@for(item of subscriptions();track item.id){<article class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">{{item.branch?.operator_display_name||item.branch?.name}}</p><h2 class="mt-1 text-2xl font-black">{{item.plan?.name||'Şube Paketi'}}</h2><p class="mt-1 text-sm text-slate-500">{{item.branch?.city}} / {{item.branch?.district}}</p></div><span [class]="statusClass(item.status)" class="rounded-full px-3 py-1 text-xs font-black">{{statusLabel(item.status)}}</span></div><div class="mt-6 rounded-2xl bg-slate-50 p-5"><strong class="text-3xl font-black">{{effectivePrice(item)|number:'1.0-0'}} ₺</strong><span class="ml-2 text-sm text-slate-500">/ ay</span>@if(item.is_complimentary){<p class="mt-2 text-sm font-black text-emerald-700">Super Admin tarafından ücretsiz kullanım tanımlandı.</p>}</div><p class="mt-4 text-sm leading-6 text-slate-600">{{item.plan?.short_description}}</p><div class="mt-5 grid grid-cols-2 gap-3 text-xs"><div class="rounded-xl border border-slate-200 p-3"><span class="text-slate-500">Dönem sonu</span><strong class="mt-1 block">{{item.current_period_end?(item.current_period_end|date:'dd.MM.yyyy'):'Süresiz'}}</strong></div><div class="rounded-xl border border-slate-200 p-3"><span class="text-slate-500">Otomatik yenileme</span><strong class="mt-1 block">{{item.auto_renew?'Açık':'Kapalı'}}</strong></div></div></article>}</div>
<div class="mt-8 rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h2 class="text-xl font-black">Faturalar</h2><p class="text-sm text-slate-500">Şubenize ait abonelik faturaları ve ödeme durumu.</p></div><div class="overflow-x-auto"><table class="min-w-[720px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="p-3">Fatura</th><th class="p-3">Tutar</th><th class="p-3">Durum</th><th class="p-3">Son ödeme</th><th class="p-3">Ödeme</th></tr></thead><tbody>@for(invoice of invoices();track invoice.id){<tr class="border-t border-slate-100"><td class="p-3 font-black">{{invoice.invoice_number}}</td><td class="p-3">{{invoice.amount|number:'1.0-0'}} {{invoice.currency}}</td><td class="p-3">{{invoice.status}}</td><td class="p-3">{{invoice.due_at|date:'dd.MM.yyyy'}}</td><td class="p-3">{{invoice.paid_at?(invoice.paid_at|date:'dd.MM.yyyy HH:mm'):'Bekliyor'}}</td></tr>}@empty{<tr><td colspan="5" class="p-8 text-center text-slate-500">Henüz fatura oluşturulmadı.</td></tr>}</tbody></table></div></div>
</section></main>`})
export class BranchSubscriptionV171Component implements OnInit{private readonly service=inject(BranchSubscriptionV171Service);readonly subscriptions=signal<BranchSubscriptionV171[]>([]);readonly invoices=signal<BranchInvoiceV171[]>([]);readonly error=signal("");ngOnInit():void{void this.load();}private async load(){try{const subscriptions=await this.service.mySubscriptions();this.subscriptions.set(subscriptions);this.invoices.set(await this.service.myInvoices());}catch(error){this.error.set(error instanceof Error?error.message:"Abonelik bilgileri yüklenemedi.");}}effectivePrice(item:BranchSubscriptionV171):number{if(item.is_complimentary)return 0;return item.price_override==null?Number(item.plan?.monthly_fee||0):Number(item.price_override||0);}statusLabel(status:string):string{return({TRIALING:"Deneme",ACTIVE:"Aktif",PAST_DUE:"Ödeme gecikmiş",PAUSED:"Duraklatılmış",CANCELED:"İptal",EXEMPT:"Muaf"} as Record<string,string>)[status]||status;}statusClass(status:string):string{return status==="ACTIVE"||status==="TRIALING"||status==="EXEMPT"?"bg-emerald-100 text-emerald-800":status==="PAST_DUE"?"bg-amber-100 text-amber-800":"bg-slate-200 text-slate-700";}}
