import { CommonModule, Location } from "@angular/common";
import { Component, OnInit, inject, signal } from "@angular/core";
import { ActivatedRoute, RouterLink } from "@angular/router";
import { Branch } from "../models/branch.model";
import { Vehicle } from "../models/car.model";
import { BranchMediaV171 } from "../services/branch-media-v171.service";
import { BranchPublicV171Service } from "../services/branch-public-v171.service";

type SocialLink = {label:string;url:string};

@Component({selector:"app-branch-detail-v171",standalone:true,imports:[CommonModule,RouterLink],template:`
<main class="min-h-screen bg-slate-950 pb-24 text-white">
  <header class="sticky top-0 z-40 border-b border-white/10 bg-slate-950/95 backdrop-blur"><div class="mx-auto flex min-h-16 max-w-7xl items-center gap-3 px-4 md:px-8"><button type="button" (click)="location.back()" class="grid h-11 w-11 place-items-center rounded-xl bg-white/5 text-xl" aria-label="Şube detayından geri dön">←</button><div class="min-w-0"><p class="text-[10px] font-black uppercase tracking-[.18em] text-blue-300">Alperler Auto Şube Ağı</p><p class="truncate font-black">{{branch()?.operatorName||branch()?.name||'Şube'}}</p></div></div></header>
  @if(loading()){<section class="mx-auto max-w-7xl px-4 py-20 md:px-8"><p role="status" class="rounded-2xl border border-white/10 bg-white/5 p-6 font-bold text-slate-300">Şube bilgileri hazırlanıyor…</p></section>}
  @if(error()){<section class="mx-auto max-w-3xl px-4 py-20"><div role="alert" class="rounded-3xl border border-rose-400/30 bg-rose-500/10 p-6"><h1 class="text-2xl font-black">Şube şu anda görüntülenemiyor</h1><p class="mt-3 text-sm leading-6 text-rose-100">Şube bilgilerine geçici olarak ulaşılamıyor. Diğer Alperler noktalarını inceleyebilir veya biraz sonra yeniden deneyebilirsiniz.</p><a routerLink="/branches" class="mt-5 inline-grid min-h-12 place-items-center rounded-xl bg-white px-5 font-black text-slate-950 no-underline">Tüm Şubelere Dön</a></div></section>}
  @if(!loading()&&!error()&&branch();as current){
    <section class="relative overflow-hidden border-b border-white/10"><div class="absolute inset-0">@if(hero()){<img [src]="hero()" [alt]="(current.operatorName||current.name)+' kapak fotoğrafı'" class="h-full w-full object-cover opacity-35"/>}<div class="absolute inset-0 bg-gradient-to-b from-slate-950/40 via-slate-950/80 to-slate-950"></div></div><div class="relative mx-auto grid max-w-7xl gap-8 px-4 py-14 md:px-8 lg:grid-cols-[1.2fr_.8fr] lg:py-20"><div><div class="flex flex-wrap gap-2"><span class="pill">{{networkLabel(current)}}</span>@if(current.operatorVerified){<span class="pill verified">Doğrulanmış İşletme</span>}</div><h1 class="mt-4 text-4xl font-black leading-tight md:text-6xl">{{current.operatorName||current.name}}</h1>@if(current.operatorLegalName){<p class="mt-2 text-sm font-semibold text-slate-400">Yasal işletme: {{current.operatorLegalName}}</p>}<p class="mt-3 text-lg font-black text-blue-200">{{current.city}} / {{current.district}}</p><p class="mt-5 max-w-3xl text-base leading-7 text-slate-300">{{current.publicDescription||'Bu şubedeki araç ve turlar Alperler hizmet standartlarıyla sunulur.'}}</p>@if(current.platformDisclaimer){<p class="mt-4 max-w-3xl rounded-2xl border border-white/10 bg-white/5 p-4 text-xs leading-5 text-slate-400">{{current.platformDisclaimer}}</p>}<div class="mt-6 flex flex-wrap gap-3"><a [href]="'tel:'+current.phone" class="btn primary">Şubeyi Ara</a>@if(current.whatsapp){<a [href]="whatsappUrl(current.whatsapp)" target="_blank" rel="noopener noreferrer" class="btn">WhatsApp</a>}@if(current.mapUrl){<a [href]="current.mapUrl" target="_blank" rel="noopener noreferrer" class="btn">Haritada Aç</a>}</div></div><aside class="rounded-3xl border border-white/10 bg-slate-900/85 p-5 backdrop-blur"><p class="text-xs font-black uppercase tracking-wider text-slate-400">Şube Özeti</p><div class="mt-4 grid grid-cols-3 gap-2"><div class="stat"><strong>{{rentals().length}}</strong><span>Kiralık</span></div><div class="stat"><strong>{{sales().length}}</strong><span>Satılık</span></div><div class="stat"><strong>{{tours().length}}</strong><span>Tur</span></div></div><div class="mt-5 space-y-3 text-sm text-slate-300"><p><strong>Adres:</strong> {{current.addressLabel}}</p>@if(current.email){<p><strong>E-posta:</strong> <a [href]="'mailto:'+current.email" class="text-blue-300">{{current.email}}</a></p>}@if(current.territoryLabel){<p><strong>Hizmet bölgesi:</strong> {{current.territoryLabel}}</p>}</div><div class="mt-5 flex flex-wrap gap-2">@for(service of current.services;track service){<span class="rounded-full bg-white/5 px-2 py-1 text-[10px] font-black text-slate-300">{{serviceLabel(service)}}</span>}</div>@if(socialLinks(current).length){<div class="socials"><strong>Sosyal hesaplar</strong><div>@for(link of socialLinks(current);track link.url){<a [href]="link.url" target="_blank" rel="noopener noreferrer">{{link.label}}</a>}</div></div>}</aside></div></section>

    @if(media().length){<section class="mx-auto max-w-7xl px-4 py-8 md:px-8"><div class="mb-4"><p class="text-xs font-black uppercase tracking-wider text-blue-300">Şubeyi Yakından Tanıyın</p><h2 class="mt-1 text-2xl font-black">Fotoğraf ve Videolar</h2></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@for(item of media();track item.id){<article class="overflow-hidden rounded-2xl border border-white/10 bg-slate-900">@if(item.kind==='IMAGE'){<img [src]="item.url" [alt]="item.altText" class="aspect-video w-full object-cover" loading="lazy"/>}@else{<video [src]="item.url" [poster]="item.posterUrl" controls preload="metadata" class="aspect-video w-full bg-black"></video>}<div class="p-3 text-xs font-semibold text-slate-400">{{item.altText}}</div></article>}</div></section>}

    @if(current.workingHours.length){<section class="mx-auto max-w-7xl px-4 py-6 md:px-8"><div class="rounded-3xl border border-white/10 bg-slate-900 p-5"><h2 class="text-xl font-black">Çalışma Saatleri</h2><div class="mt-4 grid gap-2 md:grid-cols-2">@for(row of current.workingHours;track row.label+row.value){<div class="flex justify-between gap-4 rounded-xl bg-white/5 p-3 text-sm"><span class="text-slate-400">{{row.label}}</span><strong>{{row.value}}</strong></div>}</div></div></section>}

    <section class="mx-auto max-w-7xl px-4 py-8 md:px-8"><div class="grid gap-3 md:grid-cols-3"><div class="standard"><strong>Müşteri Güvencesi</strong><p>{{standards().customerGuarantee?'Hizmetler Alperler müşteri standartlarıyla sunulur.':'İşlem koşulları size açık ve anlaşılır biçimde gösterilir.'}}</p></div><div class="standard"><strong>Şeffaf Fiyatlandırma</strong><p>{{standards().centralPricing?'Fiyatlar açık, anlaşılır ve tutarlı biçimde sunulur.':'Fiyatlar ilan üzerinde açıkça gösterilir.'}}</p></div><div class="standard"><strong>Kalite Kontrolü</strong><p>{{standards().listingApproval?'Araç ve tur seçenekleri kalite standartlarına göre incelenir.':'İlanlar Alperler hizmet standartlarıyla sunulur.'}}</p></div></div></section>

    @if(rentals().length){<section class="list-section"><div class="section-head"><div><p>Kiralık</p><h2>Bu Şubenin Kiralık Araçları</h2></div><span>{{rentals().length}} araç</span></div><div class="cards">@for(item of rentals();track item.cloudId||item.id){<a [routerLink]="['/fleet',item.id]" class="card"><img [src]="item.image||'/assets/car-placeholder.jpg'" [alt]="title(item)"/><div class="p-4"><h3>{{title(item)}}</h3><p>{{item.year||''}} · {{item.transmission||'Şanzıman bilgisi'}} · {{item.fuel||'Yakıt bilgisi'}}</p><strong>{{item.price|number:'1.0-0'}} ₺ / gün</strong></div></a>}</div></section>}
    @if(sales().length){<section class="list-section"><div class="section-head"><div><p>Satılık</p><h2>Bu Şubenin Satılık Araçları</h2></div><span>{{sales().length}} araç</span></div><div class="cards">@for(item of sales();track item.cloudId||item.id){<a [routerLink]="['/sales',item.id]" class="card"><img [src]="item.image||'/assets/car-placeholder.jpg'" [alt]="title(item)"/><div class="p-4"><h3>{{title(item)}}</h3><p>{{item.year||''}} @if(item.km!==undefined){· {{item.km|number:'1.0-0'}} km}</p><strong>{{item.price|number:'1.0-0'}} ₺</strong></div></a>}</div></section>}
    @if(tours().length){<section class="list-section"><div class="section-head"><div><p>Tur ve Deneyimler</p><h2>Bu Şubenin Turları</h2></div><span>{{tours().length}} tur</span></div><div class="cards">@for(item of tours();track item.cloudId||item.id){<a [routerLink]="['/tour',item.id]" class="card"><img [src]="item.image||'/assets/car-placeholder.jpg'" [alt]="item.title||'Tur'"/><div class="p-4"><h3>{{item.title}}</h3><p>{{item.duration||'Süre bilgisi şubede'}}</p><strong>{{item.price|number:'1.0-0'}} ₺ / kişi</strong></div></a>}</div></section>}
    @if(!rentals().length&&!sales().length&&!tours().length){<section class="mx-auto max-w-7xl px-4 py-10 md:px-8"><div class="rounded-3xl border-2 border-dashed border-white/15 p-10 text-center"><h2 class="text-xl font-black">Henüz seçenek bulunmuyor</h2><p class="mt-2 text-sm text-slate-400">Yeni araç ve tur seçenekleri eklendikçe burada keşfedebilirsiniz.</p></div></section>}
  }
</main>`,styles:[`:host{display:block}.pill{border-radius:999px;background:rgba(59,130,246,.15);padding:.4rem .65rem;font-size:.65rem;font-weight:900;color:#bfdbfe}.pill.verified{background:rgba(16,185,129,.15);color:#a7f3d0}.btn{display:inline-grid;min-height:48px;place-items:center;border:1px solid rgba(255,255,255,.14);border-radius:12px;padding:0 1rem;color:white;font-weight:900;text-decoration:none}.btn.primary{border-color:#3b82f6;background:#3b82f6}.stat{display:grid;min-height:86px;place-items:center;border:1px solid rgba(255,255,255,.08);border-radius:16px;background:rgba(255,255,255,.04)}.stat strong{font-size:1.5rem}.stat span{font-size:.65rem;font-weight:900;color:#94a3b8}.socials{margin-top:1rem;border-top:1px solid rgba(255,255,255,.08);padding-top:1rem}.socials>strong{display:block;color:#94a3b8;font-size:.65rem;text-transform:uppercase;letter-spacing:.08em}.socials>div{display:flex;flex-wrap:wrap;gap:.45rem;margin-top:.6rem}.socials a{display:inline-grid;min-height:36px;place-items:center;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:0 .75rem;color:#bfdbfe;font-size:.68rem;font-weight:900;text-decoration:none}.socials a:focus-visible,.btn:focus-visible{outline:3px solid #60a5fa;outline-offset:2px}.standard{border:1px solid rgba(255,255,255,.08);border-radius:18px;background:#0f172a;padding:1rem}.standard strong{display:block}.standard p{margin-top:.35rem;font-size:.78rem;line-height:1.4rem;color:#94a3b8}.list-section{max-width:80rem;margin:auto;padding:1.75rem 1rem}.section-head{display:flex;align-items:end;justify-content:space-between;gap:1rem;margin-bottom:1rem}.section-head p{font-size:.65rem;font-weight:900;text-transform:uppercase;color:#60a5fa}.section-head h2{font-size:1.5rem;font-weight:900}.section-head span{font-size:.75rem;font-weight:900;color:#64748b}.cards{display:grid;gap:1rem}.card{overflow:hidden;border:1px solid rgba(255,255,255,.08);border-radius:18px;background:#0f172a;color:white;text-decoration:none}.card img{width:100%;height:210px;object-fit:cover;background:#020617}.card h3{font-size:1.08rem;font-weight:900}.card p{margin-top:.35rem;font-size:.75rem;color:#94a3b8}.card strong{display:block;margin-top:.8rem;font-size:1.08rem}@media(min-width:640px){.cards{grid-template-columns:repeat(2,1fr)}}@media(min-width:1024px){.cards{grid-template-columns:repeat(3,1fr)}.list-section{padding-left:2rem;padding-right:2rem}}`]} )
export class BranchDetailV171Component implements OnInit{
  readonly location=inject(Location);
  private readonly route=inject(ActivatedRoute);
  private readonly service=inject(BranchPublicV171Service);
  readonly branch=signal<Branch|null>(null);
  readonly media=signal<BranchMediaV171[]>([]);
  readonly rentals=signal<Vehicle[]>([]);
  readonly sales=signal<Vehicle[]>([]);
  readonly tours=signal<Vehicle[]>([]);
  readonly standards=signal({centralPricing:true,listingApproval:true,customerGuarantee:true});
  readonly loading=signal(true);
  readonly error=signal(false);
  readonly hero=signal("");
  async ngOnInit(){const slug=(this.route.snapshot.paramMap.get('slug')||'').trim().toLowerCase();if(!slug){this.loading.set(false);this.error.set(true);return;}try{const payload=await this.service.detail(slug);this.branch.set(payload.branch);this.media.set(payload.media);this.rentals.set(payload.vehicles.filter(v=>v.category==='RENTAL'));this.sales.set(payload.vehicles.filter(v=>v.category==='SALE'));this.tours.set(payload.tours);this.standards.set(payload.standards);const cover=payload.media.find(m=>m.kind==='IMAGE'&&m.isCover)||payload.media.find(m=>m.kind==='IMAGE');this.hero.set(cover?.url||payload.branch.heroImage||'');}catch{this.error.set(true);}finally{this.loading.set(false);}}
  title(item:Vehicle){return[item.brand,item.model].filter(Boolean).join(' ')||item.title||'Araç';}
  whatsappUrl(value:string){return`https://wa.me/${value.replace(/\D/g,'')}`;}
  networkLabel(branch:Branch){return branch.networkType==='FRANCHISE'?'Yetkili İş Ortağı':branch.networkType==='PARTNER'?'Bölgesel Partner':'Merkez Şubesi';}
  serviceLabel(value:string){return({RENTAL:'Kiralama',SALES:'Satış',TOUR:'Tur',TRANSFER:'Transfer',PICKUP:'Teslim',RETURN:'İade'} as Record<string,string>)[value]||value;}
  socialLinks(branch:Branch):SocialLink[]{const source=branch.brandProfile||{};const candidates:[string,string][]=[['Instagram',String(source['instagramUrl']||'')],['Facebook',String(source['facebookUrl']||'')],['TikTok',String(source['tiktokUrl']||'')],['YouTube',String(source['youtubeUrl']||'')],['X',String(source['xUrl']||'')]];return candidates.filter(([,url])=>/^https:\/\/[^\s]+$/i.test(url)).map(([label,url])=>({label,url}));}
}
