import { CommonModule, Location } from "@angular/common";
import { Component, OnInit, computed, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { MatIconModule } from "@angular/material/icon";
import { RouterLink } from "@angular/router";
import { BranchPartnerBudgetRange, BranchPartnerListingModel, BranchPartnerOfficeStatus, BranchPartnerService, BranchPartnerServiceType } from "../services/branch-partner.service";
import { GeoDirectoryService } from "../services/geo-directory.service";

@Component({
  selector:"app-branch-partner-v163", standalone:true, imports:[CommonModule,FormsModule,MatIconModule,RouterLink],
  template:`<main class="page"><header><button type="button" (click)="location.back()" aria-label="Geri dön"><mat-icon aria-hidden="true">arrow_back</mat-icon></button><div><h1>Alperler Auto İş Ortaklığı</h1><p>Türkiye geneli şube ve bölgesel operasyon başvurusu</p></div></header><section class="shell">
  @if(successReference()){<article class="success" role="status" aria-live="polite"><mat-icon aria-hidden="true">check_circle</mat-icon><p>Başvuru veritabanına kaydedildi</p><h2>Şube adaylık süreciniz başladı</h2><span>Başvurunuz merkez ekibine düştü. Onaydan sonra şube hesabınız ve portal yetkiniz açılır.</span><strong>Referans: {{successReference()}}</strong><div><button type="button" (click)="reset()">Yeni Başvuru</button><a routerLink="/">Ana Sayfa</a></div></article>}@else{
  <div class="layout"><aside><p>81 İLDE ALPERLER AUTO AĞI</p><h2>Kendi bölgenizde güçlü bir şube işletin.</h2><span>Kiralık ve satılık araçlarınızı kendi şube portalınızdan yönetin. İlan, rezervasyon ve müşteri kayıtları merkezi veritabanında şubenize bağlı tutulur.</span><ul><li>Kendi kiralık ve satılık araçlarınızı yükleyin</li><li>Merkez fiyat ve yayın kuralları otomatik uygulansın</li><li>Size yönlendirilen rezervasyonları kendi portalınızda görün</li><li>Onay sonrası güvenli şube hesabı ve davet bağlantısı alın</li></ul></aside>
  <form (ngSubmit)="submit()" novalidate><h2>Şube Başvurusu</h2><p class="intro">İl ve ilçe alanları veritabanındaki Türkiye dizininden gelir.</p>@if(geo.loading()){<p role="status" class="notice">81 il ve ilçeler hazırlanıyor…</p>}@if(geo.error()){<p role="alert" class="error">Konum dizinine ulaşılamadı. Lütfen tekrar deneyin.</p>}
  <div class="grid"><label><span>Ad soyad *</span><input [(ngModel)]="fullName" name="fullName" autocomplete="name" maxlength="160" required /></label><label><span>Telefon *</span><input [(ngModel)]="phone" name="phone" type="tel" autocomplete="tel" maxlength="40" required /></label><label class="wide"><span>E-posta *</span><input [(ngModel)]="email" name="email" type="email" autocomplete="email" maxlength="160" required /><small>Onaylanırsa şube portalı daveti bu adrese gönderilir.</small></label><label><span>İl *</span><select [(ngModel)]="provinceCode" name="provinceCode" (ngModelChange)="provinceChanged($event)" required aria-label="Şube ili"><option value="">İl seçin</option>@for(p of geo.provinces();track p.code){<option [value]="p.code">{{p.name}}</option>}</select></label><label><span>İlçe *</span><select [(ngModel)]="districtCode" name="districtCode" (ngModelChange)="districtChanged($event)" [disabled]="!provinceCode" required aria-label="Şube ilçesi"><option value="">İlçe seçin</option>@for(d of districts();track d.code){<option [value]="d.code">{{d.name}}</option>}</select></label><label class="wide"><span>Hedef çalışma bölgesi</span><input [(ngModel)]="operatingArea" name="operatingArea" maxlength="180" /></label><label class="wide"><span>Mevcut işletme / şirket</span><input [(ngModel)]="currentBusiness" name="currentBusiness" maxlength="180" /></label></div>
  <fieldset><legend>Sunmak istediğiniz hizmetler *</legend><label class="check"><input type="checkbox" [(ngModel)]="serviceRental" name="serviceRental" />Araç kiralama</label><label class="check"><input type="checkbox" [(ngModel)]="serviceSales" name="serviceSales" />İkinci el araç satışı</label><label class="check"><input type="checkbox" [(ngModel)]="serviceTour" name="serviceTour" />Tur / transfer</label></fieldset>
  <div class="grid"><label><span>Otomotiv deneyimi</span><input type="number" [(ngModel)]="experienceYears" name="experienceYears" min="0" max="60" /></label><label><span>Ofis durumu</span><select [(ngModel)]="officeStatus" name="officeStatus"><option value="OWN">Kendi yerim var</option><option value="RENT">Kiralanmış yerim var</option><option value="PLAN">Yer açmayı planlıyorum</option><option value="NONE">Şimdilik ofis düşünmüyorum</option></select></label><label><span>Şu anki araç sayısı</span><input type="number" [(ngModel)]="currentFleetSize" name="currentFleetSize" min="0" max="5000" /></label><label><span>Planlanan araç sayısı *</span><input type="number" [(ngModel)]="plannedFleetSize" name="plannedFleetSize" min="1" max="5000" /></label><label><span>İlan / filo modeli</span><select [(ngModel)]="listingModel" name="listingModel"><option value="OWN_FLEET">Kendi araçlarım</option><option value="REGIONAL_NETWORK">Bölgedeki araç sahipleri</option><option value="BOTH">Her ikisi</option></select></label><label><span>Başlangıç bütçesi</span><select [(ngModel)]="budgetRange" name="budgetRange"><option value="DISCUSS">Görüşmede netleştirelim</option><option value="UNDER_100K">100.000 TL altı</option><option value="100K_250K">100.000 - 250.000 TL</option><option value="250K_500K">250.000 - 500.000 TL</option><option value="500K_PLUS">500.000 TL ve üzeri</option></select></label></div>
  <label><span>Ek bilgi</span><textarea [(ngModel)]="notes" name="notes" rows="4" maxlength="4000"></textarea></label><input class="hp" [(ngModel)]="website" name="website" tabindex="-1" aria-hidden="true" autocomplete="off" /><label class="consent"><input type="checkbox" [(ngModel)]="accuracyAccepted" name="accuracyAccepted" />Verdiğim bilgilerin doğru olduğunu kabul ediyorum.</label><label class="consent"><input type="checkbox" [(ngModel)]="privacyAccepted" name="privacyAccepted" />Kişisel verilerimin başvuru değerlendirmesi için işlenmesini kabul ediyorum. <a routerLink="/legal">Yasal bilgilendirmeler</a></label>@if(errorMessage()){<p role="alert" class="error">{{errorMessage()}}</p>}<button class="submit" type="submit" [disabled]="submitting()||!formValid()">{{submitting()?'Başvuru kaydediliyor…':'Şube Başvurumu Gönder'}}</button><small class="foot">Başvuru, il/ilçe kodları ve tüm operasyon bilgileri merkezi veritabanına kaydedilir.</small></form></div>}
  </section></main>`,
  styles:[`:host{display:block}.page{min-height:100vh;background:#020617;color:#e2e8f0;padding-bottom:5rem}header{position:sticky;top:0;z-index:40;display:flex;min-height:64px;align-items:center;gap:.7rem;border-bottom:1px solid #1e293b;background:rgba(2,6,23,.96);padding:0 max(1rem,calc((100vw - 1120px)/2))}header button{display:grid;width:44px;height:44px;place-items:center;border:0;border-radius:12px;background:#0f172a;color:white}header h1{margin:0;font-size:1rem}header p{margin:.15rem 0 0;color:#94a3b8;font-size:.72rem}.shell{width:min(1120px,calc(100% - 2rem));margin:auto;padding-top:2rem}.layout{display:grid;gap:2rem}@media(min-width:900px){.layout{grid-template-columns:.8fr 1.2fr}}aside{align-self:start;padding:1rem .25rem}aside>p{color:#60a5fa;font-size:.68rem;font-weight:950;letter-spacing:.14em}aside h2{max-width:520px;margin:.7rem 0;font:800 clamp(2rem,5vw,3.3rem)/1.05 Georgia,serif;color:white}aside span,aside li{color:#94a3b8;line-height:1.7}form,.success{border-radius:24px;background:white;padding:clamp(1rem,3vw,1.7rem);color:#0f172a;box-shadow:0 25px 70px rgba(0,0,0,.3)}form>h2{margin:0}.intro{color:#64748b}.grid{display:grid;gap:1rem;margin-top:1rem}@media(min-width:600px){.grid{grid-template-columns:1fr 1fr}.wide{grid-column:1/-1}}label{display:flex;flex-direction:column;gap:.35rem}label>span,legend{font-size:.68rem;font-weight:900;letter-spacing:.05em;text-transform:uppercase;color:#475569}input,select,textarea{width:100%;min-height:48px;border:1px solid #cbd5e1;border-radius:12px;background:#f8fafc;padding:.7rem .8rem;color:#0f172a;font:inherit}textarea{min-height:105px}small{color:#64748b}fieldset{display:grid;gap:.6rem;margin:1.2rem 0;border:1px solid #e2e8f0;border-radius:14px;padding:1rem}.check,.consent{display:flex;flex-direction:row;align-items:flex-start;gap:.6rem;color:#475569;font-size:.8rem;line-height:1.5}.check input,.consent input{width:18px;height:18px;min-height:18px}.consent{margin-top:.7rem}.consent a{color:#1d4ed8;font-weight:800}.notice,.error{border-radius:12px;padding:.8rem;font-weight:800}.notice{background:#eff6ff;color:#1e40af}.error{background:#fff1f2;color:#9f1239}.submit{width:100%;min-height:54px;margin-top:1rem;border:0;border-radius:14px;background:#2563eb;color:white;font-weight:900}.submit:disabled{opacity:.45}.foot{display:block;margin-top:.7rem;text-align:center}.hp{display:none!important}.success{text-align:center;max-width:650px;margin:auto}.success mat-icon{font-size:42px;width:42px;height:42px;color:#059669}.success>p{color:#047857;font-weight:900}.success>span,.success>strong{display:block;margin:.7rem}.success>div{display:grid;gap:.6rem;margin-top:1.2rem}@media(min-width:500px){.success>div{grid-template-columns:1fr 1fr}}.success button,.success a{display:flex;min-height:48px;align-items:center;justify-content:center;border-radius:12px;border:1px solid #cbd5e1;text-decoration:none;font-weight:900}.success a{background:#020617;color:white}`]
})
export class BranchPartnerV163Component implements OnInit{
  readonly location=inject(Location);readonly geo=inject(GeoDirectoryService);private readonly service=inject(BranchPartnerService);
  fullName="";phone="";email="";provinceCode="";districtCode="";city="";district="";operatingArea="";currentBusiness="";experienceYears=0;officeStatus:BranchPartnerOfficeStatus="PLAN";currentFleetSize=0;plannedFleetSize=1;listingModel:BranchPartnerListingModel="OWN_FLEET";budgetRange:BranchPartnerBudgetRange="DISCUSS";notes="";website="";serviceRental=true;serviceSales=false;serviceTour=false;accuracyAccepted=false;privacyAccepted=false;
  readonly submitting=signal(false);readonly errorMessage=signal("");readonly successReference=signal("");readonly districts=computed(()=>this.geo.districtsFor(this.provinceCode));
  ngOnInit(){void this.geo.ensureLoaded().catch(()=>undefined);}
  provinceChanged(code:string){this.provinceCode=String(code||"");this.districtCode="";this.city=this.geo.province(this.provinceCode)?.name||"";this.district="";}
  districtChanged(code:string){this.districtCode=String(code||"");this.city=this.geo.province(this.provinceCode)?.name||"";this.district=this.geo.district(this.districtCode)?.name||"";}
  formValid(){return Boolean(this.geo.loaded()&&this.fullName.trim()&&/^[+0-9()\s-]{7,24}$/.test(this.phone.trim())&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email.trim())&&this.provinceCode&&this.districtCode&&this.city&&this.district&&this.plannedFleetSize>=1&&(this.serviceRental||this.serviceSales||this.serviceTour)&&this.accuracyAccepted&&this.privacyAccepted);}
  private services():BranchPartnerServiceType[]{const x:BranchPartnerServiceType[]=[];if(this.serviceRental)x.push("RENTAL");if(this.serviceSales)x.push("SALES");if(this.serviceTour)x.push("TOUR_TRANSFER");return x;}
  async submit(){if(!this.formValid()||this.submitting())return;this.submitting.set(true);this.errorMessage.set("");try{const r=await this.service.submit({fullName:this.fullName,phone:this.phone,email:this.email,provinceCode:this.provinceCode,districtCode:this.districtCode,city:this.city,district:this.district,operatingArea:this.operatingArea||undefined,currentBusiness:this.currentBusiness||undefined,experienceYears:this.experienceYears,officeStatus:this.officeStatus,currentFleetSize:this.currentFleetSize,plannedFleetSize:this.plannedFleetSize,services:this.services(),listingModel:this.listingModel,budgetRange:this.budgetRange,notes:this.notes||undefined,website:this.website});this.successReference.set(r.reference);window.scrollTo({top:0,behavior:"smooth"});}catch(e){const c=e instanceof Error?e.message:"";this.errorMessage.set(c.includes("RATE_LIMITED")?"Çok fazla başvuru gönderildi. Lütfen daha sonra tekrar deneyin.":c.includes("INVALID_REQUIRED_FIELDS")?"Ad, telefon, e-posta, il, ilçe ve hizmet alanlarını kontrol edin.":"Başvuru kaydedilemedi. Form bilgileri korunuyor; tekrar deneyin.");}finally{this.submitting.set(false);}}
  reset(){this.successReference.set("");this.errorMessage.set("");this.fullName="";this.phone="";this.email="";this.provinceCode="";this.districtCode="";this.city="";this.district="";this.operatingArea="";this.currentBusiness="";this.experienceYears=0;this.officeStatus="PLAN";this.currentFleetSize=0;this.plannedFleetSize=1;this.listingModel="OWN_FLEET";this.budgetRange="DISCUSS";this.notes="";this.serviceRental=true;this.serviceSales=false;this.serviceTour=false;this.accuracyAccepted=false;this.privacyAccepted=false;}
}
