import { CommonModule } from "@angular/common";
import { Component, OnInit, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { RouterLink } from "@angular/router";
import { Branch } from "../models/branch.model";
import { BranchCommunicationService } from "../services/branch-communication.service";
import { BranchPublicV171Service } from "../services/branch-public-v171.service";

@Component({selector:"app-branch-directory-v171",standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<main class="min-h-screen bg-slate-950 pb-24 text-white">
  <section class="border-b border-white/10 bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950"><div class="mx-auto max-w-7xl px-4 py-14 md:px-8 md:py-20"><p class="text-xs font-black uppercase tracking-[.18em] text-blue-300">Alperler Auto Şube Ağı</p><h1 class="mt-3 max-w-4xl text-4xl font-black leading-tight md:text-6xl">Size en uygun Alperler noktasını kolayca bulun.</h1><p class="mt-5 max-w-3xl text-base leading-7 text-slate-300">Şubelerin hizmetlerini, iletişim bilgilerini ve bölgesel seçeneklerini karşılaştırın. Kiralama, satış ve tur ihtiyaçlarınız için size en yakın noktayı seçin.</p><div class="mt-8 flex flex-col gap-3 sm:flex-row"><label class="sr-only" for="branch-search-v171">Şube ara</label><input id="branch-search-v171" [(ngModel)]="query" type="search" autocomplete="off" placeholder="İşletme, il, ilçe veya hizmet ara…" class="min-h-12 flex-1 rounded-xl border border-white/10 bg-white/10 px-4 font-semibold text-white outline-none placeholder:text-slate-400 focus:border-blue-400"/><a routerLink="/branch-marketplace" class="grid min-h-12 place-items-center rounded-xl bg-blue-500 px-6 font-black text-white no-underline">İl / İlçeye Göre Araç ve Tur Ara</a></div></div></section>
  <section class="mx-auto max-w-7xl px-4 py-8 md:px-8">
    @if(loading()){<p role="status" class="rounded-2xl border border-white/10 bg-white/5 p-5 font-bold text-slate-300">Şubeler hazırlanıyor…</p>}
    @if(error()){<div role="alert" class="rounded-2xl border border-rose-400/30 bg-rose-500/10 p-5"><h2 class="text-lg font-black">Şubelere şu anda ulaşılamıyor</h2><p class="mt-2 text-sm leading-6 text-rose-100">Şube bilgileri geçici olarak görüntülenemiyor. Biraz sonra yeniden deneyebilirsiniz.</p><button type="button" (click)="load()" class="mt-4 min-h-11 rounded-xl bg-white px-4 font-black text-slate-950">Tekrar Dene</button></div>}
    @if(!loading()&&!error()){
      <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        @for(branch of filtered();track branch.cloudId||branch.id){<article class="overflow-hidden rounded-3xl border border-white/10 bg-slate-900 shadow-2xl"><div class="aspect-[16/9] bg-slate-800">@if(branch.heroImage){<img [src]="branch.heroImage" [alt]="(branch.operatorName||branch.name)+' şube kapak fotoğrafı'" class="h-full w-full object-cover" loading="lazy"/>}@else{<div class="grid h-full place-items-center text-sm font-black text-slate-500">Şube görseli yakında eklenecek</div>}</div><div class="p-5"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-blue-500/15 px-2 py-1 text-[10px] font-black uppercase tracking-wider text-blue-300">{{networkLabel(branch)}}</span>@if(branch.operatorVerified){<span class="rounded-full bg-emerald-500/15 px-2 py-1 text-[10px] font-black text-emerald-300">Doğrulanmış İşletme</span>}</div><h2 class="mt-3 text-2xl font-black">{{branch.operatorName||branch.name}}</h2>@if(branch.operatorLegalName){<p class="mt-1 text-xs text-slate-500">{{branch.operatorLegalName}}</p>}<p class="mt-2 text-sm font-bold text-slate-300">{{branch.city}} / {{branch.district}}</p>@if(branch.publicDescription){<p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-400">{{branch.publicDescription}}</p>}<div class="mt-4 flex flex-wrap gap-2">@for(service of branch.services;track service){<span class="rounded-full bg-white/5 px-2 py-1 text-[10px] font-black text-slate-300">{{serviceLabel(service)}}</span>}</div><div class="mt-5 grid grid-cols-2 gap-2">@if(branch.slug){<a [routerLink]="['/branches',branch.slug]" class="grid min-h-11 place-items-center rounded-xl bg-blue-500 font-black text-white no-underline">Şubeyi İncele</a>}@else{<span class="grid min-h-11 place-items-center rounded-xl bg-slate-800 text-sm font-bold text-slate-500">Detaylar yakında</span>}@if(communication.phoneUrl(branch.phone);as phone){<a [href]="phone" class="grid min-h-11 place-items-center rounded-xl border border-white/10 font-black text-white no-underline">Ara</a>}@else{<span class="grid min-h-11 place-items-center rounded-xl border border-white/10 text-sm font-bold text-slate-500">Telefon yok</span>}</div></div></article>}
        @empty{<div class="col-span-full rounded-3xl border-2 border-dashed border-white/15 p-12 text-center"><h2 class="text-xl font-black">Aramanıza uyan şube yok</h2><p class="mt-2 text-sm text-slate-400">İşletme adı, il, ilçe veya hizmet kelimesini değiştirin.</p></div>}
      </div>
    }
  </section>
</main>`,styles:[`:host{display:block}`]})
export class BranchDirectoryV171Component implements OnInit{private readonly service=inject(BranchPublicV171Service);readonly communication=inject(BranchCommunicationService);readonly branches=signal<Branch[]>([]);readonly loading=signal(true);readonly error=signal(false);query="";ngOnInit(){void this.load();}async load(){this.loading.set(true);this.error.set(false);try{this.branches.set(await this.service.list());}catch{this.branches.set([]);this.error.set(true);}finally{this.loading.set(false);}}filtered():Branch[]{const q=this.query.trim().toLocaleLowerCase("tr-TR");if(!q)return this.branches();return this.branches().filter(branch=>`${branch.operatorName||branch.name} ${branch.operatorLegalName||""} ${branch.city} ${branch.district} ${(branch.services||[]).join(" ")}`.toLocaleLowerCase("tr-TR").includes(q));}networkLabel(branch:Branch){return branch.networkType==="FRANCHISE"?"Yetkili İş Ortağı":branch.networkType==="PARTNER"?"Bölgesel Partner":"Merkez Şubesi";}serviceLabel(value:string){return({RENTAL:"Kiralama",SALES:"Satış",TOUR:"Tur",TRANSFER:"Transfer",PICKUP:"Teslim",RETURN:"İade"} as Record<string,string>)[value]||value;}}
