import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { BranchPortalProfileService } from '../services/branch-portal-profile.service';
import { BranchPortalService } from '../services/branch-portal.service';

@Component({selector:'app-branch-portal-profile-v224',standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<main class="page"><header class="head"><div><p>ŞUBE PROFİLİ</p><h1>{{branchName()}}</h1><span>Müşterilerin gördüğü Hakkında, iletişim ve sosyal hesap bilgilerini yönetin.</span></div><a routerLink="/branch-portal">Portala Dön</a></header>
@if(message()){<p class="notice success" role="status">{{message()}}</p>}@if(error()){<p class="notice error" role="alert">{{error()}}</p>}
<section class="card"><header><div><h2>Hakkında ve İletişim</h2><p>Bu bilgiler doğrudan şubenizin halka açık profilinde kullanılır. Banka ve vergi bilgileri burada tutulmaz.</p></div></header><div class="grid">
<label class="wide"><span>Şube Hakkında</span><textarea [(ngModel)]="form.publicDescription" name="branchAbout" rows="5" maxlength="2000" placeholder="Şubenizin hizmet yaklaşımı, bölge deneyimi ve müşteriye sunduğu avantajlar..."></textarea></label>
<label class="wide"><span>Adres</span><input [(ngModel)]="form.addressLabel" name="branchAddress" maxlength="500" autocomplete="street-address" /></label>
<label><span>Telefon</span><input [(ngModel)]="form.phone" name="branchPhone" maxlength="40" autocomplete="tel" /></label><label><span>WhatsApp</span><input [(ngModel)]="form.whatsapp" name="branchWhatsapp" maxlength="40" autocomplete="tel" /></label>
<label><span>E-posta</span><input [(ngModel)]="form.email" name="branchEmail" maxlength="160" autocomplete="email" /></label><label><span>Hizmet Bölgesi</span><input [(ngModel)]="form.territoryLabel" name="branchTerritory" maxlength="180" /></label>
</div></section>
<section class="card"><header><div><h2>Sosyal Medya</h2><p>Yalnız HTTPS bağlantıları kabul edilir. Boş bıraktığınız hesap halka açık profilde görünmez.</p></div></header><div class="grid"><label><span>Instagram</span><input [(ngModel)]="form.instagramUrl" name="instagramUrl" type="url" placeholder="https://instagram.com/..." /></label><label><span>Facebook</span><input [(ngModel)]="form.facebookUrl" name="facebookUrl" type="url" placeholder="https://facebook.com/..." /></label><label><span>TikTok</span><input [(ngModel)]="form.tiktokUrl" name="tiktokUrl" type="url" placeholder="https://tiktok.com/@..." /></label><label><span>YouTube</span><input [(ngModel)]="form.youtubeUrl" name="youtubeUrl" type="url" placeholder="https://youtube.com/@..." /></label><label class="wide"><span>X</span><input [(ngModel)]="form.xUrl" name="xUrl" type="url" placeholder="https://x.com/..." /></label></div></section>
<section class="card"><header><div><h2>Çalışma Saatleri</h2><p>İsterseniz en fazla 14 satır ekleyin.</p></div><button type="button" (click)="addHour()">Saat Ekle</button></header><div class="hours">@for(row of form.workingHours;track $index){<div><input [(ngModel)]="row.label" [name]="'hourLabel'+$index" placeholder="Pazartesi" maxlength="80"/><input [(ngModel)]="row.value" [name]="'hourValue'+$index" placeholder="08:00 - 18:00" maxlength="120"/><button type="button" (click)="removeHour($index)" aria-label="Çalışma saati satırını kaldır">Sil</button></div>}@empty{<p>Çalışma saati eklenmemiş.</p>}</div></section>
<div class="savebar"><button type="button" class="primary" (click)="save()" [disabled]="saving()">{{saving()?'Kaydediliyor…':'Profili Kaydet'}}</button></div></main>
`,styles:[`:host{display:block}.page{min-height:100vh;background:#07101b;color:#f8fafc;padding:16px}.head,.card,.savebar{width:min(100%,980px);margin:auto}.head{display:flex;align-items:end;justify-content:space-between;gap:16px}.head p{margin:0;color:#d6b56d;font-size:10px;font-weight:950;letter-spacing:.12em}.head h1{margin:5px 0 0;font-size:24px}.head span,.card header p{display:block;margin-top:5px;color:#94a3b8;font-size:12px;line-height:1.5}.head a,.card header button,.hours button,.primary{display:inline-flex;min-height:42px;align-items:center;justify-content:center;border:1px solid #334155;border-radius:10px;background:#101b2b;padding:0 13px;color:#fff;text-decoration:none;font-weight:900}.card{margin-top:14px;border:1px solid #263548;border-radius:16px;background:#0b1420;overflow:hidden}.card>header{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:14px;border-bottom:1px solid #263548}.card h2{margin:0;font-size:16px}.grid{display:grid;gap:10px;padding:14px}.grid label{display:grid;gap:5px}.grid span{color:#a8b4c2;font-size:10px;font-weight:900}.grid input,.grid textarea,.hours input{width:100%;border:1px solid #334155;border-radius:10px;background:#0e1724;padding:10px;color:#fff;font:inherit;font-size:12px}.grid input{min-height:44px}.hours{display:grid;gap:8px;padding:14px}.hours>div{display:grid;grid-template-columns:1fr 1fr auto;gap:8px}.hours>p{color:#94a3b8;font-size:12px}.savebar{display:flex;justify-content:flex-end;padding:14px 0 40px}.primary{border-color:#2563eb;background:#2563eb}.notice{width:min(100%,980px);margin:12px auto 0;border-radius:10px;padding:10px;font-size:12px}.success{background:#0b2d25;color:#a7f3d0}.error{background:#35131b;color:#fecdd3}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #60a5fa;outline-offset:2px}@media(min-width:720px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.wide{grid-column:1/-1}}@media(max-width:620px){.head{align-items:stretch;flex-direction:column}.hours>div{grid-template-columns:1fr}.hours button{justify-self:start}}` ]})
export class BranchPortalProfileV224Component implements OnInit{
 private readonly portal=inject(BranchPortalService);private readonly profiles=inject(BranchPortalProfileService);readonly saving=signal(false);readonly message=signal('');readonly error=signal('');
 form={addressLabel:'',phone:'',whatsapp:'',email:'',territoryLabel:'',publicDescription:'',workingHours:[] as Array<{label:string;value:string}>,instagramUrl:'',facebookUrl:'',tiktokUrl:'',youtubeUrl:'',xUrl:''};
 async ngOnInit(){try{if(!this.portal.currentMembership())await this.portal.loadMemberships();this.hydrate();}catch{this.error.set('Şube profiliniz şu anda yüklenemedi.');}}
 branchName(){return this.portal.currentMembership()?.branch.name||'Şube Profili';}
 addHour(){if(this.form.workingHours.length<14)this.form.workingHours.push({label:'',value:''});}removeHour(i:number){this.form.workingHours.splice(i,1);}
 async save(){if(this.saving())return;this.saving.set(true);this.message.set('');this.error.set('');try{await this.profiles.save(this.form);this.hydrate();this.message.set('Şube profiliniz güncellendi.');}catch(e){this.error.set(this.msg(e));}finally{this.saving.set(false);}}
 private hydrate(){const b=this.portal.currentMembership()?.branch;if(!b)return;const brand=b.brandProfile||{};this.form={addressLabel:b.addressLabel||'',phone:b.phone||'',whatsapp:b.whatsapp||'',email:b.email||'',territoryLabel:b.territoryLabel||'',publicDescription:b.publicDescription||'',workingHours:(b.workingHours||[]).map(row=>({...row})),instagramUrl:String(brand['instagramUrl']||''),facebookUrl:String(brand['facebookUrl']||''),tiktokUrl:String(brand['tiktokUrl']||''),youtubeUrl:String(brand['youtubeUrl']||''),xUrl:String(brand['xUrl']||'')};}
 private msg(e:unknown){const raw=e instanceof Error?e.message:'';if(raw.includes('SOCIAL_URL'))return'Sosyal medya bağlantıları https:// ile başlamalıdır.';if(raw.includes('SUBSCRIPTION'))return'Bu değişiklik için şube aboneliğiniz aktif olmalıdır.';return'Şube profili kaydedilemedi. Bilgileriniz değiştirilmedi.';}
}
