import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { Car } from '../models/car.model';
import { CustomerFavoritesV217Service, FavoriteEntityTypeV217, FavoriteRefV217 } from '../services/customer-favorites-v217.service';
import { BlogCardV217, ScalablePublicCatalogV217Service, TourCardV217 } from '../services/scalable-public-catalog-v217.service';

type PreviewItem={key:string;type:FavoriteEntityTypeV217;title:string;meta:string;image:string;route:any[]};

@Component({selector:'app-account-favorites-v213',standalone:true,imports:[CommonModule,MatIconModule,RouterLink],template:`
<section id="account-favorites" class="favorites-section" aria-labelledby="account-favorites-title"><header><div><p>HESABIM</p><h2 id="account-favorites-title">Favorilerim</h2><span>Beğendiğiniz araç, tur ve rehber yazılarına buradan hızlıca geri dönün.</span></div><a routerLink="/account/favorites">Tümünü Gör</a></header>
@if(loading()){<div class="state" role="status"><mat-icon>favorite_border</mat-icon><strong>Favorileriniz hazırlanıyor</strong></div>}@else if(error()){<div class="state"><mat-icon>sync_problem</mat-icon><strong>Favorilerinize şu anda ulaşamıyoruz</strong><span>Kısa bir süre sonra tekrar deneyebilirsiniz.</span></div>}@else if(items().length){<div class="grid">@for(item of items();track item.key){<a class="card" [routerLink]="item.route" [attr.aria-label]="item.title+' favorisini aç'"><div class="media">@if(item.image){<img [src]="item.image" [alt]="item.title" loading="lazy" decoding="async"/>}@else{<mat-icon>{{icon(item.type)}}</mat-icon>}<b>{{label(item.type)}}</b></div><div class="copy"><h3>{{item.title}}</h3><p>{{item.meta}}</p><span>İncele <mat-icon>arrow_forward</mat-icon></span></div></a>}</div>}@else{<div class="empty"><mat-icon>favorite_border</mat-icon><strong>Henüz favoriniz yok</strong><span>Beğendiğiniz araç, tur ve rehber yazılarını kalp simgesiyle kaydedebilirsiniz.</span><div><a routerLink="/fleet">Araçlar</a><a routerLink="/tours">Turlar</a><a routerLink="/blog">Blog</a></div></div>}
</section>`,styles:[`:host{display:block;background:#060a12;color:#f8fafc}.favorites-section{width:min(100% - 20px,1180px);margin:0 auto;padding:22px 0 30px}.favorites-section>header{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:12px}.favorites-section header p{margin:0;color:#c6a15b;font-size:9px;font-weight:950;letter-spacing:.15em}.favorites-section h2{margin:4px 0 0;font:750 clamp(26px,6vw,38px)/1 Georgia,serif}.favorites-section header span{display:block;max-width:650px;margin-top:7px;color:#8fa0b5;font-size:11px;line-height:1.55}.favorites-section header>a{display:flex;min-height:40px;align-items:center;border:1px solid #34445d;border-radius:10px;background:#111c2d;padding:0 12px;color:#fff;text-decoration:none;font-size:9px;font-weight:900}.grid{display:grid;grid-template-columns:1fr;gap:9px}.card{display:grid;grid-template-columns:102px minmax(0,1fr);overflow:hidden;border:1px solid #28364b;border-radius:16px;background:#0c1524;color:#fff;text-decoration:none}.media{position:relative;display:grid;min-height:108px;place-items:center;overflow:hidden;background:#141f31;color:#64748b}.media img{width:100%;height:100%;object-fit:cover}.media b{position:absolute;left:6px;top:6px;border-radius:999px;background:rgba(2,6,23,.88);padding:4px 6px;color:#f7e5b7;font-size:7px}.copy{min-width:0;padding:11px}.copy h3{display:-webkit-box;overflow:hidden;margin:0;font-size:13px;line-height:1.3;-webkit-line-clamp:2;-webkit-box-orient:vertical}.copy p{overflow:hidden;margin:6px 0 0;color:#8fa0b5;font-size:9px;text-overflow:ellipsis;white-space:nowrap}.copy span{display:flex;align-items:center;gap:3px;margin-top:8px;color:#93c5fd;font-size:8px;font-weight:900}.copy span mat-icon{width:14px;height:14px;font-size:14px}.state,.empty{display:grid;min-height:180px;place-content:center;justify-items:center;border:1px dashed #2c3a50;border-radius:20px;background:#0a1321;padding:24px;text-align:center;color:#8190a6}.state strong,.empty strong{margin-top:7px;color:#fff}.state span,.empty>span{max-width:480px;margin-top:6px;font-size:10px;line-height:1.6}.empty>div{display:flex;gap:6px;margin-top:11px}.empty a{display:flex;min-height:38px;align-items:center;border:1px solid #34445d;border-radius:9px;padding:0 10px;color:#fff;text-decoration:none;font-size:9px;font-weight:900}a:focus-visible{outline:3px solid #60a5fa;outline-offset:2px}@media(min-width:640px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(min-width:1000px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}` ]})
export class AccountFavoritesV213Component implements OnInit{private readonly favorites=inject(CustomerFavoritesV217Service);private readonly data=inject(ScalablePublicCatalogV217Service);readonly items=signal<PreviewItem[]>([]);readonly loading=signal(true);readonly error=signal(false);async ngOnInit(){try{const page=await this.favorites.listPage('ALL',0,6);this.items.set(await this.resolve(page.refs));}catch(error){console.error('Account favorites preview failed',error);this.error.set(true);}finally{this.loading.set(false);}}icon(type:FavoriteEntityTypeV217){return type==='TOUR'?'landscape':type==='BLOG'?'article':'directions_car';}label(type:FavoriteEntityTypeV217){return type==='TOUR'?'TUR':type==='BLOG'?'BLOG':'ARAÇ';}private async resolve(refs:FavoriteRefV217[]):Promise<PreviewItem[]>{const [cars,tours,blogs]=await Promise.all([this.data.vehiclesByIdentifiers(refs.filter(r=>r.entityType==='VEHICLE').map(r=>r.entityId)),this.data.toursByIdentifiers(refs.filter(r=>r.entityType==='TOUR').map(r=>r.entityId)),this.data.blogsByIdentifiers(refs.filter(r=>r.entityType==='BLOG').map(r=>r.entityId))]);const values=new Map<string,PreviewItem>();for(const car of cars)this.addVehicle(values,car);for(const tour of tours)this.addTour(values,tour);for(const blog of blogs)this.addBlog(values,blog);return refs.map(ref=>values.get(`${ref.entityType}:${ref.entityId}`)).filter((v):v is PreviewItem=>!!v);}private aliases(map:Map<string,PreviewItem>,type:FavoriteEntityTypeV217,item:PreviewItem,ids:unknown[]){for(const id of ids.map(v=>String(v??'')).filter(Boolean))map.set(`${type}:${id}`,item);}private addVehicle(map:Map<string,PreviewItem>,car:Car){const id=String(car.cloudId||car.id),item:PreviewItem={key:`VEHICLE:${id}`,type:'VEHICLE',title:car.title||[car.brand,car.model,car.series,car.year].filter(Boolean).join(' '),meta:[car.year,car.transmission,car.fuel].filter(Boolean).join(' · '),image:String(car.image||car.images?.[0]||''),route:[car.category==='SALE'?'/sales':'/fleet',car.cloudSlug||car.cloudId||car.id]};this.aliases(map,'VEHICLE',item,[car.cloudId,car.id,car.cloudStockCode,car.cloudSlug,(car as any).legacyId,(car as any).legacy_id]);}private addTour(map:Map<string,PreviewItem>,tour:TourCardV217){const id=String(tour.cloudId||tour.id),item:PreviewItem={key:`TOUR:${id}`,type:'TOUR',title:String(tour.title||'Tur'),meta:[tour.duration,tour.locationName||tour.meetingPoint].filter(Boolean).join(' · '),image:String(tour.image||''),route:['/tour',tour.cloudSlug||tour.cloudId||tour.id]};this.aliases(map,'TOUR',item,[tour.cloudId,tour.id,tour.cloudSlug,(tour as any).legacyId]);}private addBlog(map:Map<string,PreviewItem>,blog:BlogCardV217){const id=String(blog.cloudId||blog.id),item:PreviewItem={key:`BLOG:${id}`,type:'BLOG',title:blog.title,meta:[blog.date,blog.readTime].filter(Boolean).join(' · '),image:String(blog.image||''),route:['/blog',blog.cloudSlug||blog.cloudId]};this.aliases(map,'BLOG',item,[blog.cloudId,blog.id,blog.cloudSlug]);}}
