import PDFDocument from 'pdfkit';

function cfg(){const url=process.env.SUPABASE_PROJECT_URL?.trim()||process.env.SUPABASE_URL?.trim()||'';const key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()||'';return{url,key};}
function clean(v:unknown,max=500){return typeof v==='string'?v.trim().slice(0,max):'';}
function ascii(value:unknown){return String(value??'').replace(/[İIı]/g,'I').replace(/Ş/g,'S').replace(/ş/g,'s').replace(/Ğ/g,'G').replace(/ğ/g,'g').replace(/Ü/g,'U').replace(/ü/g,'u').replace(/Ö/g,'O').replace(/ö/g,'o').replace(/Ç/g,'C').replace(/ç/g,'c');}
function money(v:unknown,currency='TRY'){const n=Number(v||0);return `${new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2,minimumFractionDigits:2}).format(n)} ${currency}`;}
async function serviceFetch(path:string,init:RequestInit={}){const c=cfg();if(!c.url||!c.key)throw new Error('DATABASE_NOT_CONFIGURED');return fetch(`${c.url}${path}`,{...init,headers:{apikey:c.key,authorization:`Bearer ${c.key}`,accept:'application/json',...(init.headers||{})},signal:AbortSignal.timeout(10000)});}
async function requireFinance(request:Request){const c=cfg();const auth=request.headers.get('authorization')||'';if(!c.url||!c.key||!/^Bearer\s+\S+/i.test(auth))throw new Error('UNAUTHORIZED');const userRes=await fetch(`${c.url}/auth/v1/user`,{headers:{apikey:c.key,authorization:auth},signal:AbortSignal.timeout(8000)});if(!userRes.ok)throw new Error('UNAUTHORIZED');const user=await userRes.json();const id=clean(user?.id,80);const res=await serviceFetch(`/rest/v1/admin_users?user_id=eq.${encodeURIComponent(id)}&is_active=eq.true&select=role,permissions&limit=1`);if(!res.ok)throw new Error('FORBIDDEN');const row=(await res.json())?.[0];const p=row?.permissions&&typeof row.permissions==='object'?row.permissions:{};if(!row||(!['owner','admin'].includes(String(row.role))&&p['finance.read']!==true&&p['finance.manage']!==true))throw new Error('FORBIDDEN');}
function parseDate(value:string|null,fallback:Date){if(!value)return fallback;const d=new Date(value);return Number.isNaN(d.getTime())?fallback:d;}
async function pdfBuffer(rows:any[],from:Date,to:Date):Promise<Buffer>{return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:42,info:{Title:'Alperler Rent A Car Muhasebe Raporu',Author:'Alperler Rent A Car'}});const chunks:Buffer[]=[];doc.on('data',(chunk:Buffer)=>chunks.push(chunk));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);let income=0,expense=0,discount=0;for(const r of rows){const n=Number(r.net_amount||0);if(r.direction==='INCOME')income+=n;else expense+=n;discount+=Number(r.discount_amount||0);}doc.font('Helvetica-Bold').fontSize(19).text('ALPERLER RENT A CAR');doc.fontSize(14).text('Muhasebe ve Tahsilat Raporu');doc.moveDown(.4);doc.font('Helvetica').fontSize(9).fillColor('#555').text(`${from.toLocaleDateString('tr-TR')} - ${new Date(to.getTime()-1).toLocaleDateString('tr-TR')}`);doc.moveDown();doc.fillColor('#111').font('Helvetica-Bold').fontSize(11).text(`Gelir: ${money(income)}   Gider: ${money(expense)}   Net: ${money(income-expense)}   Indirim: ${money(discount)}`);doc.moveDown(.7);doc.fontSize(9).text(`Toplam hareket: ${rows.length}`);doc.moveDown();for(const r of rows){if(doc.y>750)doc.addPage();const date=new Date(r.occurred_at).toLocaleString('tr-TR');const sign=r.direction==='EXPENSE'?'-':'+';doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#111').text(`${ascii(r.category)}  ${sign}${money(r.net_amount,r.currency)}`,{continued:false});doc.font('Helvetica').fontSize(7.5).fillColor('#555').text(`${date} | ${ascii(r.counterparty_name||r.description||r.reference||'Kayit')} | ${ascii(r.payment_method||r.source||'')}`);if(r.discount_amount&&Number(r.discount_amount)>0)doc.text(`Indirim: ${money(r.discount_amount,r.currency)}`);doc.moveDown(.45);}doc.moveDown();doc.fillColor('#666').fontSize(7).text('Bu rapor operasyonel yonetim icindir. Resmi defter, e-Fatura/e-Arsiv veya mali musavir kayitlarinin yerine gecmez.');doc.end();});}

export default {async fetch(request:Request):Promise<Response>{if(request.method!=='GET')return Response.json({ok:false,code:'METHOD_NOT_ALLOWED'},{status:405});try{await requireFinance(request);const url=new URL(request.url);const now=new Date();const from=parseDate(url.searchParams.get('from'),new Date(now.getFullYear(),now.getMonth(),1));const to=parseDate(url.searchParams.get('to'),new Date(now.getFullYear(),now.getMonth()+1,1));if(to<=from||to.getTime()-from.getTime()>370*86400000)return Response.json({ok:false,code:'INVALID_PERIOD'},{status:400});const filters=`occurred_at=gte.${encodeURIComponent(from.toISOString())}&occurred_at=lt.${encodeURIComponent(to.toISOString())}`;const res=await serviceFetch(`/rest/v1/finance_transactions?status=neq.VOID&${filters}&select=*&order=occurred_at.asc&limit=10000`);if(!res.ok)throw new Error('FINANCE_READ_FAILED');const rows=await res.json();const pdf=await pdfBuffer(Array.isArray(rows)?rows:[],from,to);return new Response(pdf,{status:200,headers:{'content-type':'application/pdf','content-disposition':`attachment; filename="alperler-muhasebe-${from.toISOString().slice(0,10)}-${to.toISOString().slice(0,10)}.pdf"`,'cache-control':'no-store','x-content-type-options':'nosniff'}});}catch(error){const code=error instanceof Error?error.message:'REPORT_FAILED';return Response.json({ok:false,code},{status:code==='UNAUTHORIZED'?401:code==='FORBIDDEN'?403:500,headers:{'cache-control':'no-store'}});}}};
