import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const SOURCE_URL="https://raw.githubusercontent.com/open-admin-data/turkey-administrative-divisions/master/data/all-flat.json";
const SOURCE_PAGE="https://github.com/open-admin-data/turkey-administrative-divisions";
type Row={id?:string;level?:number;name?:{local?:string;slug?:string};parent?:{id?:string}|null;geo?:{lat?:string|number;lon?:string|number}};
function h(){return{"access-control-allow-origin":"*","access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type,apikey","content-type":"application/json; charset=utf-8","cache-control":"public, max-age=300, s-maxage=1800, stale-while-revalidate=86400","x-content-type-options":"nosniff"};}
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:h()});}
function sh(extra:Record<string,string>={}){return{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,"content-type":"application/json",...extra};}
async function rest(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...sh(),...(init.headers||{})},signal:init.signal||AbortSignal.timeout(15000)});}
async function sha(text:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(d)].map(v=>v.toString(16).padStart(2,"0")).join("");}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?Math.round(x*1e6)/1e6:null;}
async function count(path:string){const r=await rest(`${path}?select=code`,{headers:{Prefer:"count=exact",Range:"0-0"}});const m=/\/(\d+)$/.exec(r.headers.get("content-range")||"");return r.ok&&m?Number(m[1]):0;}
async function sync(){if(await count("geo_provinces")===81&&await count("geo_districts")>=970)return;const r=await fetch(SOURCE_URL,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error("GEO_SOURCE_UNAVAILABLE");const text=await r.text();if(text.length<200000||text.length>3000000)throw new Error("GEO_SOURCE_SIZE_INVALID");const payload=JSON.parse(text) as {data?:Row[]};if(!Array.isArray(payload.data))throw new Error("GEO_SOURCE_INVALID");const provinces=payload.data.filter(x=>x.level===1&&/^TUR\d{3}$/.test(String(x.id||""))).map(x=>({code:String(x.id),name:String(x.name?.local||"").normalize("NFC").trim(),slug:String(x.name?.slug||"").trim(),latitude:n(x.geo?.lat),longitude:n(x.geo?.lon)}));const pc=new Set(provinces.map(x=>x.code));const districts=payload.data.filter(x=>x.level===2&&/^TUR\d{6}$/.test(String(x.id||""))&&pc.has(String(x.parent?.id||""))).map(x=>({code:String(x.id),province_code:String(x.parent?.id),name:String(x.name?.local||"").normalize("NFC").trim(),slug:String(x.name?.slug||"").trim(),latitude:n(x.geo?.lat),longitude:n(x.geo?.lon)}));if(provinces.length!==81||districts.length<970||districts.length>1100||provinces.some(x=>!x.name||!x.slug)||districts.some(x=>!x.name||!x.slug))throw new Error("GEO_SOURCE_VALIDATION_FAILED");const s=await rest("rpc/replace_turkey_geo_directory",{method:"POST",body:JSON.stringify({p_provinces:provinces,p_districts:districts,p_source_updated_at:null,p_checksum:await sha(text)}),signal:AbortSignal.timeout(30000)});if(!s.ok){console.error("geo sync",s.status,(await s.text().catch(()=>"")).slice(0,500));throw new Error("GEO_SYNC_FAILED");}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h()});if(req.method!=="GET")return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);if(!SUPABASE_URL||!SERVICE_KEY)return json({ok:false,code:"SERVER_CONFIG_MISSING"},503);try{await sync();const[p,d]=await Promise.all([rest("geo_provinces?select=code,name,slug,latitude,longitude&order=name.asc"),rest("geo_districts?select=code,province_code,name,slug,latitude,longitude&order=province_code.asc,name.asc")]);if(!p.ok||!d.ok)return json({ok:false,code:"GEO_DIRECTORY_UNAVAILABLE"},503);return json({ok:true,source:{name:"Open Admin Data",url:SOURCE_PAGE,license:"CC-BY-4.0"},provinces:await p.json(),districts:await d.json()});}catch(e){console.error("geo-directory",e);return json({ok:false,code:e instanceof Error?e.message:"GEO_DIRECTORY_FAILED"},503);}});
