insert into public.catalog_media (tour_id, kind, external_url, source_url, source_name, license, attribution, alt_text, sort_order, is_cover, is_active, metadata)
select * from (values
('7b20482b-ccc5-46d4-ad67-12cac138a2a7'::uuid,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/BERCELAN%20FESTIVALS%2001.06.2009%20-%20panoramio.jpg?width=1600','https://commons.wikimedia.org/wiki/File:BERCELAN_FESTIVALS_01.06.2009_-_panoramio.jpg','Wikimedia Commons','CC BY-SA 3.0','mehmet şan / Wikimedia Commons','Berçelan yaylası ve geleneksel yaşam alanından görünüm',2,false,true,'{"sourceVerified":true,"location":"Berçelan, Hakkari"}'::jsonb),
('e007bbb4-d93d-4183-b89b-194ffd71ad68'::uuid,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Cennet%20Cehennem%20Vadisi%20-%20Hakkari.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Cennet_Cehennem_Vadisi_-_Hakkari.jpg','Wikimedia Commons','CC BY-SA 4.0','Hamdigumus / Wikimedia Commons','Cennet Cehennem Vadisi Hakkari doğa görünümü',2,false,true,'{"sourceVerified":true,"location":"Cennet Cehennem Vadisi, Hakkari"}'::jsonb),
('1bc16a0e-3b12-4aef-9137-858d0b68958f'::uuid,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Cilo%20Da%C4%9Flar%C4%B1.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Cilo_Da%C4%9Flar%C4%B1.jpg','Wikimedia Commons','CC BY-SA 4.0','Candanozgenkrusa / Wikimedia Commons','Cilo Dağları yüksek çözünürlüklü doğa görünümü',2,false,true,'{"sourceVerified":true,"location":"Cilo Dağları, Hakkari"}'::jsonb),
('0bb7ba83-35b6-4b6f-bf4c-18da76798209'::uuid,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakk%C3%A2ri%20Cilo%20and%20Sat%20Mountains%20jully%202023.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Hakk%C3%A2ri_Cilo_and_Sat_Mountains_jully_2023.jpg','Wikimedia Commons','CC BY-SA 4.0','Arcmem / Wikimedia Commons','Cilo ve Sat Dağları yaz mevsimi panoraması',2,false,true,'{"sourceVerified":true,"location":"Cilo ve Sat Dağları, Hakkari"}'::jsonb),
('37034935-7a92-4ccc-bc51-46163532d86f'::uuid,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakkari%20banner%20Fritillaria.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Hakkari_banner_Fritillaria.jpg','Wikimedia Commons','CC BY-SA 4.0','Engin Tavlı / Wikimedia Commons','Hakkari ters lalesi yakın plan görünümü',2,false,true,'{"sourceVerified":true,"location":"Hakkari"}'::jsonb),
('c457b08f-4d10-44fd-97e8-8c0fe7194564'::uuid,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Zap%20Nehri...%20-%20panoramio.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Zap_Nehri..._-_panoramio.jpg','Wikimedia Commons','CC BY-SA 3.0','hamza atılgan / Wikimedia Commons','Zap Nehri Hakkari doğa görünümü',2,false,true,'{"sourceVerified":true,"location":"Zap Nehri, Hakkari"}'::jsonb)
) as v(tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
where not exists (
  select 1 from public.catalog_media cm
  where cm.tour_id = v.tour_id and cm.source_url = v.source_url
);
