create table if not exists public.system_events (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  severity text not null default 'ERROR' check (severity in ('INFO','WARN','ERROR','CRITICAL')),
  source text not null check (char_length(source) between 1 and 80),
  code text not null check (char_length(code) between 1 and 120),
  message text not null check (char_length(message) between 1 and 700),
  route text null check (route is null or (char_length(route) <= 400 and route like '/%' and route not like '//%')),
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  resolved_at timestamptz null,
  auto_recovered boolean not null default false,
  recovery_action text null check (recovery_action is null or char_length(recovery_action) <= 120),
  release_sha text null check (release_sha is null or char_length(release_sha) <= 120),
  client_family text null check (client_family is null or char_length(client_family) <= 120),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object' and pg_column_size(details) <= 16384)
);

create index if not exists system_events_last_seen_idx on public.system_events(last_seen desc);
create index if not exists system_events_open_severity_idx on public.system_events(severity, last_seen desc) where resolved_at is null;

alter table public.system_events enable row level security;

drop policy if exists system_events_admin_read on public.system_events;
create policy system_events_admin_read on public.system_events for select to authenticated using (private.can_manage_settings());

drop policy if exists system_events_admin_resolve on public.system_events;
create policy system_events_admin_resolve on public.system_events for update to authenticated using (private.can_manage_settings()) with check (private.can_manage_settings());

revoke all on public.system_events from anon, authenticated;
grant select on public.system_events to authenticated;
grant update (resolved_at) on public.system_events to authenticated;
grant select, insert, update on public.system_events to service_role;
grant usage, select on sequence public.system_events_id_seq to service_role;

create or replace function public.ingest_system_event(
  p_severity text,
  p_source text,
  p_code text,
  p_message text,
  p_route text default null,
  p_auto_recovered boolean default false,
  p_recovery_action text default null,
  p_release_sha text default null,
  p_client_family text default null,
  p_details jsonb default '{}'::jsonb
) returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_fingerprint text;
  v_id bigint;
begin
  if p_severity not in ('INFO','WARN','ERROR','CRITICAL') then raise exception 'INVALID_SEVERITY'; end if;
  if p_source is null or p_source !~ '^[A-Za-z0-9_-]{1,80}$' then raise exception 'INVALID_SOURCE'; end if;
  if p_code is null or p_code !~ '^[A-Za-z0-9_.:-]{1,120}$' then raise exception 'INVALID_CODE'; end if;
  if p_message is null or char_length(p_message) < 1 or char_length(p_message) > 700 then raise exception 'INVALID_MESSAGE'; end if;
  if p_route is not null and (char_length(p_route) > 400 or p_route !~ '^/' or p_route ~ '^//') then raise exception 'INVALID_ROUTE'; end if;
  if p_details is null or jsonb_typeof(p_details) <> 'object' or pg_column_size(p_details) > 16384 then raise exception 'INVALID_DETAILS'; end if;

  v_fingerprint := encode(extensions.digest(concat_ws('|', p_source, p_code, coalesce(p_route,''), p_message), 'sha256'), 'hex');

  insert into public.system_events(
    fingerprint,severity,source,code,message,route,occurrence_count,first_seen,last_seen,resolved_at,
    auto_recovered,recovery_action,release_sha,client_family,details
  ) values (
    v_fingerprint,p_severity,p_source,p_code,p_message,p_route,1,now(),now(),null,
    coalesce(p_auto_recovered,false),p_recovery_action,p_release_sha,p_client_family,p_details
  )
  on conflict (fingerprint) do update set
    severity = case
      when excluded.severity='CRITICAL' or system_events.severity='CRITICAL' then 'CRITICAL'
      when excluded.severity='ERROR' or system_events.severity='ERROR' then 'ERROR'
      when excluded.severity='WARN' or system_events.severity='WARN' then 'WARN'
      else 'INFO' end,
    occurrence_count = system_events.occurrence_count + 1,
    last_seen = now(),
    resolved_at = null,
    auto_recovered = system_events.auto_recovered or excluded.auto_recovered,
    recovery_action = coalesce(excluded.recovery_action, system_events.recovery_action),
    release_sha = coalesce(excluded.release_sha, system_events.release_sha),
    client_family = coalesce(excluded.client_family, system_events.client_family),
    details = excluded.details
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.ingest_system_event(text,text,text,text,text,boolean,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.ingest_system_event(text,text,text,text,text,boolean,text,text,text,jsonb) to service_role;
