begin;

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakkari.JPG?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakkari.JPG?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',true,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Hakkari.JPG','coverMediaLicense','CC BY-SA 3.0','coverMediaAttribution','Perencal / Wikimedia Commons','verifiedLocation','Hakkari Province','representativeReason','Zeynel Bey Medresesi için açık lisanslı doğrudan yapı görseli doğrulanamadı; Hakkari rota görseli kullanılıyor'),updated_at=now() where (metadata->>'legacyId')::int=3010;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakkari.JPG?width=1600','https://commons.wikimedia.org/wiki/File:Hakkari.JPG','Wikimedia Commons','CC BY-SA 3.0','Perencal','Hakkari tarih rotası için temsili bölge görünümü',1,true,true,jsonb_build_object('representative',true,'verifiedLocation','Hakkari Province','representativeReason','Direct licensed Zeynel Bey Medresesi image not verified') from public.tours t where (t.metadata->>'legacyId')::int=3010 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakkari.JPG?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Da%C4%9Fl%C4%B1ca-Y%C3%BCksekova.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Da%C4%9Fl%C4%B1ca-Y%C3%BCksekova.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Da%C4%9Fl%C4%B1ca-Y%C3%BCksekova.jpg','coverMediaLicense','CC BY-SA 3.0','coverMediaAttribution','Işık Yakın / Wikimedia Commons','verifiedLocation','Yüksekova-Dağlıca road, Hakkari'),updated_at=now() where (metadata->>'legacyId')::int=3011;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Da%C4%9Fl%C4%B1ca-Y%C3%BCksekova.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Da%C4%9Fl%C4%B1ca-Y%C3%BCksekova.jpg','Wikimedia Commons','CC BY-SA 3.0','Işık Yakın','Yüksekova ile Dağlıca arasındaki yol ve Oremar bölgesi rotası',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Yüksekova-Dağlıca road, Hakkari') from public.tours t where (t.metadata->>'legacyId')::int=3011 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Da%C4%9Fl%C4%B1ca-Y%C3%BCksekova.jpg?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova.JPG?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova.JPG?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',true,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Y%C3%BCksekova.JPG','coverMediaLicense','CC BY-SA 3.0','coverMediaAttribution','Bopal / Wikimedia Commons','verifiedLocation','Yüksekova, Hakkari','representativeReason','Yeşiltaş köyünün açık lisanslı doğrudan görseli doğrulanamadı; Yüksekova bölge görünümü kullanılıyor'),updated_at=now() where (metadata->>'legacyId')::int=3012;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova.JPG?width=1600','https://commons.wikimedia.org/wiki/File:Y%C3%BCksekova.JPG','Wikimedia Commons','CC BY-SA 3.0','Bopal','Yeşiltaş ekolojik turu için temsili Yüksekova bölge görünümü',1,true,true,jsonb_build_object('representative',true,'verifiedLocation','Yüksekova, Hakkari','representativeReason','Direct licensed Yeşiltaş village image not verified') from public.tours t where (t.metadata->>'legacyId')::int=3012 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova.JPG?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakk%C3%A2ri_Y%C3%BCksekova_-_Cennet_Cehennem_Vadisi.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakk%C3%A2ri_Y%C3%BCksekova_-_Cennet_Cehennem_Vadisi.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Hakk%C3%A2ri_Y%C3%BCksekova_-_Cennet_Cehennem_Vadisi.jpg','coverMediaLicense','CC BY-SA 4.0','coverMediaAttribution','Candanozgenkrusa / Wikimedia Commons','verifiedLocation','Cennet Cehennem Vadisi, Yüksekova, Hakkari'),updated_at=now() where (metadata->>'legacyId')::int=3013;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakk%C3%A2ri_Y%C3%BCksekova_-_Cennet_Cehennem_Vadisi.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Hakk%C3%A2ri_Y%C3%BCksekova_-_Cennet_Cehennem_Vadisi.jpg','Wikimedia Commons','CC BY-SA 4.0','Candanozgenkrusa','Hakkâri Yüksekova Cennet Cehennem Vadisi',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Cennet Cehennem Vadisi, Yüksekova, Hakkari') from public.tours t where (t.metadata->>'legacyId')::int=3013 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Hakk%C3%A2ri_Y%C3%BCksekova_-_Cennet_Cehennem_Vadisi.jpg?width=1600');

commit;
