alter table public.admin_users enable row level security;
alter table public.vehicles enable row level security;
alter table public.tours enable row level security;
alter table public.branches enable row level security;
alter table public.bookings enable row level security;
alter table public.partner_requests enable row level security;
alter table public.contact_messages enable row level security;
alter table public.subscribers enable row level security;
alter table public.payment_transactions enable row level security;
alter table public.notification_deliveries enable row level security;
alter table public.blog_posts enable row level security;
alter table public.faqs enable row level security;
alter table public.site_config enable row level security;
alter table public.audit_logs enable row level security;
alter table public.media_assets enable row level security;

create policy admin_users_self_read on public.admin_users for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy vehicles_public_read on public.vehicles for select to anon, authenticated using (is_active = true or public.is_admin());
create policy vehicles_admin_insert on public.vehicles for insert to authenticated with check (public.is_admin());
create policy vehicles_admin_update on public.vehicles for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy vehicles_admin_delete on public.vehicles for delete to authenticated using (public.is_admin());
create policy tours_public_read on public.tours for select to anon, authenticated using (is_active = true or public.is_admin());
create policy tours_admin_insert on public.tours for insert to authenticated with check (public.is_admin());
create policy tours_admin_update on public.tours for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy tours_admin_delete on public.tours for delete to authenticated using (public.is_admin());
create policy branches_public_read on public.branches for select to anon, authenticated using (is_active = true or public.is_admin());
create policy branches_admin_insert on public.branches for insert to authenticated with check (public.is_admin());
create policy branches_admin_update on public.branches for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy branches_admin_delete on public.branches for delete to authenticated using (public.is_admin());
create policy bookings_admin_read on public.bookings for select to authenticated using (public.is_admin());
create policy bookings_admin_update on public.bookings for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy bookings_admin_delete on public.bookings for delete to authenticated using (public.is_admin());
create policy partner_admin_read on public.partner_requests for select to authenticated using (public.is_admin());
create policy partner_admin_update on public.partner_requests for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy partner_admin_delete on public.partner_requests for delete to authenticated using (public.is_admin());
create policy contact_admin_read on public.contact_messages for select to authenticated using (public.is_admin());
create policy contact_admin_update on public.contact_messages for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy contact_admin_delete on public.contact_messages for delete to authenticated using (public.is_admin());
create policy subscribers_admin_read on public.subscribers for select to authenticated using (public.is_admin());
create policy subscribers_admin_update on public.subscribers for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy payments_admin_read on public.payment_transactions for select to authenticated using (public.is_admin());
create policy notifications_admin_read on public.notification_deliveries for select to authenticated using (public.is_admin());
create policy blog_public_read on public.blog_posts for select to anon, authenticated using (status = 'PUBLISHED' or public.is_admin());
create policy blog_admin_insert on public.blog_posts for insert to authenticated with check (public.is_admin());
create policy blog_admin_update on public.blog_posts for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy blog_admin_delete on public.blog_posts for delete to authenticated using (public.is_admin());
create policy faqs_public_read on public.faqs for select to anon, authenticated using (is_active = true or public.is_admin());
create policy faqs_admin_insert on public.faqs for insert to authenticated with check (public.is_admin());
create policy faqs_admin_update on public.faqs for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy faqs_admin_delete on public.faqs for delete to authenticated using (public.is_admin());
create policy site_config_public_read on public.site_config for select to anon, authenticated using (is_public = true or public.is_admin());
create policy site_config_admin_insert on public.site_config for insert to authenticated with check (public.is_admin());
create policy site_config_admin_update on public.site_config for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy site_config_admin_delete on public.site_config for delete to authenticated using (public.is_admin());
create policy audit_admin_read on public.audit_logs for select to authenticated using (public.is_admin());
create policy media_public_read on public.media_assets for select to anon, authenticated using (is_public = true or public.is_admin());
create policy media_admin_insert on public.media_assets for insert to authenticated with check (public.is_admin());
create policy media_admin_update on public.media_assets for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy media_admin_delete on public.media_assets for delete to authenticated using (public.is_admin());