-- Seed the current production fallback catalog into Supabase before switching reads.
-- Stable legacy identifiers make this migration safe to re-run.

insert into public.vehicles (
  stock_code, category, brand, model, model_year, price, currency,
  rental_price_daily, mileage_km, fuel_type, transmission, body_type, color,
  engine, seats, description, features, images, cover_image, is_featured,
  is_active, availability_status, metadata
) values
('LEGACY-1001','RENTAL','Mercedes-Benz','C Serisi (Süslenmiş Gelin Arabası)',2023,6500,'TRY',6500,null,'Benzin','Otomatik','Sedan',null,null,5,
 'Özel günleriniz için özenle süslenmiş şoförlü VIP gelin arabası. Çiçek süslemeleri ve deneyimli şoförümüz fiyata dâhildir.',
 '["Şoförlü Hizmet","Süsleme Dâhil","Klima","Deri Koltuklar","Sunroof"]'::jsonb,
 '["https://images.unsplash.com/photo-1549558548-e87f17424ad3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1617531653332-bd46c24f2068?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1563720360172-67b8f3dce741?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"]'::jsonb,
 'https://images.unsplash.com/photo-1549558548-e87f17424ad3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":1001,"driverOption":"WITH_DRIVER","badge":"DÜĞÜN PAKETİ","isPopular":true,"deposit":5000,"minLicenseYears":2,"dailyMileageLimit":250}'::jsonb),
('LEGACY-1002','RENTAL','Mercedes-Benz','Vito VIP',2022,8500,'TRY',8500,null,'Dizel','Otomatik','Minibus',null,null,9,
 'Geniş aileler, özel gruplar ve turlar için ultra lüks içi yapılı VIP Mercedes Vito. TV, buzdolabı ve özel aydınlatma mevcuttur.',
 '["Deri Koltuklar","Buzdolabı","TV & Multimedya","VIP Tasarım","Arka Klima"]'::jsonb,
 '[]'::jsonb,'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":1002,"driverOption":"WITH_DRIVER","badge":"VIP","isPopular":true}'::jsonb),
('LEGACY-1003','RENTAL','Volkswagen','Amarok Aventura',2023,4500,'TRY',4500,null,'Dizel','Otomatik','Pickup',null,null,5,
 'Zorlu arazi şartlarında üstün performans gösteren, 4x4 çekiş sistemine sahip, en dolu paket VW Amarok.',
 '["4x4 Çeker","Deri Koltuk","Arazi Modu","Aventura Paket","Navigasyon"]'::jsonb,
 '[]'::jsonb,'https://images.unsplash.com/photo-1559416523-140ddc3d238c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":1003,"driverOption":"BOTH","badge":"4x4 OFFROAD","isPopular":true}'::jsonb),
('LEGACY-1004','RENTAL','Renault','Megane',2022,2800,'TRY',2800,null,'Dizel','Otomatik','Sedan',null,null,5,
 'Şehir içi ve uzun yolculuklarınız için konforlu, geniş iç hacimli ve yakıt cimrisi güncel kasa Renault Megane.',
 '["Klima","Apple CarPlay","Hız Sabitleyici","Geri Görüş Kamerası"]'::jsonb,
 '[]'::jsonb,'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":1004,"driverOption":"WITHOUT_DRIVER"}'::jsonb),
('LEGACY-1005','RENTAL','Volkswagen','Passat',2021,4000,'TRY',4000,null,'Dizel','Otomatik','Sedan',null,null,5,
 'Konfor ve prestiji bir arada sunan D segmenti VW Passat. Uzun yol seyahatleri ve iş gezileri için mükemmel tercih.',
 '["Deri/Kumaş Koltuk","Navigasyon","ErgoComfort","Üç Bölgeli Klima"]'::jsonb,
 '[]'::jsonb,'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'AVAILABLE',
 '{"legacyId":1005,"driverOption":"BOTH","badge":"PREMIUM","isPopular":true}'::jsonb),
('LEGACY-1006','RENTAL','BMW','3.20i',2022,6000,'TRY',6000,null,'Benzin','Otomatik','Sedan',null,null,5,
 'Sportif sürüş keyfi arayanlar için lüks donanımlı BMW 3.20i. Dinamik performans ve üst düzey konfor.',
 '["M Sport Paket","Hayalet Ekran","Sunroof","Harman/Kardon","Sürüş Asistanları"]'::jsonb,
 '[]'::jsonb,'https://images.unsplash.com/photo-1555008872-f03b347ffb53?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":1006,"driverOption":"WITHOUT_DRIVER","badge":"SPORT"}'::jsonb),
('LEGACY-1007','RENTAL','Ford','Focus',2021,2500,'TRY',2500,null,'Dizel','Otomatik','Sedan',null,null,5,
 'Eşsiz yol tutuşu ve verimli motoruyla sınıf lideri Ford Focus. Hem aileler hem de iş seyahatleri için ideal.',
 '["Geniş Bagaj","Apple CarPlay","Otomatik Vites","Sürüş Modları"]'::jsonb,
 '[]'::jsonb,'https://images.unsplash.com/photo-1522818610332-9cbceeb97b1a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'AVAILABLE',
 '{"legacyId":1007,"driverOption":"WITHOUT_DRIVER"}'::jsonb),
('LEGACY-2001','SALE','Audi','A3',2022,2150000,'TRY',null,25000,'Benzin','Otomatik','Hatchback','Siyah','1498 cc',null,
 'Ekspertiz garantili, yetkili servis bakımlı tramersiz Audi A3 Sportback. Hata, boya ve değişen yoktur.',
 '[]'::jsonb,
 '["https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1542282088-fe8426682b8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"]'::jsonb,
 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":2001,"series":"Sportback 35 TFSI","enginePower":"150 hp","drivetrain":"Önden Çekiş","damageStatus":"Hatasız, Boyasız","warranty":"2 Yıl Garantili","isDamageFree":true,"availability":"Satışta","badge":"FIRSAT"}'::jsonb),
('LEGACY-2002','SALE','Renault','Megane',2021,1350000,'TRY',null,68000,'Benzin','Otomatik','Sedan','Siyah','1332 cc',null,
 'En dolu paket Icon donanımıyla muazzam siyah renkli Megane. İç kondisyonu sıfır ayarında.',
 '[]'::jsonb,
 '["https://images.unsplash.com/photo-1563720223185-11003d516935?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1494976388531-d1058494cdd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"]'::jsonb,
 'https://images.unsplash.com/photo-1563720223185-11003d516935?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":2002,"series":"1.3 TCe Icon","enginePower":"140 hp","drivetrain":"Önden Çekiş","damageStatus":"1 Parça Lokal Boyalı","warranty":"Garantisi Bitti","isDamageFree":false,"availability":"Satışta"}'::jsonb),
('LEGACY-2003','SALE','Peugeot','3008',2020,1850000,'TRY',null,85000,'Dizel','Otomatik','SUV','Beyaz','1499 cc',null,
 'Ailenizle güvenle binebileceğiniz, efsane tasarımı ve gelişmiş kokpiti ile Peugeot 3008.',
 '[]'::jsonb,
 '["https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"]'::jsonb,
 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":2003,"series":"1.5 BlueHDi Allure","enginePower":"130 hp","drivetrain":"Önden Çekiş","damageStatus":"Değişensiz, Hatasız","warranty":"Garantisi Bitti","isDamageFree":true,"availability":"Satışta","badge":"POPÜLER"}'::jsonb),
('LEGACY-2004','SALE','Toyota','Hilux',2023,2450000,'TRY',null,15000,'Dizel','Otomatik','Pickup','Siyah','2393 cc',null,
 'Off-road donanımlı, sıfır ayarında, yenilmez Toyota Hilux. Yüksekova ve Hakkari coğrafyasına tam uyumlu.',
 '[]'::jsonb,
 '["https://images.unsplash.com/photo-1626262444655-b441a1eb7ce6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"]'::jsonb,
 'https://images.unsplash.com/photo-1626262444655-b441a1eb7ce6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',true,true,'AVAILABLE',
 '{"legacyId":2004,"series":"2.4 D-4D Invincible","enginePower":"150 hp","drivetrain":"4x4","damageStatus":"Hatasız, Boyasız","warranty":"Garantisi Devam Ediyor","isDamageFree":true,"availability":"Satışta","badge":"YENİ"}'::jsonb)
on conflict (stock_code) do update set
  category = excluded.category,
  brand = excluded.brand,
  model = excluded.model,
  model_year = excluded.model_year,
  price = excluded.price,
  currency = excluded.currency,
  rental_price_daily = excluded.rental_price_daily,
  mileage_km = excluded.mileage_km,
  fuel_type = excluded.fuel_type,
  transmission = excluded.transmission,
  body_type = excluded.body_type,
  color = excluded.color,
  engine = excluded.engine,
  seats = excluded.seats,
  description = excluded.description,
  features = excluded.features,
  images = excluded.images,
  cover_image = excluded.cover_image,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  availability_status = excluded.availability_status,
  metadata = excluded.metadata;

insert into public.tours (
  title, seo_slug, description, price_per_person, currency, duration,
  images, cover_image, is_featured, is_active, metadata
) values
('Cilo Dağları & Buzullar Uzman Turu','legacy-3001-cilo-buzullar','Türkiye''nin en yüksek kalıcı buzullarına ev sahipliği yapan Cilo Dağları''nda eşsiz bir macera. 4 mevsimi aynı anda yaşayacağınız bu turda Ters Laleler, sarp zirveler ve buzul gölleri eşliğinde vahşi doğanın kalbine iniyoruz.',4500,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3001,"highlights":["Günübirlik Profesyonel Tur","Bölgesel Lüks Öğle Yemeği","Tarihi Kiliseler","Buzul Alanlarına Özel Yürüyüş","Profesyonel Dağ Rehberliği"],"mapIframeUrl":"https://maps.google.com/maps?q=Cilo+Da%C4%9Flar%C4%B1+Buzullar%C4%B1&t=k&z=11&ie=UTF8&iwloc=&output=embed"}'::jsonb),
('Sat Gölleri Lüks Kamp Macerası','legacy-3002-sat-golleri','Hakkari''nin parlayan incisi İkiyaka Dağlarındaki Sat Gölleri''nde, yıldızların altında, hiçbir detaydan ödün vermeyen glamping tarzı lüks bir kamp deneyimi. Ateş başında yöresel masallar ve eşsiz manzara.',8000,'TRY','2 Gün 1 Gece','[]'::jsonb,'https://images.unsplash.com/photo-1510312305653-8ed496efae75?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3002,"highlights":["Lüks Çadır & Tam Teçhizat","Ateş Başı Canlı Müzik","Organik Tüm Öğünler","Teleskopla Yıldız Gözlemi","Sabah Yoga Seansı"],"mapIframeUrl":"https://maps.google.com/maps?q=Sat+G%C3%B6lleri+Hakkari&t=k&z=12&ie=UTF8&iwloc=&output=embed"}'::jsonb),
('Şemdinli Vadisi Doğa & Kültür Turu','legacy-3003-semdinli-vadisi','Şemdinli''nin yemyeşil vadilerinde, Nehri Köyü, Kelat Sarayı ve Taş Köprüleri kapsayan otantik bir zaman yolculuğu. Seyhun Şelalesi etrafında yerel lezzet tadımları.',3500,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1506744626753-1fa7604ed229?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3003,"highlights":["Nehri Taş Köprüleri","Seyhun Şelalesi","Otlu Peynir Tadımı","Köy Evi Ziyareti","VIP Transfer"],"mapIframeUrl":"https://maps.google.com/maps?q=%C5%9Eemdinli+Hakkari&t=&z=11&ie=UTF8&iwloc=&output=embed"}'::jsonb),
('Zap Suyu Adrenalin & Rafting Turu','legacy-3004-zap-rafting','Türkiye''nin en hırçın sularından Zap Nehri''nde adrenalin dolu bir rafting deneyimi. Uzman yönlendiriciler eşliğinde güvenli, profesyonel ekipmanlarla suyun gücüne meydan okuyun.',5000,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1530866495561-507c9faab2ed?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3004,"highlights":["Profesyonel Rafting Eğitimi","Tam Güvenlik Ekipmanı","Aksiyon Kamera Çekimi","Zap Dinlenme Tesisinde Yemek","Sertifika Verimi"]}'::jsonb),
('Çukurca Sınırları & Taş Evler Turu','legacy-3005-cukurca','Tarihi Çukurca taş evlerini, asırlık su değirmenlerini ve susam tahini üretim atölyelerini keşfedin. Irak sınırının sıfır noktasında benzersiz bir tarih ve coğrafya harmanı.',3000,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1621213032731-bf50720fb9c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3005,"highlights":["Tarihi Çukurca Evleri","Tahin Atölyesi Ziyareti","Yöresel Çay Saati","Sınır Vadisi Seyri","Rehber Desteği"]}'::jsonb),
('Yüksekova Yayla & Ters Lale Fotoğraf Safarisi','legacy-3006-ters-lale','Yediveren, Sümbül, Cilo üçgeninde baharın müjdecisi Ters Laleleri (Ağlayan Gelin) tam mevsiminde fotoğraflamak için özel olarak düzenlenen safari tarzı fotoğraf turumuz.',4000,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1517502474415-3df53b1b6015?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3006,"highlights":["Ters Lale Alanları","Profesyonel Fotoğraf Rehberliği","Bahar Kahvaltısı","4x4 VIP Safari Araçları","Yüksekova (Gever) Ovası Rotası"]}'::jsonb),
('Sümbül Dağı Panoramik 4x4 Zirve Turu','legacy-3007-sumbul-dagi','Hakkari merkezinin koruyucusu konumundaki Sümbül Dağı''nın yamaçlarına VIP 4x4 Defender araçlarımızla çıkıyor, 3400 rakımdan tüm Mezopotamya''ya yukarıdan bakıyoruz.',5500,'TRY','Yarım Gün Tur','[]'::jsonb,'https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3007,"highlights":["VIP 4x4 Offroad","Sümbül Şelalesi","Dağ Zirvesinde Barbekü","Seyir Dürbünü Kullanımı","Unutulmaz Manzaralar"]}'::jsonb),
('Berçelan Yaylası Geleneksel Yaşam Turu','legacy-3008-bercelan','Yaz aylarında göçerlerin şenlendirdiği Berçelan Yaylası''na konuk oluyoruz. Geleneksel kıl çadırlarda koyun sağımından peynir yapımına yöresel kültürü ilk elden tecrübe edin.',3200,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1518331613945-8fbe0dff8f79?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3008,"highlights":["Kıl Çadır Deneyimi","Yayık Ayranı & Peynir Yapımı","Ata Binme Etkinliği","Doğa Yürüyüşü","Canlı Dengbej Dinletisi"]}'::jsonb),
('Hakkari Merkez Kültür & Tarih Yürüyüşü','legacy-3009-hakkari-merkez','Hakkari şehir merkezinin bilinmeyenleri. Meydan Medresesi, Mir Kalesi (Colemêrg Kalesi) ve Emir Şaban Camii gibi bin yıllık eserlerin gölgesinde tarih dolu bir yürüyüş.',2000,'TRY','Yarım Gün Tur','[]'::jsonb,'https://images.unsplash.com/photo-1579603378564-99881dcca474?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3009,"highlights":["Meydan Medresesi Ziyareti","Deneyimli Arkeolog Rehber","Şehir Müzeleri","Yerel Kilim Atölyesi","Sokak Lezzetleri"]}'::jsonb),
('Zeynel Bey Medresesi & Sınır Boyları Moto-Turu','legacy-3010-zeynel-bey','Özellikle kendi motosikletleriyle gezen veya bizden lüks arazi aracı kiralayan misafirlerimiz için sınır boylarında yer alan tarihi mekanlara korumalı, rehberli premium rota gezisi.',5200,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3010,"highlights":["Zeynel Bey Medresesi","Sınır Boyu Eşsiz Rotası","Action Cam Çekimleri","Korumalı İleri Sürüş","Dış Mekan Kahvesi"]}'::jsonb),
('Oremar (Dağlıca) Vadisi & Avaşin Keşfi','legacy-3011-oremar-avasin','Hakkari''nin el değmemiş coğrafyalarında, sarp doruklarla çevrili Avaşin nehrinin oluşturduğu Oremar Vadisi''ni keşfe çıkıyoruz. Otantik köyler, şelaleler ve derin kanyonlar.',4800,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1469474968028-56623f02e42e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3011,"highlights":["Avaşin Kanyonu","Dağlıca Şelaleleri","Yöresel Köy Kahvaltısı","Özel Fotoğraf Safarisi","Rehberli Yürüyüş"]}'::jsonb),
('Yeşiltaş Köyü Ekolojik Doğa Kampı','legacy-3012-yesiltas-koyu','Yeşiltaş köyünde misafirperver yöre halkıyla iç içe, doğayla baş başa ekolojik bir köy ve kamp deneyimi. Geleneksel tarım, arıcılık ve taş evlerde konaklama opsiyonlu çadır kampı.',6800,'TRY','2 Gün 1 Gece','[]'::jsonb,'https://images.unsplash.com/photo-1508873696983-2dfd5898f08b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3012,"highlights":["Köy Evinde Akşam Yemeği","Arıcılık & Bal Hasadı","Vadi İçi Doğa Yürüyüşü","Kamp Ateşi Etkinlikleri","Ekolojik Yaşam Pratikleri"]}'::jsonb),
('Cennet-Cehennem Vadisi Adrenalin Turu','legacy-3013-cennet-cehennem','Cilo Buzul Dağları silsilesinde yer alan ve bir tarafı yemyeşil "Cennet", diğer tarafı sarp kayalıklardan inen "Cehennem" olarak adlandırılan vadide destansı bir trekkiing rotası.',4200,'TRY','Günübirlik Tur','[]'::jsonb,'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',false,true,'{"legacyId":3013,"highlights":["Profesyonel Trekking","Buzul Şelaleleri","Kaya Tırmanışı Temelleri","Vahşi Yaşam Gözlemi","Kumanya ve Çay Molası"]}'::jsonb)
on conflict (seo_slug) do update set
  title = excluded.title,
  description = excluded.description,
  price_per_person = excluded.price_per_person,
  currency = excluded.currency,
  duration = excluded.duration,
  images = excluded.images,
  cover_image = excluded.cover_image,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  metadata = excluded.metadata;
