begin;

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova_04.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova_04.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Y%C3%BCksekova_04.jpg','coverMediaLicense','CC BY-SA 4.0','coverMediaAttribution','Perencal / Wikimedia Commons','verifiedLocation','Yüksekova, Hakkari','verifiedSubject','Ters lale'),updated_at=now() where (metadata->>'legacyId')::int=3006;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova_04.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Y%C3%BCksekova_04.jpg','Wikimedia Commons','CC BY-SA 4.0','Perencal','Yüksekova Hakkari ters lale',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Yüksekova, Hakkari','verifiedSubject','Ters lale') from public.tours t where (t.metadata->>'legacyId')::int=3006 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Y%C3%BCksekova_04.jpg?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/S%C3%9CMB%C3%9CL_DA%C4%9EI..._-_panoramio.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/S%C3%9CMB%C3%9CL_DA%C4%9EI..._-_panoramio.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:S%C3%9CMB%C3%9CL_DA%C4%9EI..._-_panoramio.jpg','coverMediaLicense','CC BY-SA 3.0','coverMediaAttribution','hamza atılgan / Wikimedia Commons','verifiedLocation','Sümbül Dağı, Hakkari'),updated_at=now() where (metadata->>'legacyId')::int=3007;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/S%C3%9CMB%C3%9CL_DA%C4%9EI..._-_panoramio.jpg?width=1600','https://commons.wikimedia.org/wiki/File:S%C3%9CMB%C3%9CL_DA%C4%9EI..._-_panoramio.jpg','Wikimedia Commons','CC BY-SA 3.0','hamza atılgan','Sümbül Dağı Hakkari panoraması',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Sümbül Dağı, Hakkari') from public.tours t where (t.metadata->>'legacyId')::int=3007 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/S%C3%9CMB%C3%9CL_DA%C4%9EI..._-_panoramio.jpg?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Ber%C3%A7elan_Deresi...._-_panoramio.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Ber%C3%A7elan_Deresi...._-_panoramio.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Ber%C3%A7elan_Deresi...._-_panoramio.jpg','coverMediaLicense','CC BY-SA 3.0','coverMediaAttribution','hamza atılgan / Wikimedia Commons','verifiedLocation','Berçelan, Hakkari'),updated_at=now() where (metadata->>'legacyId')::int=3008;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Ber%C3%A7elan_Deresi...._-_panoramio.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Ber%C3%A7elan_Deresi...._-_panoramio.jpg','Wikimedia Commons','CC BY-SA 3.0','hamza atılgan','Berçelan Deresi Hakkari',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Berçelan, Hakkari') from public.tours t where (t.metadata->>'legacyId')::int=3008 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Ber%C3%A7elan_Deresi...._-_panoramio.jpg?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Meydan_Medresesi.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Meydan_Medresesi.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Meydan_Medresesi.jpg','coverMediaLicense','CC BY-SA 4.0','coverMediaAttribution','Vladdracotepeş / Wikimedia Commons','verifiedLocation','Hakkari Merkez','verifiedSubject','Meydan Medresesi'),updated_at=now() where (metadata->>'legacyId')::int=3009;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Meydan_Medresesi.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Meydan_Medresesi.jpg','Wikimedia Commons','CC BY-SA 4.0','Vladdracotepeş','Hakkari Meydan Medresesi',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Hakkari Merkez','verifiedSubject','Meydan Medresesi') from public.tours t where (t.metadata->>'legacyId')::int=3009 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Meydan_Medresesi.jpg?width=1600');

commit;
