-- Seed current public blog and FAQ fallback content before switching reads.

insert into public.blog_posts (
  title, slug, excerpt, content, cover_image, author_name, status,
  published_at, seo_title, seo_description, metadata
) values
('Hakkari ve Yöresinde Mutlaka Görmeniz Gereken 5 Gizli Rota','legacy-blog-1-hakkari-gizli-rota',
 $$Sıradan turist rotalarının dışına çıkarak Yüksekova ve Şemdinli arasındaki saklı vadileri keşfedin. Doğanın kalbine yolculuk başlasın.$$,
 $$<p>Cilo Dağları buzullarından Sat Göllerine, doğa ile iç içe unutulmaz bir deneyim için işte size muhteşem rotalar. Hakkari bölge coğrafyasının zorlu yapısı, en el değmemiş doğal güzellikleri barındırıyor. Özel araç kiralama veya turlarımızla bu noktalara güvenle ulaşabilirsiniz.</p><p>1. Cilo Buzulları Kamp Alanı: Türkiye'nin en büyük vadi buzullarına ev sahipliği yapan bu bölge, doğa severler için adeta bir cennet. Dört mevsim farklı güzellikler sunan bölgede özellikle ilkbahar aylarında eriyen karların oluşturduğu şelaleler büyüleyicidir.</p><p>2. Şemdinli Seyir Terası: İlçe merkezine tepeden bakan bu nokta eşsiz fotoğraflar çekmek için idealdir.</p>$$,
 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2026-04-10T09:00:00+03:00',null,null,'{"legacyId":1,"originalDate":"10 Nisan 2026","readTime":"4 Dk Okuma"}'::jsonb),
('Araç Kiralarken Dikkat Edilmesi Gereken 10 Altın Kural','legacy-blog-2-arac-kiralama-kurallari',
 $$Kusursuz bir araç kiralama deneyimi mi yaşamak istiyorsunuz? Gizli maliyetlerden ve sözleşme tuzaklarından nasıl kaçınabileceğinizi öğrenin.$$,
 $$<p>Araç kiralarken sözleşme detayları, kasko kapsamı, yakıt politikası ve kilometre sınırı gibi konular büyük önem taşır. Sözleşmeyi imzalamadan önce aracın her tarafının fotoğraflarını çekmek veya videoya almak iyi bir tedbirdir. Tüm kiralık araçlarımızda sunduğumuz şeffaf sözleşme politikası sayesinde kötü sürprizlerle karşılaşmazsınız.</p><p>Ayrıca aracın lastik durumunu, farlarını ve klima performansını kontrol etmeyi unutmayın. Kurumsal bir araç kiralama şirketinden kiralama yaptığınızda 7/24 yol yardım desteğinin de poliçenize dahil olacağından emin olabilirsiniz.</p>$$,
 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2026-03-15T09:00:00+03:00',null,null,'{"legacyId":2,"originalDate":"15 Mart 2026","readTime":"6 Dk Okuma"}'::jsonb),
('Şoförlü Araç Kiralama: Özel Günlerinizin Kahramanı','legacy-blog-3-soforlu-arac-kiralama',
 $$Düğün, nişan veya VIP misafir karşılamalarında neden şoförlü kiralama tercih edilmeli?$$,
 $$<p>En özel anlarınızda ulaşım stresi yaşamak istemezsiniz. Şoförlü VIP kiralama ile tüm yolculuğunuz boyunca arkanıza yaslanıp keyfini çıkarabilirsiniz.</p><p>Profesyonel şoförlerimiz bölgenin trafiğine ve alternatif güzergahlarına hakimdir. Özellikle iş seyahatlerinde, yolculuk esnasında dinlenmek veya toplantı notlarınızı gözden geçirmek için size değerli bir zaman dilimi kazandırır.</p>$$,
 'https://images.unsplash.com/photo-1549558548-e87f17424ad3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2026-02-02T09:00:00+03:00',null,null,'{"legacyId":3,"originalDate":"02 Şubat 2026","readTime":"3 Dk Okuma"}'::jsonb),
('Kış Aylarında Güvenli Sürüş İçin Pratik Bilgiler','legacy-blog-4-kis-guvenli-surus',
 $$Karlı ve buzlu yollarda direksiyon hakimiyetini nasıl korursunuz? Araç kiralamada kış donanımlarının önemi.$$, 
 $$<p>Kış sürüşü ekstra dikkat gerektirir. Lastiklerin, sileceklerin ve antifrizin durumu hayati önem taşır. Alperler Auto olarak tüm kışlık bakımları tamamlanmış araçlarımızla size güvenli bir sürüş deneyimi sunuyoruz.</p><p>Karlı yokuşları inerken motor frenini kullanmak, fren pedalına aniden basmaktan daha etkilidir. Kayma anında direksiyonu aracın kaydığı yöne doğru çok hafif çevirerek hakimiyeti tekrar sağlayabilirsiniz.</p>$$,
 'https://images.unsplash.com/photo-1506192131238-d6f76c12ba30?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2026-01-12T09:00:00+03:00',null,null,'{"legacyId":4,"originalDate":"12 Ocak 2026","readTime":"5 Dk Okuma"}'::jsonb),
('SUV vs. Sedan: Araç Kiralarken Hangisini Seçmelisiniz?','legacy-blog-5-suv-vs-sedan',
 $$Ailenizle tatile çıkarken veya zorlu arazi koşullarına sahip rotalara giderken doğru araç kategorisini nasıl belirlersiniz?$$,
 $$<p>SUV araçlar yüksek oturuş pozisyonu, geniş bagaj hacmi ve zorlu yol şartlarına uyum sağlamaları ile öne çıkarken; Sedan araçlar otoyol sürüşlerinde konfor ve ekonomi sunar. Rotanıza ve yolcu sayısına göre doğru aracı seçmek seyahatinizi güzelleştirir.</p><p>Yüksekova'nın dağlık ve eğimli yolları için SUV modellerimiz genellikle ilk tercih edilendir. Hem görüş açınızın geniş olması hem de süspansiyon sistemlerinin zorlu zeminleri daha iyi absorbe etmesi sayesinde mükemmel bir konfor yakalarsınız.</p>$$,
 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-12-04T09:00:00+03:00',null,null,'{"legacyId":5,"originalDate":"04 Aralık 2025","readTime":"5 Dk Okuma"}'::jsonb),
('Bölgedeki En İyi Kahvaltı Mekanları','legacy-blog-6-kahvalti-mekanlari',
 $$Kiralık aracınızla hafta sonu kaçamağı yaparken sabahın erken saatlerinde uğramanız gereken lezzet durakları.$$, 
 $$<p>Yörenin muhteşem doğal kahvaltılıklarıyla güne başlamak gibisi yoktur. Özellikle dağ eteklerindeki rustik restoranlar, hem manzaraları hem de organik menüleri ile göz dolduruyor.</p><p>Bal, kaymak, otlu peynir ve taze sıcak lavaş... Alperler Auto misafirlerine özel sunduğumuz rotalarla bu lezzetleri kolaylıkla keşfedebilirsiniz.</p>$$,
 'https://images.unsplash.com/photo-1525648199074-bee30ba3d027?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-11-20T09:00:00+03:00',null,null,'{"legacyId":6,"originalDate":"20 Kasım 2025","readTime":"4 Dk Okuma"}'::jsonb),
('Kilometre Tasarrufu: Yakıt Verimli Sürüş Teknikleri','legacy-blog-7-yakit-verimli-surus',
 $$Uzun yolda yakıttan tasarruf etmenizi sağlayacak, bütçe dostu pratik sürüş önerileri.$$, 
 $$<p>Ekonomik sürüş için vites değişim aralıkları, doğru lastik basıncı ve sabit hız çok önemlidir. Kiralık araçlarımız en son nesil verimli motor seçeneklerine sahiptir, ancak sizin sürüş alışkanlıklarınız da yakıt tüketimini doğrudan etkiler.</p><p>Gereksiz ağırlıklardan kurtulmak, klima kullanımını optimize etmek ve yüksek motor devirlerinden kaçınmak size uzun yolda ciddi bir avantaj sağlar.</p>$$,
 'https://images.unsplash.com/photo-1542382025-a6e53d5e3cf7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-10-11T09:00:00+03:00',null,null,'{"legacyId":7,"originalDate":"11 Ekim 2025","readTime":"4 Dk Okuma"}'::jsonb),
('Araç Bakımında Orijinal Parçanın Önemi','legacy-blog-8-orijinal-parca',
 $$Her kiralık aracımızın neden yalnızca yetkili servislerde ve orijinal parçalarla bakımdan geçtiğini açıklıyoruz.$$, 
 $$<p>Müşterilerimizin güvenliği her şeyden önce gelir. Bu nedenle filomuzdaki tüm araçların periyodik bakımları zamanında, orijinal yedek parçalar kullanılarak yapılır.</p><p>Fren sistemlerinden motor aksamına kadar her şeyin eksiksiz ve yetkili standartlarında çalışması, sürüş esnasında yaşanabilecek riskleri en aza indirir.</p>$$,
 'https://images.unsplash.com/photo-1486495146582-9ffcd8cb7bb2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-09-02T09:00:00+03:00',null,null,'{"legacyId":8,"originalDate":"02 Eylül 2025","readTime":"3 Dk Okuma"}'::jsonb),
('Havalimanı Transfer Avantajları','legacy-blog-9-havalimani-transfer',
 $$Uçuştan indiğiniz anda sizi bekleyen lüks veya ekonomik bir transferin seyahat konforunuza katacağı değer.$$, 
 $$<p>Taksi kuyrukları veya otobüs saatleri ile vakit kaybetmek yerine, havalimanından kapınıza kadar VIP araçlarla ulaşım sağlamak en mantıklı seçenektir.</p><p>Uçuş detaylarınızı sistemimize girdiğinizde şoförlerimiz rötar durumunda bile sizi zamanında karşılamak üzere hazır bekler.</p>$$,
 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-08-15T09:00:00+03:00',null,null,'{"legacyId":9,"originalDate":"15 Ağustos 2025","readTime":"3 Dk Okuma"}'::jsonb),
('Yeni Başlayanlar İçin Kamp Rotaları','legacy-blog-10-kamp-rotalari',
 $$Doğayla iç içe ilk kamp deneyiminiz için uygun alanlar ve kiralayabileceğiniz arazi araçları rehberi.$$, 
 $$<p>Şehirden uzaklaşıp doğaya dönmek isteyenler için bölgedeki en güvenli kamp rotalarını derledik. Arazi araçlarımız ve pick-up seçeneklerimiz, kamp ekipmanlarınızı yanınızda taşımanız için oldukça elverişlidir.</p><p>Kamp ateşi etrafında yıldızları izlerken aracınızın güven veren donanımı her zaman yanı başınızda olacak.</p>$$,
 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-07-28T09:00:00+03:00',null,null,'{"legacyId":10,"originalDate":"28 Temmuz 2025","readTime":"5 Dk Okuma"}'::jsonb),
('Dizel mi Benzinli mi? Yeni Nesil Hibrit Modeller','legacy-blog-11-yakit-tipleri',
 $$Hangi yakıt tipi sizin rotanız için daha avantajlı? Hibrit teknolojisinin araç kiralamasındaki yeri.$$, 
 $$<p>Dizel motorlar tork güçleri ile yokuş tırmanışlarında avantaj sağlarken benzinli motorlar genellikle daha sessiz bir sürüş vadeder. Artık hibrit modellerimizle düşük yakıt tüketimi ve çevre dostu seyahatler sunuyoruz.</p><p>Kiralama tercihinizde hem bütçenizi hem de çevre faktörlerini göz önünde bulundurmanız için tüm detayları uzman asistanlarımızdan danışabilirsiniz.</p>$$,
 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-06-10T09:00:00+03:00',null,null,'{"legacyId":11,"originalDate":"10 Haziran 2025","readTime":"4 Dk Okuma"}'::jsonb),
('Seyehatlerinizde Müzik ve Eğlence Sistemleri','legacy-blog-12-multimedya',
 $$Uzun yolların sıkıcılığını unutturacak araç içi multimedya donanımları hakkında bilmeniz gerekenler.$$, 
 $$<p>Apple CarPlay ve Android Auto destekli multimedya sistemler sayesinde tüm kiralık araçlarımızda müzik dinlemek ve harita yönetimi çok pratik.</p><p>Telefonunuzu araca bağlayıp favori çalma listenizi dinlerken yüksek ses kalitesinin tadını çıkarın.</p>$$,
 'https://images.unsplash.com/photo-1534062369680-e883838ae62d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-05-02T09:00:00+03:00',null,null,'{"legacyId":12,"originalDate":"02 Mayıs 2025","readTime":"3 Dk Okuma"}'::jsonb),
('Tarihi Mekanlar: Şemdinli Taş Köprü ve Çevresi','legacy-blog-13-semdinli-tas-kopru',
 $$Kültürel bir tur yapmak isteyenler için bölgenin önemli tarihi dokuları ve oraya giden güzergahlar.$$, 
 $$<p>Dağların arasında adeta bir zaman yolculuğu yaşatan taş köprüler, tarih meraklıları için keşfedilmesi gereken eşsiz duraklardandır. Kiralık bir araçla bu noktalara yapacağınız bir ziyaret hem konforlu hem de hafızalara kazınacak bir deneyim sunar.</p><p>Fotoğraf makinenizi yanınıza almayı unutmayın!</p>$$,
 'https://images.unsplash.com/photo-1600572703816-778f69eb56ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-04-16T09:00:00+03:00',null,null,'{"legacyId":13,"originalDate":"16 Nisan 2025","readTime":"4 Dk Okuma"}'::jsonb),
('Araç İçi Klima Kullanım Optimizasyonu','legacy-blog-14-klima-optimizasyonu',
 $$Yaz aylarında bunalmadan, aracı yormadan klima sistemini en verimli şekilde kullanmanın taktikleri.$$, 
 $$<p>Klimayı aracı ilk çalıştırdığınız anında değil, pencereleri açarak sıcak havayı bir miktar tahliye ettikten sonra açmak daha sağlıklıdır. Böylece kompresör zorlanmaz.</p><p>Tüm kiralık araçlarımızın klima gazları ve polen filtreleri yaz/kış sezon geçişlerinde eksiksiz olarak yenilenir.</p>$$,
 'https://images.unsplash.com/photo-1563821013753-15be96f863ef?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-04-05T09:00:00+03:00',null,null,'{"legacyId":14,"originalDate":"05 Nisan 2025","readTime":"3 Dk Okuma"}'::jsonb),
('Alperler Auto Araç Havuzu Sistemine Katılmanın Avantajları','legacy-blog-15-arac-havuzu',
 $$Garajınızda yatan aracınızı bizimle değerlendirerek düzenli ek gelir elde edebileceğinizi biliyor muydunuz?$$,
 $$<p>Aracınız kapıda boş yatıyorsa veya iş nedeniyle kullanamıyorsanız, Alperler Auto’nun profesyonel havuz sistemine aracınızı dahil edebilirsiniz.</p><p>Aracınızın kaskosu, periyodik bakımı ve tüm güvenlik süreçleri tarafımızdan takip edilir. Hem aracınız değerinden bir şey kaybetmeden özenle korunur, hem de sizin için risksiz bir gelir kapısı oluşur.</p>$$,
 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80','Alperler Auto','PUBLISHED','2025-03-20T09:00:00+03:00',null,null,'{"legacyId":15,"originalDate":"20 Mart 2025","readTime":"5 Dk Okuma"}'::jsonb)
on conflict (slug) do update set
  title=excluded.title, excerpt=excluded.excerpt, content=excluded.content,
  cover_image=excluded.cover_image, author_name=excluded.author_name,
  status=excluded.status, published_at=excluded.published_at,
  seo_title=excluded.seo_title, seo_description=excluded.seo_description,
  metadata=excluded.metadata;

insert into public.faqs (question,answer,category,sort_order,is_active) values
($$Araç kiralama şartları nelerdir?$$,$$Araç kiralayabilmek için en az 1 yıllık geçerli B sınıfı ehliyet sahibi olmanız ve 21 yaşını doldurmuş olmanız gerekmektedir. Üst segment araçlarımız için bu şartlar 3 yıl ehliyet ve 25 yaş olarak değişiklik göstermektedir.$$,'RENTAL',1,true),
($$Araç kiralamada depozito (provizyon) alınıyor mu?$$,$$Evet, kiraladığınız araç grubuna göre kredi kartınızdan provizyon çekilmektedir (1500 TL - 5000 TL arası). Araç sorunsuz iade edildiğinde bu tutar doğrudan kartınıza iade edilir.$$,'RENTAL',2,true),
($$Günlük kilometre sınırı var mıdır?$$,$$Kiralık araçlarımızda standart günlük kilometre sınırı 250 KM'dir. Aylık kiralamalarda ise 3500 KM veya 4000 KM sınırları uygulanabilmektedir. Ek kilometreler sözleşme sırasında karşılıklı belirlenen düşük ücretler üzerinden hesaplanır.$$,'RENTAL',3,true),
($$Araçlarınıza kasko dâhil mi, hangi durumlarda kasko bozulur?$$,$$Tüm araçlarımız Rent A Car kapsamlı muafiyetli kaskoludur. Karışılan kazalarda tutanak tutulması zorunludur. Alkol veya uyuşturucu etkisi altında yapılan kazalar kasko kapsamı dışındadır.$$,'RENTAL',4,true),
($$Havalimanı veya otogar teslimatı yapıyor musunuz?$$,$$Elbette. Yüksekova Selahaddin Eyyubi Havalimanı, Van Ferit Melen Havalimanı ve Şırnak Şerafettin Elçi Havalimanı başta olmak üzere, bölgedeki otogar ve belirli adreslere 7/24 Vale ile araç teslimat hizmetimiz bulunmaktadır.$$,'DELIVERY',5,true),
($$İkinci el satılık araçlarınızda ekspertiz ve garanti mevcut mu?$$,$$Kesinlikle. Portföyümüzde bulunan tüm ikinci el araçlar TSE onaylı, tam kapsamlı ve detaylı kurumsal ekspertiz raporlarına sahiptir. Ayrıca firmamız aracılığıyla alınan araçlara belirli sürelerde mekanik garanti sağlanabilmektedir.$$,'SALES',6,true),
($$Tur organizasyonlarınıza neler dâhildir?$$,$$Yüksekova, Hakkari, Şemdinli, Kars ve Erzurum bölgelerine düzenlediğimiz turlarımızda; lüks ulaşım, profesyonel kokartlı rehberlik, belirtilen öğünler (kahvaltı vs.) ve sigorta paketi fiyata dâhildir.$$,'TOUR',7,true)
on conflict do nothing;
