begin;

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Sat_glacier_lakes.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Sat_glacier_lakes.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Sat_glacier_lakes.jpg','coverMediaLicense','CC BY-SA 4.0','coverMediaAttribution','Hamdigumus / Wikimedia Commons','verifiedLocation','Sat Mountains glacier lakes, Hakkari'),updated_at=now() where (metadata->>'legacyId')::int=3002;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Sat_glacier_lakes.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Sat_glacier_lakes.jpg','Wikimedia Commons','CC BY-SA 4.0','Hamdigumus','Hakkari Sat Dağları buzul gölleri',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Sat Mountains glacier lakes, Hakkari') from public.tours t where (t.metadata->>'legacyId')::int=3002 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Sat_glacier_lakes.jpg?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Qesra_Kelat%C3%AA_li_gund%C3%AA_Nehriy%C3%AA_(Qesra_Sey%C3%AEd_Mihemed_Sed%C3%AEq).jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Qesra_Kelat%C3%AA_li_gund%C3%AA_Nehriy%C3%AA_(Qesra_Sey%C3%AEd_Mihemed_Sed%C3%AEq).jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Qesra_Kelat%C3%AA_li_gund%C3%AA_Nehriy%C3%AA_(Qesra_Sey%C3%AEd_Mihemed_Sed%C3%AEq).jpg','coverMediaLicense','CC BY-SA 4.0','coverMediaAttribution','Unknown historical photographer / Wikimedia Commons','verifiedLocation','Nehri village, Şemdinli, Hakkari'),updated_at=now() where (metadata->>'legacyId')::int=3003;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Qesra_Kelat%C3%AA_li_gund%C3%AA_Nehriy%C3%AA_(Qesra_Sey%C3%AEd_Mihemed_Sed%C3%AEq).jpg?width=1600','https://commons.wikimedia.org/wiki/File:Qesra_Kelat%C3%AA_li_gund%C3%AA_Nehriy%C3%AA_(Qesra_Sey%C3%AEd_Mihemed_Sed%C3%AEq).jpg','Wikimedia Commons','CC BY-SA 4.0','Unknown historical photographer','Şemdinli Nehri köyündeki tarihi Kelat Sarayı',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Nehri village, Şemdinli, Hakkari','historicalImage',true) from public.tours t where (t.metadata->>'legacyId')::int=3003 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Qesra_Kelat%C3%AA_li_gund%C3%AA_Nehriy%C3%AA_(Qesra_Sey%C3%AEd_Mihemed_Sed%C3%AEq).jpg?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Zap_Nehri.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Zap_Nehri.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Zap_Nehri.jpg','coverMediaLicense','CC BY-SA 3.0','coverMediaAttribution','Caracas / Wikimedia Commons','verifiedLocation','Zap River, Hakkari Province'),updated_at=now() where (metadata->>'legacyId')::int=3004;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Zap_Nehri.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Zap_Nehri.jpg','Wikimedia Commons','CC BY-SA 3.0','Caracas','Hakkari Zap Nehri',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Zap River, Hakkari Province') from public.tours t where (t.metadata->>'legacyId')::int=3004 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Zap_Nehri.jpg?width=1600');

update public.tours set cover_image='https://commons.wikimedia.org/wiki/Special:Redirect/file/Agit_Kilisesi_(Nestorian_church),_village_G%C3%BCnde%C5%9F_near_%C3%87ukurca.jpg?width=1600',images=jsonb_build_array('https://commons.wikimedia.org/wiki/Special:Redirect/file/Agit_Kilisesi_(Nestorian_church),_village_G%C3%BCnde%C5%9F_near_%C3%87ukurca.jpg?width=1600'),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('coverMediaRepresentative',false,'coverMediaSourceUrl','https://commons.wikimedia.org/wiki/File:Agit_Kilisesi_(Nestorian_church),_village_G%C3%BCnde%C5%9F_near_%C3%87ukurca.jpg','coverMediaLicense','CC BY 2.0','coverMediaAttribution','Mar Sharb / Wikimedia Commons','verifiedLocation','Gündeş village near Çukurca, Hakkari'),updated_at=now() where (metadata->>'legacyId')::int=3005;
insert into public.catalog_media(id,tour_id,kind,external_url,source_url,source_name,license,attribution,alt_text,sort_order,is_cover,is_active,metadata)
select gen_random_uuid(),t.id,'IMAGE','https://commons.wikimedia.org/wiki/Special:Redirect/file/Agit_Kilisesi_(Nestorian_church),_village_G%C3%BCnde%C5%9F_near_%C3%87ukurca.jpg?width=1600','https://commons.wikimedia.org/wiki/File:Agit_Kilisesi_(Nestorian_church),_village_G%C3%BCnde%C5%9F_near_%C3%87ukurca.jpg','Wikimedia Commons','CC BY 2.0','Mar Sharb','Çukurca yakınındaki Gündeş köyü tarihi Agit Kilisesi',1,true,true,jsonb_build_object('representative',false,'verifiedLocation','Gündeş village near Çukurca, Hakkari') from public.tours t where (t.metadata->>'legacyId')::int=3005 and not exists(select 1 from public.catalog_media m where m.tour_id=t.id and m.external_url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Agit_Kilisesi_(Nestorian_church),_village_G%C3%BCnde%C5%9F_near_%C3%87ukurca.jpg?width=1600');

commit;
