import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type BookingEvent = "booking_created" | "booking_pending" | "booking_approved" | "booking_rejected" | "booking_completed" | "booking_cancelled";
type RentalDuration = "hourly" | "daily" | "monthly" | "longterm";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const CORS = { "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, content-type, x-client-ip, x-idempotency-key", "access-control-allow-methods": "GET,POST,PATCH,DELETE,OPTIONS" };

function json(body: unknown, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { ...CORS, "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } }); }
function clean(value: unknown, max: number): string { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
function required(value: unknown, field: string, max: number): string { const result=clean(value,max); if(!result) throw new Error(`INVALID_${field.toUpperCase()}`); return result; }
function numberValue(value: unknown, min: number, max: number): number | null { if(value===undefined||value===null||value==="")return null; const n=Number(value); if(!Number.isFinite(n)||n<min||n>max)throw new Error("INVALID_NUMBER"); return Math.round(n*100)/100; }
function integerValue(value: unknown,min:number,max:number):number|null{if(value===undefined||value===null||value==="")return null;const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw new Error("INVALID_INTEGER");return n;}
function emailValue(value: unknown): string | null { const email=clean(value,160).toLowerCase(); if(!email)return null; if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("INVALID_EMAIL"); return email; }
function dateValue(value: unknown): string | null { const raw=clean(value,64);if(!raw)return null;const d=new Date(raw);if(Number.isNaN(d.getTime()))throw new Error("INVALID_DATE");return d.toISOString(); }
function uuid(value: string): boolean { return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }
function money(value:number):number{return Math.round(value*100)/100;}
function serviceHeaders(extra:Record<string,string>={}){return{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,"content-type":"application/json",...extra};}
async function db(path:string,init:RequestInit={}):Promise<Response>{return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...serviceHeaders(),...(init.headers||{})},signal:init.signal||AbortSignal.timeout(10000)});}
async function sha256(value:string):Promise<string>{const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(digest)].map((b)=>b.toString(16).padStart(2,"0")).join("");}
async function consumeRateLimit(keyHash:string,scope:string,seconds:number,limit:number):Promise<boolean>{const res=await db("rpc/consume_rate_limit",{method:"POST",body:JSON.stringify({p_key_hash:keyHash,p_scope:scope,p_window_seconds:seconds,p_limit:limit})});if(!res.ok)throw new Error(`RATE_LIMIT_BACKEND_${res.status}`);return Boolean(await res.json());}

interface AdminIdentity{id:string;email:string;role:string} interface CustomerIdentity{id:string;email:string|null}
async function requireAdmin(request:Request):Promise<AdminIdentity>{const authorization=request.headers.get("authorization")||"";if(!/^Bearer\s+\S+/i.test(authorization))throw new Error("UNAUTHORIZED");const userRes=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SERVICE_KEY,authorization},signal:AbortSignal.timeout(8000)});if(!userRes.ok)throw new Error("UNAUTHORIZED");const user=await userRes.json();const userId=clean(user?.id,80);const email=clean(user?.email,160).toLowerCase();if(!userId||!email)throw new Error("UNAUTHORIZED");const adminRes=await db(`admin_users?user_id=eq.${encodeURIComponent(userId)}&is_active=eq.true&select=user_id,email,role&limit=1`);if(!adminRes.ok)throw new Error("ADMIN_LOOKUP_FAILED");const rows=await adminRes.json();if(!Array.isArray(rows)||!rows[0])throw new Error("FORBIDDEN");return{id:userId,email,role:String(rows[0].role||"support")};}
async function optionalCustomer(request:Request):Promise<CustomerIdentity|null>{const authorization=request.headers.get("authorization")||"";if(!/^Bearer\s+\S+/i.test(authorization))return null;try{const userRes=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SERVICE_KEY,authorization},signal:AbortSignal.timeout(8000)});if(!userRes.ok)return null;const user=await userRes.json();const id=clean(user?.id,80);if(!uuid(id))return null;const email=emailValue(user?.email);const profileRes=await fetch(`${SUPABASE_URL}/rest/v1/rpc/ensure_customer_profile`,{method:"POST",headers:{apikey:SERVICE_KEY,authorization,"content-type":"application/json"},body:"{}",signal:AbortSignal.timeout(8000)});if(!profileRes.ok)return null;const statusRes=await db(`customer_profiles?user_id=eq.${encodeURIComponent(id)}&select=status&limit=1`);if(!statusRes.ok)return null;const statusRows=await statusRes.json();if(String(statusRows?.[0]?.status||"ACTIVE")!=="ACTIVE")throw new Error("CUSTOMER_ACCOUNT_BLOCKED");return{id,email};}catch(error){if(error instanceof Error&&error.message==="CUSTOMER_ACCOUNT_BLOCKED")throw error;return null;}}

function toApi(row:any){const metadata=row.metadata&&typeof row.metadata==="object"?row.metadata:{};return{id:row.reference,type:row.booking_type,itemId:row.legacy_item_id||undefined,itemName:row.item_name,image:row.image||undefined,customerName:row.customer_name,customerEmail:row.customer_email||undefined,customerPhone:row.customer_phone,basePrice:row.base_price===null?undefined:Number(row.base_price),totalPrice:row.total_price===null?undefined:Number(row.total_price),currency:row.currency,personCount:row.person_count??undefined,startDate:row.start_at||undefined,endDate:row.end_at||undefined,days:row.days??undefined,rentalHours:row.rental_hours??undefined,withDriver:Boolean(row.with_driver),pickupBranchId:row.pickup_branch_id||undefined,pickupLocation:row.pickup_location||undefined,dropoffLocation:row.dropoff_location||undefined,rentalDuration:row.rental_duration||undefined,selectedExtraIds:Array.isArray(metadata.selected_extra_ids)?metadata.selected_extra_ids:undefined,campaignId:row.campaign_id||undefined,notes:row.notes||undefined,paymentMethod:row.payment_method,paymentStatus:row.payment_status,externalPaymentReference:row.external_payment_reference||undefined,source:["WEB","ADMIN","PHONE"].includes(row.source)?row.source:"WEB",status:row.status,createdAt:row.created_at,updatedAt:row.updated_at};}
async function findByReference(reference:string):Promise<any|null>{const res=await db(`bookings?reference=eq.${encodeURIComponent(reference)}&deleted_at=is.null&select=*&limit=1`);if(!res.ok)throw new Error(`BOOKING_READ_${res.status}`);const rows=await res.json();return Array.isArray(rows)&&rows[0]?rows[0]:null;}
async function notify(internalId:string,event:BookingEvent){try{const res=await fetch(`${SUPABASE_URL}/functions/v1/booking-notify`,{method:"POST",headers:{authorization:`Bearer ${SERVICE_KEY}`,"content-type":"application/json"},body:JSON.stringify({bookingId:internalId,event}),signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error(`NOTIFY_${res.status}`);return await res.json();}catch{return{ok:false,event,bookingId:internalId,email:{state:"failed",reason:"NOTIFICATION_DISPATCH_FAILED"},sms:{state:"failed",reason:"NOTIFICATION_DISPATCH_FAILED"},adminEmail:{state:"failed",reason:"NOTIFICATION_DISPATCH_FAILED"}};}}
function eventForStatus(status:string):BookingEvent{if(status==="APPROVED")return"booking_approved";if(status==="REJECTED")return"booking_rejected";if(status==="COMPLETED")return"booking_completed";if(status==="CANCELLED")return"booking_cancelled";return"booking_pending";}
async function audit(admin:AdminIdentity,action:string,row:any,beforeData?:any,afterData?:any){await db("audit_logs",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({actor_user_id:admin.id,actor_email:admin.email,action,entity_type:"booking",entity_id:row.reference,before_data:beforeData||null,after_data:afterData||null})}).catch(()=>undefined);}

async function runtimeAllowsBookings():Promise<boolean>{const res=await db("site_config?key=eq.runtime_controls&select=value&limit=1");if(!res.ok)return true;const rows=await res.json();const value=Array.isArray(rows)&&rows[0]?.value&&typeof rows[0].value==="object"?rows[0].value:{};return value.maintenanceMode!==true&&value.readOnlyMode!==true&&value.allowBookings!==false;}
async function getSiteSettings():Promise<any>{const res=await db("site_config?key=eq.site_settings&select=value&limit=1");if(!res.ok)return{};const rows=await res.json();return Array.isArray(rows)&&rows[0]?.value&&typeof rows[0].value==="object"?rows[0].value:{};}
async function firstRow(path:string):Promise<any|null>{const res=await db(path);if(!res.ok)return null;const rows=await res.json();return Array.isArray(rows)?rows[0]||null:null;}
async function getVehicleByIdentifier(identifier:string,category:"RENTAL"|"SALE"):Promise<any|null>{const select="id,stock_code,brand,model,price,rental_price_daily,rental_price_hourly,hourly_rental_enabled,minimum_rental_hours,hourly_mileage_limit,branch_id,availability_status,publication_status,metadata";const base=`category=eq.${category}&is_active=eq.true&select=${select}&limit=1`;if(uuid(identifier))return firstRow(`vehicles?id=eq.${encodeURIComponent(identifier)}&${base}`);const legacy=await firstRow(`vehicles?metadata->>legacyId=eq.${encodeURIComponent(identifier)}&${base}`);if(legacy)return legacy;return firstRow(`vehicles?stock_code=eq.${encodeURIComponent(identifier)}&${base}`);}
async function getRentalVehicle(identifier:string):Promise<any>{const v=await getVehicleByIdentifier(identifier,"RENTAL");if(!v||v.publication_status!=="PUBLISHED"||v.availability_status==="UNAVAILABLE")throw new Error("INVALID_RENTAL_VEHICLE");return v;}
async function getTourByIdentifier(identifier:string):Promise<any|null>{const select="id,title,publication_status,is_active,metadata";if(uuid(identifier))return firstRow(`tours?id=eq.${encodeURIComponent(identifier)}&is_active=eq.true&select=${select}&limit=1`);const legacy=await firstRow(`tours?metadata->>legacyId=eq.${encodeURIComponent(identifier)}&is_active=eq.true&select=${select}&limit=1`);return legacy;}
async function hasApprovedOverlap(vehicleId:string,start:string,end:string,excludeId?:string):Promise<boolean>{const path=`bookings?vehicle_id=eq.${encodeURIComponent(vehicleId)}&booking_type=eq.RENTAL&status=eq.APPROVED&deleted_at=is.null&start_at=lt.${encodeURIComponent(end)}&end_at=gt.${encodeURIComponent(start)}&select=id&limit=2`;const res=await db(path);if(!res.ok)throw new Error("AVAILABILITY_CHECK_FAILED");const rows=await res.json();return Array.isArray(rows)&&rows.some((row:any)=>!excludeId||String(row.id)!==excludeId);}
function driverOption(vehicle:any):"WITH_DRIVER"|"WITHOUT_DRIVER"|"BOTH"{const value=String(vehicle?.metadata?.driverOption||"BOTH");return value==="WITH_DRIVER"||value==="WITHOUT_DRIVER"?value:"BOTH";}
function rentalDuration(value:unknown):RentalDuration{const cleanValue=clean(value,20);return cleanValue==="hourly"||cleanValue==="monthly"||cleanValue==="longterm"?cleanValue:"daily";}
function rentalDays(start:string,end:string):number{const a=new Date(start).getTime(),b=new Date(end).getTime();if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a)throw new Error("INVALID_RENTAL_DATES");const days=Math.ceil((b-a)/86_400_000);if(days<1||days>3650)throw new Error("INVALID_RENTAL_DATES");return days;}
function rentalHours(start:string,end:string,minimum:number):number{const a=new Date(start).getTime(),b=new Date(end).getTime();if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a)throw new Error("INVALID_HOURLY_RENTAL");const raw=(b-a)/3_600_000;const hours=Math.ceil(raw);if(raw<=0||hours<minimum||hours>23)throw new Error("INVALID_HOURLY_RENTAL");return hours;}
function selectedExtraIds(body:any,withDriver:boolean):string[]{const raw:unknown[]=Array.isArray(body?.selectedExtraIds)?body.selectedExtraIds:[];const normalized:string[]=raw.map((v:unknown)=>clean(v,64)).filter((v:string)=>/^[a-z0-9][a-z0-9_-]{0,63}$/i.test(v));const set=new Set<string>(normalized);if(withDriver)set.add("driver");else set.delete("driver");return[...set].slice(0,30);}
async function activeVehicleCampaign(vehicleId:string):Promise<any|null>{const res=await db(`campaigns?target_type=eq.VEHICLE&target_id=eq.${encodeURIComponent(vehicleId)}&is_active=eq.true&publication_status=eq.PUBLISHED&select=*&order=sort_order.asc,created_at.desc`);if(!res.ok)return null;const rows=await res.json();const now=Date.now();return(Array.isArray(rows)?rows:[]).find((c:any)=>(!c.starts_at||new Date(c.starts_at).getTime()<=now)&&(!c.ends_at||new Date(c.ends_at).getTime()>now))||null;}
function normalizeLocation(value:string):string{return value.replace(/\s+/g," ").trim().toLocaleLowerCase("tr-TR");}
function routeFuel(settings:any,pickup:string,dropoff:string):{distance:number;fuel:number}{const from=normalizeLocation(pickup),to=normalizeLocation(dropoff);if(!from||!to||from===to)return{distance:0,fuel:0};const routes=Array.isArray(settings.rentalRoutePricing)?settings.rentalRoutePricing:[];const route=routes.find((r:any)=>r&&r.enabled!==false&&Number(r.distanceKm||0)>0&&((normalizeLocation(String(r.from||""))===from&&normalizeLocation(String(r.to||""))===to)||(normalizeLocation(String(r.from||""))===to&&normalizeLocation(String(r.to||""))===from)));if(!route)return{distance:0,fuel:0};const distance=Math.max(0,Number(route.distanceKm||0));const fuelPrice=Math.max(0,Number(settings.rentalFuelPricePerLiter??85));const consumption=Math.max(0,Number(settings.rentalAverageConsumptionPer100Km??8.5));return{distance,fuel:Math.round(distance*consumption/100*fuelPrice)};}
function extraCost(extra:any,duration:RentalDuration,units:number):number{const flat=Math.max(0,Number(extra?.flatPrice||0));if(duration==="hourly"){const hourly=Number(extra?.pricePerHour);const derived=Number.isFinite(hourly)&&hourly>=0?hourly:Math.max(0,Number(extra?.pricePerDay||0))/8;return money(hourly>=0?hourly*units+flat:derived*units+flat);}return money(Math.max(0,Number(extra?.pricePerDay||0))*units+flat);}
async function authoritativeRental(body:any,vehicle:any,start:string,end:string,withDriver:boolean){const option=driverOption(vehicle);if(withDriver&&option==="WITHOUT_DRIVER")throw new Error("DRIVER_OPTION_NOT_ALLOWED");if(!withDriver&&option==="WITH_DRIVER")throw new Error("DRIVER_OPTION_NOT_ALLOWED");if(await hasApprovedOverlap(vehicle.id,start,end))throw new Error("VEHICLE_UNAVAILABLE");const duration=rentalDuration(body?.rentalDuration);const settings=await getSiteSettings();const extras=Array.isArray(settings.rentalExtras)?settings.rentalExtras:[];const requested=selectedExtraIds(body,withDriver);const validExtras=extras.filter((e:any)=>e&&e.enabled!==false&&requested.includes(String(e.id||"")));if(withDriver&&!validExtras.some((e:any)=>e.id==="driver"))throw new Error("DRIVER_OPTION_NOT_ALLOWED");const campaign=await activeVehicleCampaign(vehicle.id);const pickup=clean(body?.pickupLocation,240);const dropoff=clean(body?.dropoffLocation,240)||pickup;const route=routeFuel(settings,pickup,dropoff);
  if(duration==="hourly"){
    if(vehicle.hourly_rental_enabled!==true||Number(vehicle.rental_price_hourly||0)<=0)throw new Error("HOURLY_RENTAL_NOT_ALLOWED");const minimum=Math.max(1,Math.min(23,Number(vehicle.minimum_rental_hours||1)));const hours=rentalHours(start,end,minimum);const normalHourly=Math.max(0,Number(vehicle.rental_price_hourly||0));let hourly=normalHourly;const campaignHourly=Number(campaign?.metadata?.hourly_price||0);if(campaignHourly>0)hourly=campaignHourly;else if(Number(campaign?.discount_percent)>0)hourly=money(normalHourly*(100-Number(campaign.discount_percent))/100);const discountAmount=Math.max(0,money((normalHourly-hourly)*hours));const extrasTotal=money(validExtras.reduce((sum:number,e:any)=>sum+extraCost(e,"hourly",hours),0));const baseTotal=money(hourly*hours);const total=money(baseTotal+extrasTotal+route.fuel);return{duration,hours,days:null,unitPrice:hourly,baseTotal,total,extrasTotal,requested:validExtras.map((e:any)=>String(e.id)),campaign,discountAmount,route};
  }
  const days=rentalDays(start,end);const normalDaily=Math.max(0,Number(vehicle.rental_price_daily??vehicle.price??0));let daily=normalDaily;if(campaign){if(Number(campaign.new_price)>0)daily=Number(campaign.new_price);else if(Number(campaign.discount_percent)>0)daily=money(normalDaily*(100-Number(campaign.discount_percent))/100);}const discountAmount=Math.max(0,money((normalDaily-daily)*days));const extrasTotal=money(validExtras.reduce((sum:number,e:any)=>sum+extraCost(e,duration,days),0));const baseTotal=money(daily*days);const total=money(baseTotal+extrasTotal+route.fuel);return{duration,hours:null,days,unitPrice:daily,baseTotal,total,extrasTotal,requested:validExtras.map((e:any)=>String(e.id)),campaign,discountAmount,route};
}

async function createBooking(request:Request):Promise<Response>{const length=Number(request.headers.get("content-length")||0);if(length>32768)return json({ok:false,code:"PAYLOAD_TOO_LARGE"},413);let body:any;try{body=await request.json();}catch{return json({ok:false,code:"INVALID_JSON"},400);}if(clean(body?.website,200))return json({ok:true,accepted:true},202);try{if(!(await runtimeAllowsBookings()))return json({ok:false,code:"BOOKINGS_DISABLED",message:"Yeni rezervasyon işlemleri şu anda geçici olarak kapalı."},503);const type=required(body?.type,"type",30);if(!["RENTAL","TOUR","SALE_INQUIRY","APPOINTMENT"].includes(type))throw new Error("INVALID_TYPE");const itemName=required(body?.itemName,"itemName",240),customerName=required(body?.customerName,"customerName",160),customerPhone=required(body?.customerPhone,"customerPhone",40);if(!/[0-9]/.test(customerPhone)||customerPhone.replace(/\D/g,"").length<7)throw new Error("INVALID_PHONE");const customer=await optionalCustomer(request);const enteredCustomerEmail=emailValue(body?.customerEmail);const customerEmail=customer?.email||enteredCustomerEmail;const idempotencyKey=clean(body?.idempotencyKey||request.headers.get("x-idempotency-key"),120)||crypto.randomUUID();const ip=clean(request.headers.get("x-client-ip")||request.headers.get("x-forwarded-for")?.split(",")[0]||request.headers.get("cf-connecting-ip")||"unknown",100);const ua=clean(request.headers.get("user-agent"),300);const networkHash=await sha256(`${ip}|${ua}`);const contactHash=await sha256(`${customerPhone}|${customerEmail||""}`);if(!(await consumeRateLimit(networkHash,"booking_network_minute",60,8))||!(await consumeRateLimit(networkHash,"booking_network_hour",3600,40))||!(await consumeRateLimit(contactHash,"booking_contact_hour",3600,12)))return json({ok:false,code:"RATE_LIMITED",message:"Çok fazla istek gönderildi. Lütfen daha sonra tekrar deneyin."},429);const duplicateRes=await db(`bookings?idempotency_key=eq.${encodeURIComponent(idempotencyKey)}&select=*&limit=1`);if(duplicateRes.ok){const dup=await duplicateRes.json();if(Array.isArray(dup)&&dup[0])return json({ok:true,booking:toApi(dup[0]),duplicate:true});}const itemId=clean(body?.itemId===undefined?"":String(body.itemId),128);const currency=clean(body?.currency,10)||"TRY";if(!["TRY","EUR","USD","CHF"].includes(currency))throw new Error("INVALID_CURRENCY");const paymentMethod=clean(body?.paymentMethod,20)||"NONE";if(!["NONE","CARD","EFT","OFFICE"].includes(paymentMethod))throw new Error("INVALID_PAYMENT_METHOD");const paymentStatus=paymentMethod==="NONE"?"NOT_REQUIRED":"PENDING";
    let vehicleId:string|null=null,tourId:string|null=null,startAt=dateValue(body?.startDate),endAt=dateValue(body?.endDate),basePrice=numberValue(body?.basePrice,0,50000000),totalPrice=numberValue(body?.totalPrice,0,50000000),days=integerValue(body?.days,1,3650),rentalHoursValue=integerValue(body?.rentalHours,1,23),rentalDurationValue=clean(body?.rentalDuration,40)||null,campaignId:string|null=null,discountAmount=0,metadata:any={};let pickupBranchId=uuid(clean(body?.pickupBranchId,80))?clean(body?.pickupBranchId,80):null;
    if(type==="RENTAL"){if(!itemId)throw new Error("INVALID_RENTAL_VEHICLE");const vehicle=await getRentalVehicle(itemId);vehicleId=String(vehicle.id);if(!startAt||!endAt)throw new Error(rentalDurationValue==="hourly"?"INVALID_HOURLY_RENTAL":"INVALID_RENTAL_DATES");const withDriver=Boolean(body?.withDriver);const calc=await authoritativeRental(body,vehicle,startAt,endAt,withDriver);days=calc.days;rentalHoursValue=calc.hours;rentalDurationValue=calc.duration;basePrice=calc.unitPrice;totalPrice=calc.total;campaignId=calc.campaign?.id||null;discountAmount=calc.discountAmount;pickupBranchId=pickupBranchId||(uuid(String(vehicle.branch_id||""))?String(vehicle.branch_id):null);metadata={selected_extra_ids:calc.requested,price_breakdown:{rental_duration:calc.duration,unit_price:calc.unitPrice,days:calc.days,rental_hours:calc.hours,base_total:calc.baseTotal,extras_total:calc.extrasTotal,route_distance_km:calc.route.distance,route_fuel_total:calc.route.fuel},server_calculated:true,resolved_vehicle_id:vehicleId};}
    else if(type==="SALE_INQUIRY"){if(itemId){const vehicle=await getVehicleByIdentifier(itemId,"SALE");if(vehicle)vehicleId=String(vehicle.id);}}
    else if(type==="TOUR"&&itemId){const tour=await getTourByIdentifier(itemId);if(tour)tourId=String(tour.id);}
    const row={idempotency_key:idempotencyKey,booking_type:type,vehicle_id:vehicleId,tour_id:tourId,legacy_item_id:itemId||null,item_name:itemName,image:clean(body?.image,2048)||null,customer_name:customerName,customer_email:customerEmail,customer_phone:customerPhone,customer_user_id:customer?.id||null,customer_linked_at:customer?new Date().toISOString():null,start_at:startAt,end_at:endAt,pickup_branch_id:pickupBranchId,pickup_location:clean(body?.pickupLocation,240)||null,dropoff_location:clean(body?.dropoffLocation,240)||null,person_count:integerValue(body?.personCount,1,100),with_driver:Boolean(body?.withDriver),base_price:basePrice,total_price:totalPrice,currency,days,rental_hours:rentalHoursValue,rental_duration:rentalDurationValue,payment_method:paymentMethod,payment_status:paymentStatus,status:"PENDING",source:"WEB",notes:clean(body?.notes,4000)||null,customer_locale:clean(body?.customerLocale||body?.locale,10)||"tr",campaign_id:campaignId,discount_amount:discountAmount,metadata};const insertRes=await db("bookings?select=*",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});if(!insertRes.ok){const detail=(await insertRes.text()).slice(0,600);console.error("Booking insert failed",insertRes.status,detail);if(detail.includes("bookings_no_approved_rental_overlap")||detail.includes("23P01"))return json({ok:false,code:"VEHICLE_UNAVAILABLE",message:"Bu araç seçilen zaman aralığında artık müsait değil."},409);return json({ok:false,code:"BOOKING_CREATE_FAILED",message:"Talep kaydı şu anda oluşturulamadı. Lütfen tekrar deneyin."},500);}const rows=await insertRes.json();const saved=rows[0];const notification=await notify(saved.id,"booking_created");return json({ok:true,booking:toApi(saved),notification},201);
  }catch(error){const code=error instanceof Error?error.message:"INVALID_BOOKING";const status=code==="VEHICLE_UNAVAILABLE"?409:code==="CUSTOMER_ACCOUNT_BLOCKED"?403:code==="BOOKINGS_DISABLED"?503:code==="HOURLY_RENTAL_NOT_ALLOWED"||code==="INVALID_HOURLY_RENTAL"||code.startsWith("INVALID_")||code==="DRIVER_OPTION_NOT_ALLOWED"?400:500;const message=code==="VEHICLE_UNAVAILABLE"?"Bu araç seçilen zaman aralığında artık müsait değil.":code==="DRIVER_OPTION_NOT_ALLOWED"?"Bu araç seçilen sürücü tercihiyle sunulmuyor.":code==="INVALID_RENTAL_VEHICLE"?"Seçtiğiniz araç bulunamadı veya şu anda rezervasyona açık değil.":code==="INVALID_RENTAL_DATES"?"Teslim alma ve iade tarihlerini kontrol edin.":code==="INVALID_HOURLY_RENTAL"?"Saatlik kiralama tarih ve saatlerini kontrol edin.":code==="HOURLY_RENTAL_NOT_ALLOWED"?"Bu araç için saatlik kiralama kullanılamıyor.":code==="INVALID_PHONE"?"Telefon numarasını kontrol edin.":code==="CUSTOMER_ACCOUNT_BLOCKED"?"Bu müşteri hesabı yönetim tarafından işleme kapatılmış.":status===400?"Talep bilgilerini kontrol edin.":"Talep şu anda kaydedilemedi.";return json({ok:false,code,message},status);}}

async function listBookings(request:Request):Promise<Response>{try{await requireAdmin(request);const res=await db("bookings?deleted_at=is.null&select=*&order=created_at.desc&limit=500");if(!res.ok)throw new Error("BOOKING_LIST_FAILED");const rows=await res.json();return json({ok:true,bookings:rows.map(toApi)});}catch(error){const code=error instanceof Error?error.message:"UNAUTHORIZED";return json({ok:false,code},code==="FORBIDDEN"?403:code==="UNAUTHORIZED"?401:500);}}
async function patchBooking(request:Request):Promise<Response>{let body:any;try{body=await request.json();}catch{return json({ok:false,code:"INVALID_JSON"},400);}try{const admin=await requireAdmin(request);const reference=required(body?.id,"id",80);const existing=await findByReference(reference);if(!existing)return json({ok:false,code:"BOOKING_NOT_FOUND"},404);const operation=clean(body?.operation,20);let update:Record<string,unknown>={};let event:BookingEvent|null=null;if(operation==="status"){const status=required(body?.status,"status",30);if(!["PENDING","APPROVED","REJECTED","COMPLETED","CANCELLED"].includes(status))throw new Error("INVALID_STATUS");if(status==="APPROVED"&&existing.booking_type==="RENTAL"&&existing.vehicle_id&&existing.start_at&&existing.end_at&&await hasApprovedOverlap(existing.vehicle_id,existing.start_at,existing.end_at,existing.id))return json({ok:false,code:"VEHICLE_UNAVAILABLE",message:"Aynı araç için bu zaman aralığında başka bir onaylı rezervasyon var."},409);update={status};event=eventForStatus(status);}else if(operation==="payment"){const paymentStatus=required(body?.paymentStatus,"paymentStatus",30);if(!["NOT_REQUIRED","PENDING","PAID","FAILED","REFUNDED"].includes(paymentStatus))throw new Error("INVALID_PAYMENT_STATUS");update={payment_status:paymentStatus,external_payment_reference:clean(body?.externalPaymentReference,200)||null};}else throw new Error("INVALID_OPERATION");const res=await db(`bookings?id=eq.${encodeURIComponent(existing.id)}&select=*`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(update)});if(!res.ok)throw new Error("BOOKING_UPDATE_FAILED");const rows=await res.json();const saved=rows[0];await audit(admin,`booking_${operation}_updated`,saved,existing,saved);const notification=event?await notify(saved.id,event):undefined;return json({ok:true,booking:toApi(saved),notification});}catch(error){const code=error instanceof Error?error.message:"BOOKING_UPDATE_FAILED";const status=code==="UNAUTHORIZED"?401:code==="FORBIDDEN"?403:code.startsWith("INVALID_")?400:500;return json({ok:false,code},status);}}
async function deleteBooking(request:Request):Promise<Response>{let body:any;try{body=await request.json();}catch{return json({ok:false,code:"INVALID_JSON"},400);}try{const admin=await requireAdmin(request);if(!["owner","admin"].includes(admin.role))return json({ok:false,code:"FORBIDDEN"},403);const reference=required(body?.id,"id",80);const existing=await findByReference(reference);if(!existing)return json({ok:false,code:"BOOKING_NOT_FOUND"},404);const now=new Date().toISOString();const res=await db(`bookings?id=eq.${encodeURIComponent(existing.id)}&select=*`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({deleted_at:now,deleted_by:admin.id,status:"CANCELLED"})});if(!res.ok)throw new Error("BOOKING_ARCHIVE_FAILED");const rows=await res.json();await audit(admin,"booking_archived",rows[0]||existing,existing,rows[0]||null);await notify(existing.id,"booking_cancelled");return json({ok:true,archived:true});}catch(error){const code=error instanceof Error?error.message:"BOOKING_ARCHIVE_FAILED";return json({ok:false,code},code==="UNAUTHORIZED"?401:code==="FORBIDDEN"?403:500);}}

Deno.serve(async(request)=>{if(request.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(!SUPABASE_URL||!SERVICE_KEY)return json({ok:false,code:"SERVER_CONFIG_MISSING"},503);if(request.method==="POST")return createBooking(request);if(request.method==="GET")return listBookings(request);if(request.method==="PATCH")return patchBooking(request);if(request.method==="DELETE")return deleteBooking(request);return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);});
