import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { PaymentSettings, PaymentSettingsService } from '../../services/payment-settings.service';
import { PaymentService } from '../../services/payment.service';
import { ToastService } from '../../services/toast.service';

@Component({selector:'app-admin-payment-settings',standalone:true,imports:[CommonModule,FormsModule],template:`
<main class="page"><header class="head"><div><p>Ödeme yönetimi</p><h1>Ödeme ve Depozito</h1><span>Müşteriye hangi ödeme yöntemlerinin sunulacağını, depozito kuralını ve havale bilgilerini yönetin.</span></div><div class="actions"><button type="button" class="secondary" (click)="reload()" [disabled]="loading()||saving()">Yenile</button><button type="button" class="primary" (click)="save()" [disabled]="loading()||saving()">{{saving()?'Kaydediliyor…':'Kaydet ve Uygula'}}</button></div></header>
<section class="status"><div><span>Sunucu entegrasyonu</span><strong [class.ok]="integrationConfigured()">{{integrationConfigured()?'Hazır':'Sağlayıcı anahtarı bekleniyor'}}</strong></div><div><span>Kartla ödeme</span><strong [class.ok]="cardOperational()">{{cardOperational()?'Aktif':'Pasif'}}</strong></div><p>Kart ödeme anahtarları güvenlik nedeniyle bu panelde tutulmaz. PayTR Merchant ID, Merchant Key ve Merchant Salt yalnız sunucu ortam değişkenlerinde saklanır.</p></section>
<form (submit)="$event.preventDefault();save()" class="form">
<section class="card"><h2>Ödeme Sağlayıcısı</h2><div class="grid"><label><span>Sağlayıcı</span><select [(ngModel)]="form.provider" name="provider"><option value="PAYTR">PayTR</option><option value="GENERIC_HOSTED">Diğer güvenli ödeme sayfası</option><option value="NONE">Online kart kapalı</option></select></label><label class="toggle"><input type="checkbox" [(ngModel)]="form.testMode" name="testMode"/><span>Test modu</span></label></div><div class="method-grid"><label><input type="checkbox" [(ngModel)]="form.cardEnabled" name="cardEnabled"/><span><strong>Kart</strong><small>Sağlayıcı anahtarları doğrulanınca çalışır</small></span></label><label><input type="checkbox" [(ngModel)]="form.eftEnabled" name="eftEnabled"/><span><strong>Havale / EFT</strong><small>Banka bilgileri müşteriye gösterilebilir</small></span></label><label><input type="checkbox" [(ngModel)]="form.officeEnabled" name="officeEnabled"/><span><strong>Teslimde / Ofiste</strong><small>Araç tesliminde ödeme seçeneği</small></span></label></div></section>
<section class="card"><h2>Depozito Kuralı</h2><p class="hint">Rezervasyonun tamamını online tahsil etmek zorunda değilsiniz. İsterseniz sabit veya yüzdelik ön ödeme alabilirsiniz.</p><div class="grid"><label><span>Depozito tipi</span><select [(ngModel)]="form.depositMode" name="depositMode"><option value="NONE">Online depozito yok</option><option value="FIXED">Sabit tutar</option><option value="PERCENT">Toplamın yüzdesi</option></select></label><label><span>{{form.depositMode==='PERCENT'?'Yüzde':'Tutar'}}</span><input type="number" min="0" [max]="form.depositMode==='PERCENT'?100:null" [(ngModel)]="form.depositValue" name="depositValue" [disabled]="form.depositMode==='NONE'"/></label><label><span>Para birimi</span><select [(ngModel)]="form.currency" name="currency"><option value="TRY">TRY</option><option value="EUR">EUR</option><option value="USD">USD</option><option value="CHF">CHF</option></select></label></div></section>
<section class="card"><h2>Havale / EFT Bilgileri</h2><div class="grid"><label><span>Banka</span><input [(ngModel)]="form.bankName" name="bankName"/></label><label><span>Hesap sahibi</span><input [(ngModel)]="form.accountHolder" name="accountHolder"/></label><label class="wide"><span>IBAN</span><input [(ngModel)]="form.iban" name="iban" autocomplete="off"/></label></div></section>
<section class="card"><h2>Müşteriye Gösterilecek Not</h2><label><textarea rows="4" [(ngModel)]="form.customerNote" name="customerNote"></textarea></label></section>
</form></main>`,styles:[`:host{display:block}.page{min-height:100%;background:#f8fafc;padding:1rem;color:#0f172a}.head{max-width:1120px;margin:auto;display:flex;flex-direction:column;gap:1rem}.head p{margin:0;color:#2563eb;font-size:.62rem;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.head h1{margin:.2rem 0;font-size:1.5rem}.head span{color:#64748b;font-size:.75rem}.actions{display:flex;gap:.5rem}.actions button{min-height:44px;border-radius:12px;padding:0 1rem;font-weight:900}.primary{border:0;background:#2563eb;color:#fff}.secondary{border:1px solid #cbd5e1;background:#fff;color:#334155}.status,.form{max-width:1120px;margin:1rem auto 0}.status{display:grid;gap:.65rem;border:1px solid #dbe4ef;border-radius:18px;background:#fff;padding:1rem}.status div{display:flex;justify-content:space-between;gap:1rem}.status span{color:#64748b;font-size:.72rem}.status strong{color:#b45309}.status strong.ok{color:#047857}.status p,.hint{margin:0;color:#64748b;font-size:.7rem;line-height:1.55}.form{display:grid;gap:1rem}.card{border:1px solid #e2e8f0;border-radius:18px;background:#fff;padding:1rem}.card h2{margin:0;font-size:1rem}.grid,.method-grid{display:grid;gap:.7rem;margin-top:.8rem}label{display:grid;gap:.3rem}label>span{color:#475569;font-size:.63rem;font-weight:900;text-transform:uppercase}input,select,textarea{width:100%;min-height:44px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;padding:.65rem;font:inherit;font-size:.76rem}.toggle{display:flex;align-items:center;gap:.5rem}.toggle input,.method-grid input{width:20px;min-height:20px}.method-grid label{display:flex;align-items:center;gap:.6rem;border:1px solid #e2e8f0;border-radius:12px;padding:.75rem}.method-grid label span{display:grid;gap:.15rem;text-transform:none}.method-grid strong{font-size:.75rem}.method-grid small{color:#64748b;font-size:.62rem}.wide{grid-column:1/-1}@media(min-width:760px){.page{padding:1.5rem}.head{flex-direction:row;align-items:end;justify-content:space-between}.grid{grid-template-columns:repeat(3,minmax(0,1fr))}.method-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}`]} )
export class AdminPaymentSettingsComponent implements OnInit{
 private readonly paymentSettings=inject(PaymentSettingsService);readonly paymentService=inject(PaymentService);private readonly toast=inject(ToastService);readonly loading=this.paymentSettings.loading;readonly saving=signal(false);form:PaymentSettings={provider:'PAYTR',cardEnabled:false,eftEnabled:true,officeEnabled:true,depositMode:'NONE',depositValue:0,currency:'TRY',bankName:'',iban:'',accountHolder:'',customerNote:'',testMode:true};
 async ngOnInit(){await this.reload(false);}
 async reload(showToast=true){try{await Promise.all([this.paymentSettings.refreshAdmin(),this.paymentService.refreshIntegrationStatus()]);this.form=structuredClone(this.paymentSettings.settings());if(showToast)this.toast.show('Ödeme ayarları yenilendi.','success');}catch(e){this.toast.show(this.message(e),'error');}}
 integrationConfigured(){return this.paymentService.paymentStatus().configured;}
 cardOperational(){return this.form.cardEnabled&&this.paymentService.cardReady();}
 async save(){if(this.saving())return;this.saving.set(true);try{await this.paymentSettings.save(this.form);this.form=structuredClone(this.paymentSettings.settings());await this.paymentService.refreshIntegrationStatus();this.toast.show('Ödeme ayarları kaydedildi.','success');}catch(e){this.toast.show(this.message(e),'error');}finally{this.saving.set(false);}}
 private message(e:unknown){return e instanceof Error?e.message:'Ödeme ayarları kaydedilemedi.';}
}
