import { CommonModule, Location } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AdminAccessService, AdminArea } from '../../services/admin-access.service';
import { AdminReservationsComponent } from './admin-reservations.component';
import { AdminPartnerRequestsComponent } from './admin-partner-requests.component';
import { AdminBranchPartnerRequestsComponent } from './admin-branch-partner-requests.component';
import { AdminFeedbackComponent } from './admin-feedback.component';
import { AdminSubscribersComponent } from './admin-subscribers.component';
import { AdminBranchesComponent } from './admin-branches.component';
import { AdminFleetOperationsComponent } from './admin-fleet-operations.component';
import { AdminBranchIdentitiesV171Component } from './admin-branch-identities-v171.component';

type OperationsSection = 'reservations'|'fleet-control'|'vehicles'|'branches-requests'|'messages'|'newsletter'|'branches'|'branch-identities';
interface OperationsTab { id:OperationsSection; label:string; area:AdminArea; }

@Component({selector:'app-admin-operations-hub',standalone:true,imports:[CommonModule,AdminReservationsComponent,AdminPartnerRequestsComponent,AdminBranchPartnerRequestsComponent,AdminFeedbackComponent,AdminSubscribersComponent,AdminBranchesComponent,AdminFleetOperationsComponent,AdminBranchIdentitiesV171Component],template:`
<div class="workspace"><header class="workspace-head"><div class="head-row"><button type="button" class="back" (click)="goBack()" aria-label="Önceki sayfaya dön">←</button><div><p>Müşteri ve Filo İşlemleri</p><h1>Operasyonlar</h1><span>Rezervasyonları, kiralık araç kontrolünü, başvuruları, mesajları, bülteni, şubeleri ve doğrulanmış işletme kimliklerini tek alanda yönetin.</span></div></div><nav class="tabs" aria-label="Operasyon bölümleri">@for(tab of visibleTabs();track tab.id){<button type="button" [class.active]="active()===tab.id" (click)="select(tab.id)">{{tab.label}}</button>}</nav></header><main class="content">@if(ready()){@switch(active()){@case('fleet-control'){<app-admin-fleet-operations/>}@case('vehicles'){<app-admin-partner-requests/>}@case('branches-requests'){<app-admin-branch-partner-requests/>}@case('messages'){<app-admin-feedback/>}@case('newsletter'){<app-admin-subscribers/>}@case('branches'){<app-admin-branches/>}@case('branch-identities'){<app-admin-branch-identities-v171/>}@default{<app-admin-reservations/>}}} @else {<div class="p-8 text-center text-sm font-bold text-slate-500">Yönetim alanı hazırlanıyor…</div>}</main></div>`,styles:[`:host{display:block;min-height:100vh;background:#f8fafc}.workspace{min-height:100vh}.workspace-head{position:sticky;top:0;z-index:80;border-bottom:1px solid #e2e8f0;background:rgba(248,250,252,.97);padding:.8rem 3.7rem .7rem 1rem;box-shadow:0 6px 20px rgba(15,23,42,.05);backdrop-filter:blur(12px)}.head-row{display:flex;width:min(100%,1240px);margin:auto;align-items:flex-start;gap:.7rem}.back{display:grid;width:42px;height:42px;flex:none;place-items:center;border:1px solid #dbe4ef;border-radius:12px;background:#fff;color:#0f172a;font-size:1.15rem;font-weight:950}.head-row p{margin:0;color:#2563eb;font-size:.58rem;font-weight:950;letter-spacing:.14em;text-transform:uppercase}.head-row h1{margin:.12rem 0 0;font-size:1.4rem;font-weight:950;color:#0f172a}.head-row span{display:block;margin-top:.2rem;color:#64748b;font-size:.68rem}.tabs{display:flex;width:min(100%,1240px);margin:.65rem auto 0;gap:.4rem;overflow-x:auto}.tabs button{min-height:42px;flex:0 0 auto;border:1px solid #e2e8f0;border-radius:12px;background:#fff;padding:0 .85rem;color:#475569;font-size:.66rem;font-weight:900}.tabs button.active{border-color:#2563eb;background:#eff6ff;color:#1d4ed8}.content{min-height:70vh}:host ::ng-deep .content .sticky.top-16,:host ::ng-deep .content .sticky.top-0{position:static!important;top:auto!important}@media(max-width:520px){.workspace-head{padding-left:.7rem;padding-right:3.5rem}.head-row h1{font-size:1.25rem}}`]})
export class AdminOperationsHubComponent implements OnInit{private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly location=inject(Location);private readonly access=inject(AdminAccessService);readonly active=signal<OperationsSection>('reservations');readonly ready=signal(false);readonly tabs:OperationsTab[]=[{id:'reservations',label:'Rezervasyonlar',area:'operations'},{id:'fleet-control',label:'Kiralık Araç Kontrolü',area:'operations'},{id:'vehicles',label:'Araç Başvuruları',area:'operations'},{id:'branches-requests',label:'Bayilik Başvuruları',area:'operations'},{id:'messages',label:'Mesajlar',area:'operations'},{id:'newsletter',label:'Bülten',area:'operations'},{id:'branches',label:'Şubeler',area:'settings'},{id:'branch-identities',label:'Şube Kimlikleri',area:'settings'}];readonly visibleTabs=computed(()=>this.tabs.filter(tab=>!this.ready()||this.access.canCached(tab.area)));async ngOnInit(){await this.access.refresh();this.ready.set(true);const requested=this.resolveSection();const selected=this.visibleTabs().some(tab=>tab.id===requested)?requested:(this.visibleTabs()[0]?.id||'reservations');this.active.set(selected);if(!this.router.url.startsWith('/admin/operations'))await this.router.navigate(['/admin/operations'],{queryParams:{section:selected},replaceUrl:true});}select(section:OperationsSection){if(!this.visibleTabs().some(tab=>tab.id===section))return;this.active.set(section);void this.router.navigate([],{relativeTo:this.route,queryParams:{section},queryParamsHandling:'merge',replaceUrl:true});if(typeof window!=='undefined')window.scrollTo({top:0,behavior:'smooth'});}goBack(){if(typeof window!=='undefined'&&window.history.length>1)this.location.back();else void this.router.navigate(['/admin/dashboard']);}private resolveSection():OperationsSection{const query=this.route.snapshot.queryParamMap.get('section') as OperationsSection|null;if(query&&this.tabs.some(tab=>tab.id===query))return query;const data=this.route.snapshot.data['operationsSection'] as OperationsSection|undefined;return data&&this.tabs.some(tab=>tab.id===data)?data:'reservations';}}
