import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FinanceService } from '../../services/finance.service';
import { ToastService } from '../../services/toast.service';

type Period='today'|'week'|'month'|'year';
@Component({selector:'app-admin-finance',standalone:true,imports:[CommonModule,FormsModule],template:`
<main class="page"><header class="head"><div><p>Finans merkezi</p><h1>Muhasebe ve Tahsilat</h1><span>Kiralama, satış, tur, ofis/EFT tahsilatı ve giderleri tek defterde izleyin. Raporlar kayıtlı işlemlerden hesaplanır.</span></div><button type="button" class="primary" (click)="downloadPdf()" [disabled]="loading()">PDF Raporu İndir</button></header>
<nav class="periods" aria-label="Muhasebe rapor dönemi"><button type="button" [class.active]="period()==='today'" (click)="setPeriod('today')">Bugün</button><button type="button" [class.active]="period()==='week'" (click)="setPeriod('week')">Bu Hafta</button><button type="button" [class.active]="period()==='month'" (click)="setPeriod('month')">Bu Ay</button><button type="button" [class.active]="period()==='year'" (click)="setPeriod('year')">Bu Yıl</button></nav>
<section class="kpis" aria-label="Finans özeti"><article><span>Gelir</span><strong>{{money(summary().income)}}</strong></article><article><span>Gider</span><strong>{{money(summary().expense)}}</strong></article><article><span>Net</span><strong>{{money(summary().net)}}</strong></article><article><span>İndirim</span><strong>{{money(summary().discount)}}</strong></article></section>
<div class="layout"><section class="card"><header><h2>Ofis / EFT Tahsilatı</h2><p>Müşteriden gerçekten para alındığında kaydedin. Rezervasyon referansı ile ödeme defterine ve muhasebeye aynı anda işlenir.</p></header><div class="form"><label><span>Rezervasyon Referansı</span><input [(ngModel)]="payment.reference" name="paymentReference" /></label><label><span>Tutar</span><input [(ngModel)]="payment.amount" name="paymentAmount" type="number" min="0.01" step="0.01" /></label><label><span>Yöntem</span><select [(ngModel)]="payment.method" name="paymentMethod"><option value="OFFICE">Ofiste / Nakit</option><option value="EFT">Havale / EFT</option></select></label><label><span>Banka / Makbuz Referansı</span><input [(ngModel)]="payment.externalReference" name="externalReference" /></label><label class="wide"><span>Not</span><textarea [(ngModel)]="payment.note" name="paymentNote" rows="3"></textarea></label><button type="button" class="primary wide" (click)="recordPayment()" [disabled]="working()">Tahsilatı Kaydet</button></div></section>
<section class="card"><header><h2>Gelir / Gider Kaydı</h2><p>Yakıt, bakım, temizlik, reklam, sigorta, vergi, maaş ve ofis giderlerini buradan ekleyin.</p></header><div class="form"><label><span>Yön</span><select [(ngModel)]="entry.direction" name="direction"><option value="EXPENSE">Gider</option><option value="INCOME">Diğer Gelir</option></select></label><label><span>Kategori</span><select [(ngModel)]="entry.category" name="category"><option value="FUEL">Yakıt</option><option value="MAINTENANCE">Bakım</option><option value="CLEANING">Temizlik</option><option value="INSURANCE">Sigorta</option><option value="ADVERTISING">Reklam</option><option value="TAX">Vergi</option><option value="SALARY">Maaş</option><option value="OFFICE">Ofis</option><option value="SERVICE">Hizmet</option><option value="OTHER">Diğer</option></select></label><label><span>Tutar</span><input [(ngModel)]="entry.amount" name="entryAmount" type="number" min="0.01" step="0.01" /></label><label><span>Karşı Taraf</span><input [(ngModel)]="entry.counterpartyName" name="counterparty" /></label><label><span>Fiş / Makbuz No</span><input [(ngModel)]="entry.receiptNumber" name="receiptNumber" /></label><label><span>Fatura No</span><input [(ngModel)]="entry.invoiceNumber" name="invoiceNumber" /></label><label class="wide"><span>Açıklama</span><textarea [(ngModel)]="entry.description" name="entryDescription" rows="3"></textarea></label><button type="button" class="primary wide" (click)="addEntry()" [disabled]="working()">Hareketi Kaydet</button></div></section></div>
<section class="card ledger"><header><div><h2>Hesap Hareketleri</h2><p>{{dateLabel()}} · {{summary().count}} kayıt</p></div><button type="button" (click)="refresh()" [disabled]="loading()">{{loading()?'Yenileniyor…':'Yenile'}}</button></header>@if(loading()){<p class="empty">Kayıtlar yükleniyor…</p>}@else if(transactions().length===0){<p class="empty">Bu dönemde muhasebe hareketi yok.</p>}@else{<div class="rows">@for(tx of transactions();track tx.id){<article><div><strong>{{categoryLabel(tx.category)}}</strong><span>{{tx.counterparty_name||tx.description||tx.reference||'Kayıt'}} · {{tx.occurred_at|date:'dd.MM.yyyy HH:mm'}}</span></div><div class="amount" [class.expense]="tx.direction==='EXPENSE'"><strong>{{tx.direction==='EXPENSE'?'-':'+'}}{{money(tx.net_amount)}}</strong><small>{{tx.payment_method||tx.source}}</small></div></article>}</div>}</section>
</main>`,styles:[`:host{display:block}.page{min-height:100vh;background:#f8fafc;padding:1rem;color:#0f172a}.head{max-width:1240px;margin:auto;display:flex;justify-content:space-between;align-items:end;gap:1rem}.head p{margin:0;color:#2563eb;font-size:.62rem;font-weight:950;text-transform:uppercase;letter-spacing:.12em}.head h1{margin:.2rem 0;font-size:1.55rem}.head span{display:block;max-width:760px;color:#64748b;font-size:.75rem;line-height:1.5}.primary{min-height:44px;border:0;border-radius:12px;background:#0f172a;color:#fff;padding:0 1rem;font-weight:900}.periods,.kpis,.layout,.card{max-width:1240px;margin:1rem auto 0}.periods{display:flex;gap:.45rem;overflow:auto}.periods button{min-height:42px;flex:none;border:1px solid #cbd5e1;border-radius:12px;background:#fff;padding:0 .9rem;font-weight:850}.periods button.active{border-color:#2563eb;background:#eff6ff;color:#1d4ed8}.kpis{display:grid;grid-template-columns:repeat(2,1fr);gap:.65rem}.kpis article{border:1px solid #e2e8f0;border-radius:16px;background:#fff;padding:.9rem}.kpis span{display:block;color:#64748b;font-size:.62rem;font-weight:900;text-transform:uppercase}.kpis strong{display:block;margin-top:.3rem;font-size:1.15rem}.layout{display:grid;gap:1rem}.card{border:1px solid #e2e8f0;border-radius:18px;background:#fff;overflow:hidden}.card>header{display:flex;justify-content:space-between;gap:1rem;align-items:center;border-bottom:1px solid #e2e8f0;padding:1rem}.card h2{margin:0;font-size:1rem}.card header p{margin:.25rem 0 0;color:#64748b;font-size:.68rem;line-height:1.45}.card header button{min-height:40px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;padding:0 .8rem;font-weight:850}.form{display:grid;gap:.7rem;padding:1rem}.form label{display:grid;gap:.3rem}.form span{font-size:.6rem;font-weight:900;text-transform:uppercase;color:#475569}.form input,.form select,.form textarea{width:100%;min-height:44px;border:1px solid #cbd5e1;border-radius:10px;padding:.6rem;font:inherit;font-size:.76rem}.wide{grid-column:1/-1}.rows article{display:flex;justify-content:space-between;gap:1rem;align-items:center;border-top:1px solid #f1f5f9;padding:.8rem 1rem}.rows article:first-child{border-top:0}.rows article>div:first-child{min-width:0}.rows article strong,.rows article span{display:block}.rows article span{margin-top:.2rem;color:#64748b;font-size:.65rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.amount{text-align:right;flex:none;color:#047857}.amount.expense{color:#b91c1c}.amount small{display:block;margin-top:.15rem;color:#64748b;font-size:.58rem}.empty{padding:1.5rem;text-align:center;color:#64748b}@media(min-width:760px){.page{padding:1.5rem}.kpis{grid-template-columns:repeat(4,1fr)}.layout{grid-template-columns:1fr 1fr}.form{grid-template-columns:1fr 1fr}}@media(max-width:650px){.head{flex-direction:column;align-items:stretch}.head>.primary{width:100%}}` ]})
export class AdminFinanceComponent implements OnInit{
 private readonly finance=inject(FinanceService);private readonly toast=inject(ToastService);readonly transactions=this.finance.transactions;readonly summary=this.finance.summary;readonly loading=this.finance.loading;readonly working=signal(false);readonly period=signal<Period>('month');from='';to='';
 payment={reference:'',amount:0,method:'OFFICE' as 'OFFICE'|'EFT',externalReference:'',note:''};entry={direction:'EXPENSE' as 'INCOME'|'EXPENSE',category:'FUEL',amount:0,counterpartyName:'',receiptNumber:'',invoiceNumber:'',description:''};
 async ngOnInit(){this.setPeriod('month');}
 setPeriod(value:Period){this.period.set(value);const now=new Date();let start=new Date(now);if(value==='today')start=new Date(now.getFullYear(),now.getMonth(),now.getDate());else if(value==='week'){const day=(now.getDay()+6)%7;start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-day);}else if(value==='month')start=new Date(now.getFullYear(),now.getMonth(),1);else start=new Date(now.getFullYear(),0,1);const end=value==='today'?new Date(start.getFullYear(),start.getMonth(),start.getDate()+1):value==='week'?new Date(start.getFullYear(),start.getMonth(),start.getDate()+7):value==='month'?new Date(start.getFullYear(),start.getMonth()+1,1):new Date(start.getFullYear()+1,0,1);this.from=start.toISOString();this.to=end.toISOString();void this.refresh();}
 async refresh(){try{await this.finance.refresh(this.from,this.to);}catch(e){this.toast.show(this.msg(e),'error');}}
 async recordPayment(){if(!this.payment.reference.trim()||Number(this.payment.amount)<=0){this.toast.show('Rezervasyon referansı ve tutar gereklidir.','error');return;}this.working.set(true);try{await this.finance.recordPayment({bookingReference:this.payment.reference.trim(),amount:Number(this.payment.amount),method:this.payment.method,externalReference:this.payment.externalReference.trim()||undefined,note:this.payment.note.trim()||undefined});this.payment={reference:'',amount:0,method:'OFFICE',externalReference:'',note:''};await this.refresh();this.toast.show('Tahsilat ödeme ve muhasebe kayıtlarına işlendi.','success');}catch(e){this.toast.show(this.msg(e),'error');}finally{this.working.set(false);}}
 async addEntry(){if(Number(this.entry.amount)<=0){this.toast.show('Geçerli bir tutar girin.','error');return;}this.working.set(true);try{await this.finance.createTransaction({direction:this.entry.direction,category:this.entry.category,amount:Number(this.entry.amount),counterpartyName:this.entry.counterpartyName.trim()||undefined,receiptNumber:this.entry.receiptNumber.trim()||undefined,invoiceNumber:this.entry.invoiceNumber.trim()||undefined,description:this.entry.description.trim()||undefined,currency:'TRY'});this.entry={direction:'EXPENSE',category:'FUEL',amount:0,counterpartyName:'',receiptNumber:'',invoiceNumber:'',description:''};await this.refresh();this.toast.show('Muhasebe hareketi kaydedildi.','success');}catch(e){this.toast.show(this.msg(e),'error');}finally{this.working.set(false);}}
 async downloadPdf(){try{await this.finance.downloadPdf(this.from,this.to);this.toast.show('PDF raporu hazırlandı.','success');}catch(e){this.toast.show(this.msg(e),'error');}}
 money(value:number){return new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(value||0));}
 dateLabel(){return `${new Date(this.from).toLocaleDateString('tr-TR')} - ${new Date(new Date(this.to).getTime()-1).toLocaleDateString('tr-TR')}`;}
 categoryLabel(v:string){return({RENTAL:'Araç Kiralama',VEHICLE_SALE:'Araç Satışı',TOUR:'Tur',DEPOSIT:'Depozito',SERVICE:'Hizmet',REFUND:'İade',MAINTENANCE:'Bakım',FUEL:'Yakıt',CLEANING:'Temizlik',INSURANCE:'Sigorta',TAX:'Vergi',ADVERTISING:'Reklam',SALARY:'Maaş',OFFICE:'Ofis',OTHER:'Diğer'} as Record<string,string>)[v]||v;}
 private msg(e:unknown){return e instanceof Error?e.message:'İşlem tamamlanamadı.';}
}
