import { CommonModule } from "@angular/common";
import { Component, OnInit, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { MatIconModule } from "@angular/material/icon";
import { BranchPlanV171, BranchSubscriptionV171, BranchSubscriptionV171Service } from "../../services/branch-subscription-v171.service";

@Component({selector:"app-admin-branch-subscriptions-v171",standalone:true,imports:[CommonModule,FormsModule,MatIconModule],template:`
<section class="space-y-6 p-1">
  <header><p class="text-xs font-black uppercase tracking-[.18em] text-blue-600">Super Admin Gelir Merkezi</p><h1 class="mt-2 text-3xl font-black">Şube Abonelikleri</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Üç paketin ücretini, haklarını ve aktifliğini yönetin. İsterseniz herhangi bir paketi 0 TL yapabilir veya tek bir şubeyi ücretsiz/muaf olarak işaretleyebilirsiniz.</p></header>
  @if(message()){<p role="status" [class.bg-emerald-50]="messageType()==='ok'" [class.text-emerald-800]="messageType()==='ok'" [class.bg-rose-50]="messageType()==='error'" [class.text-rose-800]="messageType()==='error'" class="rounded-xl p-3 font-bold">{{message()}}</p>}

  <div class="grid gap-4 xl:grid-cols-3">@for(plan of plans();track plan.id){<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><div><span class="text-[10px] font-black uppercase tracking-wider text-blue-600">{{plan.code}}</span><h2 class="text-xl font-black">{{plan.name}}</h2></div><label class="flex items-center gap-2 text-xs font-black"><input type="checkbox" [(ngModel)]="plan.is_active"/>Aktif</label></div><label class="mt-4 grid gap-1 text-xs font-black uppercase tracking-wider text-slate-500">Aylık ücret<input type="number" min="0" step="1" [(ngModel)]="plan.monthly_fee" class="min-h-11 rounded-xl border border-slate-200 px-3 text-base font-black text-slate-900"/></label><label class="mt-3 grid gap-1 text-xs font-black uppercase tracking-wider text-slate-500">Paket adı<input [(ngModel)]="plan.name" maxlength="120" class="min-h-11 rounded-xl border border-slate-200 px-3 text-sm normal-case text-slate-900"/></label><label class="mt-3 grid gap-1 text-xs font-black uppercase tracking-wider text-slate-500">Açıklama<textarea [(ngModel)]="plan.short_description" maxlength="600" rows="3" class="rounded-xl border border-slate-200 p-3 text-sm font-normal normal-case text-slate-900"></textarea></label><button type="button" (click)="savePlan(plan)" [disabled]="saving()" class="mt-4 min-h-11 w-full rounded-xl bg-slate-950 font-black text-white disabled:opacity-50">Paketi Kaydet</button></article>}</div>

  <div class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h2 class="text-xl font-black">Şube Bazlı Abonelikler</h2><p class="mt-1 text-sm text-slate-500">Şubeye özel fiyat, ücretsiz kullanım, plan ve durum buradan yönetilir.</p></div><div class="overflow-x-auto"><table class="min-w-[980px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="p-3">Şube</th><th class="p-3">Plan</th><th class="p-3">Durum</th><th class="p-3">Özel fiyat</th><th class="p-3">Ücretsiz</th><th class="p-3">Dönem sonu</th><th class="p-3">İşlem</th></tr></thead><tbody>@for(item of subscriptions();track item.id){<tr class="border-t border-slate-100"><td class="p-3"><strong>{{item.branch?.operator_display_name||item.branch?.name||item.branch_id}}</strong><span class="block text-xs text-slate-500">{{item.branch?.city}} / {{item.branch?.district}}</span></td><td class="p-3"><select [(ngModel)]="item.plan_id" class="min-h-10 rounded-lg border border-slate-200 px-2">@for(plan of plans();track plan.id){<option [value]="plan.id">{{plan.name}}</option>}</select></td><td class="p-3"><select [(ngModel)]="item.status" class="min-h-10 rounded-lg border border-slate-200 px-2"><option value="TRIALING">Deneme</option><option value="ACTIVE">Aktif</option><option value="PAST_DUE">Gecikmiş</option><option value="PAUSED">Duraklatılmış</option><option value="CANCELED">İptal</option><option value="EXEMPT">Muaf</option></select></td><td class="p-3"><input type="number" min="0" [ngModel]="item.price_override" (ngModelChange)="item.price_override=$event===''?null:$event" placeholder="Plan fiyatı" class="w-28 min-h-10 rounded-lg border border-slate-200 px-2"/></td><td class="p-3"><input type="checkbox" [(ngModel)]="item.is_complimentary" aria-label="Şubeyi ücretsiz yap"/></td><td class="p-3"><input type="date" [ngModel]="dateOnly(item.current_period_end)" (ngModelChange)="item.current_period_end=$event?($event+'T23:59:59.000Z'):null" class="min-h-10 rounded-lg border border-slate-200 px-2"/></td><td class="p-3"><button type="button" (click)="saveSubscription(item)" [disabled]="saving()" class="min-h-10 rounded-lg bg-blue-600 px-3 font-black text-white disabled:opacity-50">Kaydet</button></td></tr>}</tbody></table></div></div>
</section>`})
export class AdminBranchSubscriptionsV171Component implements OnInit{private readonly service=inject(BranchSubscriptionV171Service);readonly plans=signal<BranchPlanV171[]>([]);readonly subscriptions=signal<BranchSubscriptionV171[]>([]);readonly saving=signal(false);readonly message=signal("");readonly messageType=signal<"ok"|"error">("ok");ngOnInit():void{void this.load();}private async load(){try{const [plans,subscriptions]=await Promise.all([this.service.plans(true),this.service.adminSubscriptions()]);this.plans.set(plans);this.subscriptions.set(subscriptions);}catch(error){this.show(error instanceof Error?error.message:"Abonelik verileri yüklenemedi.","error");}}async savePlan(plan:BranchPlanV171){this.saving.set(true);try{await this.service.updatePlan(plan.id,{name:plan.name,short_description:plan.short_description,monthly_fee:Math.max(0,Number(plan.monthly_fee)||0),is_active:plan.is_active});this.show("Paket güncellendi.","ok");}catch(error){this.show(error instanceof Error?error.message:"Paket kaydedilemedi.","error");}finally{this.saving.set(false);}}async saveSubscription(item:BranchSubscriptionV171){this.saving.set(true);try{await this.service.updateSubscription(item.id,{plan_id:item.plan_id,status:item.status,price_override:item.price_override==null?null:Math.max(0,Number(item.price_override)||0),is_complimentary:item.is_complimentary,current_period_end:item.current_period_end||null});this.show("Şube aboneliği güncellendi.","ok");}catch(error){this.show(error instanceof Error?error.message:"Abonelik kaydedilemedi.","error");}finally{this.saving.set(false);}}dateOnly(value?:string|null):string{return value?value.slice(0,10):"";}private show(text:string,type:"ok"|"error"){this.message.set(text);this.messageType.set(type);}}
