import { CommonModule } from "@angular/common";
import { Component, OnInit, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { AuthService } from "../../services/auth.service";

type Relationship="OWNED"|"INDEPENDENT_PARTNER"|"LICENSED_PARTNER";
interface BranchIdentityRow{id:string;name:string;code?:string;city:string;district:string;network_type:string;public_status:string;operator_display_name?:string|null;operator_legal_name?:string|null;operator_relationship:Relationship;operator_identity_verified_at?:string|null;operator_identity_verified_by?:string|null;partner_request_id?:string|null;province_code?:string|null;district_code?:string|null;}

@Component({selector:"app-admin-branch-identities-v171",standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="space-y-6 p-1"><header><p class="text-xs font-black uppercase tracking-[.18em] text-blue-600">Super Admin Güven Merkezi</p><h1 class="mt-2 text-3xl font-black">Şube İşletme Kimlikleri</h1><p class="mt-2 max-w-4xl text-sm leading-6 text-slate-500">Müşteriye ilan sahibi olarak gösterilen işletme adı yalnız merkez doğrulamasından sonra “doğrulanmış” olur. Şube kullanıcısı bu alanları veya doğrulama statüsünü değiştiremez.</p></header>
@if(error()){<p role="alert" class="rounded-xl bg-rose-50 p-3 font-bold text-rose-800">{{error()}}</p>}@if(message()){<p role="status" class="rounded-xl bg-emerald-50 p-3 font-bold text-emerald-800">{{message()}}</p>}
<div class="grid gap-4 xl:grid-cols-2">@for(item of branches();track item.id){<article class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><span class="text-[10px] font-black uppercase tracking-wider text-blue-600">{{item.network_type}} · {{item.city}} / {{item.district}}</span><h2 class="mt-1 text-xl font-black">{{item.name}}</h2><p class="text-xs text-slate-500">{{item.code||item.id}}</p></div><span [class.bg-emerald-100]="!!item.operator_identity_verified_at||item.network_type==='OWNED'" [class.text-emerald-800]="!!item.operator_identity_verified_at||item.network_type==='OWNED'" [class.bg-amber-100]="!item.operator_identity_verified_at&&item.network_type!=='OWNED'" [class.text-amber-800]="!item.operator_identity_verified_at&&item.network_type!=='OWNED'" class="rounded-full px-3 py-1 text-xs font-black">{{item.operator_identity_verified_at||item.network_type==='OWNED'?'Doğrulanmış':'Doğrulama bekliyor'}}</span></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><label class="grid gap-1 text-xs font-black">Müşteriye görünen işletme adı<input [(ngModel)]="item.operator_display_name" [attr.aria-label]="item.name+' görünen işletme adı'" maxlength="180" class="field"/></label><label class="grid gap-1 text-xs font-black">Yasal işletme unvanı<input [(ngModel)]="item.operator_legal_name" [attr.aria-label]="item.name+' yasal işletme unvanı'" maxlength="240" class="field"/></label><label class="grid gap-1 text-xs font-black">Operatör ilişkisi<select [(ngModel)]="item.operator_relationship" [attr.aria-label]="item.name+' operatör ilişkisi'" class="field"><option value="OWNED">Alperler Auto merkezi</option><option value="INDEPENDENT_PARTNER">Bağımsız partner</option><option value="LICENSED_PARTNER">Lisanslı partner</option></select></label><div class="rounded-xl bg-slate-50 p-3 text-xs"><span class="text-slate-500">Konum kodları</span><strong class="mt-1 block">{{item.province_code||'Eksik'}} / {{item.district_code||'Eksik'}}</strong></div></div><div class="mt-4 flex flex-wrap gap-2"><button type="button" (click)="save(item,true)" [disabled]="savingId()===item.id" class="min-h-11 rounded-xl bg-emerald-600 px-4 font-black text-white disabled:opacity-50">Doğrula ve Kaydet</button>@if(item.operator_identity_verified_at&&item.network_type!=='OWNED'){<button type="button" (click)="save(item,false)" [disabled]="savingId()===item.id" class="min-h-11 rounded-xl border border-amber-300 px-4 font-black text-amber-800 disabled:opacity-50">Doğrulamayı Kaldır</button>}</div>@if(item.operator_identity_verified_at){<p class="mt-3 text-xs text-slate-500">Doğrulama: {{item.operator_identity_verified_at|date:'dd.MM.yyyy HH:mm'}}</p>}</article>}</div></section>`,styles:[`.field{min-height:44px;border:1px solid #cbd5e1;border-radius:12px;padding:.6rem .7rem;background:#f8fafc}`]})
export class AdminBranchIdentitiesV171Component implements OnInit{
  private readonly auth=inject(AuthService);
  private readonly endpoint="/api/partner?op=branch-security-admin";
  readonly branches=signal<BranchIdentityRow[]>([]);readonly savingId=signal("");readonly error=signal("");readonly message=signal("");
  ngOnInit():void{void this.load();}
  private async load(){this.error.set("");try{const token=await this.token();const response=await fetch(`${this.endpoint}&view=identities`,{headers:this.headers(token),cache:"no-store"});const payload=await response.json().catch(()=>({})) as {ok?:boolean;code?:string;rows?:BranchIdentityRow[]};if(!response.ok||payload.ok!==true)throw new Error(String(payload.code||`BRANCH_IDENTITY_LOAD_${response.status}`));this.branches.set(Array.isArray(payload.rows)?payload.rows:[]);}catch(error){this.error.set(error instanceof Error?error.message:"Şube kimlikleri yüklenemedi.");}}
  async save(item:BranchIdentityRow,verified:boolean){if(this.savingId())return;const display=String(item.operator_display_name||"").trim(),legal=String(item.operator_legal_name||"").trim();if(!display||!legal){this.error.set("Görünen işletme adı ve yasal unvan zorunludur.");return;}this.savingId.set(item.id);this.error.set("");this.message.set("");try{const token=await this.token();const response=await fetch(this.endpoint,{method:"PATCH",headers:this.headers(token),body:JSON.stringify({action:"SET_OPERATOR_IDENTITY",branchId:item.id,displayName:display,legalName:legal,verified,relationship:item.operator_relationship}),cache:"no-store"});const payload=await response.json().catch(()=>({})) as {ok?:boolean;code?:string};if(!response.ok||payload.ok!==true)throw new Error(String(payload.code||`BRANCH_IDENTITY_SAVE_${response.status}`));this.message.set(verified?"İşletme kimliği doğrulandı ve kaydedildi.":"İşletme doğrulaması kaldırıldı.");await this.load();}catch(error){this.error.set(error instanceof Error?error.message:"İşletme kimliği kaydedilemedi.");}finally{this.savingId.set("");}}
  private async token():Promise<string>{const token=await this.auth.getAccessToken();if(!token)throw new Error("ADMIN_SESSION_REQUIRED");return token;}
  private headers(token:string):Record<string,string>{return{authorization:`Bearer ${token}`,"content-type":"application/json",accept:"application/json","x-request-id":crypto.randomUUID()};}
}
