import { CommonModule } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FleetOperationProfile, FleetOperationsService, FleetVehicle, InspectionType } from '../../services/fleet-operations.service';
import { ToastService } from '../../services/toast.service';

@Component({selector:'app-admin-fleet-operations',standalone:true,imports:[CommonModule,FormsModule],template:`
<main class="page"><header class="top"><div><p>Filo kontrol merkezi</p><h1>Kiralık Araç Operasyonu</h1><span>Müşteriye göstermeden kilometre, yakıt, temizlik, hasar, bakım, belge ve gerçek GPS cihaz bağlantısını yönetin.</span></div><button type="button" (click)="refresh()" [disabled]="loading()">{{loading()?'Yenileniyor…':'Verileri Yenile'}}</button></header>
<section class="notice"><strong>GPS hakkında:</strong> Bu ekran sahte konum üretmez. Canlı konum ancak araca gerçek telematik/GPS cihazı bağlanıp sağlayıcı entegrasyonu yapıldığında görünür.</section>
<div class="grid">
  <aside class="vehicles" aria-label="Kiralık araçlar">@for(v of vehicles();track v.id){<button type="button" [class.active]="selectedId()===v.id" (click)="select(v)"><strong>{{v.brand}} {{v.model}}</strong><small>{{v.modelYear||''}} · {{v.stockCode||'Stok kodu yok'}}</small><span>{{statusLabel(profile(v).operationalStatus)}}</span></button>}@if(!loading()&&vehicles().length===0){<p>Kiralık araç bulunamadı.</p>}</aside>
  @if(selectedVehicle();as vehicle){<section class="editor"><header><div><p>{{vehicle.stockCode||'Kiralık araç'}}</p><h2>{{vehicle.brand}} {{vehicle.model}} {{vehicle.modelYear||''}}</h2></div><span class="state">{{statusLabel(form.operationalStatus)}}</span></header>
    <div class="fields">
      <label><span>Operasyon durumu</span><select [(ngModel)]="form.operationalStatus"><option value="READY">Teslime hazır</option><option value="RESERVED">Rezerve</option><option value="RENTED">Kirada</option><option value="CLEANING">Temizlikte</option><option value="MAINTENANCE">Bakımda</option><option value="INSPECTION_HOLD">Kontrol bekliyor</option><option value="OUT_OF_SERVICE">Hizmet dışı</option></select></label>
      <label><span>Kilometre</span><input type="number" min="0" [(ngModel)]="form.odometerKm" /></label>
      <label><span>Yakıt seviyesi %</span><input type="number" min="0" max="100" [(ngModel)]="form.fuelPercent" /></label>
      <label><span>Temizlik</span><select [(ngModel)]="form.cleanlinessStatus"><option value="UNKNOWN">Kontrol edilmedi</option><option value="CLEAN">Temiz</option><option value="NEEDS_CLEANING">Temizlik gerekiyor</option><option value="DEEP_CLEANING">Detaylı temizlik gerekiyor</option></select></label>
      <label><span>Son bakım</span><input type="datetime-local" [ngModel]="localDateTime(form.lastServiceAt)" (ngModelChange)="form.lastServiceAt=isoDateTime($event)" /></label>
      <label><span>Sonraki bakım tarihi</span><input type="datetime-local" [ngModel]="localDateTime(form.nextServiceAt)" (ngModelChange)="form.nextServiceAt=isoDateTime($event)" /></label>
      <label><span>Sonraki bakım km</span><input type="number" min="0" [(ngModel)]="form.nextServiceKm" /></label>
      <label><span>Sigorta bitiş</span><input type="date" [(ngModel)]="form.insuranceExpiresAt" /></label>
      <label><span>Periyodik muayene bitiş</span><input type="date" [(ngModel)]="form.periodicInspectionExpiresAt" /></label>
    </div>
    <div class="notes"><label><span>Hasar / mevcut kusur notu</span><textarea rows="3" [(ngModel)]="form.damageNotes" placeholder="Müşteriye teslim öncesi bilinmesi gereken mevcut çizik, göçük veya teknik notlar"></textarea></label><label><span>İç operasyon notu</span><textarea rows="3" [(ngModel)]="form.internalNotes" placeholder="Temizlik, lastik, servis, teslim veya ekip notu"></textarea></label></div>
    <section class="gps"><div><p>Telematik / GPS</p><h3>{{gpsLabel(form.gpsStatus)}}</h3><span>@if(form.gpsStatus==='CONNECTED'&&form.gpsLastSyncAt){Son senkron: {{form.gpsLastSyncAt|date:'medium'}}}@else{Gerçek cihaz tanımlanmadan canlı konum gösterilmez.}</span></div><div class="fields compact"><label><span>Sağlayıcı</span><input [(ngModel)]="form.gpsProvider" placeholder="Örn. Geotab / Samsara" /></label><label><span>Cihaz kimliği</span><input [(ngModel)]="form.gpsDeviceId" /></label><label><span>Bağlantı durumu</span><select [(ngModel)]="form.gpsStatus"><option value="NOT_CONFIGURED">Bağlı değil</option><option value="CONNECTED">Bağlı</option><option value="OFFLINE">Çevrimdışı</option><option value="ERROR">Hata</option></select></label></div></section>
    <div class="actions"><button type="button" class="primary" (click)="save()" [disabled]="saving()">{{saving()?'Kaydediliyor…':'Operasyon Kaydını Kaydet'}}</button></div>
    <section class="inspection"><h3>Hızlı Araç Kontrolü</h3><p>Teslim öncesi, teslim anı, iade veya rutin kontrolde gerçek durumu kaydedin.</p><div class="fields compact"><label><span>Kontrol tipi</span><select [(ngModel)]="inspectionType"><option value="PRE_RENTAL">Kiralama öncesi</option><option value="HANDOVER">Teslim</option><option value="RETURN">İade</option><option value="ROUTINE">Rutin</option></select></label><label><span>Kilometre</span><input type="number" min="0" [(ngModel)]="inspectionKm" /></label><label><span>Yakıt %</span><input type="number" min="0" max="100" [(ngModel)]="inspectionFuel" /></label><label><span>Dış görünüm</span><select [(ngModel)]="inspectionExterior"><option value="OK">Sorun yok</option><option value="DAMAGE_NOTED">Hasar not edildi</option><option value="REQUIRES_SERVICE">Servis gerekiyor</option></select></label><label><span>İç mekan</span><select [(ngModel)]="inspectionInterior"><option value="OK">Sorun yok</option><option value="DAMAGE_NOTED">Hasar not edildi</option><option value="REQUIRES_CLEANING">Temizlik gerekiyor</option></select></label></div><label class="wide"><span>Kontrol notu</span><textarea rows="3" [(ngModel)]="inspectionNotes"></textarea></label><button type="button" (click)="addInspection()" [disabled]="inspectionSaving()">{{inspectionSaving()?'Kaydediliyor…':'Kontrol Kaydını Oluştur'}}</button></section>
  </section>}
</div></main>`,styles:[`:host{display:block}.page{min-height:100%;background:#f8fafc;padding:1rem;color:#0f172a}.top{max-width:1240px;margin:auto;display:flex;justify-content:space-between;gap:1rem;align-items:end}.top p,.editor header p,.gps p{margin:0;color:#2563eb;font-size:.62rem;font-weight:950;text-transform:uppercase;letter-spacing:.12em}.top h1{margin:.2rem 0;font-size:1.55rem}.top span{color:#64748b;font-size:.75rem}.top button,.actions button,.inspection button{min-height:44px;border:0;border-radius:12px;padding:0 1rem;font-weight:900}.top button{background:#fff;border:1px solid #dbe4ef}.notice{max-width:1240px;margin:1rem auto;border:1px solid #bfdbfe;border-radius:14px;background:#eff6ff;padding:.8rem;color:#1e3a8a;font-size:.72rem;line-height:1.5}.grid{max-width:1240px;margin:auto;display:grid;gap:1rem}.vehicles{display:grid;gap:.5rem;align-content:start}.vehicles button{display:grid;gap:.2rem;border:1px solid #e2e8f0;border-radius:14px;background:#fff;padding:.8rem;text-align:left}.vehicles button.active{border-color:#2563eb;background:#eff6ff}.vehicles strong{font-size:.78rem}.vehicles small{color:#64748b}.vehicles span{color:#2563eb;font-size:.62rem;font-weight:900}.editor{border:1px solid #e2e8f0;border-radius:20px;background:#fff;padding:1rem}.editor>header{display:flex;justify-content:space-between;gap:1rem}.editor h2{margin:.15rem 0 0;font-size:1.25rem}.state{height:max-content;border-radius:999px;background:#ecfdf5;padding:.35rem .55rem;color:#047857;font-size:.62rem;font-weight:950}.fields{display:grid;gap:.65rem;margin-top:1rem}.fields label,.notes label,.wide{display:grid;gap:.3rem}.fields span,.notes span,.wide span{color:#475569;font-size:.61rem;font-weight:900;text-transform:uppercase}input,select,textarea{width:100%;min-height:44px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;padding:.6rem;font:inherit;font-size:.75rem}textarea{resize:vertical}.notes{display:grid;gap:.65rem;margin-top:.8rem}.gps,.inspection{margin-top:1rem;border:1px solid #dbe4ef;border-radius:16px;background:#f8fafc;padding:.9rem}.gps h3{margin:.2rem 0;font-size:.9rem}.gps>div>span,.inspection p{color:#64748b;font-size:.68rem;line-height:1.5}.actions{display:flex;justify-content:flex-end;margin-top:.8rem}.primary,.inspection button{background:#0f172a;color:#fff}.inspection h3{margin:0;font-size:.9rem}.inspection button{margin-top:.7rem;background:#2563eb}.compact{margin-top:.65rem}@media(min-width:800px){.page{padding:1.5rem}.grid{grid-template-columns:280px 1fr}.fields{grid-template-columns:repeat(3,minmax(0,1fr))}.notes{grid-template-columns:1fr 1fr}.gps{display:grid;grid-template-columns:.7fr 1.3fr;gap:1rem;align-items:start}.compact{grid-template-columns:repeat(3,minmax(0,1fr))}}`]} )
export class AdminFleetOperationsComponent implements OnInit{
 private readonly fleet=inject(FleetOperationsService);private readonly toast=inject(ToastService);readonly vehicles=this.fleet.vehicles;readonly loading=this.fleet.loading;readonly selectedId=signal('');readonly selectedVehicle=computed(()=>this.vehicles().find(v=>v.id===this.selectedId()));readonly saving=signal(false);readonly inspectionSaving=signal(false);form: FleetOperationProfile=this.empty();inspectionType:InspectionType='PRE_RENTAL';inspectionKm:number|null=null;inspectionFuel:number|null=null;inspectionExterior:'OK'|'DAMAGE_NOTED'|'REQUIRES_SERVICE'='OK';inspectionInterior:'OK'|'DAMAGE_NOTED'|'REQUIRES_CLEANING'='OK';inspectionNotes='';
 async ngOnInit(){await this.refresh();}
 async refresh(){try{await this.fleet.refresh();const current=this.selectedVehicle()||this.vehicles()[0];if(current)this.select(current);}catch(e){this.toast.show(this.message(e),'error');}}
 profile(v:FleetVehicle){return this.fleet.profileFor(v);}
 select(v:FleetVehicle){this.selectedId.set(v.id);this.form=structuredClone(this.fleet.profileFor(v));this.inspectionKm=this.form.odometerKm;this.inspectionFuel=this.form.fuelPercent;}
 async save(){if(this.saving())return;this.saving.set(true);try{await this.fleet.save(this.form);const v=this.vehicles().find(x=>x.id===this.form.vehicleId);if(v)this.select(v);this.toast.show('Araç operasyon kaydı güncellendi.','success');}catch(e){this.toast.show(this.message(e),'error');}finally{this.saving.set(false);}}
 async addInspection(){if(this.inspectionSaving())return;this.inspectionSaving.set(true);try{await this.fleet.addInspection({vehicleId:this.form.vehicleId,inspectionType:this.inspectionType,odometerKm:this.inspectionKm,fuelPercent:this.inspectionFuel,cleanlinessStatus:this.form.cleanlinessStatus==='UNKNOWN'?null:this.form.cleanlinessStatus,exteriorStatus:this.inspectionExterior,interiorStatus:this.inspectionInterior,damageNotes:this.inspectionNotes});const v=this.vehicles().find(x=>x.id===this.form.vehicleId);if(v)this.select(v);this.inspectionNotes='';this.toast.show('Araç kontrol kaydı oluşturuldu.','success');}catch(e){this.toast.show(this.message(e),'error');}finally{this.inspectionSaving.set(false);}}
 statusLabel(s:string){return({READY:'Teslime hazır',RESERVED:'Rezerve',RENTED:'Kirada',CLEANING:'Temizlikte',MAINTENANCE:'Bakımda',INSPECTION_HOLD:'Kontrol bekliyor',OUT_OF_SERVICE:'Hizmet dışı'} as Record<string,string>)[s]||s;}
 gpsLabel(s:string){return({NOT_CONFIGURED:'GPS cihazı bağlı değil',CONNECTED:'GPS cihazı bağlı',OFFLINE:'GPS cihazı çevrimdışı',ERROR:'GPS bağlantı hatası'} as Record<string,string>)[s]||s;}
 localDateTime(value:string|null){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
 isoDateTime(value:string){return value?new Date(value).toISOString():null;}
 private empty():FleetOperationProfile{return{vehicleId:'',operationalStatus:'READY',odometerKm:null,fuelPercent:null,cleanlinessStatus:'UNKNOWN',lastInspectionAt:null,lastServiceAt:null,nextServiceAt:null,nextServiceKm:null,insuranceExpiresAt:null,periodicInspectionExpiresAt:null,damageNotes:'',internalNotes:'',gpsProvider:'',gpsDeviceId:'',gpsStatus:'NOT_CONFIGURED',gpsLastSyncAt:null,lastKnownLatitude:null,lastKnownLongitude:null};}
 private message(e:unknown){return e instanceof Error?e.message:'İşlem tamamlanamadı.';}
}
