import { CommonModule } from "@angular/common";
import { Component, OnInit, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { AuthService } from "../../services/auth.service";

type Kind="VEHICLE"|"TOUR";
interface QueueItem{id:string;kind:Kind;title:string;category:string;price:number;currency:string;branchId:string;branchName:string;operatorName:string;city:string;district:string;submittedAt?:string|null;updatedAt?:string|null;reviewNote?:string|null;cover?:string|null;details:string[];}
interface ModerationPayload{ok?:boolean;code?:string;data?:{vehicles?:any[];tours?:any[]};}

@Component({selector:"app-admin-branch-moderation-v171",standalone:true,imports:[CommonModule,FormsModule],template:`
<section class="space-y-6 p-1"><header><p class="text-xs font-black uppercase tracking-[.18em] text-blue-600">Merkezi Kalite Kontrolü</p><h1 class="mt-2 text-3xl font-black">Şube İlan Moderasyonu</h1><p class="mt-2 max-w-4xl text-sm leading-6 text-slate-500">Şubeler kendi araç ve turlarını hazırlar; yayın kararı merkezindir. Fiyat, operatör, temel detay ve medya doğruluğunu inceleyin. Yayındaki bir ilan şube tarafından değiştirilirse tekrar bu kuyruğa döner.</p></header>
<div class="flex flex-wrap gap-2"><button type="button" (click)="filter.set('ALL')" [class.bg-slate-950]="filter()==='ALL'" [class.text-white]="filter()==='ALL'" class="chip">Tümü {{items().length}}</button><button type="button" (click)="filter.set('VEHICLE')" [class.bg-slate-950]="filter()==='VEHICLE'" [class.text-white]="filter()==='VEHICLE'" class="chip">Araçlar {{count('VEHICLE')}}</button><button type="button" (click)="filter.set('TOUR')" [class.bg-slate-950]="filter()==='TOUR'" [class.text-white]="filter()==='TOUR'" class="chip">Turlar {{count('TOUR')}}</button><button type="button" (click)="load()" class="chip ml-auto">Yenile</button></div>
@if(error()){<p role="alert" class="rounded-xl bg-rose-50 p-3 font-bold text-rose-800">{{error()}}</p>}@if(message()){<p role="status" class="rounded-xl bg-emerald-50 p-3 font-bold text-emerald-800">{{message()}}</p>}
<div class="grid gap-5 xl:grid-cols-2">@for(item of visible();track item.kind+'-'+item.id){<article class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="grid sm:grid-cols-[180px_1fr]">@if(item.cover){<img [src]="item.cover" [alt]="item.title" class="h-full min-h-44 w-full object-cover"/>}@else{<div class="grid min-h-44 place-items-center bg-slate-100 text-slate-400">Medya bekleniyor</div>}<div class="p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><span class="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-black text-blue-800">{{item.kind==='VEHICLE'?'ARAÇ':'TUR'}} · {{item.category}}</span><h2 class="mt-2 text-xl font-black">{{item.title}}</h2><p class="mt-1 text-xs text-slate-500">{{item.operatorName}} · {{item.city}} / {{item.district}}</p></div><strong class="text-xl">{{item.price|number:'1.0-0'}} {{item.currency}}</strong></div><ul class="mt-4 grid gap-1 text-xs text-slate-600">@for(detail of item.details;track detail){<li>{{detail}}</li>}</ul><p class="mt-3 text-[11px] text-slate-400">Gönderim: {{item.submittedAt?(item.submittedAt|date:'dd.MM.yyyy HH:mm'):'Tarih yok'}} · Son güncelleme: {{item.updatedAt?(item.updatedAt|date:'dd.MM.yyyy HH:mm'):'-'}}</p></div></div><div class="border-t border-slate-200 p-4"><label class="grid gap-1 text-xs font-black">Merkez notu<textarea [(ngModel)]="notes[item.kind+'-'+item.id]" [attr.aria-label]="item.title+' moderasyon notu'" maxlength="2000" rows="2" class="rounded-xl border border-slate-200 p-3 text-sm font-normal"></textarea></label><div class="mt-3 grid grid-cols-3 gap-2"><button type="button" (click)="review(item,'APPROVE')" [disabled]="savingKey()===item.kind+'-'+item.id" class="action bg-emerald-600 text-white">Onayla</button><button type="button" (click)="review(item,'REJECT')" [disabled]="savingKey()===item.kind+'-'+item.id" class="action border border-rose-200 text-rose-700">Düzeltme İste</button><button type="button" (click)="review(item,'SUSPEND')" [disabled]="savingKey()===item.kind+'-'+item.id" class="action border border-amber-200 text-amber-800">Askıya Al</button></div></div></article>}@empty{<div class="xl:col-span-2 rounded-3xl border-2 border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">İnceleme bekleyen şube ilanı yok.</div>}</div></section>`,styles:[`.chip{min-height:42px;border:1px solid #cbd5e1;border-radius:12px;padding:0 .9rem;font-weight:900;background:white}.action{min-height:42px;border-radius:12px;padding:.5rem;font-size:.8rem;font-weight:900}`]})
export class AdminBranchModerationV171Component implements OnInit{
  private readonly auth=inject(AuthService);
  private readonly endpoint="/api/partner?op=branch-security-admin";
  readonly items=signal<QueueItem[]>([]);readonly filter=signal<"ALL"|Kind>("ALL");readonly error=signal("");readonly message=signal("");readonly savingKey=signal("");notes:Record<string,string>={};readonly visible=()=>this.filter()==="ALL"?this.items():this.items().filter(i=>i.kind===this.filter());
  ngOnInit():void{void this.load();}
  count(kind:Kind){return this.items().filter(i=>i.kind===kind).length;}
  async load(){this.error.set("");this.message.set("");try{const token=await this.token();const response=await fetch(`${this.endpoint}&view=moderation`,{headers:this.headers(token),cache:"no-store"});const payload=await response.json().catch(()=>({})) as ModerationPayload;if(!response.ok||payload.ok!==true)throw new Error(String(payload.code||`MODERATION_LOAD_${response.status}`));const vehicles=Array.isArray(payload.data?.vehicles)?payload.data!.vehicles!:[];const tours=Array.isArray(payload.data?.tours)?payload.data!.tours!:[];const mapped=[...vehicles.map(row=>this.vehicle(row)),...tours.map(row=>this.tour(row))].sort((a,b)=>String(a.submittedAt||a.updatedAt||"").localeCompare(String(b.submittedAt||b.updatedAt||"")));this.items.set(mapped);}catch(error){this.error.set(error instanceof Error?error.message:"Moderasyon kuyruğu yüklenemedi.");}}
  async review(item:QueueItem,action:"APPROVE"|"REJECT"|"SUSPEND"){const key=item.kind+'-'+item.id;if(this.savingKey())return;const note=String(this.notes[key]||"").trim();if(action==="REJECT"&&!note){this.error.set("Düzeltme istenirken merkez notu zorunludur.");return;}this.savingKey.set(key);this.error.set("");this.message.set("");try{const token=await this.token();const response=await fetch(this.endpoint,{method:"PATCH",headers:this.headers(token),body:JSON.stringify({action:"REVIEW_LISTING",kind:item.kind,id:item.id,decision:action,note:note||null}),cache:"no-store"});const payload=await response.json().catch(()=>({})) as {ok?:boolean;code?:string};if(!response.ok||payload.ok!==true)throw new Error(String(payload.code||`BRANCH_REVIEW_${response.status}`));this.message.set(action==="APPROVE"?"İlan merkez onayıyla yayınlandı.":action==="REJECT"?"İlan düzeltme için şubeye geri gönderildi.":"İlan askıya alındı.");delete this.notes[key];await this.load();}catch(error){this.error.set(error instanceof Error?error.message:"Moderasyon işlemi başarısız.");}finally{this.savingKey.set("");}}
  private vehicle(row:any):QueueItem{const branch=row.branch||{};const images=Array.isArray(row.images)?row.images:[];return{id:String(row.id),kind:"VEHICLE",title:`${row.brand||""} ${row.model||""}`.trim()||"Araç",category:String(row.category||""),price:Number(row.category==="RENTAL"?(row.rental_price_daily??row.price??0):(row.price??0)),currency:String(row.currency||"TRY"),branchId:String(row.branch_id||""),branchName:String(branch.name||""),operatorName:String(branch.operator_display_name||branch.name||""),city:String(branch.city||""),district:String(branch.district||""),submittedAt:row.submitted_for_review_at,updatedAt:row.updated_at,reviewNote:row.review_note,cover:row.cover_image||images[0]||null,details:[`Stok: ${row.stock_code||'-'}`,`Yıl: ${row.model_year||'-'}`,`Yakıt: ${row.fuel_type||'-'}`,`Vites: ${row.transmission||'-'}`,`Kasa: ${row.body_type||'-'}`]};}
  private tour(row:any):QueueItem{const branch=row.branch||{};const images=Array.isArray(row.images)?row.images:[];return{id:String(row.id),kind:"TOUR",title:String(row.title||"Tur"),category:String(row.category||"TUR"),price:Number(row.price_per_person||0),currency:String(row.currency||"TRY"),branchId:String(row.branch_id||""),branchName:String(branch.name||""),operatorName:String(branch.operator_display_name||branch.name||""),city:String(branch.city||""),district:String(branch.district||""),submittedAt:row.submitted_for_review_at,updatedAt:row.updated_at,reviewNote:row.review_note,cover:row.cover_image||images[0]||null,details:[`Süre: ${row.duration||'-'}`,`Buluşma: ${row.meeting_point||'-'}`,`Önerilen grup: ${row.capacity||'-'}`,`Program adımı: ${Array.isArray(row.itinerary)?row.itinerary.length:0}`]};}
  private async token(){const token=await this.auth.getAccessToken();if(!token)throw new Error("ADMIN_SESSION_REQUIRED");return token;}
  private headers(token:string):Record<string,string>{return{authorization:`Bearer ${token}`,"content-type":"application/json",accept:"application/json","x-request-id":crypto.randomUUID()};}
}
