import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { Branch } from "../../models/branch.model";
import { BranchPublicV171Service } from "../../services/branch-public-v171.service";
import { ConfirmService } from "../../services/confirm.service";
import { GeoDirectoryService } from "../../services/geo-directory.service";
import { PartnerMediaItem, PartnerMediaService } from "../../services/partner-media.service";
import { PartnerStatus } from "../../services/partner-request.service";
import { ToastService } from "../../services/toast.service";
import {
  OfferModelV172,
  ValuationSnapshotV172,
  ValuationStatusV172,
  VehicleValuationV172Service,
} from "../../services/vehicle-valuation-v172.service";

type StudioTab="overview"|"valuation"|"appointment"|"identity"|"operations";

@Component({
  selector:"app-admin-vehicle-valuation-studio-v172",
  standalone:true,
  imports:[CommonModule,FormsModule],
  changeDetection:ChangeDetectionStrategy.OnPush,
  template:`
  <section class="studio-shell">
    <div class="studio-hero">
      <div><p>V172 Acquisition Control</p><h2>Araç Değerleme Stüdyosu</h2><span>Başvurudan resmi değerlemeye, ekspertizden teklif ve filoya kabul kararına kadar tek operasyon ekranı.</span></div>
      <button type="button" (click)="refresh()" [disabled]="service.loading()" class="primary-action">{{service.loading()?'Yenileniyor...':'Kayıtları Yenile'}}</button>
    </div>

    @if(service.error()){<div role="alert" class="alert-error">{{service.error()}}</div>}

    <div class="metrics" aria-label="Araç değerleme metrikleri">
      <div><strong>{{service.records().length}}</strong><span>Toplam dosya</span></div>
      <div><strong>{{openCount()}}</strong><span>Açık işlem</span></div>
      <div><strong>{{finalCount()}}</strong><span>FINAL değerleme</span></div>
      <div><strong>{{appointmentCount()}}</strong><span>Randevulu</span></div>
    </div>

    <div class="toolbar">
      <input type="search" [ngModel]="searchQuery()" (ngModelChange)="searchQuery.set($event)" autocomplete="off" placeholder="Referans, müşteri, telefon veya araç ara" aria-label="Değerleme kayıtlarında ara" />
      <select [ngModel]="statusFilter()" (ngModelChange)="statusFilter.set($event)" aria-label="Durum filtresi"><option value="ALL">Tüm durumlar</option><option value="NEW">Yeni</option><option value="REVIEWING">İnceleniyor</option><option value="CONTACTED">İletişim kuruldu</option><option value="OFFERED">Teklif verildi</option><option value="ACCEPTED">Kabul edildi</option><option value="REJECTED">Reddedildi</option><option value="CLOSED">Kapalı</option></select>
      <select [ngModel]="modelFilter()" (ngModelChange)="modelFilter.set($event)" aria-label="Teklif modeli filtresi"><option value="ALL">Tüm ticari modeller</option><option value="PURCHASE">Satın alma</option><option value="MONTHLY_GUARANTEE">Aylık garanti</option><option value="REVENUE_SHARE">Gelir paylaşımı</option><option value="DECLINE">Uygun değil</option><option value="NONE">Henüz değerlenmedi</option></select>
    </div>

    <div class="workspace">
      <aside class="records" aria-label="Araç değerleme kayıtları">
        @if(service.loading()&&service.records().length===0){<div class="empty">Başvurular yükleniyor...</div>}
        @for(req of filteredRecords();track req.id){
          <button type="button" class="record-card" [class.active]="selectedReference()===req.reference" (click)="open(req)">
            <div class="record-top"><span [class]="statusClass(req.status)">{{statusLabel(req.status)}}</span><code>{{req.reference}}</code></div>
            <strong>{{req.carBrand}} {{req.carModel}}</strong>
            <small>{{req.customerName}} · {{req.customerPhone}}</small>
            <div class="record-meta"><span>{{req.modelYear||'-'}} model</span><span>{{req.km==null?'-':(req.km|number:'1.0-0')}} km</span></div>
            <div class="record-foot"><span>{{req.intent==='SELL'?'Satış':'Filoya katılım'}}</span><b>{{req.valuation?.valuationStatus==='FINAL'?'FINAL '+(req.valuation?.conditionGrade||''):req.valuation?'Taslak değerleme':'Değerleme bekliyor'}}</b></div>
          </button>
        } @empty {<div class="empty">Bu filtrelerde kayıt yok.</div>}
      </aside>

      <main class="editor">
        @if(selected();as req){
          <div class="editor-head">
            <div><div class="head-tags"><span [class]="statusClass(req.status)">{{statusLabel(req.status)}}</span><code>{{req.reference}}</code>@if(req.valuation?.valuationStatus==='FINAL'){<span class="final-badge">FINAL v{{req.valuation?.version}}</span>}</div><h3>{{req.carBrand}} {{req.carModel}}</h3><p>{{req.customerName}} · <a [href]="'tel:'+req.customerPhone">{{req.customerPhone}}</a>@if(req.customerEmail){ · <a [href]="'mailto:'+req.customerEmail">{{req.customerEmail}}</a>}</p></div>
            <div class="truth-box"><span>Müşteri fiyat beklentisi</span><strong>{{req.askingPrice?(req.askingPrice|number:'1.0-0')+' TL':'Belirtilmedi'}}</strong><small>Resmi Alperler değerlemesi değildir.</small></div>
          </div>

          <nav class="studio-tabs" aria-label="Değerleme stüdyosu bölümleri">
            <button type="button" [class.active]="tab()==='overview'" (click)="tab.set('overview')">Dosya</button>
            <button type="button" [class.active]="tab()==='valuation'" (click)="tab.set('valuation')">Resmi Değerleme</button>
            <button type="button" [class.active]="tab()==='appointment'" (click)="tab.set('appointment')">Randevu</button>
            <button type="button" [class.active]="tab()==='identity'" (click)="tab.set('identity')">Özel Kimlik</button>
            <button type="button" [class.active]="tab()==='operations'" (click)="tab.set('operations')">Operasyon</button>
          </nav>

          @switch(tab()){
            @case('overview'){
              <div class="editor-grid">
                <section class="card span-2"><h4>Araç ve müşteri özeti</h4><div class="facts"><div><span>Araç</span><b>{{req.carBrand}} {{req.carModel}}</b></div><div><span>Model / KM</span><b>{{req.modelYear||'-'}} / {{req.km==null?'-':(req.km|number:'1.0-0')}}</b></div><div><span>Yakıt / Vites</span><b>{{fuelLabel(req.fuelType)}} / {{transmissionLabel(req.transmission)}}</b></div><div><span>Kasa / Renk</span><b>{{req.bodyType||'-'}} / {{req.exteriorColor||'-'}}</b></div><div><span>Konum</span><b>{{locationLabel(req)}}</b></div><div><span>Sahiplik</span><b>{{ownershipLabel(req.ownershipStatus)}}</b></div><div><span>Ekspertiz raporu</span><b>{{req.expertReportAvailable?'Var':'Yok / belirtilmedi'}}</b></div><div><span>Dosyalar</span><b>{{req.mediaPaths.length}} adet</b></div></div></section>
                @if(req.damageDeclaration){<section class="card"><h4>Hasar beyanı</h4><p class="long-text">{{req.damageDeclaration}}</p></section>}
                @if(req.description){<section class="card"><h4>Müşteri notu</h4><p class="long-text">{{req.description}}</p></section>}
                <section class="card span-2"><div class="card-row"><div><h4>Özel yüklemeler</h4><p>Bağlantılar kısa süreli imzalı URL ile açılır.</p></div><button type="button" (click)="loadMedia(req)" [disabled]="mediaLoading()">{{mediaLoading()?'Hazırlanıyor...':'Dosyaları Güvenli Aç'}}</button></div>@if(media().length){<div class="media-list">@for(item of media();track item.path){<a [href]="item.signedUrl" target="_blank" rel="noopener noreferrer"><span>{{item.originalName||'Dosya'}}</span><small>{{formatBytes(item.size)}}</small></a>}</div>}</section>
              </div>
            }
            @case('valuation'){
              <div class="editor-grid">
                <section class="card span-2 official-card"><div class="card-row"><div><p class="eyebrow">Resmi şirket kararı</p><h4>Değerleme v{{(req.valuation?.version||0)+1}} oluştur</h4></div>@if(req.valuation){<span class="version-pill">Son kayıt: {{req.valuation?.valuationStatus}} v{{req.valuation?.version}}</span>}</div>
                  <div class="form-grid">
                    <label><span>Değerleme durumu *</span><select [ngModel]="valuationStatus()" (ngModelChange)="valuationStatus.set($event)"><option value="DRAFT">DRAFT - taslak</option><option value="FINAL">FINAL - resmi sonuç</option></select></label>
                    <label><span>Kondisyon sınıfı</span><select [ngModel]="conditionGrade()" (ngModelChange)="conditionGrade.set($event)"><option value="">Seç</option><option value="A">A - çok iyi</option><option value="B">B - iyi</option><option value="C">C - orta</option><option value="D">D - yoğun işlem gerekli</option><option value="E">E - yüksek risk</option></select></label>
                    <label><span>Piyasa alt bandı</span><input type="number" min="0" [ngModel]="marketLow()" (ngModelChange)="marketLow.set(toOptionalNumber($event))" /></label>
                    <label><span>Piyasa üst bandı</span><input type="number" min="0" [ngModel]="marketHigh()" (ngModelChange)="marketHigh.set(toOptionalNumber($event))" /></label>
                    <label><span>Teklif modeli *</span><select [ngModel]="offerModel()" (ngModelChange)="offerModel.set($event)"><option value="">Seç</option><option value="PURCHASE">Satın alma</option><option value="MONTHLY_GUARANTEE">Aylık garanti</option><option value="REVENUE_SHARE">Gelir paylaşımı</option><option value="DECLINE">Uygun bulunmadı</option></select></label>
                    <label><span>Para birimi</span><select [ngModel]="currency()" (ngModelChange)="currency.set($event)"><option>TRY</option><option>EUR</option><option>USD</option><option>CHF</option></select></label>
                    @if(offerModel()==='PURCHASE'||offerModel()==='MONTHLY_GUARANTEE'){<label><span>{{offerModel()==='PURCHASE'?'Satın alma teklifi':'Aylık garanti tutarı'}} *</span><input type="number" min="0" [ngModel]="offerAmount()" (ngModelChange)="offerAmount.set(toOptionalNumber($event))" /></label>}
                    @if(offerModel()==='REVENUE_SHARE'){<label><span>Gelir paylaşımı % *</span><input type="number" min="0" max="100" step="0.01" [ngModel]="revenueSharePercent()" (ngModelChange)="revenueSharePercent.set(toOptionalNumber($event))" /></label>}
                    <label><span>Teklif geçerlilik tarihi</span><input type="date" [ngModel]="validUntil()" (ngModelChange)="validUntil.set($event)" /></label>
                    <label class="check"><input type="checkbox" [ngModel]="inspectionRequired()" (ngModelChange)="inspectionRequired.set($event)" /><span>Fiziki ekspertiz zorunlu</span></label>
                    <label class="span-2"><span>Değerleme gerekçesi</span><textarea rows="5" maxlength="4000" [ngModel]="rationale()" (ngModelChange)="rationale.set($event)" placeholder="Piyasa karşılaştırması, kondisyon gerekçesi, riskler ve teklif mantığı"></textarea></label>
                  </div>
                  @if(valuationValidation()){<div class="validation-note">{{valuationValidation()}}</div>}
                  <div class="action-row"><button type="button" class="secondary" (click)="saveValuation('DRAFT')" [disabled]="saving()">Taslak Kaydet</button><button type="button" class="danger-primary" (click)="saveValuation('FINAL')" [disabled]="saving()||Boolean(valuationValidation(true))">FINAL Resmi Değerlemeyi Yayınla</button></div>
                  <p class="integrity-note">FINAL kayıt oluşturulduğunda sistem teklife uygunsa başvuruyu otomatik OFFERED durumuna, DECLINE ise REJECTED durumuna geçirir ve işlem audit trail'e yazılır.</p>
                </section>
                @if(req.valuation){<section class="card span-2"><h4>Son resmi/taslak kayıt</h4><div class="facts"><div><span>Sürüm</span><b>v{{req.valuation?.version}} · {{req.valuation?.valuationStatus}}</b></div><div><span>Kondisyon</span><b>{{req.valuation?.conditionGrade||'-'}}</b></div><div><span>Piyasa bandı</span><b>{{money(req.valuation?.marketLow,req.valuation?.currency)}} - {{money(req.valuation?.marketHigh,req.valuation?.currency)}}</b></div><div><span>Model</span><b>{{offerLabel(req.valuation?.offerModel)}}</b></div><div><span>Teklif</span><b>{{req.valuation?.offerModel==='REVENUE_SHARE'?'%'+(req.valuation?.revenueSharePercent??'-'):money(req.valuation?.offerAmount,req.valuation?.currency)}}</b></div><div><span>Geçerlilik</span><b>{{req.valuation?.validUntil?(req.valuation?.validUntil|date:'dd.MM.yyyy HH:mm'):'-'}}</b></div></div>@if(req.valuation?.rationale){<p class="long-text mt">{{req.valuation?.rationale}}</p>}</section>}
              </div>
            }
            @case('appointment'){
              <div class="editor-grid"><section class="card span-2"><h4>Ekspertiz, teslim veya görüşme randevusu</h4><div class="form-grid">
                <label><span>Randevu türü *</span><select [ngModel]="appointmentType()" (ngModelChange)="appointmentType.set($event)"><option value="INSPECTION">Ekspertiz</option><option value="HANDOVER">Teslim / devir</option><option value="CALL">Telefon görüşmesi</option><option value="OTHER">Diğer</option></select></label>
                <label><span>Tarih ve saat *</span><input type="datetime-local" [ngModel]="appointmentStartsAt()" (ngModelChange)="appointmentStartsAt.set($event)" /></label>
                <label><span>Şube</span><select [ngModel]="appointmentBranchId()" (ngModelChange)="appointmentBranchId.set($event)"><option value="">Şubesiz / uzaktan</option>@for(branch of branches();track branch.cloudId||branch.id){@if(branch.cloudId){<option [value]="branch.cloudId">{{branch.name}} - {{branch.city}} / {{branch.district}}</option>}}</select></label>
                <label><span>Saat dilimi</span><select [ngModel]="appointmentTimezone()" (ngModelChange)="appointmentTimezone.set($event)"><option value="Europe/Istanbul">Europe/Istanbul</option></select></label>
                <label class="span-2"><span>Randevu notu</span><textarea rows="4" maxlength="2000" [ngModel]="appointmentNotes()" (ngModelChange)="appointmentNotes.set($event)"></textarea></label>
              </div><button type="button" class="primary-action wide" (click)="saveAppointment()" [disabled]="saving()||!appointmentStartsAt()">Randevuyu Oluştur ve Bildir</button></section>
              @if(req.appointment){<section class="card span-2"><h4>Son randevu</h4><div class="facts"><div><span>Tarih</span><b>{{req.appointment?.startsAt|date:'dd.MM.yyyy HH:mm'}}</b></div><div><span>Tür</span><b>{{appointmentLabel(req.appointment?.appointmentType)}}</b></div><div><span>Durum</span><b>{{req.appointment?.status}}</b></div><div><span>Şube</span><b>{{branchLabel(req.appointment?.branchId)}}</b></div></div></section>}
              </div>
            }
            @case('identity'){
              <div class="editor-grid"><section class="card span-2 private-card"><p class="eyebrow">Private schema</p><h4>Plaka, VIN ve ruhsat kimliği</h4><p class="subtext">Bu bilgiler public partner_requests satırında tutulmaz. Erişim yalnız yetkili operasyon yöneticisi ve service-role katmanı üzerinden yapılır.</p><div class="form-grid">
                <label><span>Plaka</span><input maxlength="20" autocomplete="off" [ngModel]="licensePlate()" (ngModelChange)="licensePlate.set($event)" /></label>
                <label><span>VIN / Şasi</span><input maxlength="30" autocomplete="off" [ngModel]="vin()" (ngModelChange)="vin.set($event)" /></label>
                <label><span>Ruhsat referansı</span><input maxlength="80" autocomplete="off" [ngModel]="registrationReference()" (ngModelChange)="registrationReference.set($event)" /></label>
                <label class="check"><input type="checkbox" [ngModel]="ownershipConfirmed()" (ngModelChange)="ownershipConfirmed.set($event)" /><span>Sahiplik / yetki doğrulandı</span></label>
              </div><button type="button" class="primary-action wide" (click)="saveIdentity()" [disabled]="saving()">Özel Kimliği Güvenli Kaydet</button></section></div>
            }
            @case('operations'){
              <div class="editor-grid">
                <section class="card"><h4>Durum yönetimi</h4><label><span>Başvuru durumu</span><select [ngModel]="statusDraft()" (ngModelChange)="statusDraft.set($event)"><option value="NEW">Yeni</option><option value="REVIEWING">İnceleniyor</option><option value="CONTACTED">İletişim kuruldu</option><option value="OFFERED" [disabled]="!hasOfferableFinal(req)">Teklif verildi</option><option value="ACCEPTED" [disabled]="!hasOfferableFinal(req)">Kabul edildi</option><option value="REJECTED">Reddedildi</option><option value="CLOSED">Kapalı</option></select></label>@if(!hasOfferableFinal(req)){<p class="guard-note">OFFERED ve ACCEPTED kilitli. Önce DECLINE olmayan bir FINAL resmi değerleme oluşturulmalı.</p>}<label class="mt-label"><span>İç operasyon notu</span><textarea rows="5" maxlength="4000" [ngModel]="internalNotes()" (ngModelChange)="internalNotes.set($event)"></textarea></label><button type="button" class="primary-action wide" (click)="saveStatus()" [disabled]="saving()">Durumu ve Notu Kaydet</button></section>
                <section class="card"><h4>Sorumlu ve sonraki işlem</h4><label><span>Sorumlu kullanıcı UUID</span><input [ngModel]="assignedTo()" (ngModelChange)="assignedTo.set($event)" autocomplete="off" placeholder="Boşsa atama kaldırılır" /></label><label class="mt-label"><span>Sonraki işlem zamanı</span><input type="datetime-local" [ngModel]="nextActionAt()" (ngModelChange)="nextActionAt.set($event)" /></label><button type="button" class="secondary wide" (click)="saveAssignment()" [disabled]="saving()">Atamayı Kaydet</button>@if(req.assignedTo){<p class="subtext mt">Mevcut sorumlu: <code>{{req.assignedTo}}</code></p>}</section>
              </div>
            }
          }
        } @else {<div class="select-placeholder"><strong>Bir başvuru seç</strong><span>Soldaki listeden dosya seçildiğinde değerleme stüdyosu burada açılır.</span></div>}
      </main>
    </div>
  </section>
  `,
  styles:[`
    :host{display:block}.studio-shell{width:min(100%,1440px);margin:auto;padding:1.25rem;color:#0f172a}.studio-hero{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;border-radius:1.5rem;background:linear-gradient(135deg,#07111f,#0f172a 58%,#064e3b);padding:1.5rem;color:#fff;box-shadow:0 24px 70px rgba(15,23,42,.15)}.studio-hero p,.eyebrow{margin:0;color:#6ee7b7;font-size:.62rem;font-weight:950;letter-spacing:.15em;text-transform:uppercase}.studio-hero h2{margin:.2rem 0 0;font-size:1.65rem;font-weight:950;letter-spacing:-.03em}.studio-hero span{display:block;margin-top:.35rem;max-width:780px;color:#cbd5e1;font-size:.72rem;line-height:1.25rem}.primary-action,.secondary,.danger-primary{min-height:44px;border:0;border-radius:.85rem;padding:0 .95rem;font-size:.72rem;font-weight:950;cursor:pointer}.primary-action{background:#34d399;color:#052e16}.secondary{background:#e2e8f0;color:#0f172a}.danger-primary{background:#0f172a;color:#fff}.primary-action:disabled,.secondary:disabled,.danger-primary:disabled{opacity:.45;cursor:not-allowed}.wide{width:100%;margin-top:1rem}.alert-error{margin-top:1rem;border:1px solid #fecaca;border-radius:1rem;background:#fff1f2;padding:.85rem;color:#9f1239;font-size:.75rem;font-weight:850}
    .metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem;margin-top:1rem}.metrics div{border:1px solid #e2e8f0;border-radius:1rem;background:#fff;padding:1rem}.metrics strong{display:block;font-size:1.35rem;font-weight:950}.metrics span{display:block;margin-top:.15rem;color:#64748b;font-size:.62rem;font-weight:850}.toolbar{display:grid;grid-template-columns:1fr 190px 210px;gap:.65rem;margin-top:1rem}.toolbar input,.toolbar select,.card input,.card select,.card textarea{width:100%;min-height:44px;border:1px solid #dbe3ee;border-radius:.8rem;background:#fff;padding:.65rem .8rem;color:#0f172a;font-size:.72rem;font-weight:750;outline:none}.toolbar input:focus,.toolbar select:focus,.card input:focus,.card select:focus,.card textarea:focus{border-color:#10b981;box-shadow:0 0 0 2px rgba(16,185,129,.12)}
    .workspace{display:grid;grid-template-columns:355px minmax(0,1fr);gap:1rem;margin-top:1rem;align-items:start}.records{display:grid;max-height:calc(100vh - 300px);gap:.6rem;overflow:auto;padding-right:.2rem}.record-card{width:100%;border:1px solid #e2e8f0;border-radius:1rem;background:#fff;padding:.9rem;text-align:left;transition:.15s}.record-card:hover,.record-card.active{border-color:#34d399;box-shadow:0 8px 24px rgba(15,23,42,.07)}.record-card.active{background:#f0fdf4}.record-top,.record-meta,.record-foot{display:flex;align-items:center;justify-content:space-between;gap:.5rem}.record-top code{color:#64748b;font-size:.58rem;font-weight:900}.record-card>strong{display:block;margin-top:.65rem;font-size:.83rem;font-weight:950}.record-card>small{display:block;margin-top:.25rem;color:#64748b;font-size:.62rem;font-weight:700}.record-meta{margin-top:.55rem;color:#475569;font-size:.6rem;font-weight:800}.record-foot{margin-top:.7rem;border-top:1px solid #e2e8f0;padding-top:.6rem;font-size:.58rem}.record-foot span{color:#64748b}.record-foot b{color:#047857}.empty{border:1px dashed #cbd5e1;border-radius:1rem;background:#fff;padding:2rem;text-align:center;color:#64748b;font-size:.72rem;font-weight:800}
    .editor{min-height:560px;border:1px solid #e2e8f0;border-radius:1.4rem;background:#fff;overflow:hidden}.editor-head{display:flex;justify-content:space-between;gap:1rem;padding:1.25rem;border-bottom:1px solid #e2e8f0}.head-tags{display:flex;flex-wrap:wrap;align-items:center;gap:.45rem}.head-tags code{color:#64748b;font-size:.65rem;font-weight:900}.editor-head h3{margin:.55rem 0 .15rem;font-size:1.25rem;font-weight:950}.editor-head p{margin:0;color:#64748b;font-size:.7rem;font-weight:750}.editor-head a{color:#0369a1}.truth-box{min-width:220px;border:1px solid #fde68a;border-radius:1rem;background:#fffbeb;padding:.8rem}.truth-box span,.truth-box small{display:block;color:#92400e;font-size:.58rem;font-weight:850}.truth-box strong{display:block;margin:.2rem 0;color:#78350f;font-size:1rem;font-weight:950}.studio-tabs{display:flex;gap:.35rem;overflow:auto;border-bottom:1px solid #e2e8f0;padding:.65rem}.studio-tabs button{min-height:38px;flex:none;border:1px solid #e2e8f0;border-radius:.7rem;background:#fff;padding:0 .75rem;color:#475569;font-size:.64rem;font-weight:900}.studio-tabs button.active{border-color:#10b981;background:#ecfdf5;color:#047857}.editor-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.85rem;padding:1rem}.card{border:1px solid #e2e8f0;border-radius:1rem;background:#f8fafc;padding:1rem}.span-2{grid-column:span 2}.card h4{margin:0;font-size:.82rem;font-weight:950}.card>p.subtext,.subtext{color:#64748b;font-size:.65rem;line-height:1.1rem}.official-card{background:linear-gradient(180deg,#f8fafc,#f0fdf4)}.private-card{background:linear-gradient(180deg,#f8fafc,#eff6ff)}.version-pill,.final-badge{border-radius:999px;background:#dcfce7;padding:.3rem .55rem;color:#166534;font-size:.58rem;font-weight:950}.card-row{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}.card-row p{margin:.25rem 0 0;color:#64748b;font-size:.62rem}.card-row button{min-height:38px;border:0;border-radius:.65rem;background:#e2e8f0;padding:0 .75rem;font-size:.62rem;font-weight:900}.facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.6rem;margin-top:.85rem}.facts div{border-radius:.7rem;background:#fff;padding:.7rem}.facts span{display:block;color:#64748b;font-size:.55rem;font-weight:850;text-transform:uppercase;letter-spacing:.05em}.facts b{display:block;margin-top:.2rem;font-size:.68rem}.long-text{white-space:pre-wrap;overflow-wrap:anywhere;color:#334155;font-size:.68rem;line-height:1.2rem}.mt{margin-top:.85rem}.media-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.5rem;margin-top:.8rem}.media-list a{display:flex;justify-content:space-between;gap:.6rem;border:1px solid #dbeafe;border-radius:.7rem;background:#fff;padding:.65rem;color:#1d4ed8;text-decoration:none;font-size:.62rem;font-weight:850}.media-list span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.media-list small{color:#64748b}
    .form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;margin-top:1rem}.form-grid label>span,.card>label>span{display:block;margin-bottom:.3rem;color:#475569;font-size:.58rem;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.card textarea{resize:vertical;min-height:88px}.check{display:flex;align-items:center;gap:.55rem;border:1px solid #dbe3ee;border-radius:.8rem;background:#fff;padding:.75rem}.check input{width:1rem!important;min-height:auto!important;height:1rem;flex:none}.check span{margin:0!important;text-transform:none!important}.action-row{display:flex;justify-content:flex-end;gap:.6rem;margin-top:1rem}.validation-note,.guard-note,.integrity-note{margin-top:.8rem;border-radius:.75rem;padding:.7rem;font-size:.62rem;font-weight:800;line-height:1.05rem}.validation-note{background:#fff1f2;color:#9f1239}.guard-note{background:#fffbeb;color:#92400e}.integrity-note{background:#ecfdf5;color:#065f46}.mt-label{display:block;margin-top:.75rem}.select-placeholder{display:flex;min-height:560px;align-items:center;justify-content:center;flex-direction:column;gap:.35rem;text-align:center;color:#64748b}.select-placeholder strong{color:#0f172a;font-size:1rem}.select-placeholder span{font-size:.7rem}.status-chip{display:inline-flex;border-radius:999px;padding:.28rem .5rem;font-size:.54rem;font-weight:950;text-transform:uppercase}.status-new{background:#dbeafe;color:#1d4ed8}.status-review{background:#fef3c7;color:#92400e}.status-contact{background:#e0e7ff;color:#4338ca}.status-offer{background:#dcfce7;color:#166534}.status-accept{background:#bbf7d0;color:#14532d}.status-reject{background:#ffe4e6;color:#9f1239}.status-closed{background:#e2e8f0;color:#475569}
    @media(max-width:1050px){.workspace{grid-template-columns:1fr}.records{max-height:none;grid-template-columns:repeat(2,minmax(0,1fr))}.editor{min-height:0}}@media(max-width:760px){.studio-shell{padding:.75rem}.studio-hero{flex-direction:column}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.toolbar{grid-template-columns:1fr}.records{grid-template-columns:1fr}.editor-head{flex-direction:column}.truth-box{min-width:0}.editor-grid,.form-grid,.facts{grid-template-columns:1fr}.span-2{grid-column:span 1}.media-list{grid-template-columns:1fr}.action-row{flex-direction:column}.action-row button{width:100%}}
  `]
})
export class AdminVehicleValuationStudioV172Component implements OnInit{
  readonly service=inject(VehicleValuationV172Service);readonly geo=inject(GeoDirectoryService);private readonly branchSource=inject(BranchPublicV171Service);private readonly mediaSource=inject(PartnerMediaService);private readonly toast=inject(ToastService);private readonly confirm=inject(ConfirmService);
  readonly searchQuery=signal("");readonly statusFilter=signal<"ALL"|PartnerStatus>("ALL");readonly modelFilter=signal("ALL");readonly selectedReference=signal("");readonly tab=signal<StudioTab>("overview");readonly saving=signal(false);readonly mediaLoading=signal(false);readonly media=signal<PartnerMediaItem[]>([]);readonly branches=signal<Branch[]>([]);
  readonly valuationStatus=signal<ValuationStatusV172>("DRAFT");readonly conditionGrade=signal("");readonly marketLow=signal<number|null>(null);readonly marketHigh=signal<number|null>(null);readonly offerModel=signal<OfferModelV172|"">("");readonly offerAmount=signal<number|null>(null);readonly revenueSharePercent=signal<number|null>(null);readonly currency=signal("TRY");readonly inspectionRequired=signal(true);readonly rationale=signal("");readonly validUntil=signal("");
  readonly appointmentType=signal("INSPECTION");readonly appointmentStartsAt=signal("");readonly appointmentBranchId=signal("");readonly appointmentTimezone=signal("Europe/Istanbul");readonly appointmentNotes=signal("");
  readonly licensePlate=signal("");readonly vin=signal("");readonly registrationReference=signal("");readonly ownershipConfirmed=signal(false);
  readonly statusDraft=signal<Exclude<PartnerStatus,"UPLOADING">>("NEW");readonly internalNotes=signal("");readonly assignedTo=signal("");readonly nextActionAt=signal("");

  readonly selected=computed(()=>this.service.records().find(row=>row.reference===this.selectedReference())||null);
  readonly openCount=computed(()=>this.service.records().filter(row=>!["REJECTED","CLOSED"].includes(row.status)).length);
  readonly finalCount=computed(()=>this.service.records().filter(row=>row.valuation?.valuationStatus==="FINAL").length);
  readonly appointmentCount=computed(()=>this.service.records().filter(row=>Boolean(row.appointment)).length);
  readonly filteredRecords=computed(()=>{const q=this.searchQuery().trim().toLocaleLowerCase("tr-TR"),status=this.statusFilter(),model=this.modelFilter();return this.service.records().filter(row=>status==="ALL"||row.status===status).filter(row=>model==="ALL"||(model==="NONE"?!row.valuation:row.valuation?.offerModel===model)).filter(row=>!q||`${row.reference} ${row.customerName} ${row.customerPhone} ${row.customerEmail||""} ${row.carBrand} ${row.carModel}`.toLocaleLowerCase("tr-TR").includes(q));});

  async ngOnInit(){await Promise.allSettled([this.geo.ensureLoaded(),this.loadBranches(),this.refresh()]);}
  async loadBranches(){try{this.branches.set(await this.branchSource.list());}catch{this.branches.set([]);}}
  async refresh(){try{await this.service.refreshAdmin();if(this.selectedReference()&&!this.selected())this.selectedReference.set("");}catch{this.toast.show("V172 değerleme kayıtları yüklenemedi.","error");}}
  open(req:ValuationSnapshotV172){this.selectedReference.set(req.reference);this.tab.set("overview");this.media.set([]);this.loadEditor(req);}
  private loadEditor(req:ValuationSnapshotV172){const v=req.valuation;this.valuationStatus.set(v?.valuationStatus==="FINAL"?"DRAFT":((v?.valuationStatus as ValuationStatusV172)||"DRAFT"));this.conditionGrade.set(v?.conditionGrade||"");this.marketLow.set(v?.marketLow??null);this.marketHigh.set(v?.marketHigh??null);this.offerModel.set(v?.offerModel||"");this.offerAmount.set(v?.offerAmount??null);this.revenueSharePercent.set(v?.revenueSharePercent??null);this.currency.set(v?.currency||"TRY");this.inspectionRequired.set(v?.inspectionRequired!==false);this.rationale.set(v?.rationale||"");this.validUntil.set(this.dateInput(v?.validUntil));this.appointmentType.set(req.appointment?.appointmentType||"INSPECTION");this.appointmentBranchId.set(req.appointment?.branchId||req.preferredBranchId||"");this.appointmentTimezone.set(req.appointment?.timezone||"Europe/Istanbul");this.appointmentNotes.set(req.appointment?.notes||"");this.licensePlate.set(req.identity?.licensePlate||"");this.vin.set(req.identity?.vin||"");this.registrationReference.set(req.identity?.registrationReference||"");this.ownershipConfirmed.set(Boolean(req.identity?.ownershipConfirmed));this.statusDraft.set(req.status==="UPLOADING"?"NEW":req.status);this.internalNotes.set(req.internalNotes||"");this.assignedTo.set(req.assignedTo||"");this.nextActionAt.set(this.dateTimeInput(req.nextActionAt));}
  valuationValidation(finalOnly=false){const low=this.marketLow(),high=this.marketHigh(),offer=this.offerModel(),amount=this.offerAmount(),share=this.revenueSharePercent();if(low!==null&&low<0||high!==null&&high<0)return "Piyasa değerleri negatif olamaz.";if(low!==null&&high!==null&&high<low)return "Piyasa üst bandı alt bandın altında olamaz.";if(finalOnly||this.valuationStatus()==="FINAL"){if(!offer)return "FINAL değerleme için teklif modeli zorunludur.";if(!this.conditionGrade())return "FINAL değerleme için A-E kondisyon sınıfı zorunludur.";if((offer==="PURCHASE"||offer==="MONTHLY_GUARANTEE")&&(amount===null||amount<0))return "Bu teklif modeli için tutar zorunludur.";if(offer==="REVENUE_SHARE"&&(share===null||share<0||share>100))return "Gelir paylaşımı yüzdesi 0-100 arasında olmalıdır.";}return "";}
  async saveValuation(status:ValuationStatusV172){const req=this.selected();if(!req||this.saving())return;this.valuationStatus.set(status);const invalid=this.valuationValidation(status==="FINAL");if(invalid){this.toast.show(invalid,"error");return;}if(status==="FINAL"){const ok=await this.confirm.confirm({title:"FINAL resmi değerleme",message:"Bu işlem yeni bir resmi değerleme sürümü oluşturur, müşteriye bildirim gönderebilir ve başvuru durumunu otomatik değiştirebilir. Devam edilsin mi?",confirmText:"FINAL Yayınla"});if(!ok)return;}this.saving.set(true);try{await this.service.saveValuation(req.reference,{valuationStatus:status,conditionGrade:this.conditionGrade()||undefined,marketLow:this.marketLow(),marketHigh:this.marketHigh(),offerModel:this.offerModel()||undefined,offerAmount:this.offerAmount(),revenueSharePercent:this.revenueSharePercent(),currency:this.currency(),inspectionRequired:this.inspectionRequired(),rationale:this.rationale().trim()||undefined,validUntil:this.validUntil()?`${this.validUntil()}T23:59:59+03:00`:null});const fresh=this.selected();if(fresh)this.loadEditor(fresh);this.toast.show(status==="FINAL"?"FINAL resmi değerleme oluşturuldu.":"Değerleme taslağı kaydedildi.","success");}catch(error){this.toast.show(this.errorText(error),"error");}finally{this.saving.set(false);}}
  async saveAppointment(){const req=this.selected();if(!req||!this.appointmentStartsAt()||this.saving())return;this.saving.set(true);try{await this.service.scheduleAppointment(req.reference,{branchId:this.appointmentBranchId()||undefined,startsAt:`${this.appointmentStartsAt()}:00+03:00`,timezone:this.appointmentTimezone(),appointmentType:this.appointmentType(),notes:this.appointmentNotes().trim()||undefined});this.toast.show("Randevu oluşturuldu ve bildirim süreci çalıştırıldı.","success");}catch(error){this.toast.show(this.errorText(error),"error");}finally{this.saving.set(false);}}
  async saveIdentity(){const req=this.selected();if(!req||this.saving())return;const cleanVin=this.vin().replace(/[^A-HJ-NPR-Z0-9]/gi,"").toUpperCase();if(cleanVin&&cleanVin.length!==17){this.toast.show("VIN tam 17 geçerli karakter olmalıdır.","error");return;}this.saving.set(true);try{await this.service.saveIdentity(req.reference,{licensePlate:this.licensePlate().trim()||undefined,vin:cleanVin||undefined,registrationReference:this.registrationReference().trim()||undefined,ownershipConfirmed:this.ownershipConfirmed()});this.toast.show("Özel araç kimliği güvenli alana kaydedildi.","success");}catch(error){this.toast.show(this.errorText(error),"error");}finally{this.saving.set(false);}}
  async saveStatus(){const req=this.selected(),status=this.statusDraft();if(!req||this.saving())return;if((status==="OFFERED"||status==="ACCEPTED")&&!this.hasOfferableFinal(req)){this.toast.show("FINAL ve DECLINE olmayan resmi değerleme olmadan bu durum kullanılamaz.","error");return;}this.saving.set(true);try{await this.service.updateStatus(req.reference,status,this.internalNotes().trim());this.toast.show("Başvuru durumu kaydedildi.","success");}catch(error){this.toast.show(this.errorText(error),"error");}finally{this.saving.set(false);}}
  async saveAssignment(){const req=this.selected();if(!req||this.saving())return;const user=this.assignedTo().trim();if(user&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(user)){this.toast.show("Sorumlu kullanıcı kimliği geçerli UUID olmalıdır.","error");return;}this.saving.set(true);try{await this.service.assign(req.reference,{assignedTo:user||undefined,nextActionAt:this.nextActionAt()?new Date(this.nextActionAt()).toISOString():undefined});this.toast.show("Sorumlu ve sonraki işlem kaydedildi.","success");}catch(error){this.toast.show(this.errorText(error),"error");}finally{this.saving.set(false);}}
  async loadMedia(req:ValuationSnapshotV172){if(this.mediaLoading())return;this.mediaLoading.set(true);try{this.media.set(await this.mediaSource.getSignedMedia(req.reference));if(!this.media().length)this.toast.show("Bu başvuruda açılabilir özel dosya yok.","info");}catch{this.toast.show("Özel dosyalar için imzalı bağlantı oluşturulamadı.","error");}finally{this.mediaLoading.set(false);}}
  hasOfferableFinal(req:ValuationSnapshotV172){return req.valuation?.valuationStatus==="FINAL"&&Boolean(req.valuation?.offerModel)&&req.valuation?.offerModel!=="DECLINE";}
  toOptionalNumber(value:unknown){if(value===null||value===undefined||value==="")return null;const n=Number(value);return Number.isFinite(n)?n:null;}
  locationLabel(req:ValuationSnapshotV172){const province=this.geo.province(req.provinceCode||"")?.name, district=this.geo.district(req.districtCode||"")?.name;return [province,district].filter(Boolean).join(" / ")||"Belirtilmedi";}
  branchLabel(id?:string){if(!id)return "Şubesiz / uzaktan";return this.branches().find(branch=>branch.cloudId===id||branch.id===id)?.name||id;}
  fuelLabel(v?:string){return({GASOLINE:"Benzin",DIESEL:"Dizel",LPG:"LPG",HYBRID:"Hibrit",ELECTRIC:"Elektrik",OTHER:"Diğer"} as Record<string,string>)[v||""]||"-";}
  transmissionLabel(v?:string){return({AUTOMATIC:"Otomatik",MANUAL:"Manuel",SEMI_AUTOMATIC:"Yarı otomatik",OTHER:"Diğer"} as Record<string,string>)[v||""]||"-";}
  ownershipLabel(v?:string){return({OWNER:"Araç sahibi",AUTHORIZED_SELLER:"Yetkili satıcı",COMPANY_VEHICLE:"Şirket aracı",OTHER:"Diğer"} as Record<string,string>)[v||""]||"-";}
  offerLabel(v?:string){return({PURCHASE:"Satın alma",MONTHLY_GUARANTEE:"Aylık garanti",REVENUE_SHARE:"Gelir paylaşımı",DECLINE:"Uygun bulunmadı"} as Record<string,string>)[v||""]||"-";}
  appointmentLabel(v?:string){return({INSPECTION:"Ekspertiz",HANDOVER:"Teslim / devir",CALL:"Telefon görüşmesi",OTHER:"Diğer"} as Record<string,string>)[v||""]||v||"-";}
  statusLabel(status:PartnerStatus){return({UPLOADING:"Yükleniyor",NEW:"Yeni",REVIEWING:"İnceleniyor",CONTACTED:"İletişim",OFFERED:"Teklif",ACCEPTED:"Kabul",REJECTED:"Red",CLOSED:"Kapalı"} as Record<PartnerStatus,string>)[status];}
  statusClass(status:PartnerStatus){const map:Record<PartnerStatus,string>={UPLOADING:"status-chip status-review",NEW:"status-chip status-new",REVIEWING:"status-chip status-review",CONTACTED:"status-chip status-contact",OFFERED:"status-chip status-offer",ACCEPTED:"status-chip status-accept",REJECTED:"status-chip status-reject",CLOSED:"status-chip status-closed"};return map[status];}
  money(value?:number,currency="TRY"){return value==null?"-":`${new Intl.NumberFormat("tr-TR",{maximumFractionDigits:2}).format(value)} ${currency}`;}
  formatBytes(bytes:number){return bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;}
  private dateInput(value?:Date){if(!value||Number.isNaN(value.getTime()))return "";return value.toISOString().slice(0,10);}
  private dateTimeInput(value?:Date){if(!value||Number.isNaN(value.getTime()))return "";const local=new Date(value.getTime()-value.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
  private errorText(error:unknown){const code=error instanceof Error?error.message:"";if(code.includes("PARTNER_FINAL_VALUATION_REQUIRED"))return "FINAL resmi değerleme olmadan teklif veya kabul durumuna geçilemez.";if(code.includes("INVALID_VIN"))return "VIN doğrulanamadı.";if(code.includes("ADMIN_SESSION_REQUIRED"))return "Yönetici oturumu gerekli.";return code||"V172 işlemi tamamlanamadı.";}
}
