import { createHmac, timingSafeEqual } from 'node:crypto';
import { getPaymentConfig, isAllowedRequestOrigin } from './_lib/integration-config';
import { resolveIyzicoCredentials } from './_lib/payment-provider-credentials';

type Json = Record<string, unknown>;
type AuthUser = { id: string; email?: string | null; email_confirmed_at?: string | null };
type PublicMethod = { id:string; provider:string; provider_environment:string; brand:string|null; last4:string|null; expiry_month:number|null; expiry_year:number|null; label:string|null; is_default:boolean; status:string };
type BookingRow = { id:string; reference:string; item_name:string; customer_name:string; customer_email:string|null; customer_phone:string; total_price:number|null; currency:string; payment_method:string; payment_status:string; customer_user_id:string|null; pickup_location:string|null };
type PaymentSettingsRow = { provider:string; card_enabled:boolean; deposit_mode:string; deposit_value:number; currency:string; test_mode:boolean };
type PaymentClaim = { id:string; status:string; provider_reference:string|null; created_at:string };
type ChargeBody = { bookingReference?:unknown; paymentMethodId?:unknown; method?:unknown; customer?:{name?:unknown;email?:unknown;phone?:unknown;identityNumber?:unknown;billingAddress?:unknown;city?:unknown;country?:unknown;zipCode?:unknown} };

type ProviderCard = {
  cardToken?: unknown; cardAlias?: unknown; lastFourDigits?: unknown; cardAssociation?: unknown;
  cardFamily?: unknown; cardBankName?: unknown; expireMonth?: unknown; expireYear?: unknown; binNumber?: unknown;
};

function json(body:unknown,status=200):Response{return Response.json(body,{status,headers:{'cache-control':'private, no-store, max-age=0','content-type':'application/json; charset=utf-8','x-content-type-options':'nosniff'}});}
function clean(value:unknown,max:number):string{return typeof value==='string'?value.trim().slice(0,max):'';}
function digits(value:unknown,max=32):string{return clean(value,max).replace(/\D/g,'');}
function sameHash(a:string,b:string):boolean{const aa=Buffer.from(a);const bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);}
function hmacHex(value:string,key:string):string{return createHmac('sha256',key).update(value,'utf8').digest('hex');}
function base64(value:string):string{return Buffer.from(value,'utf8').toString('base64');}
function serviceConfig(){const url=process.env.SUPABASE_PROJECT_URL?.trim()||process.env.SUPABASE_URL?.trim()||'';const key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()||'';return{url,key,configured:Boolean(url&&key)};}
function serviceHeaders(){const cfg=serviceConfig();return{apikey:cfg.key,authorization:`Bearer ${cfg.key}`,'content-type':'application/json',accept:'application/json'};}
async function db<T>(path:string,init:RequestInit={}):Promise<T>{const cfg=serviceConfig();if(!cfg.configured)throw new Error('WALLET_DATABASE_NOT_CONFIGURED');const response=await fetch(`${cfg.url}/rest/v1/${path}`,{...init,headers:{...serviceHeaders(),...(init.headers||{})},cache:'no-store',signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`WALLET_DATABASE_${response.status}`);if(response.status===204)return undefined as T;return await response.json() as T;}
async function rpc<T>(name:string,body:Json):Promise<T>{return db<T>(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)});}
async function authenticatedUser(request:Request):Promise<AuthUser>{const authorization=request.headers.get('authorization')||'';if(!/^Bearer\s+\S+/i.test(authorization))throw new Error('UNAUTHORIZED');const cfg=serviceConfig();if(!cfg.configured)throw new Error('WALLET_DATABASE_NOT_CONFIGURED');const response=await fetch(`${cfg.url}/auth/v1/user`,{headers:{apikey:cfg.key,authorization},cache:'no-store',signal:AbortSignal.timeout(8000)});const user=await response.json().catch(()=>({})) as AuthUser;if(!response.ok||!user.id||!user.email_confirmed_at)throw new Error('UNAUTHORIZED');return user;}
async function paymentSettings():Promise<PaymentSettingsRow>{const rows=await db<PaymentSettingsRow[]>('payment_settings?config_key=eq.main&select=provider,card_enabled,deposit_mode,deposit_value,currency,test_mode&limit=1');return rows[0]||{provider:'NONE',card_enabled:false,deposit_mode:'NONE',deposit_value:0,currency:'TRY',test_mode:true};}
async function testMode():Promise<boolean>{return (await paymentSettings()).test_mode!==false;}
function environment(test:boolean):'sandbox'|'live'{return test?'sandbox':'live';}
function luhn(value:string):boolean{let sum=0,alt=false;for(let i=value.length-1;i>=0;i--){let n=Number(value[i]);if(alt){n*=2;if(n>9)n-=9;}sum+=n;alt=!alt;}return value.length>=13&&value.length<=19&&sum%10===0;}
function expiryValid(month:number,year:number):boolean{if(month<1||month>12||year<2026||year>2200)return false;const now=new Date();return year>now.getFullYear()||year===now.getFullYear()&&month>=now.getMonth()+1;}
function iyzicoAuthorization(path:string,body:string,apiKey:string,secretKey:string):{authorization:string;randomKey:string}{const randomKey=`${Date.now()}${crypto.randomUUID().replace(/-/g,'').slice(0,12)}`;const signature=hmacHex(`${randomKey}${path}${body}`,secretKey);return{authorization:`IYZWSv2 ${base64(`apiKey:${apiKey}&randomKey:${randomKey}&signature:${signature}`)}`,randomKey};}
async function iyzicoRequest(method:'POST'|'DELETE',path:string,payload:Json,test:boolean):Promise<Json>{const credentials=await resolveIyzicoCredentials(test);if(!credentials.configured||!credentials.apiKey||!credentials.secretKey)throw new Error(test?'IYZICO_SANDBOX_NOT_CONFIGURED':'IYZICO_LIVE_NOT_CONFIGURED');const body=JSON.stringify(payload);const auth=iyzicoAuthorization(path,body,credentials.apiKey,credentials.secretKey);const response=await fetch(`${credentials.baseUrl}${path}`,{method,headers:{authorization:auth.authorization,'x-iyzi-rnd':auth.randomKey,'content-type':'application/json'},body,cache:'no-store',signal:AbortSignal.timeout(15000)});const result=await response.json().catch(()=>({})) as Json;if(!response.ok)throw new Error(`IYZICO_HTTP_${response.status}`);return result;}
function providerFailure(result:Json):never{const errorCode=clean(String(result.errorCode??''),40);if(errorCode==='3007')throw new Error('CARD_STORAGE_NOT_ENABLED');throw new Error(`IYZICO_CARD_${errorCode||'FAILED'}`);}
async function cardUserKey(userId:string,test:boolean):Promise<string>{return clean(await rpc<string|null>('service_customer_card_user_key_v225',{p_user_id:userId,p_test_mode:test}),500);}
async function setCardUserKey(userId:string,test:boolean,key:string):Promise<void>{await rpc('service_set_customer_card_user_key_v225',{p_user_id:userId,p_test_mode:test,p_card_user_key:key});}
async function syncCard(userId:string,test:boolean,userKey:string,card:ProviderCard,submitted?:{month:number;year:number;label:string}):Promise<string>{const token=clean(card.cardToken,500);const last4=digits(card.lastFourDigits,8).slice(-4);if(!token||last4.length!==4)throw new Error('IYZICO_CARD_RESPONSE_INVALID');const month=Number(card.expireMonth||submitted?.month||0)||null;const year=Number(card.expireYear||submitted?.year||0)||null;const brand=clean(card.cardAssociation||card.cardFamily||card.cardBankName,80)||'Kart';const label=clean(card.cardAlias,80)||submitted?.label||`${brand} •••• ${last4}`;return await rpc<string>('service_sync_customer_payment_method_v225',{p_user_id:userId,p_provider:'IYZICO',p_environment:environment(test),p_provider_customer_ref:userKey,p_provider_payment_method_ref:token,p_brand:brand,p_last4:last4,p_expiry_month:month,p_expiry_year:year,p_label:label,p_provider_fingerprint:clean(card.binNumber,16)||null});}
async function localCards(userId:string,test:boolean):Promise<PublicMethod[]>{return db<PublicMethod[]>(`customer_payment_methods?user_id=eq.${encodeURIComponent(userId)}&provider=eq.IYZICO&provider_environment=eq.${environment(test)}&status=eq.ACTIVE&select=id,provider,provider_environment,brand,last4,expiry_month,expiry_year,label,is_default,status&order=is_default.desc,created_at.asc`);}
function customerCard(row:PublicMethod){return{id:row.id,brand:row.brand||'Kart',last4:row.last4||'••••',expiryMonth:row.expiry_month,expiryYear:row.expiry_year,label:row.label||`${row.brand||'Kart'} •••• ${row.last4||''}`,isDefault:row.is_default};}

async function listCards(request:Request):Promise<Response>{const user=await authenticatedUser(request);const test=await testMode();const credentials=await resolveIyzicoCredentials(test);if(!credentials.configured)return json({ok:true,available:false,cards:[]});const userKey=await cardUserKey(user.id,test);if(!userKey)return json({ok:true,available:true,cards:[]});let refreshed=true;try{const result=await iyzicoRequest('POST','/cardstorage/cards',{locale:'tr',conversationId:`wallet-${crypto.randomUUID()}`,cardUserKey:userKey},test);if(result.status!=='success')providerFailure(result);const cards=Array.isArray(result.cardDetails)?result.cardDetails as ProviderCard[]:[];for(const card of cards)await syncCard(user.id,test,userKey,card);}catch(error){refreshed=false;console.error('Saved-card refresh failed',error instanceof Error?error.message:'WALLET_REFRESH_FAILED');}const cards=await localCards(user.id,test);return json({ok:true,available:true,refreshed,cards:cards.map(customerCard)});}

async function addCard(request:Request):Promise<Response>{if(!isAllowedRequestOrigin(request))return json({ok:false,code:'ORIGIN_NOT_ALLOWED'},403);const user=await authenticatedUser(request);const test=await testMode();const credentials=await resolveIyzicoCredentials(test);if(!credentials.configured)return json({ok:false,code:'SAVED_CARDS_NOT_CONFIGURED'},503);const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>4096)return json({ok:false,code:'PAYLOAD_TOO_LARGE'},413);let body:Json;try{body=JSON.parse(raw) as Json;}catch{return json({ok:false,code:'INVALID_JSON'},400);}const cardNumber=digits(body.cardNumber,32);const holderName=clean(body.cardHolderName,100);const alias=clean(body.cardAlias,80)||'Kartım';const month=Number(digits(body.expireMonth,2));let year=Number(digits(body.expireYear,4));if(year>0&&year<100)year+=2000;if(!luhn(cardNumber)||holderName.length<2||!expiryValid(month,year))return json({ok:false,code:'INVALID_CARD_DETAILS'},400);const existingKey=await cardUserKey(user.id,test);const payload:Json={locale:'tr',conversationId:`wallet-${crypto.randomUUID()}`,card:{cardAlias:alias,cardNumber,expireYear:String(year),expireMonth:String(month).padStart(2,'0'),cardHolderName:holderName}};if(existingKey)payload.cardUserKey=existingKey;else{payload.externalId=user.id;payload.email=user.email||'';}const result=await iyzicoRequest('POST','/cardstorage/card',payload,test);if(result.status!=='success')providerFailure(result);const userKey=clean(result.cardUserKey,500)||existingKey;if(!userKey)return json({ok:false,code:'CARD_STORAGE_RESPONSE_INVALID'},502);await setCardUserKey(user.id,test,userKey);const methodId=await syncCard(user.id,test,userKey,result as ProviderCard,{month,year,label:alias});const cards=await localCards(user.id,test);return json({ok:true,id:methodId,cards:cards.map(customerCard)},201);}

async function removeCard(request:Request):Promise<Response>{if(!isAllowedRequestOrigin(request))return json({ok:false,code:'ORIGIN_NOT_ALLOWED'},403);const user=await authenticatedUser(request);let body:Json;try{body=await request.json() as Json;}catch{return json({ok:false,code:'INVALID_JSON'},400);}const methodId=clean(body.id,80);if(!/^[0-9a-f-]{36}$/i.test(methodId))return json({ok:false,code:'INVALID_PAYMENT_METHOD'},400);const token=await rpc<Json|null>('service_customer_payment_method_token_v225',{p_user_id:user.id,p_method_id:methodId});if(!token)return json({ok:false,code:'PAYMENT_METHOD_NOT_FOUND'},404);const provider=clean(token.provider,20);const providerToken=clean(token.providerPaymentMethodRef,500);const userKey=clean(token.providerCustomerRef,500);const env=clean(token.environment,20);if(provider!=='IYZICO'||!providerToken||!userKey||!['sandbox','live'].includes(env))return json({ok:false,code:'PAYMENT_METHOD_NOT_REMOVABLE'},409);const test=env==='sandbox';const result=await iyzicoRequest('DELETE','/cardstorage/card',{locale:'tr',conversationId:`wallet-${crypto.randomUUID()}`,cardUserKey:userKey,cardToken:providerToken},test);const code=clean(String(result.errorCode??''),40);if(result.status!=='success'&&code!=='3006')providerFailure(result);await rpc('service_revoke_customer_payment_method_v225',{p_user_id:user.id,p_method_id:methodId});const cards=await localCards(user.id,test);return json({ok:true,cards:cards.map(customerCard)});}

async function setDefault(request:Request):Promise<Response>{if(!isAllowedRequestOrigin(request))return json({ok:false,code:'ORIGIN_NOT_ALLOWED'},403);const user=await authenticatedUser(request);let body:Json;try{body=await request.json() as Json;}catch{return json({ok:false,code:'INVALID_JSON'},400);}const methodId=clean(body.id,80);const owned=await db<Array<{id:string}>>(`customer_payment_methods?id=eq.${encodeURIComponent(methodId)}&user_id=eq.${encodeURIComponent(user.id)}&status=eq.ACTIVE&select=id&limit=1`);if(!owned[0])return json({ok:false,code:'PAYMENT_METHOD_NOT_FOUND'},404);await db(`customer_payment_methods?user_id=eq.${encodeURIComponent(user.id)}&is_default=eq.true`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_default:false,updated_at:new Date().toISOString()})});await db(`customer_payment_methods?id=eq.${encodeURIComponent(methodId)}&user_id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({is_default:true,updated_at:new Date().toISOString()})});return listCards(request);}

function paymentSignatureValue(field:string,value:unknown):string{const raw=String(value??'');if((field==='price'||field==='paidPrice')&&/^-?\d+(?:\.\d+)?$/.test(raw)){const[int,decimal='']=raw.split('.');const trimmed=decimal.replace(/0+$/,'');return trimmed?`${int}.${trimmed}`:int;}return raw;}
function verifyPaymentSignature(result:Json,secretKey:string):boolean{const signature=clean(result.signature,256);if(!signature)return false;const fields=['paymentId','currency','basketId','conversationId','paidPrice','price'];const expected=hmacHex(fields.map(field=>paymentSignatureValue(field,result[field])).join(':'),secretKey);return sameHash(expected.toLowerCase(),signature.toLowerCase());}
function calculateCharge(total:number,settings:PaymentSettingsRow):number{if(!Number.isFinite(total)||total<=0)throw new Error('INVALID_BOOKING_TOTAL');const mode=String(settings.deposit_mode||'NONE');const value=Number(settings.deposit_value||0);if(mode==='PERCENT'&&value>0)return Math.max(1,Math.round(total*Math.min(100,value)/100*100)/100);if(mode==='FIXED'&&value>0)return Math.max(1,Math.min(total,Math.round(value*100)/100));return Math.round(total*100)/100;}
function splitName(full:string):{name:string;surname:string}{const parts=full.trim().split(/\s+/).filter(Boolean);if(parts.length<2)throw new Error('PAYMENT_SURNAME_REQUIRED');return{name:parts.slice(0,-1).join(' ').slice(0,80),surname:parts.at(-1)!.slice(0,80)};}
async function booking(reference:string):Promise<BookingRow>{const rows=await db<BookingRow[]>(`bookings?reference=eq.${encodeURIComponent(reference)}&deleted_at=is.null&select=id,reference,item_name,customer_name,customer_email,customer_phone,total_price,currency,payment_method,payment_status,customer_user_id,pickup_location&limit=1`);if(!rows[0])throw new Error('BOOKING_NOT_FOUND');return rows[0];}
async function claimPayment(bookingRow:BookingRow,methodId:string,amount:number,currency:string):Promise<{claim:PaymentClaim;fresh:boolean}>{const idempotencyKey=`iyzico:saved:${bookingRow.id}:${methodId}`;const inserted=await db<PaymentClaim[]>(`payment_transactions?on_conflict=idempotency_key&select=id,status,provider_reference,created_at`,{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:JSON.stringify({booking_id:bookingRow.id,provider:'iyzico',provider_reference:`saved-${bookingRow.id}`,idempotency_key:idempotencyKey,amount,currency,status:'PENDING',request_snapshot:{bookingReference:bookingRow.reference,paymentMethodId:methodId,storedCard:true},response_snapshot:{phase:'CLAIMED'}})});if(inserted[0])return{claim:inserted[0],fresh:true};const rows=await db<PaymentClaim[]>(`payment_transactions?idempotency_key=eq.${encodeURIComponent(idempotencyKey)}&select=id,status,provider_reference,created_at&limit=1`);if(!rows[0])throw new Error('PAYMENT_CLAIM_FAILED');return{claim:rows[0],fresh:false};}
async function settleClaim(claimId:string,bookingId:string,status:'PAID'|'AUTHORIZED'|'FAILED',providerReference:string|null,result:Json,signatureValid:boolean):Promise<void>{const bookingStatus=status==='PAID'?'PAID':status==='FAILED'?'FAILED':'PENDING';await db(`payment_transactions?id=eq.${encodeURIComponent(claimId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status,provider_reference:providerReference,response_snapshot:{paymentStatus:result.paymentStatus||null,paymentId:result.paymentId||null,paidPrice:Number(result.paidPrice),currency:result.currency||null,fraudStatus:Number(result.fraudStatus),signatureValid},updated_at:new Date().toISOString()})});await db(`bookings?id=eq.${encodeURIComponent(bookingId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({payment_status:bookingStatus,external_payment_reference:providerReference,updated_at:new Date().toISOString()})});}

async function chargeSavedCard(request:Request):Promise<Response>{
  if(!isAllowedRequestOrigin(request))return json({ok:false,code:'ORIGIN_NOT_ALLOWED'},403);
  if(Number(request.headers.get('content-length')||0)>16_384)return json({ok:false,code:'PAYLOAD_TOO_LARGE'},413);
  let body:ChargeBody;try{body=await request.json() as ChargeBody;}catch{return json({ok:false,code:'INVALID_JSON'},400);}
  const reference=clean(body.bookingReference,128),methodId=clean(body.paymentMethodId,80);
  if(!reference||!/^[0-9a-f-]{36}$/i.test(methodId)||body.method!=='CARD')return json({ok:false,code:'INVALID_SAVED_CARD_PAYMENT_REQUEST'},400);
  const user=await authenticatedUser(request);const [bookingRow,settings]=await Promise.all([booking(reference),paymentSettings()]);const globalConfig=getPaymentConfig();
  if(!globalConfig.cardEnabled||!settings.card_enabled)return json({ok:false,status:'not_configured',provider:'iyzico',code:'CARD_DISABLED_BY_ADMIN'},409);
  if(String(settings.provider||'').toUpperCase()!=='IYZICO')return json({ok:false,status:'rejected',provider:settings.provider==='PAYTR'?'paytr':'none',code:'SAVED_CARD_PROVIDER_MISMATCH',message:'Kayıtlı kartla ödeme yalnız iyzico aktif ödeme sağlayıcısıyken kullanılabilir.'},409);
  if(bookingRow.customer_user_id!==user.id)return json({ok:false,status:'rejected',provider:'iyzico',code:'BOOKING_ACCESS_DENIED'},403);
  if(bookingRow.payment_status==='PAID')return json({ok:false,status:'rejected',provider:'iyzico',code:'BOOKING_ALREADY_PAID'},409);
  if(bookingRow.payment_method!=='CARD')return json({ok:false,status:'rejected',provider:'iyzico',code:'BOOKING_CARD_PAYMENT_NOT_SELECTED'},409);
  const token=await rpc<Json|null>('service_customer_payment_method_token_v225',{p_user_id:user.id,p_method_id:methodId});if(!token)return json({ok:false,status:'rejected',provider:'iyzico',code:'PAYMENT_METHOD_NOT_FOUND'},404);
  const expectedEnvironment=settings.test_mode?'sandbox':'live';const provider=clean(token.provider,20),env=clean(token.environment,20),cardUserKey=clean(token.providerCustomerRef,500),cardToken=clean(token.providerPaymentMethodRef,500);
  if(provider!=='IYZICO'||env!==expectedEnvironment||!cardUserKey||!cardToken)return json({ok:false,status:'rejected',provider:'iyzico',code:'PAYMENT_METHOD_ENVIRONMENT_MISMATCH'},409);
  const amount=calculateCharge(Number(bookingRow.total_price),settings),currency=(settings.currency||bookingRow.currency||'TRY').toUpperCase();if(!['TRY','EUR','USD','CHF'].includes(currency))throw new Error('IYZICO_CURRENCY_UNSUPPORTED');
  const email=bookingRow.customer_email||clean(body.customer?.email,100),phone=bookingRow.customer_phone||clean(body.customer?.phone,40),identityNumber=clean(body.customer?.identityNumber,50),billingAddress=clean(body.customer?.billingAddress,500),city=clean(body.customer?.city,100),country=clean(body.customer?.country,100),zipCode=clean(body.customer?.zipCode,20)||'00000';
  if(!email||!email.includes('@'))throw new Error('PAYMENT_EMAIL_REQUIRED');if(!phone)throw new Error('PAYMENT_PHONE_REQUIRED');if(!identityNumber||identityNumber.length<5)throw new Error('IYZICO_IDENTITY_REQUIRED');if(!billingAddress||billingAddress.length<5||!city||!country)throw new Error('IYZICO_BILLING_ADDRESS_REQUIRED');
  const names=splitName(bookingRow.customer_name||String(body.customer?.name||''));const claimed=await claimPayment(bookingRow,methodId,amount,currency);
  if(!claimed.fresh){if(claimed.claim.status==='PAID')return json({ok:true,status:'paid',provider:'iyzico',externalReference:claimed.claim.provider_reference,message:'Kart ödemeniz daha önce başarıyla alındı.'});if(claimed.claim.status==='AUTHORIZED'||claimed.claim.status==='PENDING')return json({ok:true,status:'ready',provider:'iyzico',externalReference:claimed.claim.provider_reference,message:'Bu kart ödemesi zaten işleniyor. Aynı karttan tekrar çekim yapılmadı.'});return json({ok:false,status:'rejected',provider:'iyzico',code:'SAVED_CARD_ATTEMPT_ALREADY_FAILED',message:'Bu kartla yapılan önceki ödeme denemesi tamamlanmadı. Başka bir kart veya ödeme yöntemi seçin.'},409);}
  const credentials=await resolveIyzicoCredentials(settings.test_mode);if(!credentials.configured||!credentials.secretKey)throw new Error(settings.test_mode?'IYZICO_SANDBOX_NOT_CONFIGURED':'IYZICO_LIVE_NOT_CONFIGURED');
  const conversationId=`saved-${bookingRow.id}-${methodId.slice(0,8)}`;const payload:Json={locale:'tr',conversationId,price:amount,paidPrice:amount,installment:1,paymentChannel:'WEB',currency,basketId:bookingRow.reference,paymentGroup:'PRODUCT',paymentCard:{cardUserKey,cardToken},buyer:{id:user.id,name:names.name,surname:names.surname,identityNumber,email,gsmNumber:phone,registrationAddress:billingAddress,city,country,zipCode,ip:(request.headers.get('x-vercel-forwarded-for')||request.headers.get('x-forwarded-for')||'127.0.0.1').split(',')[0].trim().slice(0,64)},billingAddress:{address:billingAddress,zipCode,contactName:bookingRow.customer_name,city,country},basketItems:[{id:bookingRow.id,price:amount,name:bookingRow.item_name,category1:'Araç Kiralama',itemType:'VIRTUAL'}]};
  const result=await iyzicoRequest('POST','/payment/auth',payload,settings.test_mode);
  if(result.status!=='success'||result.paymentStatus!=='SUCCESS'){await settleClaim(claimed.claim.id,bookingRow.id,'FAILED',null,result,false);return json({ok:false,status:'rejected',provider:'iyzico',code:String(result.errorCode||'IYZICO_PAYMENT_REJECTED'),message:String(result.errorMessage||'Kart ödemesi onaylanmadı. Başka bir kart veya ödeme yöntemi deneyin.').slice(0,220)},402);}
  const signatureValid=verifyPaymentSignature(result,credentials.secretKey);if(!signatureValid)throw new Error('IYZICO_PAYMENT_SIGNATURE_INVALID');
  const receivedAmount=Number(result.paidPrice),amountValid=Number.isFinite(receivedAmount)&&Math.round(receivedAmount*100)===Math.round(amount*100),currencyValid=String(result.currency||'').toUpperCase()===currency;if(!amountValid||!currencyValid)throw new Error('IYZICO_PAYMENT_AMOUNT_MISMATCH');
  const fraudStatus=Number(result.fraudStatus),providerReference=clean(result.paymentId,160);if(!providerReference)throw new Error('IYZICO_PAYMENT_ID_MISSING');
  if(fraudStatus===1){await settleClaim(claimed.claim.id,bookingRow.id,'PAID',providerReference,result,true);return json({ok:true,status:'paid',provider:'iyzico',externalReference:providerReference,message:'Kart ödemeniz başarıyla alındı.'});}
  if(fraudStatus===0){await settleClaim(claimed.claim.id,bookingRow.id,'AUTHORIZED',providerReference,result,true);return json({ok:true,status:'ready',provider:'iyzico',externalReference:providerReference,message:'Kart ödemeniz güvenlik incelemesinde. Aynı karttan tekrar çekim yapılmayacaktır.'});}
  await settleClaim(claimed.claim.id,bookingRow.id,'FAILED',providerReference,result,true);return json({ok:false,status:'rejected',provider:'iyzico',code:'IYZICO_FRAUD_REJECTED',message:'Kart ödemesi güvenlik kontrolünden geçmedi. Başka bir kart veya ödeme yöntemi deneyin.'},402);
}

export default{async fetch(request:Request):Promise<Response>{try{const operation=new URL(request.url).searchParams.get('op');if(operation==='charge'){if(request.method!=='POST')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);return chargeSavedCard(request);}if(request.method==='GET')return listCards(request);if(request.method==='POST')return addCard(request);if(request.method==='DELETE')return removeCard(request);if(request.method==='PATCH')return setDefault(request);return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);}catch(error){const code=error instanceof Error?error.message:'WALLET_CARDS_FAILED';console.error('wallet-cards',code);const status=code==='UNAUTHORIZED'?401:code==='BOOKING_NOT_FOUND'||code.includes('NOT_FOUND')?404:code==='CARD_STORAGE_NOT_ENABLED'||code.includes('NOT_CONFIGURED')?503:code.startsWith('INVALID_')?400:502;return json({ok:false,status:'error',provider:code.startsWith('PAYMENT_')||code.startsWith('IYZICO_')?'iyzico':undefined,code,message:code.startsWith('PAYMENT_')||code.startsWith('IYZICO_')?'Kayıtlı kart ödemesi tamamlanamadı. Rezervasyon kaydınız korunuyor.':undefined},status);}}};
