import { createHash, createHmac } from 'node:crypto';
import { resolveIyzicoCredentials, resolvePaytrCredentials } from './_lib/payment-provider-credentials';
import { corsHeaders, guardOrigin, originDecision } from './_lib/request-security';

type Json=Record<string,unknown>;
type AuthUser={id:string;email?:string|null;email_confirmed_at?:string|null};
type WalletToken={id?:string;provider?:string;providerScope?:string;providerUserKey?:string;providerCardToken?:string};
type WalletIdentity={providerUserKey?:string|null};
type PaymentSettings={test_mode:boolean};

const METHODS='GET,POST,DELETE,PATCH,OPTIONS';
const MAX_BODY_BYTES=8192;
function clean(value:unknown,max=500){return typeof value==='string'?value.trim().slice(0,max):'';}
function json(request:Request,body:unknown,status=200){const d=originDecision(request);return Response.json(body,{status,headers:{...corsHeaders(d,METHODS),'cache-control':'private, no-store','content-type':'application/json; charset=utf-8'}});}
function serviceConfig(){const url=process.env.SUPABASE_PROJECT_URL?.trim()||process.env.SUPABASE_URL?.trim()||'';const key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()||'';return{url,key,configured:Boolean(url&&key)};}
async function db<T>(path:string,init:RequestInit={}):Promise<T>{const cfg=serviceConfig();if(!cfg.configured)throw new Error('WALLET_DATABASE_NOT_CONFIGURED');const response=await fetch(`${cfg.url}/rest/v1/${path}`,{...init,headers:{apikey:cfg.key,authorization:`Bearer ${cfg.key}`,accept:'application/json',...(init.headers||{})},cache:'no-store',signal:AbortSignal.timeout(10_000)});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(String((payload as any)?.message||(payload as any)?.code||`WALLET_DATABASE_${response.status}`));return payload as T;}
async function rpc<T>(name:string,body:Json):Promise<T>{return await db<T>(`rpc/${name}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});}
async function authenticatedUser(request:Request):Promise<AuthUser>{const authorization=request.headers.get('authorization')||'';if(!/^Bearer\s+\S+/i.test(authorization))throw new Error('UNAUTHORIZED');const cfg=serviceConfig();if(!cfg.configured)throw new Error('WALLET_DATABASE_NOT_CONFIGURED');const response=await fetch(`${cfg.url}/auth/v1/user`,{headers:{apikey:cfg.key,authorization},cache:'no-store',signal:AbortSignal.timeout(8000)});const user=await response.json().catch(()=>({})) as AuthUser;if(!response.ok||!user.id||!user.email_confirmed_at)throw new Error('UNAUTHORIZED');return user;}
async function rateLimit(userId:string,scope:string,limit:number){const hash=createHash('sha256').update(`${scope}:${userId}`).digest('hex');const allowed=await rpc<boolean>('consume_rate_limit',{p_key_hash:hash,p_scope:scope,p_window_seconds:60,p_limit:limit});if(allowed!==true)throw new Error('RATE_LIMITED');}
async function settings():Promise<PaymentSettings>{const rows=await db<PaymentSettings[]>('payment_settings?config_key=eq.main&select=test_mode&limit=1');return rows[0]||{test_mode:true};}
function luhn(number:string){let sum=0,alternate=false;for(let i=number.length-1;i>=0;i--){let n=Number(number[i]);if(alternate){n*=2;if(n>9)n-=9;}sum+=n;alternate=!alternate;}return sum%10===0;}
function hmacHex(value:string,key:string){return createHmac('sha256',key).update(value,'utf8').digest('hex');}
function base64(value:string){return Buffer.from(value,'utf8').toString('base64');}
function iyzicoAuth(path:string,body:string,apiKey:string,secretKey:string){const randomKey=`${Date.now()}${crypto.randomUUID().replace(/-/g,'').slice(0,12)}`;const signature=hmacHex(`${randomKey}${path}${body}`,secretKey);return{authorization:`IYZWSv2 ${base64(`apiKey:${apiKey}&randomKey:${randomKey}&signature:${signature}`)}`,randomKey};}
async function iyzicoRequest(method:'POST'|'DELETE',path:string,payload:Json,testMode:boolean):Promise<Json>{const credentials=await resolveIyzicoCredentials(testMode);if(!credentials.configured||!credentials.apiKey||!credentials.secretKey)throw new Error(testMode?'IYZICO_SANDBOX_NOT_CONFIGURED':'IYZICO_LIVE_NOT_CONFIGURED');const body=JSON.stringify(payload);const auth=iyzicoAuth(path,body,credentials.apiKey,credentials.secretKey);const response=await fetch(`${credentials.baseUrl}${path}`,{method,headers:{authorization:auth.authorization,'x-iyzi-rnd':auth.randomKey,'content-type':'application/json',accept:'application/json'},body,cache:'no-store',signal:AbortSignal.timeout(15_000)});const result=await response.json().catch(()=>({})) as Json;if(!response.ok||result.status!=='success'){const code=String(result.errorCode||'');if(code==='3007')throw new Error('IYZICO_CARD_STORAGE_NOT_ENABLED');throw new Error(`IYZICO_WALLET_${code||response.status}`);}return result;}
function paytrToken(value:string,key:string){return createHmac('sha256',key).update(value,'utf8').digest('base64');}
async function deletePaytrCard(token:WalletToken){const paytr=await resolvePaytrCredentials();if(!paytr.configured||!paytr.merchantId||!paytr.merchantKey||!paytr.merchantSalt)throw new Error('PAYTR_NOT_CONFIGURED');const utoken=clean(token.providerUserKey,500),ctoken=clean(token.providerCardToken,500);if(!utoken||!ctoken)throw new Error('PAYMENT_METHOD_TOKEN_INVALID');const form=new URLSearchParams({merchant_id:paytr.merchantId,utoken,ctoken,paytr_token:paytrToken(`${ctoken}${utoken}${paytr.merchantSalt}`,paytr.merchantKey)});const response=await fetch('https://www.paytr.com/odeme/capi/delete',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form,cache:'no-store',signal:AbortSignal.timeout(15_000)});const result=await response.json().catch(()=>({})) as Json;if(!response.ok||result.status!=='success')throw new Error('PAYTR_WALLET_DELETE_FAILED');}
function friendlyCode(error:unknown){const code=error instanceof Error?error.message:'WALLET_FAILED';if(code==='UNAUTHORIZED')return{status:401,code};if(code==='RATE_LIMITED')return{status:429,code};if(code==='IYZICO_CARD_STORAGE_NOT_ENABLED')return{status:409,code};if(code.includes('NOT_CONFIGURED'))return{status:503,code};if(code.includes('NOT_FOUND'))return{status:404,code};if(code.includes('INVALID')||code.includes('REQUIRED')||code.includes('LIMIT'))return{status:400,code};return{status:502,code:'WALLET_PROVIDER_UNAVAILABLE'};}

async function status(request:Request){const user=await authenticatedUser(request);await rateLimit(user.id,'customer-wallet-read-v225',60);const s=await settings();const [iyzico,paytr]=await Promise.all([resolveIyzicoCredentials(s.test_mode),resolvePaytrCredentials()]);return json(request,{ok:true,mode:s.test_mode?'SANDBOX':'LIVE',canAddCard:iyzico.configured,providers:{iyzico:{configured:iyzico.configured},paytr:{configured:paytr.configured,savingRequiresDirectApi:true}}});}

async function addCard(request:Request){const user=await authenticatedUser(request);await rateLimit(user.id,'customer-wallet-write-v225',8);const declared=Number(request.headers.get('content-length')||0);if(declared>MAX_BODY_BYTES)return json(request,{ok:false,code:'PAYLOAD_TOO_LARGE'},413);const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)return json(request,{ok:false,code:'PAYLOAD_TOO_LARGE'},413);let body:any;try{body=JSON.parse(raw);}catch{return json(request,{ok:false,code:'INVALID_JSON'},400);}
  const consent=body?.consent===true;const cardNumber=clean(body?.cardNumber,32).replace(/\D/g,'');const holder=clean(body?.cardHolderName,100);const alias=clean(body?.cardAlias,80)||'Kartım';const month=clean(body?.expireMonth,2).padStart(2,'0');const year=clean(body?.expireYear,4);
  if(!consent)return json(request,{ok:false,code:'CARD_STORAGE_CONSENT_REQUIRED'},400);if(!/^[0-9]{13,19}$/.test(cardNumber)||!luhn(cardNumber))return json(request,{ok:false,code:'INVALID_CARD_NUMBER'},400);if(holder.length<3)return json(request,{ok:false,code:'CARD_HOLDER_REQUIRED'},400);if(!/^(0[1-9]|1[0-2])$/.test(month))return json(request,{ok:false,code:'INVALID_CARD_EXPIRY_MONTH'},400);const currentYear=new Date().getUTCFullYear();if(!/^20\d{2}$/.test(year)||Number(year)<currentYear||Number(year)>currentYear+30)return json(request,{ok:false,code:'INVALID_CARD_EXPIRY_YEAR'},400);
  const s=await settings();const scope=s.test_mode?'SANDBOX':'LIVE';const identity=await rpc<WalletIdentity>('service_customer_wallet_identity_v225',{p_user_id:user.id,p_provider:'IYZICO',p_scope:scope});const conversationId=`wallet-${crypto.randomUUID()}`;const card={cardAlias:alias,cardNumber,expireYear:year,expireMonth:month,cardHolderName:holder};const payload:Json=identity?.providerUserKey?{locale:'tr',conversationId,cardUserKey:identity.providerUserKey,card}:{locale:'tr',conversationId,externalId:user.id,email:user.email||'',card};
  const result=await iyzicoRequest('POST','/cardstorage/card',payload,s.test_mode);const cardUserKey=clean(result.cardUserKey,500),cardToken=clean(result.cardToken,500),last4=clean(result.lastFourDigits,4);if(!cardUserKey||!cardToken||!/^[0-9]{4}$/.test(last4))throw new Error('IYZICO_WALLET_RESPONSE_INVALID');const brand=clean(result.cardAssociation||result.cardFamily,80)||'Kart';
  try{const saved=await rpc<{id?:string;isDefault?:boolean}>('service_save_customer_payment_method_v225',{p_user_id:user.id,p_provider:'IYZICO',p_scope:scope,p_provider_user_key:cardUserKey,p_provider_card_token:cardToken,p_brand:brand,p_last4:last4,p_expiry_month:Number(month),p_expiry_year:Number(year),p_label:alias});return json(request,{ok:true,method:{id:saved.id,provider:'IYZICO',provider_scope:scope,brand,last4,expiry_month:Number(month),expiry_year:Number(year),label:alias,is_default:saved.isDefault===true,status:'ACTIVE'}},201);}catch(error){await iyzicoRequest('DELETE','/cardstorage/card',{locale:'tr',conversationId:`wallet-rollback-${crypto.randomUUID()}`,cardUserKey,cardToken},s.test_mode).catch(()=>undefined);throw error;}}

async function removeCard(request:Request){const user=await authenticatedUser(request);await rateLimit(user.id,'customer-wallet-write-v225',12);let body:any;try{body=await request.json();}catch{return json(request,{ok:false,code:'INVALID_JSON'},400);}const methodId=clean(body?.methodId,80);if(!/^[0-9a-f-]{36}$/i.test(methodId))return json(request,{ok:false,code:'INVALID_PAYMENT_METHOD'},400);const token=await rpc<WalletToken>('service_customer_payment_method_token_v225',{p_user_id:user.id,p_method_id:methodId});if(String(token.provider).toUpperCase()==='IYZICO'){const testMode=String(token.providerScope).toUpperCase()==='SANDBOX';await iyzicoRequest('DELETE','/cardstorage/card',{locale:'tr',conversationId:`wallet-delete-${crypto.randomUUID()}`,cardUserKey:token.providerUserKey,cardToken:token.providerCardToken},testMode);}else if(String(token.provider).toUpperCase()==='PAYTR'){await deletePaytrCard(token);}else throw new Error('INVALID_PAYMENT_PROVIDER');await rpc('service_revoke_customer_payment_method_v225',{p_user_id:user.id,p_method_id:methodId});return json(request,{ok:true});}

async function setDefault(request:Request){const user=await authenticatedUser(request);await rateLimit(user.id,'customer-wallet-write-v225',20);let body:any;try{body=await request.json();}catch{return json(request,{ok:false,code:'INVALID_JSON'},400);}const methodId=clean(body?.methodId,80);if(!/^[0-9a-f-]{36}$/i.test(methodId))return json(request,{ok:false,code:'INVALID_PAYMENT_METHOD'},400);await rpc('service_set_default_customer_payment_method_v225',{p_user_id:user.id,p_method_id:methodId});return json(request,{ok:true});}

export default{async fetch(request:Request):Promise<Response>{const guarded=guardOrigin(request,METHODS);if(guarded)return guarded;try{const op=new URL(request.url).searchParams.get('op')||'status';if(op==='status'&&request.method==='GET')return await status(request);if(op==='add'&&request.method==='POST')return await addCard(request);if(op==='remove'&&request.method==='DELETE')return await removeCard(request);if(op==='default'&&request.method==='PATCH')return await setDefault(request);return json(request,{ok:false,code:'METHOD_NOT_ALLOWED'},405);}catch(error){const mapped=friendlyCode(error);return json(request,{ok:false,code:mapped.code},mapped.status);}}};
